(function(global){
  "use strict";
  function rng(seed){let s=(Number(seed)>>>0)||1;return{next(){s+=0x6D2B79F5;let v=s;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296;},int(a,b){return a+Math.floor(this.next()*(b-a+1));},pick(a){return a[this.int(0,a.length-1)];}};}
  function gcd(a,b){while(b)[a,b]=[b,a%b];return a;}
  function lcm(a,b){return a/gcd(a,b)*b;}
  function same(a,b){return JSON.stringify(a)===JSON.stringify(b);}

  function q48Pool(workers){const out=[];function visit(start,row){if(row.length===workers){const basis=row.reduce(lcm,1),units=row.reduce((s,t)=>s+basis/t,0);if(basis<=72&&basis%units===0){const together=basis/units;if(together>=2&&together<Math.min(...row))out.push({times:row.slice(),basis,units,together});}return;}for(let t=start;t<=24;t+=1)visit(t,row.concat(t));}visit(3,[]);return out;}
  const Q48_POOLS={2:q48Pool(2),3:q48Pool(3)};
  function generateQ48(difficulty,seed){const r=rng(seed),workerCount=difficulty==="hard"?3:2,pool=Q48_POOLS[workerCount].filter((row)=>difficulty!=="easy"||row.times[1]%row.times[0]===0),picked=r.pick(pool),names=["민수","철수","지우"].slice(0,workerCount);return{workerCount,names,individualTimes:picked.times,basis:picked.basis,dailyUnits:picked.times.map((t)=>picked.basis/t),answer:picked.together,difficulty,seed:Number(seed)||1};}
  function q48Candidates(p){const b=p.individualTimes.reduce(lcm,1),u=p.individualTimes.reduce((s,t)=>s+b/t,0);return b%u===0?[b/u]:[];}
  function validateQ48(p){const n=p&&p.difficulty==="hard"?3:2,c=p?q48Candidates(p):[];return Boolean(p&&p.workerCount===n&&p.individualTimes.length===n&&c.length===1&&c[0]===p.answer);}
  function renderQ48Problem(p){const rows=p.names.map((name,i)=>{const y=50+i*66,w=460*p.dailyUnits[i]/p.basis;return`<text x="90" y="${y+22}" text-anchor="end" font-size="17" font-weight="900">${name}</text><rect x="110" y="${y}" width="460" height="36" rx="8" fill="#eef3f6" stroke="#84919b"/><rect x="110" y="${y}" width="${w}" height="36" rx="8" fill="#7ba99d"/><text x="590" y="${y+23}" font-size="15" font-weight="850">하루 ${p.dailyUnits[i]}칸</text>`;}).join("");return`<svg class="hf-app hf-work" viewBox="0 0 680 ${95+p.workerCount*66}" role="img" aria-label="같은 전체 일을 칸으로 나눈 막대"><rect width="680" height="${95+p.workerCount*66}" rx="18" fill="#fff"/><text x="340" y="28" text-anchor="middle" font-size="16" font-weight="900">전체 일을 ${p.basis}칸으로 생각합니다.</text>${rows}<text x="340" y="${78+p.workerCount*66}" text-anchor="middle" font-size="16" font-weight="850">하루에 함께 ${p.dailyUnits.reduce((a,b)=>a+b,0)}칸</text></svg>`;}
  function answerQ48(p){return`정답: ${p.answer}일 — 전체를 ${p.basis}칸으로 보면 하루에 ${p.dailyUnits.join("칸과 ")}칸씩, 함께 ${p.dailyUnits.reduce((a,b)=>a+b,0)}칸을 합니다.`;}

  function generateQ49(difficulty,seed){const r=rng(seed),rate=r.int(2,7),givenAnimals=r.int(2,5),givenDays=r.int(2,5),givenNuts=rate*givenAnimals*givenDays,targetAnimals=r.int(difficulty==="hard"?6:3,difficulty==="hard"?12:9),wholeDays=r.int(2,difficulty==="easy"?5:7),fraction=difficulty==="easy"?0:r.int(1,targetAnimals*rate-1),targetNuts=targetAnimals*rate*(wholeDays-1)+fraction+1,answer=Math.ceil(targetNuts/(targetAnimals*rate));return{rate,givenAnimals,givenDays,givenNuts,targetAnimals,targetNuts,exactDays:targetNuts/(targetAnimals*rate),answer,difficulty,seed:Number(seed)||1};}
  function candidatesQ49(p){const unit=p.givenNuts/(p.givenAnimals*p.givenDays);return Number.isInteger(unit)?[Math.ceil(p.targetNuts/(p.targetAnimals*unit))]:[];}
  function validateQ49(p){const c=p?candidatesQ49(p):[];return Boolean(p&&p.rate===p.givenNuts/(p.givenAnimals*p.givenDays)&&c.length===1&&c[0]===p.answer);}
  function renderQ49Problem(p){return`<svg class="hf-app hf-unit-rate" viewBox="0 0 680 220" role="img" aria-label="한 마리 하루 기준으로 바꾸는 그림"><rect width="680" height="220" rx="18" fill="#fff"/><rect x="45" y="48" width="235" height="105" rx="15" fill="#fff8e9" stroke="#c9ad6c"/><text x="162" y="82" text-anchor="middle" font-size="18" font-weight="900">${p.givenAnimals}마리 · ${p.givenDays}일</text><text x="162" y="124" text-anchor="middle" font-size="27" font-weight="950">${p.givenNuts}개</text><path d="M300 100 H370" stroke="#687581" stroke-width="4" marker-end="url(#q49a)"/><defs><marker id="q49a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#687581"/></marker></defs><rect x="395" y="48" width="235" height="105" rx="15" fill="#eaf4f1" stroke="#6e9b8e"/><text x="512" y="82" text-anchor="middle" font-size="18" font-weight="900">${p.targetAnimals}마리 · ?일</text><text x="512" y="124" text-anchor="middle" font-size="27" font-weight="950">${p.targetNuts}개 이상</text><text x="340" y="197" text-anchor="middle" font-size="16" font-weight="850">먼저 1마리가 하루에 모으는 수를 구하세요.</text></svg>`;}
  function answerQ49(p){return`정답: ${p.answer}일 — 1마리는 하루 ${p.rate}개, ${p.targetAnimals}마리는 하루 ${p.targetAnimals*p.rate}개를 모읍니다. ${p.answer}일째에 처음 ${p.targetNuts}개 이상이 됩니다.`;}

  const ITEMS=["지우개","연필","크레파스","클립"];
  function q50Solutions(p){const targets=p.items.slice(1),out=[];function visit(row){if(row.length===targets.length){const values=[p.unitLength].concat(row);if(p.rows.every((coeff)=>coeff.reduce((s,c,i)=>s+c*values[i],0)===p.totalLength))out.push(Object.fromEntries(targets.map((name,i)=>[name,row[i]])));return;}for(let v=1;v<=15;v+=1)visit(row.concat(v));}visit([]);return out;}
  function q50Rows(values,total){const rows=[];function visit(i,left,row){if(i===values.length){if(left===0&&row.reduce((a,b)=>a+b,0)>=1)rows.push(row);return;}for(let c=0;c<=Math.min(8,Math.floor(left/values[i]));c+=1)visit(i+1,left-c*values[i],row.concat(c));}visit(0,total,[]);return rows;}
  function generateQ50(difficulty,seed){const r=rng(seed),itemCount=difficulty==="easy"?3:4;for(let a=0;a<300;a+=1){const unitLength=r.int(2,5),values=[unitLength];while(values.length<itemCount){const v=r.int(2,12);if(!values.includes(v))values.push(v);}const totalLength=unitLength*r.int(6,12),possible=q50Rows(values,totalLength).filter((row)=>row.some((c,i)=>i>0&&c>0)),base=[totalLength/unitLength].concat(Array(itemCount-1).fill(0)),rows=[base],shuffled=possible.sort(()=>r.next()-.5);for(const row of shuffled){rows.push(row);const p={items:ITEMS.slice(0,itemCount),unitLength,totalLength,rows};if(rows.length>=itemCount&&q50Solutions(p).length===1&&ITEMS.slice(1,itemCount).every((_,i)=>rows.some((x)=>x[i+1]>0))){p.answer=q50Solutions(p)[0];p.difficulty=difficulty;p.seed=Number(seed)||1;return p;}if(rows.length>itemCount+3)break;}}throw new Error(`q50 ${difficulty}`);}
  function candidatesQ50(p){const s=p?q50Solutions(p):[];return s.length===1?s:[];}
  function validateQ50(p){const n=p&&p.difficulty==="easy"?3:4,c=p?candidatesQ50(p):[];return Boolean(p&&p.items.length===n&&c.length===1&&same(c[0],p.answer));}
  function renderQ50Problem(p){const colors=["#d7e7e2","#e8dfca","#d8e2f0","#ecd4d0"],marks=["지","연","크","클"],h=98+p.rows.length*58,rows=p.rows.map((coeff,ri)=>{let x=80,parts="";coeff.forEach((count,i)=>{for(let k=0;k<count;k+=1){const w=500*(i===0?p.unitLength:p.answer[p.items[i]])/p.totalLength;parts+=`<rect x="${x}" y="${45+ri*58}" width="${w}" height="34" fill="${colors[i]}" stroke="#596872"/><text x="${x+w/2}" y="${68+ri*58}" text-anchor="middle" font-size="16" font-weight="950">${marks[i]}</text>`;x+=w;}});return parts;}).join("");const legend=p.items.map((name,i)=>`${marks[i]}=${name}`).join(" · ");return`<svg class="hf-app hf-length-bars" viewBox="0 0 680 ${h}" role="img" aria-label="끝 길이가 같은 물건 줄"><rect width="680" height="${h}" rx="18" fill="#fff"/>${rows}<text x="340" y="${h-38}" text-anchor="middle" font-size="15" font-weight="900">${legend}</text><text x="340" y="${h-14}" text-anchor="middle" font-size="16" font-weight="850">모든 줄의 양 끝 길이가 같습니다.</text></svg>`;}
  function answerQ50(p){return`정답: ${Object.entries(p.answer).map(([k,v])=>`${k} ${v}cm`).join(", ")} — 지우개 ${p.unitLength}cm를 기준으로 같은 전체 길이를 맞춥니다.`;}

  function q51HourBell(absHour){const h=((absHour-1)%12+12)%12+1;return h;}
  function q51Count(p){let total=0;for(let half=p.includeStart?0:1;half<=p.spanHours*2;half+=1){const abs=p.startHour+Math.floor(half/2);total+=half%2?1:q51HourBell(abs);}return total;}
  function generateQ51(difficulty,seed){const r=rng(seed),spanHours={easy:3,same:7,hard:12}[difficulty]||7,startHour=r.int(1,12),includeStart=Boolean(r.int(0,1)),p={startHour,endHour:startHour+spanHours,spanHours,includeStart,difficulty,seed:Number(seed)||1};p.answer=q51Count(p);return p;}
  function candidatesQ51(p){return p?[q51Count(p)]:[];}
  function validateQ51(p){const span={easy:3,same:7,hard:12}[p&&p.difficulty],c=p?candidatesQ51(p):[];return Boolean(span&&p.spanHours===span&&c[0]===p.answer);}
  function clockLabel(h){return`${((h-1)%12)+1}시`;}
  function renderQ51Problem(p){return`<svg class="hf-app hf-clock-range" viewBox="0 0 680 210" role="img" aria-label="시작 시각과 끝 시각 사이 종 횟수"><rect width="680" height="210" rx="18" fill="#fff"/><circle cx="135" cy="85" r="48" fill="#fff8e9" stroke="#8a7040" stroke-width="3"/><text x="135" y="93" text-anchor="middle" font-size="23" font-weight="950">${clockLabel(p.startHour)}</text><path d="M205 85 H475" stroke="#687581" stroke-width="5" marker-end="url(#q51a)"/><defs><marker id="q51a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#687581"/></marker></defs><circle cx="545" cy="85" r="48" fill="#eaf4f1" stroke="#477b70" stroke-width="3"/><text x="545" y="93" text-anchor="middle" font-size="23" font-weight="950">${clockLabel(p.endHour)}</text><text x="340" y="158" text-anchor="middle" font-size="18" font-weight="950">${p.spanHours}시간 동안</text><text x="340" y="188" text-anchor="middle" font-size="16" font-weight="850">시작 정각 종 ${p.includeStart?'포함':'제외'} · 끝 정각 종 포함 · 30분마다 1번</text></svg>`;}
  function answerQ51(p){return`정답: ${p.answer}번 — 정각 종과 30분 종을 따로 세고, 시작 정각 종은 ${p.includeStart?'포함':'제외'}합니다.`;}

  const SHAPES=["○","□","△","◇"];
  function generateQ52(difficulty,seed){const r=rng(seed),count={easy:2,same:3,hard:4}[difficulty]||3,weights=[1];for(let i=1;i<count;i+=1)weights.push(weights[i-1]*r.int(2,difficulty==="hard"?4:3));const target=Array.from({length:count-1},()=>r.int(0,2));if(!target.some(Boolean))target[0]=1;const answer=target.reduce((s,c,i)=>s+c*weights[i+1],0);return{count,weights,target,answer,difficulty,seed:Number(seed)||1};}
  function candidatesQ52(p){if(!p)return[];const values=[1];for(let i=1;i<p.count;i+=1){const ratio=p.weights[i]/p.weights[i-1];if(!Number.isInteger(ratio)||ratio<2)return[];values.push(values[i-1]*ratio);}return[p.target.reduce((s,c,i)=>s+c*values[i+1],0)];}
  function validateQ52(p){const n={easy:2,same:3,hard:4}[p&&p.difficulty],c=p?candidatesQ52(p):[];return Boolean(n&&p.count===n&&c.length===1&&c[0]===p.answer);}
  function renderQ52Problem(p){const h=90+(p.count-1)*62,rows=p.weights.slice(1).map((w,i)=>`<text x="205" y="${55+i*62}" text-anchor="middle" font-size="30">${SHAPES[i+1]}</text><text x="340" y="${55+i*62}" text-anchor="middle" font-size="22" font-weight="950">=</text><text x="475" y="${55+i*62}" text-anchor="middle" font-size="27" font-weight="900">${SHAPES[i].repeat(Math.round(w/p.weights[i]))}</text>`).join("");return`<svg class="hf-app hf-balance-shapes" viewBox="0 0 680 ${h}" role="img" aria-label="평형인 도형 저울 관계"><rect width="680" height="${h}" rx="18" fill="#fff"/>${rows}<text x="340" y="${h-18}" text-anchor="middle" font-size="18" font-weight="900">${p.target.map((c,i)=>SHAPES[i+1].repeat(c)).join(" + ")} = ○ 몇 개?</text></svg>`;}
  function answerQ52(p){return`정답: ${p.answer}개 — 가장 가벼운 ○를 1로 두고 각 도형을 ○의 개수로 바꿉니다.`;}

  function generateQ53(difficulty,seed){const r=rng(seed),count={easy:2,same:3,hard:4}[difficulty]||3,lengths=[1];for(let i=1;i<count;i+=1)lengths.push(lengths[i-1]*r.int(2,3));const target=Array.from({length:count-1},()=>r.int(0,2));if(!target.some(Boolean))target[target.length-1]=1;const answer=target.reduce((s,c,i)=>s+c*lengths[i+1],0);return{count,lengths,target,answer,difficulty,seed:Number(seed)||1};}
  function candidatesQ53(p){let vals=[1];for(let i=1;i<p.count;i+=1)vals.push(vals[i-1]*(p.lengths[i]/p.lengths[i-1]));return vals.every(Number.isInteger)?[p.target.reduce((s,c,i)=>s+c*vals[i+1],0)]:[];}
  function validateQ53(p){const n={easy:2,same:3,hard:4}[p&&p.difficulty],c=p?candidatesQ53(p):[];return Boolean(n&&p.count===n&&c.length===1&&c[0]===p.answer);}
  function renderQ53Problem(p){const colors=["#6da7c9","#79ad77","#e1b941","#e58d45"],names=["파랑","초록","노랑","주황"],h=125+(p.count-1)*65,scale=165/p.lengths[p.lengths.length-1],rows=p.lengths.slice(1).map((len,i)=>{const ratio=len/p.lengths[i],leftW=len*scale,partW=p.lengths[i]*scale;return`<rect x="90" y="${38+i*65}" width="${leftW}" height="28" rx="10" fill="${colors[i+1]}"/><text x="300" y="${59+i*65}" font-size="20" font-weight="950">=</text>${Array.from({length:ratio},(_,k)=>`<rect x="${345+k*partW}" y="${38+i*65}" width="${partW}" height="28" rx="4" fill="${colors[i]}" stroke="#fff" stroke-width="2"/>`).join("")}`;}).join(""),target=p.target.map((count,i)=>`${names[i+1]} ${count}개`).join(" + ");return`<svg class="hf-app hf-unit-rods" viewBox="0 0 680 ${h}" role="img" aria-label="같은 길이를 만드는 여러 단위 막대"><rect width="680" height="${h}" rx="18" fill="#fff"/>${rows}<text x="340" y="${h-42}" text-anchor="middle" font-size="17" font-weight="900">${target}</text><text x="340" y="${h-16}" text-anchor="middle" font-size="16" font-weight="850">= 가장 짧은 파랑 막대 몇 개?</text></svg>`;}
  function answerQ53(p){return`정답: ${p.answer}개 — 모든 막대 길이를 가장 짧은 막대 1개의 길이로 바꿉니다.`;}

  function q54Parities(a,b,n){const out=[a%2,b%2];while(out.length<n)out.push((out[out.length-1]+out[out.length-2])%2);return out.slice(0,n);}
  function generateQ54(difficulty,seed){const r=rng(seed),base={easy:15,same:40,hard:60}[difficulty]||40,termCount=base+r.int(0,5),startA=r.pick([1,3,5]),startB=r.pick([1,2,4,5]);if(startA%2===0&&startB%2===0)return generateQ54(difficulty,(Number(seed)||1)+1);const parities=q54Parities(startA,startB,termCount),answer=parities.filter(Boolean).length;return{startA,startB,termCount,parities:parities.slice(0,9),answer,difficulty,seed:Number(seed)||1};}
  function candidatesQ54(p){return p?[q54Parities(p.startA,p.startB,p.termCount).filter(Boolean).length]:[];}
  function validateQ54(p){const base={easy:15,same:40,hard:60}[p&&p.difficulty],c=p?candidatesQ54(p):[];return Boolean(base&&p.termCount>=base&&p.termCount<=base+5&&c[0]===p.answer);}
  function renderQ54Problem(p){const dots=p.parities.map((v,i)=>`<circle cx="${75+i*66}" cy="85" r="24" fill="${v?'#e8dfca':'#dcebe7'}" stroke="#596872"/><text x="${75+i*66}" y="92" text-anchor="middle" font-size="18" font-weight="950">${v?'홀':'짝'}</text>`).join("");return`<svg class="hf-app hf-parity" viewBox="0 0 680 175" role="img" aria-label="앞의 두 수를 더하는 수열의 홀짝 패턴"><rect width="680" height="175" rx="18" fill="#fff"/>${dots}<text x="340" y="150" text-anchor="middle" font-size="17" font-weight="850">수 자체보다 홀수·짝수의 반복을 찾으세요.</text></svg>`;}
  function answerQ54(p){return`정답: ${p.answer}개 — 처음 두 수의 홀짝부터 앞의 두 칸을 더한 홀짝 패턴을 ${p.termCount}번째까지 반복해 셉니다.`;}

  global.HFQ48={generateQ48,validateQ48,enumerateQ48AnswerCandidates:q48Candidates,renderQ48Problem,deriveQ48Answer:(p)=>p.answer,renderQ48Answer:answerQ48};
  global.HFQ49={generateQ49,validateQ49,enumerateQ49AnswerCandidates:candidatesQ49,renderQ49Problem,deriveQ49Answer:(p)=>p.answer,renderQ49Answer:answerQ49};
  global.HFQ50={generateQ50,validateQ50,enumerateQ50AnswerCandidates:candidatesQ50,renderQ50Problem,deriveQ50Answer:(p)=>p.answer,renderQ50Answer:answerQ50};
  global.HFQ51={generateQ51,validateQ51,enumerateQ51AnswerCandidates:candidatesQ51,renderQ51Problem,deriveQ51Answer:(p)=>p.answer,renderQ51Answer:answerQ51};
  global.HFQ52={generateQ52,validateQ52,enumerateQ52AnswerCandidates:candidatesQ52,renderQ52Problem,deriveQ52Answer:(p)=>p.answer,renderQ52Answer:answerQ52};
  global.HFQ53={generateQ53,validateQ53,enumerateQ53AnswerCandidates:candidatesQ53,renderQ53Problem,deriveQ53Answer:(p)=>p.answer,renderQ53Answer:answerQ53};
  global.HFQ54={generateQ54,validateQ54,enumerateQ54AnswerCandidates:candidatesQ54,renderQ54Problem,deriveQ54Answer:(p)=>p.answer,renderQ54Answer:answerQ54};
})(typeof window!=="undefined"?window:globalThis);
