(function(global){
  "use strict";
  function makeRng(seed){let state=(Number(seed)>>>0)||1;return{next(){state+=0x6D2B79F5;let v=state;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296;},int(min,max){return min+Math.floor(this.next()*(max-min+1));},pick(values){return values[this.int(0,values.length-1)];}};}
  function shuffle(values,rng){const out=values.slice();for(let i=out.length-1;i>0;i-=1){const j=rng.int(0,i);[out[i],out[j]]=[out[j],out[i]];}return out;}
  function combinations(values,count){const out=[];function visit(start,row){if(row.length===count){out.push(row);return;}for(let i=start;i<=values.length-(count-row.length);i+=1)visit(i+1,row.concat([values[i]]));}visit(0,[]);return out;}
  function permutations(values){const out=[];function visit(rest,row){if(!rest.length){out.push(row);return;}rest.forEach((value,index)=>visit(rest.slice(0,index).concat(rest.slice(index+1)),row.concat(value)));}visit(values,[]);return out;}
  function same(a,b){return JSON.stringify(a)===JSON.stringify(b);}

  const Q41_OUTERS=["circle","square","star","hexagon"],Q41_INNERS=["triangle","diamond","heart"],Q41_COLORS=["orange","purple","blue","green"],Q41_COLOR_HEX={orange:"#e89a63",purple:"#8067b7",blue:"#6da7c9",green:"#79ad77"};
  const Q41_OPS=["outer","color","inner","flip","innerFlip"];
  function q41Next(values,value){return values[(values.indexOf(value)+1)%values.length];}
  function q41Apply(state,op){const out={...state};if(op==="outer")out.outer=q41Next(Q41_OUTERS,out.outer);else if(op==="color"){out.outerColor=q41Next(Q41_COLORS,out.outerColor);out.innerColor=q41Next(Q41_COLORS,out.innerColor);}else if(op==="inner")out.inner=q41Next(Q41_INNERS,out.inner);else if(op==="flip")out.direction=out.direction==="up"?"down":"up";else if(op==="innerFlip"){out.inner=q41Next(Q41_INNERS,out.inner);out.direction=out.direction==="up"?"down":"up";}return out;}
  function q41RandomState(rng){let outerColor=rng.pick(Q41_COLORS),innerColor=rng.pick(Q41_COLORS);if(innerColor===outerColor)innerColor=q41Next(Q41_COLORS,innerColor);return{outer:rng.pick(Q41_OUTERS),outerColor,inner:rng.pick(Q41_INNERS),innerColor,direction:rng.pick(["up","down"])};}
  function q41Compatible(example){return Q41_OPS.filter((op)=>same(q41Apply(example.before,op),example.after));}
  function q41RuleAssignments(payload){let rows=[[]];for(const button of payload.buttons){const matches=q41Compatible(payload.examples.find((row)=>row.button===button));rows=rows.flatMap((row)=>matches.map((op)=>row.concat(op)));}return rows;}
  function q41Finals(payload){const finals=[];for(const rules of q41RuleAssignments(payload)){const map=Object.fromEntries(payload.buttons.map((button,index)=>[button,rules[index]]));let state={...payload.start};payload.sequence.forEach((button)=>{state=q41Apply(state,map[button]);});if(!finals.some((row)=>same(row,state)))finals.push(state);}return finals;}
  function generateQ41(difficulty,seed){const rng=makeRng(seed),buttonCount=difficulty==="easy"?2:3,ops=difficulty==="easy"?["outer","color"]:difficulty==="hard"?["outer","color","innerFlip"]:["outer","color","inner"],buttons=["가","나","다"].slice(0,buttonCount),start=q41RandomState(rng),sequence=shuffle(buttons,rng),examples=buttons.map((button,index)=>{const op=ops[index],before=q41RandomState(rng);if(op==="outer")before.outer=start.outer;if(op==="color"){before.outerColor=start.outerColor;before.innerColor=start.innerColor;}if(op==="inner")before.inner=start.inner;if(op==="flip")before.direction=start.direction;if(op==="innerFlip"){before.inner=start.inner;before.direction=start.direction;}return{button,before,after:q41Apply(before,op)};}),payload={buttons,examples,start,sequence,difficulty,seed:Number(seed)||1};const finals=q41Finals(payload);if(finals.length!==1||q41RuleAssignments(payload).length!==1)return generateQ41(difficulty,(Number(seed)||1)+7919);payload.answer=finals[0];return payload;}
  function enumerateQ41AnswerCandidates(payload){return payload?q41Finals(payload):[];}
  function validateQ41(payload){const expected={easy:2,same:3,hard:3}[payload&&payload.difficulty],rules=payload?q41RuleAssignments(payload):[],answers=enumerateQ41AnswerCandidates(payload);return Boolean(expected&&payload.buttons.length===expected&&payload.examples.length===expected&&payload.sequence.length===expected&&new Set(payload.sequence).size===expected&&rules.length===1&&answers.length===1&&same(answers[0],payload.answer));}
  function deriveQ41Answer(payload){return payload.answer;}
  function q41Shape(kind,cx,cy,size,fill,stroke,direction){const turn=direction==="down"?` transform="rotate(180 ${cx} ${cy})"`:"";if(kind==="circle")return`<circle cx="${cx}" cy="${cy}" r="${size}" fill="${fill}" stroke="${stroke}" stroke-width="3"/>`;if(kind==="square")return`<rect x="${cx-size}" y="${cy-size}" width="${size*2}" height="${size*2}" rx="5" fill="${fill}" stroke="${stroke}" stroke-width="3"/>`;if(kind==="diamond")return`<polygon points="${cx},${cy-size} ${cx+size},${cy} ${cx},${cy+size} ${cx-size},${cy}" fill="${fill}" stroke="${stroke}" stroke-width="3"${turn}/>`;if(kind==="triangle")return`<polygon points="${cx},${cy-size} ${cx+size},${cy+size} ${cx-size},${cy+size}" fill="${fill}" stroke="${stroke}" stroke-width="3"${turn}/>`;if(kind==="heart")return`<path d="M ${cx} ${cy+size} C ${cx-size*1.45} ${cy}, ${cx-size*.75} ${cy-size}, ${cx} ${cy-size*.25} C ${cx+size*.75} ${cy-size}, ${cx+size*1.45} ${cy}, ${cx} ${cy+size} Z" fill="${fill}" stroke="${stroke}" stroke-width="3"${turn}/>`;const pts=kind==="star"?Array.from({length:10},(_,i)=>{const a=-Math.PI/2+i*Math.PI/5,r=i%2?size*.45:size;return`${cx+r*Math.cos(a)},${cy+r*Math.sin(a)}`;}).join(" "):Array.from({length:6},(_,i)=>{const a=Math.PI/6+i*Math.PI/3;return`${cx+size*Math.cos(a)},${cy+size*Math.sin(a)}`;}).join(" ");return`<polygon points="${pts}" fill="${fill}" stroke="${stroke}" stroke-width="3"/>`;}
  function q41StateSvg(state,cx,cy,scale){return q41Shape(state.outer,cx,cy,scale,Q41_COLOR_HEX[state.outerColor],"#52636f","up")+q41Shape(state.inner,cx,cy,scale*.42,Q41_COLOR_HEX[state.innerColor],"#fff",state.direction);}
  function renderQ41Problem(payload){const rows=payload.examples.map((row,i)=>{const y=62+i*92;return`${q41StateSvg(row.before,105,y,32)}<rect x="165" y="${y-25}" width="54" height="50" rx="25" fill="#e7edf2" stroke="#687581"/><text x="192" y="${y+7}" text-anchor="middle" font-size="23" font-weight="950">${row.button}</text><path d="M230 ${y} H285" stroke="#687581" stroke-width="3" marker-end="url(#q41arrow)"/>${q41StateSvg(row.after,340,y,32)}`;}).join(""),targetY=75+payload.examples.length*92,buttons=payload.sequence.map((button,i)=>`<rect x="${235+i*58}" y="${targetY-24}" width="48" height="48" rx="24" fill="#fff8e9" stroke="#a88442"/><text x="${259+i*58}" y="${targetY+7}" text-anchor="middle" font-size="21" font-weight="950">${button}</text>`).join("");return`<svg class="hf-counting hf-shape-code" viewBox="0 0 680 ${targetY+80}" role="img" aria-label="버튼마다 일정한 도형 변화 규칙"><rect width="680" height="${targetY+80}" rx="18" fill="#fff"/><defs><marker id="q41arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#687581"/></marker></defs><text x="55" y="28" font-size="17" font-weight="900" fill="#59636a">버튼 보기</text>${rows}<line x1="35" y1="${targetY-53}" x2="645" y2="${targetY-53}" stroke="#d5dce3"/>${q41StateSvg(payload.start,105,targetY,38)}${buttons}<rect x="590" y="${targetY-39}" width="74" height="78" rx="8" fill="#fff" stroke="#687581" stroke-width="3"/><text x="627" y="${targetY+7}" text-anchor="middle" font-size="26" font-weight="950">?</text></svg>`;}
  function renderQ41Answer(payload){const a=payload.answer,n={circle:"원",square:"네모",star:"별",hexagon:"육각형",triangle:"삼각형",diamond:"마름모",heart:"하트",orange:"주황",purple:"보라",blue:"파랑",green:"초록"};return`정답: ${n[a.outerColor]}색 ${n[a.outer]} 안에 ${a.direction==="down"?'아래를':'위를'} 향한 ${n[a.innerColor]}색 ${n[a.inner]} — 버튼을 순서대로 한 번씩 적용합니다.`;}

  const Q42_SPEC={easy:{cells:5,fill:2},same:{cells:7,fill:3},hard:{cells:8,fill:3}},Q42_DIRS=[[1,0],[-1,0],[0,1],[0,-1]];
  function q42Grow(count,rng){const cells=[[0,0]],seen=new Set(["0,0"]);while(cells.length<count){const base=rng.pick(cells),dir=rng.pick(Q42_DIRS),next=[base[0]+dir[0],base[1]+dir[1]],key=next.join(",");if(!seen.has(key)){seen.add(key);cells.push(next);}}const minX=Math.min(...cells.map((c)=>c[0])),minY=Math.min(...cells.map((c)=>c[1]));return cells.map(([x,y])=>[x-minX,y-minY]).sort((a,b)=>a[1]-b[1]||a[0]-b[0]);}
  function q42Cases(payload){return combinations(payload.cells,payload.fillCount).filter((row)=>row.every((cell,i)=>row.slice(i+1).every((other)=>Math.abs(cell[0]-other[0])+Math.abs(cell[1]-other[1])!==1)));}
  function generateQ42(difficulty,seed){const spec=Q42_SPEC[difficulty]||Q42_SPEC.same,rng=makeRng(seed);for(let attempt=0;attempt<500;attempt+=1){const cells=q42Grow(spec.cells,rng),payload={cells,fillCount:spec.fill,difficulty,seed:Number(seed)||1},answer=q42Cases(payload).length;if(answer>=2&&answer<=40){payload.answer=answer;return payload;}}throw new Error(`q42 ${difficulty} 생성 실패`);}
  function enumerateQ42AnswerCandidates(payload){return payload?[q42Cases(payload).length]:[];}
  function validateQ42(payload){const spec=Q42_SPEC[payload&&payload.difficulty],c=enumerateQ42AnswerCandidates(payload);return Boolean(spec&&payload.cells.length===spec.cells&&payload.fillCount===spec.fill&&new Set(payload.cells.map((p)=>p.join(","))).size===spec.cells&&c.length===1&&c[0]===payload.answer);}
  function deriveQ42Answer(payload){return payload.answer;}
  function renderQ42Problem(payload){const size=70,minX=Math.min(...payload.cells.map((c)=>c[0])),maxX=Math.max(...payload.cells.map((c)=>c[0])),minY=Math.min(...payload.cells.map((c)=>c[1])),maxY=Math.max(...payload.cells.map((c)=>c[1])),w=(maxX-minX+1)*size,h=(maxY-minY+1)*size,ox=(680-w)/2,oy=45,cells=payload.cells.map(([x,y])=>`<rect x="${ox+(x-minX)*size}" y="${oy+(y-minY)*size}" width="${size}" height="${size}" fill="#fff" stroke="#687581" stroke-width="3"/>`).join("");return`<svg class="hf-counting hf-grid-fill" viewBox="0 0 680 ${h+95}" role="img" aria-label="한 변으로 이웃하지 않게 칠할 칸 모양"><rect width="680" height="${h+95}" rx="18" fill="#fff"/>${cells}<text x="340" y="${h+78}" text-anchor="middle" font-size="17" font-weight="850" fill="#59636a">${payload.fillCount}칸을 칠합니다. 꼭짓점만 닿는 것은 이웃이 아닙니다.</text></svg>`;}
  function renderQ42Answer(payload){return`정답: ${payload.answer}가지 — ${payload.cells.length}칸에서 ${payload.fillCount}칸을 고른 뒤, 한 변으로 이웃한 쌍이 있는 경우를 뺍니다.`;}

  const Q43_PALETTE=[{id:"red",name:"빨강",hex:"#d95c52"},{id:"blue",name:"파랑",hex:"#5f8fbd"},{id:"yellow",name:"노랑",hex:"#e1b941"},{id:"purple",name:"보라",hex:"#8b6fba"},{id:"green",name:"초록",hex:"#65a46d"},{id:"orange",name:"주황",hex:"#e58d45"}];
  function q43Colorings(payload){const ids=payload.palette.map((c)=>c.id),keys=new Set();for(const picked of combinations(ids,payload.pickCount))for(const row of permutations(picked)){const rev=row.slice().reverse(),key=[row.join("|"),rev.join("|")].sort()[0];keys.add(key);}return[...keys];}
  function generateQ43(difficulty,seed){const rng=makeRng(seed),base={easy:3,same:4,hard:5}[difficulty]||4,paletteSize=base+(rng.int(0,1)),pickCount=difficulty==="easy"?2:3,palette=shuffle(Q43_PALETTE,rng).slice(0,paletteSize),payload={palette,pickCount,difficulty,seed:Number(seed)||1};payload.answer=q43Colorings(payload).length;return payload;}
  function enumerateQ43AnswerCandidates(payload){return payload?[q43Colorings(payload).length]:[];}
  function validateQ43(payload){const base={easy:3,same:4,hard:5}[payload&&payload.difficulty],c=enumerateQ43AnswerCandidates(payload);return Boolean(base&&payload.palette.length>=base&&payload.palette.length<=base+1&&payload.pickCount===(payload.difficulty==="easy"?2:3)&&c.length===1&&c[0]===payload.answer);}
  function deriveQ43Answer(payload){return payload.answer;}
  function renderQ43Problem(payload){const swatches=payload.palette.map((color,i)=>`<circle cx="${175+i*68}" cy="54" r="23" fill="${color.hex}" stroke="#52636f" stroke-width="2"/><text x="${175+i*68}" y="91" text-anchor="middle" font-size="13" font-weight="850">${color.name}</text>`).join(""),cell=80,start=(680-payload.pickCount*cell)/2,boxes=Array.from({length:payload.pickCount},(_,i)=>`<rect x="${start+i*cell}" y="128" width="${cell}" height="${cell}" fill="#fff" stroke="#687581" stroke-width="3"/>`).join("");return`<svg class="hf-counting hf-color-line" viewBox="0 0 680 255" role="img" aria-label="서로 다른 색을 고르는 일렬 칸"><rect width="680" height="255" rx="18" fill="#fff"/>${swatches}${boxes}<text x="340" y="238" text-anchor="middle" font-size="16" font-weight="850" fill="#59636a">서로 다른 ${payload.pickCount}색 사용 · 돌리거나 뒤집어 같으면 한 가지</text></svg>`;}
  function renderQ43Answer(payload){return`정답: ${payload.answer}가지 — 색을 고른 뒤 배열하고, 앞뒤 순서가 반대인 두 배열은 같은 한 가지로 셉니다.`;}

  function q44Numbers(payload){const out=[];for(let n=100;n<=999;n+=1){const digits=String(n).split("").map(Number),[h,t,o]=digits;if(!digits.includes(payload.requiredDigit)||h+t+o!==payload.sumTarget)continue;if(payload.relation==="less"&&!(h<o))continue;if(payload.relation==="greater"&&!(h>o))continue;if(payload.onesParity&&o%2!==(payload.onesParity==="even"?0:1))continue;out.push(String(n));}return out;}
  function generateQ44(difficulty,seed){const rng=makeRng(seed);for(let attempt=0;attempt<1000;attempt+=1){const requiredDigit=difficulty==="easy"?rng.int(1,5):0,sumTarget=rng.int(difficulty==="easy"?8:10,difficulty==="hard"?20:18),relation=difficulty==="easy"?rng.pick(["less","greater"]):"less",onesParity=difficulty==="hard"?rng.pick(["odd","even"]):null,payload={requiredDigit,sumTarget,relation,onesParity,difficulty,seed:Number(seed)||1},answer=q44Numbers(payload);if(answer.length>=1&&answer.length<=7){payload.answer=answer;return payload;}}throw new Error(`q44 ${difficulty} 생성 실패`);}
  function enumerateQ44AnswerCandidates(payload){return payload?[q44Numbers(payload)]:[];}
  function validateQ44(payload){const c=enumerateQ44AnswerCandidates(payload);return Boolean(payload&&payload.requiredDigit===(payload.difficulty==="easy"?payload.requiredDigit:0)&&c.length===1&&c[0].length>=1&&c[0].length<=7&&same(c[0],payload.answer));}
  function deriveQ44Answer(payload){return payload.answer;}
  function renderQ44Problem(payload){const relation=payload.relation==="less"?"백의 자리 수는 일의 자리 수보다 작습니다.":"백의 자리 수는 일의 자리 수보다 큽니다.",parity=payload.onesParity?`<text x="90" y="188" font-size="19" font-weight="850">• 일의 자리 수는 ${payload.onesParity==="even"?'짝수':'홀수'}입니다.</text>`:"";return`<svg class="hf-counting hf-three-digits" viewBox="0 0 680 ${payload.onesParity?230:195}" role="img" aria-label="세 자리 수 조건"><rect x="45" y="22" width="590" height="${payload.onesParity?185:150}" rx="16" fill="#fff8e9" stroke="#cdb57e" stroke-width="2"/><text x="90" y="70" font-size="19" font-weight="850">• ${relation}</text><text x="90" y="111" font-size="19" font-weight="850">• 각 자리 수의 합은 ${payload.sumTarget}입니다.</text><text x="90" y="152" font-size="19" font-weight="850">• 숫자 ${payload.requiredDigit}이 꼭 들어갑니다.</text>${parity}</svg>`;}
  function renderQ44Answer(payload){return`정답: ${payload.answer.join(", ")} — 100부터 999까지 조건을 하나씩 확인해 남는 수를 빠짐없이 씁니다.`;}

  const Q45_SPEC={easy:{w:[2,3],h:[2,3]},same:{w:[3,4],h:[3,4]},hard:{w:[4,5],h:[4,5]}};
  function q45Graph(widths){const vertices=[],keys=new Set();widths.forEach((width,y)=>{for(let x=0;x<=width;x+=1){vertices.push([x,y]);keys.add(`${x},${y}`);}});const edges=[];for(const [x,y] of vertices)for(const [dx,dy] of [[1,0],[0,1]])if(keys.has(`${x+dx},${y+dy}`))edges.push([[x,y],[x+dx,y+dy]]);return{vertices,edges};}
  function q45Count(payload){const end=[payload.width,payload.height],graph=q45Graph(payload.rowWidths),queue=[[0,0]],dist=new Map([["0,0",0]]),ways=new Map([["0,0",1]]);for(let head=0;head<queue.length;head+=1){const cur=queue[head],key=cur.join(","),d=dist.get(key);for(const edge of graph.edges){let next=null;if(same(edge[0],cur))next=edge[1];else if(same(edge[1],cur))next=edge[0];if(!next)continue;const nk=next.join(",");if(!dist.has(nk)){dist.set(nk,d+1);ways.set(nk,ways.get(key));queue.push(next);}else if(dist.get(nk)===d+1)ways.set(nk,ways.get(nk)+ways.get(key));}}return ways.get(end.join(","))||0;}
  function generateQ45(difficulty,seed){const spec=Q45_SPEC[difficulty]||Q45_SPEC.same,rng=makeRng(seed);for(let attempt=0;attempt<300;attempt+=1){const width=rng.int(spec.w[0],spec.w[1]),height=rng.int(spec.h[0],spec.h[1]);let rowWidths;if(difficulty==="easy")rowWidths=Array(height+1).fill(width);else if(difficulty==="same"){const cut=rng.int(1,height);rowWidths=Array.from({length:height+1},(_,y)=>y<cut?width-1:width);}else{const cut1=rng.int(1,height-1),cut2=rng.int(cut1+1,height);rowWidths=Array.from({length:height+1},(_,y)=>y<cut1?width-2:y<cut2?width-1:width);}const payload={width,height,rowWidths,difficulty,seed:Number(seed)||1},answer=q45Count(payload);if(answer>=2&&answer<=150){payload.answer=answer;return payload;}}throw new Error(`q45 ${difficulty} 생성 실패`);}
  function enumerateQ45AnswerCandidates(payload){return payload?[q45Count(payload)]:[];}
  function validateQ45(payload){const spec=Q45_SPEC[payload&&payload.difficulty],c=enumerateQ45AnswerCandidates(payload);return Boolean(spec&&payload.rowWidths.length===payload.height+1&&payload.rowWidths[payload.rowWidths.length-1]===payload.width&&c.length===1&&c[0]===payload.answer&&payload.answer>0);}
  function deriveQ45Answer(payload){return payload.answer;}
  function renderQ45Problem(payload){const graph=q45Graph(payload.rowWidths),step=Math.min(92,470/Math.max(payload.width,payload.height)),ox=95,oy=48,edges=graph.edges.map((edge)=>`<line x1="${ox+edge[0][0]*step}" y1="${oy+edge[0][1]*step}" x2="${ox+edge[1][0]*step}" y2="${oy+edge[1][1]*step}" stroke="#52636f" stroke-width="4"/>`).join(""),endX=ox+payload.width*step,endY=oy+payload.height*step;return`<svg class="hf-counting hf-shortest-path" viewBox="0 0 680 ${endY+62}" role="img" aria-label="오른쪽과 아래쪽 길로 가는 최단 경로 격자"><rect width="680" height="${endY+62}" rx="18" fill="#fff"/>${edges}<circle cx="${ox}" cy="${oy}" r="8" fill="#b54a3b"/><text x="${ox}" y="30" text-anchor="middle" font-size="16" font-weight="900">출발</text><circle cx="${endX}" cy="${endY}" r="8" fill="#2f7188"/><text x="${endX}" y="${endY+30}" text-anchor="middle" font-size="16" font-weight="900">도착</text></svg>`;}
  function renderQ45Answer(payload){return`정답: ${payload.answer}가지 — 출발점에서 가까운 교차로부터, 최단 거리로 오는 길의 수를 차례로 더합니다.`;}

  const Q46_STEPS={easy:2,same:3,hard:4};
  function generateQ46(difficulty,seed){const rng=makeRng(seed),stepCount=Q46_STEPS[difficulty]||3,finalCount=rng.int(1,difficulty==="hard"?5:7),actions=Array.from({length:stepCount},(_,i)=>i%2===0?"주었습니다":"먹었습니다"),answer=finalCount*(2**stepCount);return{stepCount,finalCount,actions,answer,difficulty,seed:Number(seed)||1};}
  function enumerateQ46AnswerCandidates(payload){return payload&&Number.isInteger(payload.finalCount)&&payload.finalCount>0?[payload.finalCount*(2**payload.stepCount)]:[];}
  function validateQ46(payload){const count=Q46_STEPS[payload&&payload.difficulty],c=enumerateQ46AnswerCandidates(payload);return Boolean(count&&payload.stepCount===count&&payload.actions.length===count&&c.length===1&&c[0]===payload.answer);}
  function deriveQ46Answer(payload){return payload.answer;}
  function renderQ46Problem(payload){const gap=76,height=payload.stepCount*gap+110,nodes=Array.from({length:payload.stepCount+1},(_,i)=>{const y=45+i*gap,last=i===payload.stepCount;return`<circle cx="120" cy="${y}" r="28" fill="${last?'#dcebe7':'#fff'}" stroke="#52636f" stroke-width="2"/><text x="120" y="${y+7}" text-anchor="middle" font-size="${last?18:24}" font-weight="950">${last?payload.finalCount:'?'}</text>${i<payload.stepCount?`<path d="M120 ${y+31} V${y+gap-31}" stroke="#8a7040" stroke-width="3" marker-end="url(#q46arrow)"/><rect x="185" y="${y+23}" width="405" height="46" rx="12" fill="#fff8e9" stroke="#d5c18e"/><text x="387" y="${y+52}" text-anchor="middle" font-size="18" font-weight="850">남은 사탕의 반을 ${payload.actions[i]}</text>`:''}`;}).join("");return`<svg class="hf-counting hf-reverse-story" viewBox="0 0 680 ${height}" role="img" aria-label="마지막 수에서 거꾸로 두 배씩 찾는 그림"><rect width="680" height="${height}" rx="18" fill="#fff"/><defs><marker id="q46arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#8a7040"/></marker></defs>${nodes}<text x="340" y="${height-15}" text-anchor="middle" font-size="16" font-weight="850" fill="#59636a">마지막 ${payload.finalCount}개에서 거꾸로 생각하세요.</text></svg>`;}
  function renderQ46Answer(payload){const trail=Array.from({length:payload.stepCount+1},(_,i)=>payload.finalCount*(2**i));return`정답: ${payload.answer}개 — 거꾸로 ${trail.join(" → ")}로 두 배씩 올라갑니다.`;}

  const Q47_STATES={easy:3,same:4,hard:5};
  function q47Simulate(initialRed,total,operations){let red=initialRed;const states=[red];for(const delta of operations){red+=delta;if(red<0||red>total)return null;states.push(red);}return states;}
  function q47Initials(payload){const out=[];for(let red=0;red<=payload.total;red+=1){const states=q47Simulate(red,payload.total,payload.operations);if(states&&states[states.length-1]===payload.finalRed)out.push(red);}return out;}
  function generateQ47(difficulty,seed){const rng=makeRng(seed),stateCount=Q47_STATES[difficulty]||4;for(let attempt=0;attempt<500;attempt+=1){const total=2*rng.int(difficulty==="easy"?8:10,difficulty==="hard"?20:16),finalRed=total/2,operations=Array.from({length:stateCount-1},()=>{const amount=rng.int(1,difficulty==="hard"?5:4);return rng.pick([-amount,amount]);}),initialRed=finalRed-operations.reduce((sum,value)=>sum+value,0),states=q47Simulate(initialRed,total,operations),payload={total,operations,finalRed,finalBlue:total-finalRed,stateCount,difficulty,seed:Number(seed)||1};if(states&&initialRed>0&&initialRed<total&&q47Initials(payload).length===1){payload.answer=initialRed;payload.states=states;return payload;}}throw new Error(`q47 ${difficulty} 생성 실패`);}
  function enumerateQ47AnswerCandidates(payload){return payload?q47Initials(payload):[];}
  function validateQ47(payload){const count=Q47_STATES[payload&&payload.difficulty],c=enumerateQ47AnswerCandidates(payload),states=payload?q47Simulate(payload.answer,payload.total,payload.operations):null;return Boolean(count&&payload.stateCount===count&&payload.operations.length===count-1&&payload.total===payload.finalRed+payload.finalBlue&&c.length===1&&c[0]===payload.answer&&states&&same(states,payload.states));}
  function deriveQ47Answer(payload){return payload.answer;}
  function renderQ47Problem(payload){const rowH=48,height=92+payload.stateCount*rowH,rows=Array.from({length:payload.stateCount},(_,i)=>{const y=52+i*rowH,last=i===payload.stateCount-1,label=i===0?"처음":`${i}번 뒤`,change=i===0?"-":payload.operations[i-1]>0?`파랑 ${payload.operations[i-1]}개 → 빨강`:`빨강 ${-payload.operations[i-1]}개 → 파랑`,red=last?payload.finalRed:"?",blue=last?payload.finalBlue:"?";return`<rect x="65" y="${y}" width="550" height="${rowH}" fill="${last?'#eaf4f1':'#fff'}" stroke="#7a8791"/><text x="115" y="${y+31}" text-anchor="middle" font-size="16" font-weight="900">${label}</text><text x="300" y="${y+31}" text-anchor="middle" font-size="16" font-weight="850">${change}</text><text x="480" y="${y+31}" text-anchor="middle" font-size="16" font-weight="900">빨강 ${red} · 파랑 ${blue}</text>`;}).join("");return`<svg class="hf-counting hf-reverse-table" viewBox="0 0 680 ${height}" role="img" aria-label="구슬 색 수 변화를 거꾸로 추적하는 표"><rect width="680" height="${height}" rx="18" fill="#fff"/><text x="115" y="35" text-anchor="middle" font-size="16" font-weight="900">때</text><text x="300" y="35" text-anchor="middle" font-size="16" font-weight="900">색을 바꾼 수</text><text x="480" y="35" text-anchor="middle" font-size="16" font-weight="900">그때의 구슬 수</text>${rows}<text x="340" y="${height-12}" text-anchor="middle" font-size="15" font-weight="850" fill="#59636a">전체는 언제나 ${payload.total}개입니다.</text></svg>`;}
  function renderQ47Answer(payload){return`정답: ${payload.answer}개 — 마지막 빨강 ${payload.finalRed}개에서 표를 한 줄씩 거꾸로 올라가 처음 빨강 구슬 수를 찾습니다.`;}

  global.HFQ41={generateQ41,validateQ41,enumerateQ41AnswerCandidates,renderQ41Problem,deriveQ41Answer,renderQ41Answer};
  global.HFQ42={generateQ42,validateQ42,enumerateQ42AnswerCandidates,renderQ42Problem,deriveQ42Answer,renderQ42Answer};
  global.HFQ43={generateQ43,validateQ43,enumerateQ43AnswerCandidates,renderQ43Problem,deriveQ43Answer,renderQ43Answer};
  global.HFQ44={generateQ44,validateQ44,enumerateQ44AnswerCandidates,renderQ44Problem,deriveQ44Answer,renderQ44Answer};
  global.HFQ45={generateQ45,validateQ45,enumerateQ45AnswerCandidates,renderQ45Problem,deriveQ45Answer,renderQ45Answer};
  global.HFQ46={generateQ46,validateQ46,enumerateQ46AnswerCandidates,renderQ46Problem,deriveQ46Answer,renderQ46Answer};
  global.HFQ47={generateQ47,validateQ47,enumerateQ47AnswerCandidates,renderQ47Problem,deriveQ47Answer,renderQ47Answer};
})(typeof window!=="undefined"?window:globalThis);
