(function(global){
  "use strict";
  function makeRng(seed){let state=(Number(seed)>>>0)||1;return{next(){state+=0x6D2B79F5;let v=state;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296;},int(min,max){return min+Math.floor(this.next()*(max-min+1));},pick(values){return values[this.int(0,values.length-1)];}};}
  function shuffle(values,rng){const out=values.slice();for(let i=out.length-1;i>0;i-=1){const j=rng.int(0,i);[out[i],out[j]]=[out[j],out[i]];}return out;}
  function permutations(values){const out=[];function visit(rest,row){if(!rest.length){out.push(row);return;}rest.forEach((value,index)=>visit(rest.slice(0,index).concat(rest.slice(index+1)),row.concat(value)));}visit(values,[]);return out;}
  function topic(word){const last=String(word).charCodeAt(String(word).length-1),hasFinal=last>=0xAC00&&last<=0xD7A3&&(last-0xAC00)%28!==0;return`${word}${hasFinal?'은':'는'}`;}

  const NAMES=["지민","서준","하윤","도윤","서아","민준","지우","예준","수아","시우"];
  const Q35_SPEC={easy:4,same:5,hard:6};
  function q35RelationPass(order,relation){const pos=(name)=>order.indexOf(name);if(relation.type==="rank")return pos(relation.person)===relation.rank-1;if(relation.type==="before")return pos(relation.first)<pos(relation.second);if(relation.type==="between")return pos(relation.first)<pos(relation.middle)&&pos(relation.middle)<pos(relation.last);if(relation.type==="immediatelyBehind")return pos(relation.behind)===pos(relation.ahead)+1;return false;}
  function q35Orders(payload){return permutations(payload.participants).filter((order)=>payload.relations.every((relation)=>q35RelationPass(order,relation)));}
  function generateQ35(difficulty,seed){const count=Q35_SPEC[difficulty]||5,rng=makeRng(seed),participants=shuffle(NAMES,rng).slice(0,count),order=shuffle(participants,rng),relations=[];if(count===4){relations.push({type:"rank",person:order[1],rank:2},{type:"before",first:order[0],second:order[1]},{type:"immediatelyBehind",ahead:order[2],behind:order[3]});}else if(count===5){relations.push({type:"between",first:order[0],middle:order[1],last:order[2]},{type:"rank",person:order[2],rank:3},{type:"immediatelyBehind",ahead:order[3],behind:order[4]});}else{relations.push({type:"between",first:order[0],middle:order[1],last:order[2]},{type:"rank",person:order[2],rank:3},{type:"immediatelyBehind",ahead:order[3],behind:order[4]},{type:"immediatelyBehind",ahead:order[4],behind:order[5]});}const queryRank=rng.int(1,count),payload={participants,relations,queryRank,order,answer:order[queryRank-1],difficulty,seed:Number(seed)||1};if(q35Orders(payload).length!==1)throw new Error(`q35 ${difficulty} 생성 실패`);return payload;}
  function enumerateQ35AnswerCandidates(payload){if(!payload)return[];return[...new Set(q35Orders(payload).map((order)=>order[payload.queryRank-1]))];}
  function validateQ35(payload){const count=Q35_SPEC[payload&&payload.difficulty],orders=q35Orders(payload),answers=enumerateQ35AnswerCandidates(payload);return Boolean(count&&payload.participants.length===count&&orders.length===1&&answers.length===1&&answers[0]===payload.answer&&JSON.stringify(orders[0])===JSON.stringify(payload.order));}
  function deriveQ35Answer(payload){return payload.answer;}
  function q35RelationText(r){if(r.type==="rank")return`${topic(r.person)} ${r.rank}등입니다.`;if(r.type==="before")return`${topic(r.first)} ${r.second}보다 앞에서 달립니다.`;if(r.type==="between")return`${topic(r.middle)} ${r.first}보다 뒤, ${r.last}보다 앞에서 달립니다.`;return`${topic(r.behind)} ${r.ahead} 바로 뒤에서 달립니다.`;}
  function renderQ35Problem(payload){const rows=payload.relations.map((r,i)=>`<text x="70" y="${55+i*34}" font-size="18" font-weight="850" fill="#243746">${i+1}. ${q35RelationText(r)}</text>`).join(""),y=85+payload.relations.length*34,slots=Array.from({length:payload.participants.length},(_,i)=>`<circle cx="${110+i*(460/(payload.participants.length-1))}" cy="${y}" r="24" fill="#fff" stroke="#687581" stroke-width="2"/><text x="${110+i*(460/(payload.participants.length-1))}" y="${y+6}" text-anchor="middle" font-size="14" font-weight="900">${i+1}등</text>`).join("");return`<svg class="hf-logic hf-line-order" viewBox="0 0 680 ${y+62}" role="img" aria-label="달리기 순서 조건"><rect width="680" height="${y+62}" rx="18" fill="#fff"/>${rows}<line x1="80" y1="${y}" x2="600" y2="${y}" stroke="#b5bec6" stroke-width="3"/>${slots}</svg>`;}
  function renderQ35Answer(payload){return`정답: ${payload.answer} — 순서는 ${payload.order.join(" → ")}입니다.`;}

  const Q36_SPEC={easy:{f:[5,10],b:[4,8],k:[1,3]},same:{f:[10,16],b:[7,12],k:[3,6]},hard:{f:[14,24],b:[10,17],k:[5,9]}};
  function q36Totals(payload){const out=[];for(let total=2;total<=100;total+=1){const posA=payload.frontRank,posB=total-payload.backRank+1;if(posA>=1&&posA<=total&&posB>=1&&posB<=total&&posA!==posB&&Math.abs(posA-posB)-1===payload.peopleBetween)out.push(total);}return out;}
  function generateQ36(difficulty,seed){const spec=Q36_SPEC[difficulty]||Q36_SPEC.same,rng=makeRng(seed);for(let attempt=0;attempt<500;attempt+=1){const frontRank=rng.int(spec.f[0],spec.f[1]),backRank=rng.int(spec.b[0],spec.b[1]),peopleBetween=rng.int(spec.k[0],Math.min(spec.k[1],frontRank-2)),payload={frontRank,backRank,peopleBetween,difficulty,seed:Number(seed)||1},totals=q36Totals(payload);if(totals.length===2){payload.validTotals=totals;payload.answer={min:totals[0],max:totals[1]};return payload;}}throw new Error(`q36 ${difficulty} 생성 실패`);}
  function enumerateQ36AnswerCandidates(payload){if(!payload)return[];const totals=q36Totals(payload);return totals.length?[{min:Math.min(...totals),max:Math.max(...totals)}]:[];}
  function validateQ36(payload){const spec=Q36_SPEC[payload&&payload.difficulty],totals=q36Totals(payload),answers=enumerateQ36AnswerCandidates(payload);return Boolean(spec&&totals.length===2&&answers.length===1&&JSON.stringify(answers[0])===JSON.stringify(payload.answer));}
  function deriveQ36Answer(payload){return payload.answer;}
  function renderQ36Problem(payload){return`<svg class="hf-logic hf-min-max-line" viewBox="0 0 680 245" role="img" aria-label="줄서기 최소 최대"><rect width="680" height="245" rx="18" fill="#fff"/><line x1="75" y1="135" x2="605" y2="135" stroke="#71808c" stroke-width="4"/><circle cx="220" cy="135" r="30" fill="#dcebe7" stroke="#426c64" stroke-width="2"/><text x="220" y="130" text-anchor="middle" font-size="16" font-weight="900">지민</text><text x="220" y="151" text-anchor="middle" font-size="13">앞 ${payload.frontRank}번째</text><circle cx="460" cy="135" r="30" fill="#e8dfca" stroke="#8a7040" stroke-width="2"/><text x="460" y="130" text-anchor="middle" font-size="16" font-weight="900">지수</text><text x="460" y="151" text-anchor="middle" font-size="13">뒤 ${payload.backRank}번째</text><text x="340" y="58" text-anchor="middle" font-size="20" font-weight="950" fill="#243746">두 사람 사이에는 ${payload.peopleBetween}명</text><text x="340" y="218" text-anchor="middle" font-size="16" font-weight="850" fill="#59636a">전체 사람 수의 최솟값과 최댓값을 구하세요.</text></svg>`;}
  function renderQ36Answer(payload){return`정답: 최솟값 ${payload.answer.min}명, 최댓값 ${payload.answer.max}명 — 가능한 전체 인원은 ${payload.validTotals.join("명, ")}명입니다.`;}

  const Q37_SPEC={easy:4,same:5,hard:6};
  function q37Seatings(payload){const anchor=payload.anchor,others=payload.participants.filter((name)=>name!==anchor);return permutations(others).map((rest)=>[anchor,...rest]).filter((order)=>payload.relations.every((r)=>order[(order.indexOf(r.from)+r.steps)%order.length]===r.person));}
  function generateQ37(difficulty,seed){const count=Q37_SPEC[difficulty]||5,rng=makeRng(seed),participants=shuffle(NAMES,rng).slice(0,count),order=shuffle(participants,rng),anchor=order[0],relations=[];for(let i=1;i<count;i+=1){const from=i===1?anchor:order[i-1],steps=1;relations.push({type:"leftSteps",person:order[i],from,steps});}const payload={participants,anchor,order,relations,answer:order.slice(1),difficulty,seed:Number(seed)||1};if(q37Seatings(payload).length!==1)throw new Error(`q37 ${difficulty} 생성 실패`);return payload;}
  function enumerateQ37AnswerCandidates(payload){return payload?q37Seatings(payload).map((order)=>order.slice(1)):[];}
  function validateQ37(payload){const count=Q37_SPEC[payload&&payload.difficulty],seatings=q37Seatings(payload),answers=enumerateQ37AnswerCandidates(payload);return Boolean(count&&payload.participants.length===count&&seatings.length===1&&answers.length===1&&JSON.stringify(answers[0])===JSON.stringify(payload.answer));}
  function deriveQ37Answer(payload){return payload.answer;}
  function renderQ37Problem(payload){const cx=185,cy=155,r=92,seats=payload.order.map((name,i)=>{const a=-Math.PI/2+i*2*Math.PI/payload.order.length,x=cx+r*Math.cos(a),y=cy+r*Math.sin(a);return`<circle cx="${x}" cy="${y}" r="28" fill="${i===0?'#dcebe7':'#fff'}" stroke="#53636f" stroke-width="2"/><text x="${x}" y="${y+5}" text-anchor="middle" font-size="15" font-weight="900">${i===0?name:'?'}</text>`;}).join(""),conditions=payload.relations.map((r,i)=>`<text x="365" y="${78+i*35}" font-size="18" font-weight="850">${i+1}. ${topic(r.person)} ${r.from}의 바로 왼쪽</text>`).join("");return`<svg class="hf-logic hf-round-table" viewBox="0 0 680 315" role="img" aria-label="왼쪽 방향이 표시된 원탁 자리"><rect width="680" height="315" rx="18" fill="#fff"/><circle cx="${cx}" cy="${cy}" r="58" fill="#f7f2e7" stroke="#9b875e" stroke-width="2"/><path d="M145 47 Q185 20 225 47" fill="none" stroke="#b54a3b" stroke-width="4" marker-end="url(#q37arrow)"/><defs><marker id="q37arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#b54a3b"/></marker></defs><text x="185" y="28" text-anchor="middle" font-size="16" font-weight="900" fill="#b54a3b">왼쪽 방향</text>${seats}<rect x="345" y="48" width="320" height="${45+payload.relations.length*35}" rx="12" fill="#f7f9fb" stroke="#d5dce3"/>${conditions}<text x="185" y="300" text-anchor="middle" font-size="15" font-weight="850" fill="#59636a">모두 가운데를 보고 있습니다.</text></svg>`;}
  function renderQ37Answer(payload){return`정답: 왼쪽 방향으로 ${payload.order.join(" → ")} 순서입니다.`;}

  const Q38_SPEC={easy:6,same:10,hard:12};
  function generateQ38(difficulty,seed){const participantCount=Q38_SPEC[difficulty]||10,rng=makeRng(seed),rightOffset=rng.int(1,participantCount/2-1),answer=participantCount/2-rightOffset;return{participantCount,rightOffset,answer,difficulty,seed:Number(seed)||1};}
  function enumerateQ38AnswerCandidates(payload){return payload&&payload.participantCount%2===0?[payload.participantCount/2-payload.rightOffset]:[];}
  function validateQ38(payload){const count=Q38_SPEC[payload&&payload.difficulty],c=enumerateQ38AnswerCandidates(payload);return Boolean(count&&payload.participantCount===count&&payload.rightOffset>0&&payload.rightOffset<count/2&&c.length===1&&c[0]===payload.answer);}
  function deriveQ38Answer(payload){return payload.answer;}
  function renderQ38Problem(payload){const cx=340,cy=145,r=98,dots=Array.from({length:payload.participantCount},(_,i)=>{const a=-Math.PI/2+i*2*Math.PI/payload.participantCount,x=cx+r*Math.cos(a),y=cy+r*Math.sin(a),anchor=i===0;return`<circle cx="${x}" cy="${y}" r="${anchor?18:10}" fill="${anchor?'#dcebe7':'#fff'}" stroke="#52636f" stroke-width="2"/>${anchor?`<text x="${x}" y="${y+5}" text-anchor="middle" font-size="11" font-weight="900">지연</text>`:''}`;}).join("");return`<svg class="hf-logic hf-circle-view" viewBox="0 0 680 295" role="img" aria-label="가운데를 보는 원형 자리"><rect width="680" height="295" rx="18" fill="#fff"/><circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="#b6c0c8" stroke-width="2"/>${dots}<text x="340" y="270" text-anchor="middle" font-size="16" font-weight="850" fill="#59636a">${payload.participantCount}명이 가운데를 보고 앉아 있습니다.</text></svg>`;}
  function renderQ38Answer(payload){return`정답: 왼쪽 ${payload.answer}번째 — ${payload.participantCount}÷2-${payload.rightOffset}=${payload.answer}입니다.`;}

  const Q39_CATEGORIES=["사과","배","귤","딸기","포도"],Q39_SPEC={easy:3,same:4,hard:5};
  function combinations(values,count){const out=[];function visit(start,row){if(row.length===count){out.push(row);return;}for(let i=start;i<=values.length-(count-row.length);i+=1)visit(i+1,row.concat(values[i]));}visit(0,[]);return out;}
  function q39Pairs(payload){const fixed=payload.entities.filter((name)=>name!==payload.queryEntity),base=Object.fromEntries(payload.categories.map((category)=>[category,0]));fixed.forEach((name)=>payload.knownLikes[name].forEach((category)=>{base[category]+=1;}));return combinations(payload.categories,2).filter((pair)=>payload.categories.every((category)=>base[category]+(pair.includes(category)?1:0)===payload.categoryCounts[category]));}
  function generateQ39(difficulty,seed){const count=Q39_SPEC[difficulty]||4,rng=makeRng(seed),entities=Array.from({length:count},(_,i)=>String.fromCharCode(65+i)),categories=Q39_CATEGORIES.slice(0,count),matrix={},pairs=combinations(categories,2);entities.forEach((name)=>{matrix[name]=rng.pick(pairs);});const queryEntity=rng.pick(entities),knownLikes=Object.fromEntries(entities.filter((name)=>name!==queryEntity).map((name)=>[name,matrix[name]])),categoryCounts=Object.fromEntries(categories.map((category)=>[category,entities.filter((name)=>matrix[name].includes(category)).length])),payload={entities,categories,queryEntity,knownLikes,categoryCounts,answer:matrix[queryEntity].slice().sort(),difficulty,seed:Number(seed)||1};if(q39Pairs(payload).length!==1)return generateQ39(difficulty,(Number(seed)||1)+7919);return payload;}
  function enumerateQ39AnswerCandidates(payload){return payload?q39Pairs(payload).map((pair)=>pair.slice().sort()):[];}
  function validateQ39(payload){const count=Q39_SPEC[payload&&payload.difficulty],c=enumerateQ39AnswerCandidates(payload);return Boolean(count&&payload.entities.length===count&&payload.categories.length===count&&c.length===1&&JSON.stringify(c[0])===JSON.stringify(payload.answer));}
  function deriveQ39Answer(payload){return payload.answer;}
  function renderQ39Problem(payload){const cell=54,ox=115,oy=45,heads=payload.categories.map((category,i)=>`<text x="${ox+(i+1)*cell+cell/2}" y="28" text-anchor="middle" font-size="13" font-weight="900">${category}</text>`).join(""),rows=payload.entities.map((name,r)=>{const cells=payload.categories.map((category,c)=>{const known=name!==payload.queryEntity,like=known&&payload.knownLikes[name].includes(category);return`<rect x="${ox+(c+1)*cell}" y="${oy+r*cell}" width="${cell}" height="${cell}" fill="${name===payload.queryEntity?'#fff8e9':'#fff'}" stroke="#75828d"/><text x="${ox+(c+1)*cell+cell/2}" y="${oy+r*cell+35}" text-anchor="middle" font-size="20" font-weight="950">${known?(like?'O':'×'):'?'}</text>`;}).join("");return`<rect x="${ox}" y="${oy+r*cell}" width="${cell}" height="${cell}" fill="#eef3f6" stroke="#75828d"/><text x="${ox+cell/2}" y="${oy+r*cell+35}" text-anchor="middle" font-size="17" font-weight="950">${name}</text>${cells}`;}).join(""),counts=payload.categories.map((category)=>`${category} ${payload.categoryCounts[category]}명`).join(" · ");return`<svg class="hf-logic hf-logic-matrix" viewBox="0 0 680 ${95+payload.entities.length*cell}" role="img" aria-label="좋아하는 것을 찾는 논리표"><rect width="680" height="${95+payload.entities.length*cell}" rx="18" fill="#fff"/>${heads}${rows}<text x="340" y="${78+payload.entities.length*cell}" text-anchor="middle" font-size="14" font-weight="850" fill="#59636a">각 사람은 2개 선택 · ${counts}</text></svg>`;}
  function renderQ39Answer(payload){return`정답: ${payload.answer.join(", ")} — 다른 사람의 O를 먼저 세고 각 열의 ${payload.categories.map((c)=>payload.categoryCounts[c]).join(", ")}명 조건을 맞춥니다.`;}

  const Q40_RULES=[[1,1,-1],[1,-1,1],[-1,1,1]],Q40_SPEC={easy:2,same:3,hard:4};
  function q40Apply(rule,outer){return rule[0]*outer[0]+rule[1]*outer[1]+rule[2]*outer[2];}
  function q40Candidates(payload){const rules=Q40_RULES.filter((rule)=>payload.examples.every((example)=>q40Apply(rule,example.outer)===example.inner)),answers=[];for(const rule of rules){const [a,b]=payload.target.outer,coefficient=rule[2],value=(payload.target.inner-rule[0]*a-rule[1]*b)/coefficient;if(Number.isInteger(value)&&value>=0&&value<=9)answers.push({rule,answer:value});}return answers;}
  function generateQ40(difficulty,seed){const count=Q40_SPEC[difficulty]||3,rng=makeRng(seed);for(let attempt=0;attempt<1000;attempt+=1){const rule=rng.pick(Q40_RULES),examples=[];while(examples.length<count){const outer=[rng.int(1,9),rng.int(1,9),rng.int(1,9)],inner=q40Apply(rule,outer);if(inner>=1&&inner<=15)examples.push({outer,inner});}const answer=rng.int(1,9),targetOuter=[rng.int(1,9),rng.int(1,9),answer],target={outer:[targetOuter[0],targetOuter[1],null],inner:q40Apply(rule,targetOuter)},payload={rule,examples,target,answer,difficulty,seed:Number(seed)||1},c=q40Candidates(payload);if(c.length===1&&c[0].answer===answer)return payload;}throw new Error(`q40 ${difficulty} 생성 실패`);}
  function enumerateQ40AnswerCandidates(payload){if(!payload)return[];return[...new Set(q40Candidates(payload).map((row)=>row.answer))];}
  function validateQ40(payload){const count=Q40_SPEC[payload&&payload.difficulty],rules=q40Candidates(payload),answers=enumerateQ40AnswerCandidates(payload);return Boolean(count&&payload.examples.length===count&&rules.length===1&&answers.length===1&&answers[0]===payload.answer);}
  function deriveQ40Answer(payload){return payload.answer;}
  function q40Triangle(outer,inner,cx,cy,label){const values=outer.map((value)=>value===null?'?':value);return`<g><polygon points="${cx},${cy-55} ${cx-62},${cy+50} ${cx+62},${cy+50}" fill="#fff8e9" stroke="#8a7040" stroke-width="3"/><circle cx="${cx}" cy="${cy+12}" r="23" fill="#fff" stroke="#8a7040"/><text x="${cx}" y="${cy-27}" text-anchor="middle" font-size="20" font-weight="950">${values[0]}</text><text x="${cx-39}" y="${cy+39}" text-anchor="middle" font-size="20" font-weight="950">${values[1]}</text><text x="${cx+39}" y="${cy+39}" text-anchor="middle" font-size="20" font-weight="950">${values[2]}</text><text x="${cx}" y="${cy+19}" text-anchor="middle" font-size="20" font-weight="950">${inner}</text><text x="${cx}" y="${cy+74}" text-anchor="middle" font-size="13" font-weight="850" fill="#59636a">${label}</text></g>`;}
  function renderQ40Problem(payload){const all=payload.examples.concat(payload.target),isTwoRows=all.length===5,positions=isTwoRows?[[130,100],[340,100],[550,100],[230,280],[450,280]]:all.map((_,i)=>[40+300/all.length+i*(600/all.length),105]),figures=all.map((row,i)=>q40Triangle(row.outer,row.inner,positions[i][0],positions[i][1],i<payload.examples.length?`${i+1}번 예`:'문제')).join("");const height=isTwoRows?390:210;return`<svg class="hf-logic hf-number-code" viewBox="0 0 680 ${height}" role="img" aria-label="삼각형 안 숫자 규칙"><rect width="680" height="${height}" rx="18" fill="#fff"/>${figures}</svg>`;}
  function renderQ40Answer(payload){const signs=payload.rule.map((c)=>c===1?'+':'-');return`정답: ${payload.answer} — 바깥 수를 ${signs[0]}${signs[1]}${signs[2]} 규칙으로 계산하면 가운데 수가 됩니다.`;}

  global.HFQ35={generateQ35,validateQ35,enumerateQ35AnswerCandidates,renderQ35Problem,deriveQ35Answer,renderQ35Answer};
  global.HFQ36={generateQ36,validateQ36,enumerateQ36AnswerCandidates,renderQ36Problem,deriveQ36Answer,renderQ36Answer};
  global.HFQ37={generateQ37,validateQ37,enumerateQ37AnswerCandidates,renderQ37Problem,deriveQ37Answer,renderQ37Answer};
  global.HFQ38={generateQ38,validateQ38,enumerateQ38AnswerCandidates,renderQ38Problem,deriveQ38Answer,renderQ38Answer};
  global.HFQ39={generateQ39,validateQ39,enumerateQ39AnswerCandidates,renderQ39Problem,deriveQ39Answer,renderQ39Answer};
  global.HFQ40={generateQ40,validateQ40,enumerateQ40AnswerCandidates,renderQ40Problem,deriveQ40Answer,renderQ40Answer};
})(typeof window!=="undefined"?window:globalThis);
