(function(root){
 'use strict';
 const $=id=>document.getElementById(id),catalog=root.HFChallengeAccessCatalog.list();
 let students=[],selected=null,original=new Set(),desired=new Set(),busy=false,authEpoch=0,authListener=false,expiryTimer=null;
 function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
 function clearPrivate(){authEpoch++;students=[];selected=null;original.clear();desired.clear();$('student').replaceChildren(new Option('학생 선택',''));$('student').disabled=true;$('permissions').hidden=true;$('book-options').replaceChildren();$('bank-options').replaceChildren();$('student-name').textContent='';if(expiryTimer)clearTimeout(expiryTimer);status('로그인 상태가 바뀌었습니다. 학생 목록을 다시 확인해 주세요.');}
 async function invoke(name,body){if(root.GFieldHFSupabase?.enabled()!==true)throw Error('서버 연결 설정을 확인해 주세요.');const version=authEpoch,client=await root.GFieldHFSupabase.ready();if(!authListener&&client.auth?.onAuthStateChange){authListener=true;client.auth.onAuthStateChange(event=>{if(['SIGNED_OUT','SIGNED_IN','USER_UPDATED','TOKEN_REFRESHED'].includes(event))clearPrivate();});}if(client.auth?.getSession){const result=await client.auth.getSession(),expires=result.data?.session?.expires_at;if(Number.isFinite(expires)){if(expiryTimer)clearTimeout(expiryTimer);expiryTimer=setTimeout(clearPrivate,Math.max(0,expires*1000-Date.now()));}}const {data,error}=await client.functions.invoke(name,{body});if(version!==authEpoch)throw Error('로그인 상태가 변경되어 이전 응답을 표시하지 않습니다.');if(error||data?.error)throw Error(data?.error||'관리자 로그인과 서버 연결을 확인해 주세요.');return data;}
 function changes(){return catalog.filter(e=>original.has(e.key)!==desired.has(e.key)).map(e=>({key:e.key,enabled:desired.has(e.key)}));}
 function sync(){const count=changes().length;$('change-count').textContent=count?`${count}개 항목 변경`:'변경 없음';$('save').disabled=busy||!selected||count===0;}
 function option(entry){const label=document.createElement('label');label.className='permission-item';const input=document.createElement('input');input.type='checkbox';input.checked=desired.has(entry.key);input.disabled=busy||selected?.status!=='active';input.dataset.key=entry.key;input.addEventListener('change',()=>{input.checked?desired.add(entry.key):desired.delete(entry.key);sync();});const span=document.createElement('span');span.textContent=entry.label;if(entry.kind==='bank'){const small=document.createElement('small');small.textContent=`${entry.round}회 ${entry.section==='extra'?'추가 ':''}${entry.number}번 · ${entry.area}`;span.append(small);}label.append(input,span);return label;}
 function render(){const books=$('book-options');books.replaceChildren();for(const[kind,title]of[['concept','개념 교재'],['mock','모의고사']]){const section=document.createElement('section');section.className='permission-group';const h=document.createElement('h3');h.textContent=title;section.append(h);catalog.filter(e=>e.kind===kind).forEach(e=>section.append(option(e)));books.append(section);}renderBank();sync();}
 function renderBank(){const bank=$('bank-options'),round=$('round-filter').value,area=$('area-filter').value,search=$('type-search').value.trim();bank.replaceChildren();const entries=catalog.filter(e=>e.kind==='bank'&&(round==='all'||String(e.round)===round)&&(area==='all'||e.area===area)&&(!search||e.label.includes(search)));entries.forEach(e=>bank.append(option(e)));if(!entries.length){const p=document.createElement('p');p.textContent='조건에 맞는 유형이 없습니다.';bank.append(p);}}
 function selectStudent(){selected=students.find(s=>s.id===$('student').value)||null;$('permissions').hidden=!selected;if(!selected)return;original=new Set((selected.permissions||[]).filter(k=>root.HFChallengeAccessCatalog.has(k)));desired=new Set(original);$('student-name').textContent=selected.name+' 학생';render();status(selected.status==='active'?'필요한 교재와 유형을 선택해 주세요.':'비활성 학생입니다. 기존 학생 관리에서 상태를 확인해 주세요.',selected.status!=='active');}
 async function load(){if(busy)return;busy=true;$('reload').disabled=true;status('기존 학생 목록을 확인하고 있습니다.');try{const data=await invoke('admin-students',{action:'list'});if(!Array.isArray(data.students))throw Error('학생 목록 응답을 확인할 수 없습니다.');students=data.students;const select=$('student');select.replaceChildren(new Option('학생 선택',''));students.forEach(s=>select.append(new Option(s.name+(s.status==='active'?'':' · 비활성'),s.id)));select.disabled=false;selected=null;$('permissions').hidden=true;status('학생을 선택해 주세요.');}catch(e){students=[];selected=null;$('student').disabled=true;$('permissions').hidden=true;status(e.message,true);}finally{busy=false;$('reload').disabled=false;}}
 async function save(){if(busy||!selected)return;const edits=changes();if(!edits.length)return;busy=true;render();$('student').disabled=true;$('reload').disabled=true;let done=0;try{for(const edit of edits){await invoke('challenge-access',{action:'set',studentId:selected.id,permissionKey:edit.key,enabled:edit.enabled});edit.enabled?original.add(edit.key):original.delete(edit.key);done++;}status(`${done}개 승인 항목을 저장했습니다.`);}catch(e){status(`${done}개 저장되었습니다. 저장되지 않은 변경은 남아 있습니다. ${e.message}`,true);}finally{if(selected)selected.permissions=[...new Set([...(selected.permissions||[]).filter(k=>!root.HFChallengeAccessCatalog.has(k)),...original])];busy=false;$('student').disabled=!students.length;$('reload').disabled=false;render();}}
 [...new Set(catalog.filter(e=>e.kind==='bank').map(e=>e.area))].forEach(area=>$('area-filter').append(new Option(area,area)));
 $('reload').addEventListener('click',load);$('student').addEventListener('change',selectStudent);$('save').addEventListener('click',save);['round-filter','area-filter'].forEach(id=>$(id).addEventListener('change',renderBank));$('type-search').addEventListener('input',renderBank);
 // No automatic write or fake local grants; the user initiates the authenticated server read.
})(window);
