import { levels, resultFor } from "./levels.js?v=hidden-shape-3";
import { shapeSvg } from "./art.js?v=hidden-shape-3";
import { readGameProgress, saveGameProgress } from "../../shared/profile-storage.js";

const $ = (selector) => document.querySelector(selector);
const params = new URLSearchParams(location.search);
const saved = readGameProgress("hiddenShape");
const storedLanguage = localStorage.getItem("gfield-language") || "ko";
const lang = ["ko","en","zh","ja"].includes(storedLanguage) ? storedLanguage : "ko";
const requestedLevel = Math.max(1, Math.min(5, Number(params.get("level")) || Number(saved.level) || 1));
const SESSION_SIZE = 5, recentKey = "gfield-hidden-shape-recent";

const copy = {
  ko:{levels:"레벨",hint:"힌트",retry:"다시",next:"다음 문제",promptFan:"다음 도형에서 찾을 수 있는 크고 작은 삼각형은 모두 몇 개인가요?",promptSquare:"정사각형 모눈에서 찾을 수 있는 크고 작은 정사각형은 모두 몇 개인가요?",promptRect:"그림에서 찾을 수 있는 크고 작은 사각형은 모두 몇 개입니까?",promptTri:"정삼각형 모눈에서 찾을 수 있는 크고 작은 삼각형은 모두 몇 개인가요?",triangle:"삼각형",square:"정사각형",rectangle:"사각형",thinking:"생각 중",correct:"정답",wrong:"조금 빠뜨렸거나 겹쳐 센 것 같아요.",found:"숨어 있는 도형을 모두 찾았어요!",breakdown:"이렇게 나누어 셀 수 있어요",fanBreakdown:"밑변 길이별 개수를 모두 더해요",levelComplete:"레벨 {n} 완료!",complete:"숨어 있는 도형을 기준에 따라 빠짐없이 찾았어요.",nextLevel:"다음 레벨",practice:"같은 레벨 더 풀기",garden:"도형 정원",chooseLevel:"레벨 선택",problem:"문제",countRule:"세는 기준",guideFan:"밑변의 길이",guideLayer:"가로선과 밑변의 길이",guideSquare:"한 변의 칸 수",guideRect:"사각형의 넓이",guideTri:"방향과 크기",hintFan:"밑변이 1칸짜리부터 가장 긴 것까지 차례로 세어 모두 더해 보세요.",hintLayer:"각 가로선에서 밑변이 1칸짜리부터 가장 긴 것까지 세어 보세요.",hintSquare:"1칸짜리를 센 뒤 2칸, 3칸 정사각형으로 넓혀 보세요.",hintRect:"빈칸이 끼어 있으면 완성된 사각형이 아니에요.",hintTri:"위쪽을 향한 삼각형을 센 뒤 아래쪽도 따로 찾아보세요.",oneBase:"가로선 한 줄",bases:"가로선",fanSize:"밑변 {n}칸",size:"한 변 {n}칸",area:"넓이 {n}",up:"위 방향",down:"아래 방향"},
  en:{levels:"Levels",hint:"Hint",retry:"Retry",next:"Next",promptFan:"How many large and small triangles can you find in the figure?",promptSquare:"How many large and small squares can you find in the square grid?",promptRect:"How many large and small quadrilaterals can you find in the figure?",promptTri:"How many large and small triangles can you find in the triangular grid?",triangle:"triangles",square:"squares",rectangle:"quadrilaterals",thinking:"Thinking",correct:"Correct",wrong:"Check for a missed or double-counted shape.",found:"You found every hidden shape!",breakdown:"Count them in these groups",fanBreakdown:"Add the counts for every base length",levelComplete:"Level {n} complete!",complete:"You found every shape using a clear counting rule.",nextLevel:"Next level",practice:"Practice again",garden:"Shape Garden",chooseLevel:"Choose a level",problem:"Problem",countRule:"Counting rule",guideFan:"Base length",guideLayer:"Base line and length",guideSquare:"Side length",guideRect:"Quadrilateral area",guideTri:"Direction and size",hintFan:"Count base lengths from 1 unit through the longest, then add.",hintLayer:"On every horizontal line, count base lengths from 1 unit through the longest.",hintSquare:"Count 1-cell squares, then 2-cell and larger squares.",hintRect:"A quadrilateral with a missing cell is not complete.",hintTri:"Count upward triangles, then downward triangles.",oneBase:"One base line",bases:"Base lines",fanSize:"Base {n} units",size:"Side {n} units",area:"Area {n}",up:"Upward",down:"Downward"}
};
const t=(key,vars={})=>Object.entries(vars).reduce((value,[name,replacement])=>value.replaceAll(`{${name}}`,replacement),copy[lang]?.[key]||copy.ko[key]||key);
const local=(value)=>value?.[lang]||value?.ko||value;
function shuffle(items){const result=[...items];for(let index=result.length-1;index>0;index-=1){const swap=Math.floor(Math.random()*(index+1));[result[index],result[swap]]=[result[swap],result[index]];}return result;}
function makeSession(levelIndex){let recent={};try{recent=JSON.parse(localStorage.getItem(recentKey)||"{}");}catch{recent={};}const excluded=new Set(recent[levelIndex+1]||[]);let pool=levels[levelIndex].problems.filter((problem)=>!excluded.has(problem.id));if(pool.length<SESSION_SIZE)pool=levels[levelIndex].problems;const session=shuffle(pool).slice(0,SESSION_SIZE);recent[levelIndex+1]=session.map((problem)=>problem.id);localStorage.setItem(recentKey,JSON.stringify(recent));return session;}

const state={level:requestedLevel-1,index:0,queue:makeSession(requestedLevel-1),solved:false,audio:localStorage.getItem("gfield-audio-muted")!=="true"};
const ui={levelLabel:$("#levelLabel"),problemLabel:$("#problemLabel"),difficulty:$("#difficultyLabel"),title:$("#missionTitle"),prompt:$("#prompt"),guideTitle:$("#guideTitle"),guideText:$("#guideText"),clueTitle:$("#clueTitle"),clueValue:$("#clueValue"),problemId:$("#problemId"),boardTag:$("#boardTag"),boardTitle:$("#boardTitle"),status:$("#answerStatus"),board:$("#shapeBoard"),choices:$("#choiceTray"),breakdown:$("#breakdown"),breakdownTitle:$("#breakdownTitle"),breakdownList:$("#breakdownList"),hint:$("#hintButton"),retry:$("#retryButton"),next:$("#nextButton"),sound:$("#soundButton"),levels:$("#levelButton"),levelDialog:$("#levelDialog"),levelList:$("#levelList"),closeLevels:$("#closeLevels"),complete:$("#completeDialog"),completeTitle:$("#completeTitle"),completeText:$("#completeText"),nextLevel:$("#nextLevelButton"),practice:$("#practiceButton"),success:$("#success"),toast:$("#toast")};
const problem=()=>state.queue[state.index], currentLevel=()=>levels[state.level];

function kindCopy(problemData){
  if(problemData.kind==="fan")return {shape:t("triangle"),tag:problemData.horizontalCount?"LAYERED TRIANGLES":"TRIANGLE FAN",rule:problemData.horizontalCount?t("guideLayer"):t("guideFan"),hint:problemData.horizontalCount?t("hintLayer"):t("hintFan")};
  if(problemData.kind==="square-grid")return {shape:t("square"),tag:"SQUARE GRID",rule:t("guideSquare"),hint:t("hintSquare")};
  if(problemData.kind==="irregular-grid")return {shape:t("rectangle"),tag:"JOINED RECTANGLES",rule:t("guideRect"),hint:t("hintRect")};
  return {shape:t("triangle"),tag:"TRIANGLE GRID",rule:t("guideTri"),hint:t("hintTri")};
}
function promptFor(problemData){if(problemData.kind==="fan")return t("promptFan");if(problemData.kind==="square-grid")return t("promptSquare");if(problemData.kind==="irregular-grid")return t("promptRect");return t("promptTri");}

function render(){
  const p=problem(),level=currentLevel(),kind=kindCopy(p);state.solved=false;document.documentElement.lang=lang;
  ui.levelLabel.textContent=`LEVEL ${level.id}`;ui.problemLabel.textContent=`${state.index+1} / ${SESSION_SIZE}`;ui.difficulty.textContent=level.difficulty;ui.title.textContent=local(level.title);ui.prompt.textContent=promptFor(p);ui.guideTitle.textContent=local(level.description);ui.guideText.textContent=kind.hint;ui.clueTitle.textContent=t("countRule");ui.clueValue.textContent=kind.rule;ui.problemId.textContent=p.id.slice(-2);ui.boardTag.textContent=kind.tag;ui.boardTitle.textContent=local(level.description);ui.status.textContent=t("thinking");ui.status.classList.remove("correct");ui.board.innerHTML=shapeSvg(p,{label:ui.prompt.textContent});ui.board.classList.remove("hint");ui.breakdown.hidden=true;ui.breakdownTitle.textContent=t("breakdown");ui.breakdownList.replaceChildren();ui.next.hidden=true;renderChoices();saveGameProgress("hiddenShape",{level:state.level+1,problemIndex:state.index,queue:state.queue.map((item)=>item.id)});
}

function renderChoices(){ui.choices.replaceChildren();problem().choices.forEach((choice,index)=>{const button=document.createElement("button");button.type="button";button.textContent=choice;button.addEventListener("click",()=>choose(index,button));ui.choices.append(button);});}
function choose(index,button){if(state.solved)return;const p=problem();if(index!==p.answerIndex){button.classList.add("wrong");tone("wrong");showToast(t("wrong"));setTimeout(()=>button.classList.remove("wrong"),500);return;}state.solved=true;button.classList.add("correct");ui.choices.querySelectorAll("button").forEach((item)=>item.disabled=true);ui.status.textContent=`${t("correct")} · ${p.answer}`;ui.status.classList.add("correct");showBreakdown();ui.next.hidden=false;showToast(t("found"));celebrate();saveGameProgress("hiddenShape",{level:state.level+1,completedProblem:p.id});}

function chip(label,value){const span=document.createElement("span");span.textContent=`${label} · ${value}`;ui.breakdownList.append(span);}
function showBreakdown(){const p=problem(),result=resultFor(p);ui.breakdown.hidden=false;if(p.kind==="fan"){ui.breakdownTitle.textContent=t("fanBreakdown");if(p.horizontalCount)chip(t("bases"),result.bases);result.byWidth.forEach((item)=>chip(t("fanSize",{n:item.size}),item.count));chip(result.byWidth.map((item)=>item.count).join(" + "),result.total);}else if(p.kind==="square-grid"){result.bySize.forEach((item)=>chip(t("size",{n:item.size}),item.count));}else if(p.kind==="irregular-grid"){result.byArea.forEach((item)=>chip(t("area",{n:item.area}),item.count));}else{chip(t("up"),result.upward);chip(t("down"),result.downward);}}
function hint(){if(state.solved)return;const kind=kindCopy(problem());showToast(kind.hint);ui.board.classList.remove("hint");void ui.board.offsetWidth;ui.board.classList.add("hint");setTimeout(()=>ui.board.classList.remove("hint"),900);}
function nextProblem(){if(!state.solved)return;if(state.index<SESSION_SIZE-1){state.index+=1;render();return;}ui.completeTitle.textContent=t("levelComplete",{n:state.level+1});ui.completeText.textContent=t("complete");ui.nextLevel.textContent=t("nextLevel");ui.nextLevel.hidden=state.level===levels.length-1;ui.practice.textContent=t("practice");ui.complete.querySelector("a").textContent=t("garden");ui.complete.hidden=false;}
function startLevel(index){state.level=index;state.index=0;state.queue=makeSession(index);ui.levelDialog.hidden=true;ui.complete.hidden=true;render();}
function renderLevelDialog(){ui.levelList.replaceChildren();levels.forEach((level,index)=>{const button=document.createElement("button");button.type="button";button.innerHTML=`<span>${level.id}</span><strong>${local(level.title)}</strong><small>${local(level.description)}</small>`;button.addEventListener("click",()=>startLevel(index));ui.levelList.append(button);});}
function tone(kind){if(!state.audio)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;const context=new AudioContext(),notes=kind==="success"?[523,659,784]:[180,145];notes.forEach((frequency,index)=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,context.currentTime+index*.08);gain.gain.exponentialRampToValueAtTime(.08,context.currentTime+index*.08+.015);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+index*.08+.18);oscillator.connect(gain).connect(context.destination);oscillator.start(context.currentTime+index*.08);oscillator.stop(context.currentTime+index*.08+.2);});setTimeout(()=>context.close(),600);}
function celebrate(){ui.success.classList.remove("show");void ui.success.offsetWidth;ui.success.classList.add("show");tone("success");}
function showToast(message){ui.toast.textContent=message;ui.toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>ui.toast.classList.remove("show"),2200);}

ui.hint.addEventListener("click",hint);ui.retry.addEventListener("click",render);ui.next.addEventListener("click",nextProblem);ui.levels.addEventListener("click",()=>{ui.levelDialog.hidden=false;});ui.closeLevels.addEventListener("click",()=>{ui.levelDialog.hidden=true;});ui.nextLevel.addEventListener("click",()=>startLevel(Math.min(levels.length-1,state.level+1)));ui.practice.addEventListener("click",()=>startLevel(state.level));ui.sound.addEventListener("click",()=>{state.audio=!state.audio;localStorage.setItem("gfield-audio-muted",String(!state.audio));ui.sound.innerHTML=state.audio?"&#9835;":"&#9834;&#824;";});
renderLevelDialog();render();
