-- Local additive catalogue only. No student grants, revocations, or automatic mode switch.
-- Written without CLI under explicit scope exception; not applied to any database.
begin;
insert into public.hf_permission_catalog(permission_key,label,description) values
('hyperfocus-bank-q01','HF 01 유형','Hyper Focus 유사문제·문제은행 유형 1 개별 승인'),
('hyperfocus-bank-q02','HF 02 유형','Hyper Focus 유사문제·문제은행 유형 2 개별 승인'),
('hyperfocus-bank-q03','HF 03 유형','Hyper Focus 유사문제·문제은행 유형 3 개별 승인'),
('hyperfocus-bank-q04','HF 04 유형','Hyper Focus 유사문제·문제은행 유형 4 개별 승인'),
('hyperfocus-bank-q05','HF 05 유형','Hyper Focus 유사문제·문제은행 유형 5 개별 승인'),
('hyperfocus-bank-q06','HF 06 유형','Hyper Focus 유사문제·문제은행 유형 6 개별 승인'),
('hyperfocus-bank-q07','HF 07 유형','Hyper Focus 유사문제·문제은행 유형 7 개별 승인'),
('hyperfocus-bank-q08','HF 08 유형','Hyper Focus 유사문제·문제은행 유형 8 개별 승인'),
('hyperfocus-bank-q09','HF 09 유형','Hyper Focus 유사문제·문제은행 유형 9 개별 승인'),
('hyperfocus-bank-q18','HF 18 유형','Hyper Focus 유사문제·문제은행 유형 18 개별 승인'),
('hyperfocus-bank-q10','HF 10 유형','Hyper Focus 유사문제·문제은행 유형 10 개별 승인'),
('hyperfocus-bank-q11','HF 11 유형','Hyper Focus 유사문제·문제은행 유형 11 개별 승인'),
('hyperfocus-bank-q12','HF 12 유형','Hyper Focus 유사문제·문제은행 유형 12 개별 승인'),
('hyperfocus-bank-q13','HF 13 유형','Hyper Focus 유사문제·문제은행 유형 13 개별 승인'),
('hyperfocus-bank-q14','HF 14 유형','Hyper Focus 유사문제·문제은행 유형 14 개별 승인'),
('hyperfocus-bank-q15','HF 15 유형','Hyper Focus 유사문제·문제은행 유형 15 개별 승인'),
('hyperfocus-bank-q16','HF 16 유형','Hyper Focus 유사문제·문제은행 유형 16 개별 승인'),
('hyperfocus-bank-q17','HF 17 유형','Hyper Focus 유사문제·문제은행 유형 17 개별 승인'),
('hyperfocus-bank-q19','HF 19 유형','Hyper Focus 유사문제·문제은행 유형 19 개별 승인'),
('hyperfocus-bank-q32','HF 32 유형','Hyper Focus 유사문제·문제은행 유형 32 개별 승인'),
('hyperfocus-bank-q38','HF 38 유형','Hyper Focus 유사문제·문제은행 유형 38 개별 승인'),
('hyperfocus-bank-q22','HF 22 유형','Hyper Focus 유사문제·문제은행 유형 22 개별 승인'),
('hyperfocus-bank-q23','HF 23 유형','Hyper Focus 유사문제·문제은행 유형 23 개별 승인'),
('hyperfocus-bank-q24','HF 24 유형','Hyper Focus 유사문제·문제은행 유형 24 개별 승인'),
('hyperfocus-bank-q25','HF 25 유형','Hyper Focus 유사문제·문제은행 유형 25 개별 승인'),
('hyperfocus-bank-q27','HF 27 유형','Hyper Focus 유사문제·문제은행 유형 27 개별 승인'),
('hyperfocus-bank-q34','HF 34 유형','Hyper Focus 유사문제·문제은행 유형 34 개별 승인'),
('hyperfocus-bank-q40','HF 40 유형','Hyper Focus 유사문제·문제은행 유형 40 개별 승인'),
('hyperfocus-bank-q21','HF 21 유형','Hyper Focus 유사문제·문제은행 유형 21 개별 승인'),
('hyperfocus-bank-q29','HF 29 유형','Hyper Focus 유사문제·문제은행 유형 29 개별 승인'),
('hyperfocus-bank-q31','HF 31 유형','Hyper Focus 유사문제·문제은행 유형 31 개별 승인'),
('hyperfocus-bank-q35','HF 35 유형','Hyper Focus 유사문제·문제은행 유형 35 개별 승인'),
('hyperfocus-bank-q37','HF 37 유형','Hyper Focus 유사문제·문제은행 유형 37 개별 승인'),
('hyperfocus-bank-q39','HF 39 유형','Hyper Focus 유사문제·문제은행 유형 39 개별 승인'),
('hyperfocus-bank-q41','HF 41 유형','Hyper Focus 유사문제·문제은행 유형 41 개별 승인'),
('hyperfocus-bank-q20','HF 20 유형','Hyper Focus 유사문제·문제은행 유형 20 개별 승인'),
('hyperfocus-bank-q30','HF 30 유형','Hyper Focus 유사문제·문제은행 유형 30 개별 승인'),
('hyperfocus-bank-q42','HF 42 유형','Hyper Focus 유사문제·문제은행 유형 42 개별 승인'),
('hyperfocus-bank-q43','HF 43 유형','Hyper Focus 유사문제·문제은행 유형 43 개별 승인'),
('hyperfocus-bank-q44','HF 44 유형','Hyper Focus 유사문제·문제은행 유형 44 개별 승인'),
('hyperfocus-bank-q45','HF 45 유형','Hyper Focus 유사문제·문제은행 유형 45 개별 승인'),
('hyperfocus-bank-q26','HF 26 유형','Hyper Focus 유사문제·문제은행 유형 26 개별 승인'),
('hyperfocus-bank-q28','HF 28 유형','Hyper Focus 유사문제·문제은행 유형 28 개별 승인'),
('hyperfocus-bank-q36','HF 36 유형','Hyper Focus 유사문제·문제은행 유형 36 개별 승인'),
('hyperfocus-bank-q50','HF 50 유형','Hyper Focus 유사문제·문제은행 유형 50 개별 승인'),
('hyperfocus-bank-q51','HF 51 유형','Hyper Focus 유사문제·문제은행 유형 51 개별 승인'),
('hyperfocus-bank-q52','HF 52 유형','Hyper Focus 유사문제·문제은행 유형 52 개별 승인'),
('hyperfocus-bank-q54','HF 54 유형','Hyper Focus 유사문제·문제은행 유형 54 개별 승인'),
('hyperfocus-bank-q33','HF 33 유형','Hyper Focus 유사문제·문제은행 유형 33 개별 승인'),
('hyperfocus-bank-q46','HF 46 유형','Hyper Focus 유사문제·문제은행 유형 46 개별 승인'),
('hyperfocus-bank-q47','HF 47 유형','Hyper Focus 유사문제·문제은행 유형 47 개별 승인'),
('hyperfocus-bank-q48','HF 48 유형','Hyper Focus 유사문제·문제은행 유형 48 개별 승인'),
('hyperfocus-bank-q49','HF 49 유형','Hyper Focus 유사문제·문제은행 유형 49 개별 승인'),
('hyperfocus-bank-q53','HF 53 유형','Hyper Focus 유사문제·문제은행 유형 53 개별 승인'),
('hyperfocus-bank-individual-mode','HF 문제은행 개별 승인 모드','관리자가 명시 전환한 학생만 개별 유형 승인 적용. 기존 진단 및 응시기록에는 영향 없음')
on conflict (permission_key) do nothing;
commit;

