-- Additive catalog only. No student grants/revocations and no changes to existing RLS/RPC.
-- Parent: Hyper Focus. Child: Challenge. Fixed source type IDs; no wildcard grant.
insert into public.hf_permission_catalog(permission_key,label,description) values
('challenge-concept-1','개념 교재 1권','Hyper Focus > 챌린지 대비 / concept'),
('challenge-concept-2','개념 교재 2권','Hyper Focus > 챌린지 대비 / concept'),
('challenge-mock-1','모의고사 1회','Hyper Focus > 챌린지 대비 / mock'),
('challenge-mock-2','모의고사 2회','Hyper Focus > 챌린지 대비 / mock'),
('challenge-mock-3','모의고사 3회','Hyper Focus > 챌린지 대비 / mock'),
('challenge-mock-4','모의고사 4회','Hyper Focus > 챌린지 대비 / mock'),
('challenge-bank-replace-count-constraints','여러 수 조건을 함께 만족하기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-split-merge-chain','수 가르기와 모으기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-mock-balance-substitution-pictures','수평 저울의 무게 바꾸기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-triangle-number-rule','삼각형 수의 규칙','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-divided-square-cycle','반복되는 그림 규칙','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-total-difference','합과 차로 두 수 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-rotated-grid-pair','돌려서 같은 그림 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-mountain-digit-count','늘어나는 수 배열 세기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-apartment-floor-order','조건을 연결해 순서 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-house-between','사이와 가운데 위치','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-card-sum-count','합이 되는 카드 고르기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-mock-dice-target-bottom','주사위 굴리기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-arrow-number-move','방향에 따른 수 이동','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-mock-object-length-equivalence','물건으로 길이 비교','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-minimum-sum-pyramid','카드 배치에 따른 합 비교','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-paper-remainder','남은 양을 나누기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-age-chain','나이 관계 연결하기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-cube-count-fill','쌓기나무 채우기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-rectangle-count','선을 따라 사각형 세기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-four-cell-code','그림으로 나타낸 수','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-extra-digit-multiselect','여러 수 조건을 함께 만족하기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-priority-cube-top-view','위에서 본 모양','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-priority-fold-holes','접은 종이의 구멍','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-extra-congruent-partition','조건에 맞게 같은 모양으로 나누기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-extra-inside-outside-analogy','안팎 도형의 변화','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-extra-digital-mirror','거울 속 디지털 식','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-fruit-equations','같은 기호의 수 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-number-machines','수 상자의 규칙과 역산','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-grid-mirror-polygon','모눈의 거울상','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-student-queue','조건을 연결해 순서 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-missing-star-combination','빠진 색칠 조합 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-orange-reverse','처음 수를 거꾸로 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-digit-constraint','자리 숫자의 합과 차','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-compound-matrix','가로·세로 도형 규칙','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-circular-seating','원탁의 방향과 이웃','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-magic-triangle','직선 위 수의 합','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-fruit-pair-cancel','같은 종류를 짝지어 없애기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-priority-route-count','조건이 있는 길의 가짓수','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-domino-side-sums','도미노 테두리의 합','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-replace-line-rotation-series','반복되는 그림 규칙','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-bird-departure','처음 수를 거꾸로 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-number-reference-reading','처음 수를 거꾸로 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-three-balance-order','기울어진 저울의 무게 순서','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-priority-diagonal-length','대각선이 있는 길이 비교','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-triangle-enumeration','선을 따라 삼각형 세기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r2-fruit-logic-table','표를 그려 조건 추리','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-extra-maximum-under-conditions','여러 수 조건을 함께 만족하기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-priority-card-rank','카드로 수를 만들어 순서 정하기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-extra-card-distribution','카드를 한 번씩 나누기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-extra-general-quadrilateral-count','선을 따라 사각형 세기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-extra-independent-color-shape-period','색과 모양의 다른 반복','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-extra-circle-bar-code','그림으로 나타낸 수','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-1','빈칸 수를 구해 비교하기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-2','양이 바뀌는 이야기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-3','늘어나는 묶음의 규칙','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-4','전개도의 마주 보는 색','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-5','서로 다른 세 수 고르기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-6','대각선이 있는 길이 비교','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-7','나이 관계 연결하기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-8','도미노 점의 규칙','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-9-shortest-path-grid','조건이 있는 길의 가짓수','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-10','조건을 연결해 순서 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-11','기호를 넣어 참인 식 만들기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-12','조각으로 모양 채우기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-13','주사위 굴리기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-14','늘어나는 색의 배열','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-15-checker-stack-count','쌓기나무 채우기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-16','남은 양을 나누기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-17','표를 그려 조건 추리','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-18-tetra-cube-hole-count','길쭉한 블록 세기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-19','모든 칸을 한 번씩 지나기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-main-20','처음 수를 거꾸로 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-extra-1-congruent-marked-partition','조건에 맞게 같은 모양으로 나누기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-extra-2','전개도의 마주 보는 눈','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-extra-3-block-build-count','길쭉한 블록 세기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-extra-4-object-length-equivalence','물건으로 길이 비교','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-extra-5','서로 다른 수로 가르기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r3-extra-6-stack-box-fill','쌓기나무 채우기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-1','같은 기호의 수 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-2','양이 바뀌는 이야기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-3','늘어나는 묶음의 규칙','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-4','조각으로 모양 채우기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-5','서로 다른 수로 가르기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-6','앞뒤 순서와 사이의 수','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-7','도미노 점의 규칙','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-8','전개도의 마주 보는 눈','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-9','기호를 넣어 참인 식 만들기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-10','처음 수를 거꾸로 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-11','겹치지 않게 같은 도형 연결','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-12-block-build-count','길쭉한 블록 세기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-13','서로 다른 세 수 고르기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-14','카드를 한 번씩 나누기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-15','주사위 굴리기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-16','옮겨도 같은 전체','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-17-balance-substitution-pictures','수평 저울의 무게 바꾸기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-18-congruent-marked-partition','조건에 맞게 같은 모양으로 나누기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-19','표를 그려 조건 추리','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-main-20','똑같이 나눈 뒤 처음 양 찾기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-extra-1-object-length-equivalence','물건으로 길이 비교','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-extra-2-checker-stack-count','쌓기나무 채우기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-extra-3-tetra-cube-hole-count','길쭉한 블록 세기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-extra-4-shortest-path-grid','조건이 있는 길의 가짓수','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-extra-5-stack-box-fill','쌓기나무 채우기','Hyper Focus > 챌린지 대비 / bank'),
('challenge-bank-r4-extra-6-simple-path-network','조건이 있는 길의 가짓수','Hyper Focus > 챌린지 대비 / bank')
on conflict (permission_key) do update set label=excluded.label,description=excluded.description,is_active=true;
