const SHAPES = {
  L: [[0,0],[0,1],[1,1]], T: [[0,0],[1,0],[2,0],[1,1]], S: [[1,0],[2,0],[0,1],[1,1]],
  I: [[0,0],[1,0],[2,0]], O: [[0,0],[1,0],[0,1],[1,1]], P: [[0,0],[1,0],[0,1],[1,1],[0,2]]
};
const ACTIVITIES = [
  { id: "same", icon: "=", ko: ["같은 모양 찾기", "돌려도 같은 조각을 찾아요."], en: ["Find the Same Shape", "Find the piece that is still the same after a turn."], zh: ["找相同图形", "找出旋转后仍相同的拼片。"], ja: ["同じ形を探す", "回しても同じピースを探します。"], target: "L", choices: ["T","L","S"], answer: 1 },
  { id: "gap", icon: "+", ko: ["빈칸 완성하기", "빈자리에 꼭 맞는 조각을 골라요."], en: ["Fill the Gap", "Choose the piece that fits the empty space."], zh: ["补上空格", "选择正好放进空格的拼片。"], ja: ["空きをうめる", "空いた所にぴったりのピースを選びます。"], target: "T", choices: ["L","T","O"], answer: 1 },
  { id: "hide", icon: "o", ko: ["보이게 가리기", "필요한 그림만 남게 할 조각을 골라요."], en: ["Cover and Reveal", "Choose a piece to leave only what you need to see."], zh: ["遮住再发现", "选择拼片，只留下需要看的图案。"], ja: ["かくして見つける", "見たいものだけ残すピースを選びます。"], target: "O", choices: ["I","O","L"], answer: 1 },
  { id: "blanket", icon: "#", ko: ["담요 만들기", "같은 조각으로 판을 덮을 수 있는 모양을 찾아요."], en: ["Make a Blanket", "Find the shape that can cover the little board."], zh: ["制作小毯子", "找出可以盖满小棋盘的形状。"], ja: ["毛布を作る", "小さな板をおおえる形を探します。"], target: "I", choices: ["S","I","T"], answer: 1 },
  { id: "move", icon: "1", ko: ["한 칸만 옮기기", "한 칸을 옮긴 뒤 생기는 모양을 찾아요."], en: ["Move One Cell", "Find the shape after moving one square."], zh: ["只移动一格", "找出移动一格后形成的图形。"], ja: ["一マス動かす", "一マス動かしたあとの形を探します。"], target: "S", choices: ["T","S","L"], answer: 1 },
  { id: "missing", icon: "?", ko: ["빠진 조각 찾기", "그림을 완성할 마지막 조각을 찾아요."], en: ["Find the Missing Piece", "Find the last piece needed to finish the picture."], zh: ["找缺少的拼片", "找出完成图形的最后一块。"], ja: ["足りないピース", "形を完成させる最後のピースを探します。"], target: "P", choices: ["P","T","S"], answer: 0 },
  { id: "two", icon: "2", ko: ["두 가지 방법 찾기", "같은 모양을 만드는 또 다른 방법을 찾아요."], en: ["Find Another Way", "Find another way to make the same shape."], zh: ["寻找另一种方法", "找出组成同一图形的另一种方法。"], ja: ["もう一つの方法", "同じ形を作る別の方法を探します。"], target: "L", choices: ["S","L","T"], answer: 1 }
];
const copy = { ko:{name:"조각 놀이", kinder:"킨더", kids:"키즈", choose:"알맞은 조각을 눌러 보세요.", good:"맞아요! 다음 활동으로 가 볼까요?", again:"다시 살펴봐요.", next:"다음 활동"}, en:{name:"Piece Play",kinder:"Kinder",kids:"Kids",choose:"Tap the piece that fits.",good:"That is right! Ready for the next activity?",again:"Look one more time.",next:"Next activity"}, zh:{name:"拼片游戏",kinder:"幼儿",kids:"儿童",choose:"点击合适的拼片。",good:"答对了！准备下一个活动。",again:"再看一看。",next:"下一个活动"}, ja:{name:"ピースあそび",kinder:"キンダー",kids:"キッズ",choose:"合うピースを押してみよう。",good:"正解！次の活動に進もう。",again:"もう一度見てみよう。",next:"次の活動"} };
const $ = (s) => document.querySelector(s); const params = new URLSearchParams(location.search); const lang = localStorage.getItem("gfield-language") || "ko"; const track = params.get("track") === "kids" ? "kids" : "kinder"; let index = Math.max(0, ACTIVITIES.findIndex((item) => item.id === params.get("activity"))); if (index < 0) index = 0; let solved = false;
const cells = (shape) => SHAPES[shape];
function renderShape(node, shape, className = "") { const data = cells(shape); const cols = Math.max(...data.map(([x])=>x))+1, rows = Math.max(...data.map(([,y])=>y))+1; node.className = `piece ${className}`; node.style.setProperty("--cols", cols); node.style.setProperty("--rows", rows); data.forEach(([x,y]) => { const cell=document.createElement("i"); cell.style.gridColumn=x+1; cell.style.gridRow=y+1; node.append(cell); }); }
function activity() { return ACTIVITIES[index]; }
function render() { const item=activity(), words=item[lang]||item.en, ui=copy[lang]||copy.en; solved=false; $("#subtitle").textContent=ui.name; $("#trackLabel").textContent=track === "kids" ? ui.kids : ui.kinder; $("#eyebrow").textContent=`${ui.name.toUpperCase()} · ${index+1} / ${ACTIVITIES.length}`; $("#title").textContent=words[0]; $("#description").textContent=words[1]; $("#step").textContent=`${track === "kids" ? ui.kids : ui.kinder} · ${item.icon}`; $("#prompt").textContent=words[0]; $("#hint").textContent=ui.choose; $("#feedback").textContent=""; $("#next").hidden=true; const target=$("#target"); target.replaceChildren(); renderShape(target,item.target,"target-piece"); const choices=$("#choices"); choices.replaceChildren(); item.choices.forEach((shape, choiceIndex)=>{const button=document.createElement("button");button.type="button";button.className="choice";button.setAttribute("aria-label",`${words[0]} ${choiceIndex+1}`);renderShape(button,shape);button.addEventListener("click",()=>judge(choiceIndex,button));choices.append(button);}); const list=$("#activityList"); list.replaceChildren(); ACTIVITIES.forEach((entry,entryIndex)=>{const button=document.createElement("button");button.type="button";button.className=entryIndex===index?"active":"";button.textContent=(entry[lang]||entry.en)[0];button.addEventListener("click",()=>{index=entryIndex;history.replaceState({},"",`?track=${track}&activity=${entry.id}`);render();});list.append(button);}); }
function judge(choiceIndex, button) { if(solved) return; const ui=copy[lang]||copy.en; if(choiceIndex===activity().answer){solved=true;button.classList.add("correct");$("#feedback").textContent=ui.good;$("#next").textContent=ui.next;$("#next").hidden=false;}else{button.classList.add("wrong");$("#feedback").textContent=ui.again;setTimeout(()=>button.classList.remove("wrong"),500);} }
$("#next").addEventListener("click",()=>{index=(index+1)%ACTIVITIES.length;history.replaceState({},"",`?track=${track}&activity=${activity().id}`);render();}); render();
