export const COPY = {
  ko: {
    title: "단위 넓이 탐구", worksheet: "학습지", brand: "GFIELD 학습지", subject: "수학 · 도형 탐구", all: "전체 활동", activity: "활동", count: "문항 수", language: "언어", cover: "표지", answers: "정답·풀이", name: "이름", date: "날짜", back: "단위 넓이 활동으로 돌아가기", refresh: "새 문제", print: "학습지 인쇄", retry: "다시 불러오기", loading: "학습지를 불러오는 중입니다.", error: "학습 자료를 불러오지 못했습니다. 잠시 후 다시 불러와 주세요.", unavailable: "선택한 활동은 준비되지 않았습니다.", noScript: "학습지를 보려면 자바스크립트를 켜 주세요.",
    unit: "작은 정사각형 1칸의 넓이를 1로 봅니다.", coverUnit: "넓이는 도형이 차지하는 크기입니다. 같은 크기의 작은 정사각형으로 비교해 봅시다.", contents: "학습 순서", look: "살펴보기", area: "넓이", squareCount: "단위 정사각형", whole: "온전한 칸", half: "반 칸", pieces: "개", pairGuide: "반 칸 2개가 한 칸입니다. 짝지을 반 칸에 같은 표시를 해 보세요.", wholeGuide: "센 칸에 작은 표시를 하며 빠짐없이 세어 보세요.", compareGuide: "A와 B의 넓이를 비교해 <, =, >를 쓰세요.", compareReason: "그렇게 생각한 까닭", drawGuide: "변끼리 이어진 하나의 도형을 그리거나 색칠하세요.", example: "예시 답안", otherAnswers: "목표 넓이만큼의 칸이 변끼리 모두 이어져 있으면 다른 모양도 답입니다.", working: "풀이를 쓰는 공간", total: (n, p, cover) => `${n}문항 · ${p}쪽${cover ? " (표지 포함)" : ""}`, adjusted: (n) => `${n}문항으로 조정했습니다. `, questions: (n) => `${n}문항`, bodyPages: (n) => `본문 ${n}쪽`, page: (n) => `${n}쪽`, ranges: (a, b) => `${a}-${b}번`,
    descriptions: { whole: "온전한 칸을 세어 넓이 구하기", halves: "반 칸을 짝지어 넓이 구하기", compare: "두 도형의 넓이 비교하기", build: "주어진 넓이의 도형 만들기" }
  },
  en: {
    title: "Unit Area", worksheet: "Worksheet", brand: "GFIELD Worksheets", subject: "Mathematics · Geometry", all: "All activities", activity: "Activity", count: "Questions", language: "Language", cover: "Cover", answers: "Answers", name: "Name", date: "Date", back: "Back to Unit Area", refresh: "New questions", print: "Print worksheet", retry: "Try again", loading: "Loading worksheet.", error: "The learning material could not be loaded. Please try again.", unavailable: "This activity is not available.", noScript: "Enable JavaScript to view the worksheet.",
    unit: "One small square has an area of 1.", coverUnit: "Area measures how much space a shape covers. Compare shapes using equal-sized unit squares.", contents: "Learning sequence", look: "Preview", area: "Area", squareCount: "unit squares", whole: "Whole squares", half: "Half squares", pieces: "", pairGuide: "Two halves make one square. Mark matching pairs of halves.", wholeGuide: "Mark each square as you count it once.", compareGuide: "Compare the areas of A and B. Write <, =, or >.", compareReason: "Explain your thinking", drawGuide: "Draw or shade one shape with all its squares joined edge to edge.", example: "Example answer", otherAnswers: "Any shape with the target number of squares, all connected edge to edge, is correct.", working: "Working space", total: (n, p, cover) => `${n} questions · ${p} pages${cover ? " (with cover)" : ""}`, adjusted: (n) => `Adjusted to ${n} questions. `, questions: (n) => `${n} questions`, bodyPages: (n) => `${n} worksheet pages`, page: (n) => `p. ${n}`, ranges: (a, b) => `${a}-${b}`, descriptions: { whole: "Count whole squares", halves: "Pair half squares", compare: "Compare two areas", build: "Make a shape with a given area" }
  },
  zh: {
    title: "单位面积探究", worksheet: "练习单", brand: "GFIELD 练习单", subject: "数学 · 图形探究", all: "全部活动", activity: "活动", count: "题数", language: "语言", cover: "封面", answers: "答案与解答", name: "姓名", date: "日期", back: "返回单位面积活动", refresh: "换一组题", print: "打印练习单", retry: "重新加载", loading: "正在加载练习单。", error: "未能加载学习资料，请重试。", unavailable: "该活动暂不可用。", noScript: "请启用 JavaScript。",
    unit: "每个小正方形的面积是1。", coverUnit: "面积表示图形所占的大小。用同样大小的小正方形来比较。", contents: "学习顺序", look: "观察", area: "面积", squareCount: "单位正方形", whole: "整格", half: "半格", pieces: "个", pairGuide: "两个半格合成一格。给配对的半格做相同的标记。", wholeGuide: "边数边做标记，每格只数一次。", compareGuide: "比较A与B的面积，填入 <、= 或 >。", compareReason: "说说你的理由", drawGuide: "画出或涂出一个所有格子都以边相连的图形。", example: "示例答案", otherAnswers: "只要格数符合要求，且所有格子都以边相连，其他形状也正确。", working: "解题空间", total: (n, p, cover) => `${n}题 · ${p}页${cover ? "（含封面）" : ""}`, adjusted: (n) => `已调整为${n}题。`, questions: (n) => `${n}题`, bodyPages: (n) => `正文${n}页`, page: (n) => `第${n}页`, ranges: (a, b) => `${a}-${b}题`, descriptions: { whole: "数整格求面积", halves: "把半格配对求面积", compare: "比较两个图形的面积", build: "画出指定面积的图形" }
  },
  ja: {
    title: "単位面積の探究", worksheet: "ワークシート", brand: "GFIELD ワークシート", subject: "算数 · 図形", all: "すべての活動", activity: "活動", count: "問題数", language: "言語", cover: "表紙", answers: "答え・解説", name: "名前", date: "日付", back: "単位面積の活動に戻る", refresh: "新しい問題", print: "印刷", retry: "再読み込み", loading: "読み込み中です。", error: "学習資料を読み込めませんでした。もう一度お試しください。", unavailable: "この活動は利用できません。", noScript: "JavaScriptを有効にしてください。",
    unit: "小さな正方形1マスの面積を1とします。", coverUnit: "面積は図形がしめる広さです。同じ大きさの正方形で比べましょう。", contents: "学習の順序", look: "見てみよう", area: "面積", squareCount: "単位正方形", whole: "まるごとのマス", half: "半分のマス", pieces: "個", pairGuide: "半分のマス2個で1マスです。組になる半分のマスに同じ印をつけましょう。", wholeGuide: "数えたマスに印をつけて、もれなく数えましょう。", compareGuide: "AとBの面積を比べ、<、=、>を書きましょう。", compareReason: "そう考えた理由", drawGuide: "すべてのマスが辺でつながる一つの図形をかくか、色をぬりましょう。", example: "答えの例", otherAnswers: "目標のマス数になり、すべてのマスが辺でつながっていれば、別の形も正解です。", working: "考えを書く場所", total: (n, p, cover) => `${n}問 · ${p}ページ${cover ? "（表紙を含む）" : ""}`, adjusted: (n) => `${n}問に調整しました。`, questions: (n) => `${n}問`, bodyPages: (n) => `本文${n}ページ`, page: (n) => `${n}ページ`, ranges: (a, b) => `${a}-${b}問`, descriptions: { whole: "まるごとのマスを数える", halves: "半分のマスを組にする", compare: "二つの面積を比べる", build: "決められた面積の図形を作る" }
  }
};
