const copy = {
  ko: {
    title: "단위넓이 탐구", back: "도형 정원", worksheet: "학습지", language: "언어", area: "학습 영역", progress: "진행", retry: "이 문제 다시 하기", undo: "마지막 조작 되돌리기", check: "확인하기", next: "다음 문제", done: "마치기", answer: "넓이", compare: "두 도형의 넓이", less: "A의 넓이가 B보다 작습니다", equal: "A와 B의 넓이가 같습니다", greater: "A의 넓이가 B보다 큽니다", hint: "생각의 실마리", review: "확인한 원리", align: "칸을 나란히 놓기", correct: "좋아요. 넓이를 정확히 확인했어요.", retryAnswer: "단위가 몇 개 들어가는지 다시 살펴보세요.", disconnected: "색칠한 칸들이 변끼리 이어지도록 만들어 보세요.", invalid: "답을 다시 확인해 주세요.", pairFirst: "반칸을 두 개씩 모두 묶은 뒤 넓이를 구해 보세요.", chooseHalf: "함께 묶을 반칸을 하나 더 골라 보세요.", paired: n => `반칸 ${n}쌍을 묶었어요.`, marked: n => `${n}칸에 세기 표시를 했어요.`, built: n => `색칠한 칸: ${n}개`, complete: "단위넓이 탐구 완료", completeText: "같은 단위로 재면 서로 다른 모양의 넓이도 비교할 수 있어요.", practice: "다른 문제 풀기", storage: "이번 학습 기록을 이 기기에 저장하지 못했습니다.",
    rules: { whole: "한 칸의 넓이를 1로 정합니다. 도형 안에 들어 있는 단위를 빠짐없이 세어 봅니다.", halves: "같은 정사각형을 대각선으로 나눈 반칸 두 개는 한 칸과 넓이가 같습니다.", compare: "같은 크기의 칸으로 비교합니다. 칸을 옮겨도 더하거나 빼지 않으면 넓이는 그대로입니다.", build: "같은 넓이의 도형은 여러 모양으로 만들 수 있습니다. 이 활동에서는 칸의 변끼리 이어 하나의 도형을 만듭니다." }
  },
  en: {
    title: "Unit Area Studio", back: "Shape Garden", worksheet: "Worksheet", language: "Language", area: "Activities", progress: "Progress", retry: "Restart this problem", undo: "Undo last action", check: "Check", next: "Next problem", done: "Finish", answer: "Area", compare: "Compare the areas", less: "A has less area than B", equal: "A and B have equal area", greater: "A has more area than B", hint: "A clue", review: "What we found", align: "Line up the squares", correct: "Yes. You checked the area correctly.", retryAnswer: "Look again at how many units cover the shape.", disconnected: "Join the shaded squares along their sides.", invalid: "Please check your answer.", pairFirst: "Pair all the half-squares, then find the area.", chooseHalf: "Choose another half-square to make a pair.", paired: n => `${n} half-square pairs made.`, marked: n => `${n} squares marked for counting.`, built: n => `Shaded squares: ${n}`, complete: "Unit area exploration complete", completeText: "Using the same unit lets us compare the areas of different shapes.", practice: "More problems", storage: "This device could not save your progress.",
    rules: { whole: "One square has area 1. Count each unit inside the shape once.", halves: "Two halves made by cutting equal squares diagonally have the same area as one square.", compare: "Compare using equal-sized squares. Moving squares does not change area unless some are added or removed.", build: "Different shapes can have equal area. In this activity, join squares along their sides to make one shape." }
  },
  zh: {
    title: "单位面积探究", back: "图形花园", worksheet: "练习纸", language: "语言", area: "学习领域", progress: "进度", retry: "重做本题", undo: "撤销上一步", check: "检查", next: "下一题", done: "完成", answer: "面积", compare: "比较两个图形的面积", less: "A的面积小于B", equal: "A和B的面积相等", greater: "A的面积大于B", hint: "思考提示", review: "发现的规律", align: "把方格排列整齐", correct: "对了，你正确地确认了面积。", retryAnswer: "再看看图形里有多少个面积单位。", disconnected: "让涂色方格沿着边连接。", invalid: "请检查你的答案。", pairFirst: "先把所有半格两两配对，再求面积。", chooseHalf: "再选一个半格来配对。", paired: n => `已组成${n}对半格。`, marked: n => `已标记${n}个方格。`, built: n => `涂色方格：${n}个`, complete: "单位面积探究完成", completeText: "用相同的单位，可以比较不同图形的面积。", practice: "练习其他题目", storage: "无法在此设备上保存学习记录。",
    rules: { whole: "规定一格的面积为1。把图形内的每个面积单位数一次。", halves: "把相同的正方形沿对角线分成两半，两个半格的面积等于一格。", compare: "用大小相同的方格比较。只移动方格，不增加也不减少，面积就不变。", build: "不同形状的图形可以有相同的面积。本活动中，方格要沿着边连成一个图形。" }
  },
  ja: {
    title: "単位面積の探究", back: "図形の庭", worksheet: "プリント", language: "言語", area: "学習領域", progress: "進み具合", retry: "この問題をやり直す", undo: "一つ前に戻す", check: "確かめる", next: "次の問題", done: "終わる", answer: "面積", compare: "二つの図形の面積", less: "Aの面積はBより小さい", equal: "AとBの面積は等しい", greater: "Aの面積はBより大きい", hint: "考えるヒント", review: "分かったこと", align: "マスを並べる", correct: "面積を正しく確かめられました。", retryAnswer: "図形に単位がいくつ入るか、もう一度考えましょう。", disconnected: "色を塗ったマスを辺でつなぎましょう。", invalid: "答えを確かめてください。", pairFirst: "半マスをすべて二つずつ組にして、面積を求めましょう。", chooseHalf: "組にする半マスをもう一つ選びましょう。", paired: n => `半マスを${n}組にしました。`, marked: n => `${n}マスに数える印を付けました。`, built: n => `色を塗ったマス：${n}個`, complete: "単位面積の探究が終わりました", completeText: "同じ単位を使えば、違う形の面積も比べられます。", practice: "別の問題に挑戦", storage: "この端末に学習記録を保存できませんでした。",
    rules: { whole: "一マスの面積を1とします。図形の中の単位を一つずつ数えましょう。", halves: "同じ正方形を対角線で半分にした半マス二つの面積は、一マスと等しくなります。", compare: "同じ大きさのマスで比べます。マスを増やしたり減らしたりせずに動かしても、面積は変わりません。", build: "同じ面積でもいろいろな形を作れます。この活動では、マスの辺をつなげて一つの図形にします。" }
  }
};
export const translation = lang => copy[lang] || copy.ko;
