import { levels, directionInfo, roll, rollMany, visibleFaces } from "../../games/dice-roll/levels.js?v=dice-roll-3";

const $=(selector)=>document.querySelector(selector);let offset=0;
const select=$("#levelSelect"),toggle=$("#answerToggle"),grid=$("#problemGrid");
levels.forEach((level)=>{const option=document.createElement("option");option.value=level.id;option.textContent=`${level.id}. ${level.title} · ${level.band}`;select.append(option);});

const quads={top:[[34,39],[80,12],[121,36],[74,63]],front:[[34,39],[74,63],[74,117],[34,92]],right:[[74,63],[121,36],[121,90],[74,117]]};
const pips={1:[[.5,.5]],2:[[.25,.25],[.75,.75]],3:[[.24,.24],[.5,.5],[.76,.76]],4:[[.25,.25],[.75,.25],[.25,.75],[.75,.75]],5:[[.23,.23],[.77,.23],[.5,.5],[.23,.77],[.77,.77]],6:[[.25,.2],[.75,.2],[.25,.5],[.75,.5],[.25,.8],[.75,.8]]};
const flatPips={1:[[50,50]],2:[[35,35],[65,65]],3:[[34,34],[50,50],[66,66]],4:[[35,35],[65,35],[35,65],[65,65]],5:[[34,34],[66,34],[50,50],[34,66],[66,66]],6:[[35,29],[65,29],[35,50],[65,50],[35,71],[65,71]]};
const flatFaces={top:[[35,35],[65,35],[65,65],[35,65]],north:[[0,0],[100,0],[65,35],[35,35]],east:[[100,0],[100,100],[65,65],[65,35]],south:[[35,65],[65,65],[100,100],[0,100]],west:[[0,0],[35,35],[35,65],[0,100]]};
function point(quad,u,v){const[a,b,c,d]=quad;return[(1-u)*(1-v)*a[0]+u*(1-v)*b[0]+u*v*c[0]+(1-u)*v*d[0],(1-u)*(1-v)*a[1]+u*(1-v)*b[1]+u*v*c[1]+(1-u)*v*d[1]];}
function dieSvg(orientation,blank=false){const visible=visibleFaces(orientation);return `<svg class="die-svg${blank?" blank":""}" viewBox="12 4 132 124" aria-hidden="true">${Object.entries(quads).map(([face,quad])=>`<polygon class="die-face ${face}" points="${quad.map((item)=>item.join(",")).join(" ")}"/>${blank?"":pips[visible[face]].map(([u,v])=>{const[cx,cy]=point(quad,u,v);return `<circle cx="${cx}" cy="${cy}" r="4.2"/>`;}).join("")}`).join("")}</svg>`;}
function flatFiveSvg(orientation,blank=false){return `<svg class="flat-five-svg${blank?" blank":""}" viewBox="-4 -4 108 108" aria-hidden="true">${Object.entries(flatFaces).map(([face,quad])=>`<polygon class="flat-face ${face}" points="${quad.map((item)=>item.join(",")).join(" ")}"/>${blank?"":pips[orientation[face]].map(([u,v])=>{const[cx,cy]=point(quad,u,v);return `<circle cx="${cx}" cy="${cy}" r="3"/>`;}).join("")}`).join("")}</svg>`;}
function boardDie(orientation,x,y){const visible=visibleFaces(orientation),scale=.54,tx=x-77.5*scale,ty=y-64.5*scale;return `<g class="board-die" transform="translate(${tx} ${ty}) scale(${scale})">${Object.entries(quads).map(([face,quad])=>`<polygon class="die-face ${face}" points="${quad.map((item)=>item.join(",")).join(" ")}"/>${pips[visible[face]].map(([u,v])=>{const[cx,cy]=point(quad,u,v);return `<circle cx="${cx}" cy="${cy}" r="4.5"/>`;}).join("")}`).join("")}</g>`;}
function flatDie(value,x,y,size){const dots=flatPips[value].map(([px,py])=>`<circle cx="${x+(px-50)*size/100}" cy="${y+(py-50)*size/100}" r="${size*.065}"/>`).join("");return `<g class="flat-die"><rect x="${x-size/2}" y="${y-size*.34}" width="${size}" height="${size*.68}" rx="${size*.12}"/>${dots}</g>`;}
function boardSvg(problem){const width=problem.cols*100,height=problem.rows*100,start=problem.path[0];return `<svg class="route-board" viewBox="0 0 ${width} ${height}" aria-hidden="true"><defs><marker id="sheetArrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10z"/></marker></defs>${Array.from({length:problem.rows*problem.cols},(_,index)=>{const row=Math.floor(index/problem.cols),col=index%problem.cols;return `<rect x="${col*100}" y="${row*100}" width="100" height="100"/><text x="${col*100+9}" y="${row*100+18}">${index+1}</text>`;}).join("")}${problem.path.slice(1).map((cell,index)=>{const previous=problem.path[index];return `<line x1="${previous[1]*100+50}" y1="${previous[0]*100+50}" x2="${cell[1]*100+50}" y2="${cell[0]*100+50}" marker-end="url(#sheetArrow)"/>`;}).join("")}${boardDie(problem.startOrientation,start[1]*100+50,start[0]*100+50)}</svg>`;}
function stateSequence(problem){const states=[];let current=problem.startOrientation;problem.directions.forEach((direction)=>{current=roll(current,direction);states.push(current);});return states;}
function prompt(problem){if(problem.interaction==="route-answer")return "출발 주사위가 목표 주사위가 되도록 굴리는 경로를 고르세요.";if(problem.turn)return `${problem.path[0][0]*problem.cols+problem.path[0][1]+1}번 위치에서 ${problem.turn==="clockwise"?"시계":"시계 반대"} 방향으로 ${problem.directions.length}번 굴리면 주사위의 눈은 어떻게 변하나요?`;if(problem.directions.length===1)return "화살표 방향으로 한 번 굴린 뒤 주사위의 눈을 그리세요.";return "화살표를 따라 차례로 굴린 뒤 주사위의 눈을 그리세요.";}
function directionStrip(directions){return `<div class="direction-strip">${directions.map((direction,index)=>`<span><b>${index+1}</b>${directionInfo[direction].arrow}</span>`).join("")}</div>`;}
function routeChoices(problem,show){return `<div class="route-choices">${problem.routeChoices.map((route,index)=>`<div class="route-choice${show&&index===problem.answer?" correct":""}"><em>${index+1}</em>${route.map((direction)=>directionInfo[direction].arrow).join(" ")}</div>`).join("")}</div>`;}
function visual(problem,show){if(problem.interaction==="route-answer")return `<div class="worksheet-layout"><div>${boardSvg(problem)}<small>출발 주사위</small></div><div class="route-target"><div class="start-target"><figure>${dieSvg(problem.startOrientation)}<figcaption>출발</figcaption></figure><i>→</i><figure>${dieSvg(problem.finalOrientation)}<figcaption>목표</figcaption></figure></div>${routeChoices(problem,show)}</div></div>`;
  const states=stateSequence(problem),shownStates=states.length<=4?states:[states.at(-1)],labels=states.length<=4?states.map((_,index)=>`${index+1}번 굴린 뒤`):["끝까지 굴린 뒤"];
  return `<div class="worksheet-layout"><div>${boardSvg(problem)}${directionStrip(problem.directions)}</div><div class="dice-record"><figure>${dieSvg(problem.startOrientation)}<figcaption>출발 주사위</figcaption></figure><div class="record-row">${shownStates.map((state,index)=>`<figure><span>${flatFiveSvg(state,!show)}</span><figcaption>${labels[index]}</figcaption></figure>`).join("")}</div></div></div>`;}
function answerText(problem){const final=problem.finalOrientation;const visible=visibleFaces(final);if(problem.interaction==="route-answer")return `정답 ${problem.answer+1}번`;return `도착: 윗면 ${visible.top}, 앞면 ${visible.front}, 오른쪽 면 ${visible.right}`;}
function render(){const level=levels[Number(select.value||1)-1],show=toggle.checked,problems=Array.from({length:2},(_,index)=>level.problems[(offset+index)%level.problems.length]);$("#sheetTitle").textContent=level.title;$("#sheetDescription").textContent=level.subtitle;grid.replaceChildren();problems.forEach((problem,index)=>{const article=document.createElement("article");article.className=`problem level-${level.id}`;article.innerHTML=`<header><b>${index+1}</b><span>${prompt(problem)}</span></header><div class="visual">${visual(problem,show)}</div><div class="answer-line">${show?answerText(problem):"답: ________________________________________________"}</div>`;grid.append(article);});}
select.addEventListener("change",()=>{offset=0;render();});toggle.addEventListener("change",render);$("#refreshButton").addEventListener("click",()=>{offset=(offset+2)%10;render();});$("#printButton").addEventListener("click",()=>print());render();
