"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const source=require("../learning/grade6-ns-c-unit-workbook.js");
const expected={"nsca-w01":"7/4","nsca-w02":"-5/3","nsca-w03":"9/4","nsca-w04":"7/4","nsca-w05":"11/6","nsca-w06":"13/6","nsca-w07":"3","nsca-w08":"-12","nsca-w09":"8","nsca-w10":"0","nsca-w11":"4","nsca-w12":"-5","nsca-w13":"<","nsca-w14":"-7/4","nsca-w15":">","nsca-w16":"<","nsca-w17":">","nsca-w18":"<","nsca-w19":"-9/5","nsca-w20":"-7/4","nsca-w21":">","nsca-w22":">","nsca-w23":"-13/6","nsca-w24":"-4/3","nsca-w25":"1","nsca-w26":"2","nsca-w27":"4","nsca-w28":"2","nsca-w29":"1","nsca-w30":"3","nsca-w31":"4","nsca-w32":"7","nsca-w33":"8","nsca-w34":"3","nsca-w35":"5","nsca-w36":"4","nsca-r01":"-14","nsca-r02":"11/6","nsca-r03":"13/5","nsca-r04":"<","nsca-r05":">","nsca-r06":"3","nsca-r07":"3/2","nsca-r08":"-7/3"};
function all(){return source.pack.workbookItems.concat(source.pack.recheckItems);}
function val(n,d){return n/d;}
function asNumber(text){const parts=String(text).split("/");return parts.length===2?Number(parts[0])/Number(parts[1]):Number(parts[0]);}
function circles(svg){return[...svg.matchAll(/<circle[^>]*cx="([\d.]+)"[^>]*cy="([\d.]+)"/g)].map(function(match){return{x:Number(match[1]),y:Number(match[2])};});}

test("6.NS.C is a balanced 36-item unit with an eight-structure recheck",function(){assert.equal(source.validatePack(),true);assert.equal(source.pack.workbookItems.length,36);assert.equal(source.pack.recheckItems.length,8);assert.deepEqual(Object.fromEntries(["meaning","order","coordinates"].map(function(section){return[section,source.pack.workbookItems.filter(function(candidate){return candidate.section===section;}).length];})),{meaning:12,order:12,coordinates:12});assert.equal(new Set(source.pack.recheckItems.map(function(candidate){return candidate.strand;})).size,8);assert.equal(source.pack.sourceReuse.geometryRenderer,"geometry/worksheet/render.js GW_RENDER primitives");});

test("all 44 answers match a fixed independent ledger",function(){assert.equal(Object.keys(expected).length,44);all().forEach(function(candidate){assert.equal(source.formatResult(candidate),expected[candidate.id],candidate.id);assert.equal(source.evaluateResponse(candidate,expected[candidate.id]),true,candidate.id);});});

test("operations, comparisons, quadrants, and distances recompute independently",function(){all().forEach(function(candidate){const d=candidate.data;if(candidate.kind==="quadrant-classification"){const x=val(d.xNumerator,d.xDenominator),y=val(d.yNumerator,d.yDenominator);const answer=x>0?(y>0?"1":"4"):(y>0?"2":"3");assert.equal(expected[candidate.id],answer,candidate.id);return;}if(candidate.kind==="signed-rational-comparison"){let left=val(d.leftNumerator,d.leftDenominator),right=val(d.rightNumerator,d.rightDenominator);if(d.basis==="absolute-magnitude"){left=Math.abs(left);right=Math.abs(right);}assert.equal(expected[candidate.id],left<right?"<":">",candidate.id);return;}if(d.operation==="axis-distance"){const first=d.axis==="horizontal"?val(d.firstXNumerator,d.firstXDenominator):val(d.firstYNumerator,d.firstYDenominator);const second=d.axis==="horizontal"?val(d.secondXNumerator,d.secondXDenominator):val(d.secondYNumerator,d.secondYDenominator);assert.equal(asNumber(expected[candidate.id]),Math.abs(second-first),candidate.id);return;}if(d.operation==="distance"){assert.equal(asNumber(expected[candidate.id]),Math.abs(val(d.leftNumerator,d.leftDenominator)-val(d.rightNumerator,d.rightDenominator)),candidate.id);return;}if(d.operation==="opposite"){const opposite=-val(d.numerator,d.denominator);assert.equal(asNumber(expected[candidate.id]),Object.is(opposite,-0)?0:opposite,candidate.id);}});});

test("coordinate SVG positions are calculated from mirrored or axis-aligned",function(){const yItem=source.pack.workbookItems.find(function(candidate){return candidate.id==="nsca-w35";});assert.equal(circles(source.renderVisual(yItem,"ko","student")).length,1);const yMirror=circles(source.renderVisual(yItem,"ko","teacher"));assert.equal(yMirror.length,2);assert.ok(Math.abs((yMirror[0].x+yMirror[1].x)-280)<0.01);assert.equal(yMirror[0].y,yMirror[1].y);const xMirror=circles(source.renderVisual(source.pack.workbookItems.find(function(candidate){return candidate.id==="nsca-w36";}),"ko","teacher"));assert.equal(xMirror[0].x,xMirror[1].x);assert.ok(Math.abs((xMirror[0].y+xMirror[1].y)-176)<0.01);const horizontal=circles(source.renderVisual(source.pack.workbookItems.find(function(candidate){return candidate.id==="nsca-w32";}),"ko","student"));assert.equal(horizontal[0].y,horizontal[1].y);const vertical=circles(source.renderVisual(source.pack.workbookItems.find(function(candidate){return candidate.id==="nsca-w33";}),"ko","student"));assert.equal(vertical[0].x,vertical[1].x);});

test("standards, locales, and response visibility stay explicit",function(){all().forEach(function(candidate){assert.match(candidate.standardIds[0],/^6\.NS\.C\.(?:5|6[abc]|7[abcd]|8[abcd])$/);assert.deepEqual(Object.keys(candidate.prompt).sort(),["en","ko","zh-Hans"]);["ko","en","zh-Hans"].forEach(function(locale){const visual=source.renderVisual(candidate,locale,"student");assert.match(visual,/^<svg /,candidate.id);assert.doesNotMatch(visual,/aria-label="[^"]*(?:-?\d+\/\d+|Quadrant [1-4])/);if(candidate.strand==="coordinate-reflection"){assert.equal(circles(visual).length,1,candidate.id);assert.doesNotMatch(visual,/A′|is-target/);}});assert.equal(Object.prototype.hasOwnProperty.call(candidate,"answer"),false);});});
