"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const source=require("../learning/grade6-ee-a-unit-workbook.js");

const expected={"eeau-w01":"32","eeau-w02":"81","eeau-w03":"41","eeau-w04":"64","eeau-w05":"28","eeau-w06":"52","eeau-w07":"3","eeau-w08":"8","eeau-w09":"4","eeau-w10":"12","eeau-w11":"4","eeau-w12":"15","eeau-w13":"19","eeau-w14":"22","eeau-w15":"19","eeau-w16":"47","eeau-w17":"23","eeau-w18":"60","eeau-w19":"49","eeau-w20":"34","eeau-w21":"45","eeau-w22":"129","eeau-w23":"26","eeau-w24":"84","eeau-w25":"21","eeau-w26":"8","eeau-w27":"3","eeau-w28":"20","eeau-w29":"1","eeau-w30":"0","eeau-w31":"7","eeau-w32":"18","eeau-w33":"12","eeau-w34":"2","eeau-w35":"1","eeau-w36":"8","eeau-r01":"49","eeau-r02":"55","eeau-r03":"4","eeau-r04":"2","eeau-r05":"38","eeau-r06":"84","eeau-r07":"15","eeau-r08":"0"};
function all(){return source.pack.workbookItems.concat(source.pack.recheckItems);}
function substitute(candidate){return candidate.data.terms.reduce(function(sum,term){if(Object.prototype.hasOwnProperty.call(term,"constant"))return sum+term.constant;const variables=term.variables||[{name:term.variable,exponent:term.exponent||1}];return sum+variables.reduce(function(product,entry){return product*(candidate.data.values[entry.name]**entry.exponent);},term.coefficient);},0);}
function coefficientPairs(candidate,answer){const d=candidate.data;if(d.rule==="constant-after-expansion")return[[d.outerFactor*d.insideVariableCoefficient,d.outerFactor*d.insideConstant],[d.targetVariableCoefficient,answer]];if(d.rule==="variable-after-expansion")return[[d.outerFactor*d.insideVariableCoefficient,d.outerFactor*d.insideConstant],[answer,d.targetConstant]];if(d.rule==="variable-inside-factor")return[[d.expandedVariableCoefficient,d.expandedConstant],[d.outerFactor*answer,d.outerFactor*d.insideConstant]];if(d.rule==="binary-coefficient-pair")return[[d.leftVariableCoefficient,d.leftConstant],[d.rightVariableCoefficient,d.rightConstant]];if(d.rule==="outer-factor-for-pair")return[[answer*d.insideVariableCoefficient,answer*d.insideConstant],[d.targetVariableCoefficient,d.targetConstant]];throw new Error("UNEXPECTED_RULE");}

test("6.EE.A is balanced as 36 unit items plus eight distinct recheck structures",function(){assert.equal(source.validatePack(),true);assert.equal(source.pack.workbookItems.length,36);assert.equal(source.pack.recheckItems.length,8);assert.deepEqual(Object.fromEntries(["structure","evaluate","equivalence"].map(function(section){return[section,source.pack.workbookItems.filter(function(candidate){return candidate.section===section;}).length];})),{structure:12,evaluate:12,equivalence:12});assert.equal(new Set(source.pack.recheckItems.map(function(candidate){return candidate.strand;})).size,8);assert.equal(source.pack.sourceReuse.shortClinic,"grade6-ee-a-clinic-pack.js exact solver and error guides");});

test("all 44 answers match a fixed independent ledger",function(){assert.equal(Object.keys(expected).length,44);all().forEach(function(candidate){assert.equal(source.formatResult(candidate),expected[candidate.id],candidate.id);assert.equal(source.evaluateResponse(candidate,expected[candidate.id]),true,candidate.id);assert.equal(source.evaluateResponse(candidate,String(Number(expected[candidate.id])+1)),false,candidate.id);});});

test("powers, substitutions, and equivalent forms recompute independently",function(){all().forEach(function(candidate){const answer=Number(expected[candidate.id]);const d=candidate.data;if(candidate.kind==="whole-power"){assert.equal(answer,d.base**d.exponent,candidate.id);return;}if(candidate.kind==="power-combination"){const left=d.left.base**d.left.exponent,right=d.right.base**d.right.exponent;assert.equal(answer,d.operator==="+"?left+right:left-right,candidate.id);return;}if(candidate.kind==="expression-part"){assert.equal(answer,d.part==="term-count"?d.terms.length:d.coefficient,candidate.id);return;}if(candidate.kind==="substitution"){assert.equal(answer,substitute(candidate),candidate.id);return;}const pairs=coefficientPairs(candidate,answer);const same=pairs[0][0]===pairs[1][0]&&pairs[0][1]===pairs[1][1];assert.equal(same,d.rule==="binary-coefficient-pair"?answer===1:true,candidate.id);});});

test("student expression models keep the result out of markup and accessibility labels",function(){all().forEach(function(candidate){["ko","en","zh-Hans"].forEach(function(locale){const visual=source.renderVisual(candidate,locale,"student");assert.match(visual,/^<div class="eea-expression-model" role="img"/);assert.doesNotMatch(visual,/data-answer|teacher-key|solution/i);assert.match(visual,/aria-label="(?:[^0-9"]*)"/);if(candidate.kind!=="expression-part"&&candidate.data.rule!=="binary-coefficient-pair")assert.match(visual,/□/,candidate.id+" "+locale);});assert.equal(Object.prototype.hasOwnProperty.call(candidate,"answer"),false);});});

test("standards, locales, rights, and teacher-observation limits stay explicit",function(){assert.equal(source.pack.rights.assetRights,"original");assert.equal(source.pack.contentOrigin,"gfield-original-authored-public-unit-workbook");assert.match(source.pack.scopeNotice.en,/teacher separately reviews/i);assert.match(source.pack.scopeNotice.en,/does not determine full mastery, placement, or promotion/i);all().forEach(function(candidate){assert.match(candidate.standardIds[0],/^6\.EE\.A\.(?:1|2[bc]|3|4)$/);assert.deepEqual(Object.keys(candidate.prompt).sort(),["en","ko","zh-Hans"]);});const coefficient=source.pack.workbookItems.find(function(candidate){return candidate.id==="eeau-w12";});assert.match(source.solutionFor(coefficient,"ko"),/문자항에서 문자에 곱해진 수/);});
