"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const source=require("../learning/grade6-ee-b-unit-workbook.js");

const expected={"eebu-w01":"1","eebu-w02":"1","eebu-w03":"0","eebu-w04":"0","eebu-w05":"1","eebu-w06":"1","eebu-w07":"2","eebu-w08":"2","eebu-w09":"2","eebu-w10":"3","eebu-w11":"2","eebu-w12":"2","eebu-w13":"8","eebu-w14":"5/4","eebu-w15":"23","eebu-w16":"9","eebu-w17":"12","eebu-w18":"6","eebu-w19":"13/2","eebu-w20":"3/2","eebu-w21":"63/2","eebu-w22":"15/2","eebu-w23":"16","eebu-w24":"8","eebu-w25":"48","eebu-w26":"12","eebu-w27":"7/2","eebu-w28":"0","eebu-w29":"1","eebu-w30":"0","eebu-w31":"1","eebu-w32":"0","eebu-w33":"2","eebu-w34":"3","eebu-w35":"2","eebu-w36":"2","eebu-r01":"1","eebu-r02":"0","eebu-r03":"2","eebu-r04":"13/5","eebu-r05":"12","eebu-r06":"41","eebu-r07":"25","eebu-r08":"1"};
function all(){return source.pack.workbookItems.concat(source.pack.recheckItems);}
function rat(value){return{n:BigInt(value.numerator),d:BigInt(value.denominator==null?1:value.denominator)};}
function compare(a,b){return a.n*b.d===b.n*a.d?0:(a.n*b.d<b.n*a.d?-1:1);}
function result(candidate){const d=candidate.data;if(candidate.kind==="substitution-truth"){const x=rat(d.candidate),p=rat(d.p),total=rat(d.total);const left=d.form==="add"?{n:x.n*p.d+p.n*x.d,d:x.d*p.d}:{n:x.n*p.n,d:x.d*p.d};return compare(left,total)===0?"1":"0";}if(candidate.kind==="add-equation"){const total=rat(d.total),p=rat(d.p);return reduce(total.n*p.d-p.n*total.d,total.d*p.d);}if(candidate.kind==="multiply-equation"){const total=rat(d.total),coefficient=rat(d.coefficient);return reduce(total.n*coefficient.d,total.d*coefficient.n);}if(candidate.kind==="inequality-boundary")return reduce(BigInt(d.boundary.numerator),BigInt(d.boundary.denominator||1));if(candidate.kind==="inequality-direction")return d.relation===">"?"1":"0";if(candidate.kind==="inequality-set-count"){const boundary=rat(d.boundary);return String(d.candidates.filter(function(value){const order=compare(rat(value),boundary);return d.relation===">"?order>0:order<0;}).length);}throw new Error("UNKNOWN_KIND");}
function reduce(n,d){const sign=d<0n?-1n:1n;n*=sign;d*=sign;let a=n<0n?-n:n,b=d;while(b){const next=a%b;a=b;b=next;}const divisor=a||1n;n/=divisor;d/=divisor;return d===1n?String(n):n+"/"+d;}

test("6.EE.B contains 36 balanced unit items and eight distinct recheck structures",function(){assert.equal(source.validatePack(),true);assert.equal(source.pack.workbookItems.length,36);assert.equal(source.pack.recheckItems.length,8);assert.deepEqual(Object.fromEntries(["solutions","equations","inequalities"].map(function(section){return[section,source.pack.workbookItems.filter(function(candidate){return candidate.section===section;}).length];})),{solutions:12,equations:12,inequalities:12});assert.equal(new Set(source.pack.recheckItems.map(function(candidate){return candidate.strand;})).size,8);});

test("all 44 answers match the fixed ledger and an independent rational calculation",function(){assert.equal(Object.keys(expected).length,44);all().forEach(function(candidate){assert.equal(source.formatResult(candidate),expected[candidate.id],candidate.id);assert.equal(result(candidate),expected[candidate.id],candidate.id);assert.equal(source.evaluateResponse(candidate,expected[candidate.id]),true,candidate.id);assert.equal(source.evaluateResponse(candidate,"999999"),false,candidate.id);});});

test("student visuals do not reveal boundary or direction answers",function(){const boundary=source.pack.workbookItems.find(function(candidate){return candidate.id==="eebu-w25";});const direction=source.pack.workbookItems.find(function(candidate){return candidate.id==="eebu-w30";});const studentBoundary=source.renderVisual(boundary,"ko","student");const studentDirection=source.renderVisual(direction,"ko","student");const teacherDirection=source.renderVisual(direction,"ko","teacher");assert.doesNotMatch(studentBoundary,/>48</);assert.match(studentBoundary,/>c</);assert.doesNotMatch(studentDirection,/solution-ray/);assert.match(teacherDirection,/solution-ray/);all().forEach(function(candidate){assert.equal(Object.prototype.hasOwnProperty.call(candidate,"answer"),false);});});

test("standards, locales, public rights, and teacher limits remain explicit",function(){assert.equal(source.pack.rights.assetRights,"original");assert.equal(source.pack.contentOrigin,"gfield-original-authored-public-unit-workbook");assert.match(source.pack.scopeNotice.en,/teacher separately reviews/i);assert.match(source.pack.scopeNotice.en,/does not determine full mastery, placement, or promotion/i);const standards=new Set(all().flatMap(function(candidate){return candidate.standardIds;}));assert.deepEqual([...standards].sort(),["6.EE.B.5","6.EE.B.6","6.EE.B.7","6.EE.B.8"]);all().forEach(function(candidate){assert.deepEqual(Object.keys(candidate.prompt).sort(),["en","ko","zh-Hans"]);});assert.match(source.solutionFor(source.pack.workbookItems.find(function(candidate){return candidate.id==="eebu-w30";}),"en"),/left/);});
