import { steps, quiz, helpers } from './lesson.js';
import { createRig, circuitState } from './model.js?v=3';
import { createGuide } from './guide.js';
import { observations, observationKey, safetyWords, studyHint, quizHints } from './study.js?v=1';
import { openMagazine } from './magazine.js?v=4';
import { openWorkbook } from './workbook.js?v=6';
import { workbookPageForStep } from './workbook-pages.js?v=6';
import { prepareNotebook, selectRecordSource, comparisonNote, notebookSupport, noteKeys } from './notebook.js?v=1';
const app=document.querySelector('#app'), KEY='popcorn.fabre09.current.v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch{}
let state={index:0,furthest:0,done:{},prediction:'',records:{},recordKind:'screen',answers:{},tries:{},checked:{},report:'',checks:[],practice:'screen',screenChecks:[],observations:[],tested:[],...saved};
state.index=Math.max(0,Math.min(steps.length-1,Number(state.index)||0));state.furthest=Math.max(state.index,Math.min(steps.length-1,Number(state.furthest)||0));
prepareNotebook(state);
let mode='home', rig, guide, recognition, helpGuide, closeHelp, exploded=false, highlight=true, studentState;
let closeMagazine, closeWorkbook, safetyReturn=null;
let guideAnchor, notesOn=false, votes=[0,0,0];
let compareMode='one',cell1=true,cell2=true,position='off',observed=new Set(), tested=new Set(), hotStop=false;
function save(){if(mode==='teacher')return;try{localStorage.setItem(KEY,JSON.stringify(state));document.querySelector('.save-note')?.setAttribute('data-saved','true');}catch{const el=document.querySelector('.save-note');if(el)el.textContent='저장이 안 되는 환경이에요. 기록을 파일로 저장해 주세요.';}}
function cleanup(){closeWorkbook?.();closeWorkbook=null;closeMagazine?.();closeMagazine=null;closeHelp?.();closeHelp=null;recognition?.abort();recognition=null;guide?.dispose();guide=null;rig?.dispose();rig=null;}
function header(){return `<header class="top"><a class="brand" href="#home">팝콘 실험실<small>파브르 9호 · 전류</small></a><div class="top-actions">${mode!=='home'?`<button data-action="workbook">교재 보기</button><button data-action="magazine">읽을거리</button><button data-action="steps" aria-expanded="false" aria-controls="lesson-steps">단계 보기</button>${mode==='teacher'?`<button data-action="notes" aria-expanded="${notesOn}" aria-controls="teacher-notes">발문 노트</button>`:''}<button data-action="home">처음 화면</button><button data-action="fullscreen">전체 화면</button>`:''}</div></header>`;}
function makeRig(id){const canvas=document.querySelector('#model');try{rig=createRig(canvas);updateRig(id);}catch(e){console.error(e);canvas.parentElement.innerHTML='<div class="fallback">이 기기에서는 3D를 열 수 없어요.<br>옆의 글 안내와 함께 조립해 주세요.</div>';}}
function updateRig(id=steps[state.index].id){return rig?.set({id,mode:id==='compare'?compareMode:'stand',position,cell1,cell2,exploded,highlight});}
function home(){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});cleanup();if(studentState){state=studentState;studentState=null;}mode='home';document.body.className='';app.innerHTML=header()+`<main class="home"><section class="hero"><div><div class="eyebrow">함께 만들고, 스스로 알아내는 과학</div><h1>작은 전구에<br>두 가지 밝기를.</h1><p class="lead">전선은 어디에 꽂을까?<br>불이 안 켜지면 어떻게 할까?<br>코미랑 하나씩 만들어요.</p><div class="mentor" id="home-guide"></div></div><div class="hero-view"><div class="view-label">돌려 볼 수 있는 3D 조립 모형</div><canvas id="model" aria-label="2단 밝기 스탠드 3D 모형" tabindex="0"></canvas><div class="model-disclaimer">실제 교구의 홈과 단자는 함께 확인해요</div></div></section><div class="entry"><button data-start="self"><b>${state.furthest>0?`이어서 공부하기 · ${state.index+1}/20 →`:'스스로 공부하기 →'}</b><span>코미와 예상부터 조립·관찰·설명까지</span></button><button data-start="helper"><b>조립 도움 받기 →</b><span>전선과 부품을 한 단계씩, 막힐 때 다시 살펴요</span></button><button data-start="teacher"><b>선생님 수업하기 →</b><span>큰 화면으로 조립 시범과 실험을 직접 진행해요</span></button></div><div class="brief"><span>3단원 · 전류</span><span>1.5V 건전지 두 개 · 보호자 확인</span><span>내 기기에만 학습 기록 저장</span></div><section class="home-library"><div><span class="eyebrow">실험 옆 작은 과학 잡지</span><h2>전구 하나에서 궁궐의 밤까지</h2><p>전지의 연결 · 에디슨과 테슬라 · 우리나라 첫 전등</p></div><button data-action="magazine">읽을거리와 영상 펼치기 →</button></section></main>`;document.querySelector('.home-library').insertAdjacentHTML('beforebegin',`<section class="home-workbook"><div class="workbook-cover" aria-hidden="true"><span>팝콘 실험실</span><b>전류<br>탐험 노트</b><span>직접 쓰는 8쪽</span></div><div><span class="eyebrow">화면에서 살피고, 교재에 남겨요</span><h2>내 생각이 담기는 실험 교재</h2><p>예상부터 관찰, 나의 설명까지.<br>빈 교재를 인쇄하거나 이 기기에 남긴 기록을 이어 볼 수 있어요.</p></div><div class="workbook-entry-actions"><button data-action="workbook">교재 펼치기 →</button><a href="docs/student-workbook.pdf" download>학생용 PDF 받기 · 8쪽</a></div></section>`);position='off';exploded=false;makeRig('welcome');guide=createGuide(document.querySelector('#home-guide'));guide.set('fabre09-welcome',steps[0].voice,false);}
function start(which){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>{});notesOn=false;votes=[0,0,0];mode=which;observed=new Set();tested=new Set();position='off';cell1=cell2=true;compareMode='one';hotStop=false; if(which==='teacher'){studentState=structuredClone(state);state={index:0,furthest:0,done:{},prediction:'',records:{},recordKind:'screen',answers:{},tries:{},checked:{},report:'',checks:[]};}else if(which==='helper'){state.index=1;state.practice='real';}prepareNotebook(state);observed=new Set(state.observations||[]);tested=new Set(state.tested||[]);safetyReturn=null;render();}
function teacherNotes(s){const ask=s.kind==='predict'?'어떤 연결이 더 밝을까요? 그렇게 생각한 까닭은요?':s.kind==='compare'?'전지 하나를 빼면 어느 길이 남을까요?':s.kind==='wire'?'이 선의 시작과 끝은 각각 어느 단자일까요?':s.kind==='test'?'스위치를 바꾸면 전지 몇 개를 지나는 길이 될까요?':s.kind==='report'?'1단과 2단의 차이를 전지의 연결 방법으로 설명할 수 있나요?':'지금 확인할 부품과 연결 위치는 어디일까요?';return `<aside class="teacher-notes" id="teacher-notes" ${notesOn?'':'hidden'}><b>${esc(s.phase)} · 발문 노트</b><p>${esc(ask)}</p><p>${esc(s.tip)}</p><small>← 이전 · → / 스페이스 다음 · N 노트 · F 전체 화면<br>입력칸과 3D 조작 중에는 키보드 진행이 작동하지 않아요.</small></aside>`;}
function activity(s){
 const approved=state.done[s.id];
 if(s.kind==='ready')return '<h2>오늘의 실험</h2><p>예상 → 연결 비교 → 스탠드 조립 → 관찰 → 나의 설명</p><button class="primary" data-action="confirm" data-kind="ready">한 단계씩 시작할래요</button>';
 if(s.kind==='safety')return `<h2>어떻게 해 볼까요?</h2>${safetyReturn!==null?'<p class="feedback">실물 활동을 표시하기 전에 보호자와 확인해요. 확인 후 하던 단계로 돌아가요.</p>':''}<div class="choices practice-choice">${[['screen','화면으로 먼저 연습'],['real','실물 교구로 실험']].map(([v,t])=>`<button data-practice="${v}" aria-pressed="${practice()===v}">${t}</button>`).join('')}</div><p class="mode-label">${practice()==='screen'?'교구가 없어도 괜찮아요. 실물로 만들 때 지킬 약속을 읽어요.':'전지를 넣기 전에 보호자와 함께 아래 세 가지를 확인해요.'}</p><div class="checks">${safetyWords[practice()].map((t,i)=>`<label><input type="checkbox" data-safe="${i}" ${safetyChecks().includes(i)?'checked':''}>${t}</label>`).join('')}</div><p class="success" id="safe-feedback"></p>`;
 if(mode==='teacher'&&s.kind==='predict')return `<h2>예상 손들기</h2><p>학생들의 예상을 먼저 듣고, 손든 수를 표시해요.</p><div class="class-votes">${['직렬이 더 밝다','병렬이 더 밝다','밝기가 같다'].map((t,i)=>`<div><b>${t}</b><button data-vote="${i}" data-delta="-1" aria-label="${t} 한 명 줄이기">−</button><output id="vote-${i}">${votes[i]}</output><button data-vote="${i}" data-delta="1" aria-label="${t} 한 명 더하기">+</button></div>`).join('')}</div>`;
 if(mode==='teacher'&&s.kind==='quiz')return quiz.map((q,i)=>`<section class="class-question"><h2>${i+1}. ${esc(q.q)}</h2><ol>${q.options.map((t,j)=>`<li data-class-option="${i}-${j}">${esc(t)}</li>`).join('')}</ol><button data-reveal="${i}" aria-expanded="false">정답·해설 열기</button><p id="class-answer-${i}" class="feedback" hidden>○ ${esc(q.options[q.answer])}<br>${esc(q.why)}</p></section>`).join('');
 if(s.kind==='predict')return `<h2>내 예상은?</h2><div class="choices">${['직렬이 더 밝을 것 같아요','병렬이 더 밝을 것 같아요','둘 다 같을 것 같아요'].map(t=>`<button data-predict="${t}" aria-pressed="${state.prediction===t}">${t}</button>`).join('')}</div><p class="success" id="prediction-feedback">${state.prediction?'예상을 남겼어요. 다음 화면에서 비교해 봐요.':''}</p>`;
 if(s.kind==='compare')return `<h2>화면에서 연결을 바꿔요</h2><div class="choices">${[['one','전지 한 개'],['series','두 개 직렬'],['parallel','두 개 병렬']].map(([v,t])=>`<button data-compare="${v}" aria-pressed="${compareMode===v}">${t}</button>`).join('')}</div><div class="checks"><label><input type="checkbox" data-cell="1" ${cell1?'checked':''}>첫 번째 전지 넣기</label><label><input type="checkbox" data-cell="2" ${cell2?'checked':''} ${compareMode==='one'?'disabled':''}>두 번째 전지 넣기</label></div><div class="reading" id="reading"></div><div id="compare-plan" class="observation-plan"></div>${mode!=='teacher'?'<div id="comparison-note"></div>':''}<p class="success" id="observe-feedback" aria-live="polite"></p><button data-action="observe">지금 결과를 관찰했어요</button>`;
 if(['parts','confirm','wire','assemble'].includes(s.kind))return `<h2>${s.kind==='parts'?'부품을 찾았다면':'직접 한 뒤 표시해요'}</h2>${s.kind==='parts'?'<div class="material-tags"><b>A 바닥판</b><b>B 전구판</b><b>C 윗판</b><b>D 앞판</b><b>E 뒷판</b><b>F 옆판 ×2</b></div>':''}<div class="work-confirm"><button data-action="confirm" data-kind="screen">화면으로 조립을 연습했어요</button><button data-action="confirm" data-kind="real">실물 교구로 해 봤어요</button></div><p class="success" id="confirm-feedback">${approved?approved==='real'?'실물 조립으로 기록했어요.':'화면 연습으로 기록했어요.':''}</p>`;
 if(s.kind==='test')return `<h2>스위치를 눌러 비교해요</h2><div class="position">${[['off','가운데 · 꺼짐'],['low','1단'],['high','2단']].map(([v,t])=>`<button data-position="${v}" aria-pressed="${position===v}" ${hotStop?'disabled':''}>${t}</button>`).join('')}</div><div class="reading" id="reading"></div><p id="test-feedback" class="success" aria-live="polite"></p>`;
 if(s.kind==='record')return `<h2>관찰한 결과만 적어요</h2><label for="record-kind">어디서 관찰했나요?</label><select id="record-kind"><option value="screen" ${state.recordKind==='screen'?'selected':''}>화면 실험</option><option value="real" ${state.recordKind==='real'?'selected':''}>실물 교구 실험</option></select><p class="record-origin-note">화면과 실물 기록은 따로 보관해요. 관찰한 곳을 바꾸면 그곳에서 적은 기록이 보여요.</p><table><thead><tr><th>스위치</th><th>내가 본 밝기</th></tr></thead><tbody>${[['off','가운데'],['low','1단'],['high','2단']].map(([k,t])=>`<tr><td>${t}</td><td><select data-record="${k}" aria-label="${t} 관찰 밝기">${[['','선택해 주세요'],['off','꺼짐'],['dim','약하게 켜짐'],['bright','밝게 켜짐'],['other','다른 결과 / 잘 모르겠어요']].map(([v,l])=>`<option value="${v}" ${state.records[k]===v?'selected':''}>${l}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table><p class="success" id="record-feedback"></p>`;
 if(s.kind==='concept')return '<h2>스위치가 고르는 전류의 길</h2><p><strong>1단</strong>은 전지 한 개의 길.<br><strong>2단</strong>은 전지 두 개의 직렬 길.<br><strong>가운데</strong>는 길을 끊는 자리예요.</p><button data-action="confirm" data-kind="screen">그림과 설명을 비교했어요</button>';
 if(s.kind==='quiz')return quiz.map((q,i)=>`<fieldset class="quiz-block"><legend>${i+1}. ${esc(q.q)}</legend>${q.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}" ${state.answers[i]===j?'checked':''}>${esc(o)}</label>`).join('')}<button data-quiz="${i}">답 확인하기</button><p class="quiz-why" id="why-${i}">${state.checked[i]?esc(q.why):''}</p></fieldset>`).join('');
 if(s.kind==='report')return `<h2>글로 쓰거나 말로 시작해요</h2><label for="draft">내 설명 · 말로 입력해도 수정할 수 있어요</label><textarea id="draft" placeholder="1단과 2단에서 전지가 어떻게 연결되는지 써 보세요.">${esc(state.report)}</textarea><div class="report-actions"><button data-action="mic">마이크로 말하기</button><button data-action="selfcheck">초안 확인 · 셀프 체크</button></div><p class="mode-label">말한 내용은 브라우저 음성 인식 서비스로 전달될 수 있어요. 이 앱에는 글 초안만 저장돼요.</p><p id="mic-state" aria-live="polite"></p><div id="report-feedback"></div><div class="checks"><label><input type="checkbox" id="reviewed" ${state.done.report?'checked':''}>초안을 읽고 고친 뒤, 내 생각과 맞는지 확인했어요.</label></div>`;
 return `<h2>내 실험 기록</h2><p>${Object.values(state.done).filter(v=>v==='real').length}단계를 실물로, ${Object.values(state.done).filter(v=>v==='screen').length}단계를 화면으로 해 봤어요.</p><div class="report-actions"><button data-action="workbook">교재에 담긴 내 기록 보기</button><button data-action="print">한 장 기록 인쇄하기</button><button data-action="download">기록 파일 저장</button></div><p class="tip">오늘의 발견을 가족에게 설명해 보세요. 실험이 끝나면 전지를 빼고 정리해요.</p>`;
}
function assemblyVideo(s){return ['parts','confirm','wire','assemble','test'].includes(s.kind)?'<a class="assembly-video" href="https://m.site.naver.com/1e5E0" target="_blank" rel="noopener noreferrer" aria-label="책의 조립 영상 보기 (새 창)">▶ 책의 조립 영상 보기 ↗</a>':'';}
function render(){
 cleanup();document.body.className='lesson-mode '+mode;const s=steps[state.index];
 app.innerHTML=header()+`<main class="lesson"><aside class="rail" id="lesson-steps" hidden><div class="rail-title"><span>${mode==='helper'?'코미랑 조립하기':'나의 탐험'}</span><span>${state.index+1}/20</span></div><div class="progress"><i style="width:${(state.index+1)*5}%"></i></div><ol>${steps.map((t,i)=>`<li><button data-step="${i}" class="${i===state.index?'on':''}" ${mode!=='teacher'&&i>state.furthest?'disabled':''} ${i===state.index?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${esc(t.phase)}</button></li>`).join('')}</ol><p class="save-note">기록은 이 기기에만 저장돼요.<br>사진이나 이름을 보내지 않아요.</p></aside><section class="workspace"><div class="step-kicker">${esc(s.phase)} · ${mode==='teacher'?'선생님 수업':mode==='helper'?'코미랑 조립하기':'스스로 공부하기'}</div><div class="lesson-head"><h1 tabindex="-1">${esc(s.title)}</h1><div class="step-number">${state.index+1} / 20</div></div><div class="learning-grid"><div class="model-panel"><div class="viewport"><button class="fullscreen-close" data-action="model-exit">작게 보기 ×</button><div class="viewport-label">돌리기 · 두 손가락 확대</div><canvas id="model" tabindex="0" aria-label="${esc(s.title)} 3D 조립 안내"></canvas></div><div class="scene-tools">${assemblyVideo(s)}${['confirm','wire','assemble'].includes(s.kind)?'<button data-action="demo">조립 시범 다시 보기</button>':''}<button data-action="explode" aria-pressed="${exploded}">${exploded?'조립 모습 보기':'분해해서 보기'}</button><button data-action="highlight" aria-pressed="${highlight}">연결 위치 강조</button><button data-action="resetview">다시 가운데로</button><button data-action="model-fullscreen">3D 크게 보기</button></div></div><div class="text-panel"><div class="lesson-reading"><p class="instruction">${esc(s.body)}</p>${mode!=='teacher'?'<p class="task-next" id="task-next" aria-live="polite"></p>':''}<div class="activity">${activity(s)}</div>${studySupport(s)}${notebookSupport(s.id,state,mode==='teacher')}<p class="tip">${esc(s.tip)}</p></div>${mode!=='teacher'?'<div class="mentor" id="guide"></div>':''}</div></div><nav class="navigation" aria-label="학습 단계"><button class="help-link" data-action="help">${mode==='teacher'?'실험 도움말':'막혔어요 · 도움받기'}</button><span class="nav-state" id="nav-state"></span><div class="controls"><button data-action="previous" ${state.index===0?'disabled':''}>이전</button><button class="primary" data-action="next">${state.index===19?'처음으로':'다음 →'}</button></div></nav></section></main>${mode==='teacher'?teacherNotes(s):''}<section class="print-report" id="print-report"></section>`;
 makeRig(s.id);if(mode!=='teacher'){guide=createGuide(document.querySelector('#guide'));guide.set('fabre09-'+s.id,s.voice,true,()=>promptAction());}
 if(s.id==='compare'||s.id==='test')reading();refreshGate();document.querySelector('.lesson-head h1')?.focus({preventScroll:true});window.scrollTo(0,0);
}

function practice(){return state.practice==='real'?'real':'screen';}
function safetyChecks(){return practice()==='real'?state.checks:(state.screenChecks||[]);}
function pendingTask(){
 const s=steps[state.index];
 if(hotStop)return '실험을 멈췄어요. 도움말에서 보호자 확인을 받아 주세요.';
 if(allowed()&&state.index===1&&safetyReturn!==null)return `확인했어요. 다음을 누르면 “${steps[safetyReturn].phase}”로 돌아가요.`;
 if(allowed())return state.index===19?'기록을 저장하고 오늘의 발견을 이야기해요.':`확인했어요. 다음은 “${steps[state.index+1].phase}”예요.`;
 if(s.kind==='safety')return `안전 약속 ${safetyChecks().length}/3 · 남은 항목을 읽고 표시해 주세요.`;
 if(s.kind==='predict')return '내 예상을 하나 골라 주세요. 나중에 바뀌어도 괜찮아요.';
 if(s.kind==='compare'){const next=observations.find(t=>!observed.has(t.id));return `다음 관찰: ${next.label}. 아래 목록에서 고르고 전구를 살핀 뒤 관찰 버튼을 눌러요.`;}
 if(s.kind==='test'){const names={off:'가운데',low:'1단',high:'2단'};return `아직 ${['off','low','high'].filter(v=>!tested.has(v)).map(v=>names[v]).join(' · ')}을 살펴보지 않았어요. 버튼을 눌러 비교해요.`;}
 if(s.kind==='record'){const names={off:'가운데',low:'1단',high:'2단'};return `${names[['off','low','high'].find(v=>!state.records[v])]}에서 직접 본 밝기를 골라 주세요.`;}
 if(s.kind==='quiz')return `${quiz.findIndex((_,i)=>!state.checked[i])+1}번 답을 고르고 “답 확인하기”를 눌러 주세요.`;
 if(s.kind==='report')return state.report.trim()?'초안을 읽고 고친 뒤, 아래 확인란에 표시해 주세요.':'아래 질문을 떠올리며 내 설명을 쓰거나 말해 보세요.';
 if(s.kind==='ready')return '오늘 알아낼 두 가지를 읽고 “한 단계씩 시작할래요”를 눌러요.';
 if(s.kind==='concept')return '관찰한 밝기와 전지가 연결된 길을 비교한 뒤 확인해요.';
 return '모형을 돌려 위치를 살펴보고, 화면 연습 또는 실물 조립을 했는지 표시해요.';
}
function studySupport(s){const h=studyHint(s.id);return `<div class="workbook-bridge"><span>${workbookCue(s.id)}</span><button data-action="workbook">교재 ${workbookPageForStep(s.id)}쪽 →</button></div><details class="study-hint"><summary>${esc(h[0])} · 도움 보기</summary><ol>${h.slice(1).map(t=>`<li>${esc(t)}</li>`).join('')}</ol></details>${['welcome','compare','concept'].includes(s.id)?'<details class="study-hint"><summary>회로·전류, 무슨 뜻일까요?</summary><dl><dt>전기 회로</dt><dd>전지·전구·전선처럼 전기 부품을 연결해 만든 길이에요.</dd><dt>전류</dt><dd>전기 회로를 따라 흐르는 전기의 흐름이에요. 전구가 켜지려면 전지를 지나 되돌아오는 길이 이어져야 해요.</dd></dl></details>':''}${['compare','concept'].includes(s.id)?'<div class="reading-links"><button data-reading="battery">읽기 · 전지 두 개의 다른 쓰임</button></div>':['report','finish'].includes(s.id)?'<div class="reading-links"><button data-reading="city">에디슨과 테슬라</button><button data-reading="palace">우리나라 첫 전등</button></div>':''}`;}
function refreshObservations(){
 const host=document.querySelector('#compare-plan');
 if(host){const focus=document.activeElement?.dataset.observation;const current=observationKey(compareMode,cell1,cell2);host.innerHTML=`<p>관찰 노트 <b>${observations.filter(t=>observed.has(t.id)).length}/5</b></p><div>${observations.map(t=>`<button data-observation="${t.id}" ${hotStop?'disabled':''} aria-pressed="${current===t.id}">${observed.has(t.id)?'✓':'○'} ${t.label}<span>${observed.has(t.id)?'관찰함':'살펴보기'}</span></button>`).join('')}</div>`;if(focus)host.querySelector(`[data-observation="${focus}"]`)?.focus({preventScroll:true});}
 renderComparisonNote();
 const test=document.querySelector('#test-feedback');if(test)test.textContent=`${tested.size}/3 위치를 비교했어요.`;
}
function magazine(articleId){guide?.pause();recognition?.abort();closeWorkbook?.();closeMagazine?.();closeMagazine=openMagazine({teacher:mode==='teacher',articleId,onClose:()=>{closeMagazine=null;}});}
function workbookCue(id){if(id==='compare')return '교재 2~3쪽 · 본 결과와 남은 길을 기록해요.';if(['parts','paper','socket','switch','wire1','wire2','junction','wirelow','wirehigh','assembly'].includes(id))return '연결을 마친 뒤 교재에서 확인해요.';if(['test','record'].includes(id))return '예상과 달라도 직접 본 결과를 남겨요.';if(id==='report')return '내 관찰을 근거로 설명해요.';return '내가 적은 생각과 관찰을 이어 볼 수 있어요.';}
function renderComparisonNote(){const host=document.querySelector('#comparison-note');if(!host)return;const key=observationKey(compareMode,cell1,cell2);const open=host.querySelector('details')?.open||false;const signature=(key||'none')+':'+hotStop;if(host.dataset.signature===signature)return;host.dataset.signature=signature;host.innerHTML=comparisonNote(key,observations.find(t=>t.id===key)?.label||'',state,hotStop);if(open&&host.querySelector('details'))host.querySelector('details').open=true;}
function workbook(){guide?.pause();recognition?.abort();closeMagazine?.();closeWorkbook?.();const teacher=mode==='teacher';closeWorkbook=openWorkbook({teacher,record:teacher?{}:structuredClone(state),initialPage:mode==='home'?1:workbookPageForStep(steps[state.index].id),onClose:()=>{closeWorkbook=null;},onRead:articleId=>magazine(articleId),onNavigate:index=>{if(!Number.isInteger(index)||index<0||index>=steps.length||(!teacher&&index>state.furthest))return;if(steps[state.index].id==='compare'&&index!==state.index){cell1=cell2=true;position='off';}state.index=index;exploded=false;if(mode==='home')start('self');else render();save();}});}


function promptAction(){const next=document.querySelector('[data-action=next]');if(allowed())next?.classList.add('ready-pulse');else{const target=document.querySelector('.activity button:not(:disabled),.activity input:not(:checked),.activity select,.activity textarea');(target?.closest('label')||target)?.classList.add('ready-pulse');}}
function allowed(){const s=steps[state.index];if(mode==='teacher'||s.kind==='finish')return true;
 if(s.kind==='safety')return safetyChecks().length===3;
 if(s.kind==='predict')return !!state.prediction;
 if(s.kind==='compare')return !hotStop&&observations.every(v=>observed.has(v.id));
 if(s.kind==='test')return !hotStop&&['off','low','high'].every(v=>tested.has(v))||!hotStop&&!!state.done.test;
 if(s.kind==='record')return ['off','low','high'].every(k=>!!state.records[k]);
 if(s.kind==='quiz')return quiz.every((_,i)=>state.checked[i]);
 if(s.kind==='report')return !!state.report.trim()&&!!state.done.report;
 return !!state.done[s.id];}
function refreshGate(){const ok=allowed();const next=document.querySelector('[data-action=next]');if(next){next.disabled=!ok;next.classList.toggle('ready-pulse',ok&&mode!=='teacher');}const n=document.querySelector('#nav-state');if(n)n.textContent=ok?'준비되면 다음으로 가요':pendingTask();const task=document.querySelector('#task-next');if(task)task.textContent=pendingTask();refreshObservations();}
function mark(kind){state.done[steps[state.index].id]=kind;save();refreshGate();guide?.praise();}
function reading(){const id=steps[state.index].id;const r=circuitState({mode:id==='compare'?compareMode:'stand',position,cell1,cell2});const el=document.querySelector('#reading');if(el)el.innerHTML=`${r.brightness} · ${r.volts} V<small>${r.lit?'전구를 지나는 닫힌 길이 있어요.':'전구를 지나는 길이 끊겼어요.'} 화면의 밝기는 비교 모형이에요.</small>`;document.querySelectorAll('[data-position]').forEach(b=>{b.disabled=hotStop;b.setAttribute('aria-pressed',String(b.dataset.position===position));});document.querySelectorAll('[data-cell]').forEach(b=>{b.disabled=hotStop||(b.dataset.cell==='2'&&compareMode==='one');b.checked=b.dataset.cell==='1'?cell1:cell2;});document.querySelectorAll('[data-compare]').forEach(b=>{b.disabled=hotStop;});updateRig();}
function move(delta){if(delta>0&&!allowed())return;if(steps[state.index].id==='compare'){cell1=cell2=true;position='off';}if(state.index===19&&delta>0){home();return;}if(delta>0&&state.index===1&&safetyReturn!==null){state.index=safetyReturn;safetyReturn=null;}else if(delta>0&&mode==='helper'&&state.index===1)state.index=4;else state.index=Math.max(0,Math.min(19,state.index+delta));if(mode!=='teacher'){state.furthest=Math.max(state.furthest,state.index);save();}exploded=false;render();}
function help(){guide?.pause();recognition?.abort();const previous=document.activeElement;const overlay=document.createElement('div');overlay.className='popover-backdrop';overlay.innerHTML='<section class="dialog" role="dialog" aria-modal="true" aria-labelledby="help-title"><header><h2 id="help-title">어디에서 막혔나요?</h2><button data-close aria-label="도움말 닫기">닫기</button></header><div id="help-content"><section class="context-help"><h3>지금 할 일</h3><p>'+esc(pendingTask())+'</p><ol>'+studyHint(steps[state.index].id).slice(1).map(t=>'<li>'+esc(t)+'</li>').join('')+'</ol></section><h3>실물 교구에서 막혔나요?</h3><div class="help-options">'+helpers.map((h,i)=>`<button data-helper="${i}">${h.title}</button>`).join('')+'</div></div></section>';document.body.append(overlay);
 const key=e=>{if(e.key==='Escape'){e.preventDefault();closeHelp();}if(e.key==='Tab'){const buttons=[...overlay.querySelectorAll('button')];const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}};
 closeHelp=()=>{helpGuide?.dispose();helpGuide=null;overlay.remove();document.removeEventListener('keydown',key);previous?.focus();closeHelp=null;};document.addEventListener('keydown',key);overlay.querySelector('[data-close]').addEventListener('click',()=>closeHelp());overlay.addEventListener('click',e=>{const button=e.target.closest('[data-helper]');if(!button)return;const i=Number(button.dataset.helper),h=helpers[i];helpGuide?.dispose();const dialog=overlay.querySelector('.dialog');dialog.classList.toggle('hot',h.id==='hot');overlay.querySelector('#help-title').textContent=h.title;overlay.querySelector('#help-content').innerHTML=`${h.id==='hot'?'<p class="heat-care">실험을 멈추고 뜨거운 부분을 만지지 않은 채 어른에게 알려요. 전지 분리·제거는 보호자가 확인해요.</p>':''}<ul>${h.checks.map(t=>`<li>${t}</li>`).join('')}</ul>${mode!=='teacher'?'<div class="mentor" id="help-guide"></div>':''}<div class="help-actions"><button data-back-help>다른 도움말</button><button data-help-done>${h.id==='hot'?'보호자가 확인했어요':'확인하고 다시 해 볼게요'}</button></div>`;if(h.id==='hot'){hotStop=true;position='off';cell1=cell2=false;reading();refreshGate();}if(mode!=='teacher'){helpGuide=createGuide(overlay.querySelector('#help-guide'));helpGuide.set('fabre09-help-'+i,h.voice,true);}overlay.querySelector('[data-back-help]').onclick=()=>{closeHelp();help();};overlay.querySelector('[data-help-done]').onclick=()=>{if(h.id==='hot'){hotStop=false;cell1=cell2=true;reading();refreshGate();}closeHelp();};overlay.querySelector('[data-help-done]').focus();});overlay.querySelector('[data-close]').focus();}
function mic(){const button=document.querySelector('[data-action=mic]'),note=document.querySelector('#mic-state');if(recognition){recognition.stop();return;}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){note.textContent='이 브라우저에서는 말로 입력할 수 없어요. 글로 써 주세요.';return;}const r=new Speech();recognition=r;r.lang='ko-KR';r.continuous=false;r.interimResults=true;const initial=state.report;guide?.listen();button.textContent='말하기 마치기';note.textContent='말을 글자로 옮기는 중이에요. 초안은 나중에 고칠 수 있어요.';
 r.onresult=e=>{if(recognition!==r||!document.querySelector('#draft'))return;let result='';for(let i=0;i<e.results.length;i++)result+=e.results[i][0].transcript;state.report=initial+(initial?' ':'')+result;state.done.report=false;document.querySelector('#draft').value=state.report;document.querySelector('#reviewed').checked=false;save();refreshGate();};r.onerror=e=>{note.textContent=e.error==='not-allowed'?'마이크 사용이 허용되지 않았어요. 글로 써 주세요.':'말을 듣지 못했어요. 글로 쓰거나 다시 눌러 주세요.';};r.onend=()=>{if(recognition!==r)return;recognition=null;guide?.wait();button.textContent='마이크로 말하기';if(!note.textContent.includes('않'))note.textContent='초안을 읽고 고친 뒤 셀프 체크해 주세요.';};try{r.start();}catch{recognition=null;button.textContent='마이크로 말하기';note.textContent='마이크를 시작하지 못했어요. 글로 써 주세요.';}}
function reportCheck(){const t=state.report.trim();const el=document.querySelector('#report-feedback');if(!t){el.innerHTML='<p class="feedback retry">먼저 내 생각을 써 주세요.</p>';return;}const reminders=['1단에서 전지 한 개의 길을 설명했나요?','2단에서 전지 두 개가 직렬인 것을 설명했나요?','가운데 위치에서 길이 끊기는 것을 설명했나요?'];el.innerHTML='<div class="feedback"><strong>내 설명을 다시 읽어 봐요</strong><ul>'+reminders.map(t=>`<li>${t}</li>`).join('')+'</ul>자동 채점 결과가 아니에요. 내 글과 아래 기준을 비교해 고쳐 주세요.</div>';guide?.listen();}
function print(){const titles={off:'가운데',low:'1단',high:'2단'},values={off:'꺼짐',dim:'약하게 켜짐',bright:'밝게 켜짐',other:'다른 결과 / 잘 모르겠어요'};document.querySelector('#print-report').innerHTML=`<h1>나의 전류 실험 기록</h1><p>팝콘 실험실 · 파브르 9호 · 2단 밝기 스탠드</p><h2>나의 예상</h2><p>${esc(state.prediction||'아직 기록하지 않았어요')}</p><h2>${state.recordKind==='real'?'실물 교구':'화면 실험'} 관찰</h2><table>${Object.entries(titles).map(([k,t])=>`<tr><th>${t}</th><td>${esc(values[state.records[k]]||'미기록')}</td></tr>`).join('')}</table><h2>내가 설명한 전류의 길</h2><p>${esc(state.report||'아직 기록하지 않았어요')}</p><footer>학생이 직접 남긴 관찰과 설명입니다. 실물 연결 확인이나 자동 채점 결과를 뜻하지 않습니다.</footer>`;window.print();}
app.addEventListener('click',async e=>{if(e.target.closest('.brand')){e.preventDefault();home();return;}const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.start){start(b.dataset.start);return;}if(b.dataset.vote!=null&&mode==='teacher'){const i=Number(b.dataset.vote);votes[i]=Math.max(0,votes[i]+Number(b.dataset.delta));document.querySelector('#vote-'+i).textContent=votes[i];return;}if(b.dataset.reveal!=null&&mode==='teacher'){const i=Number(b.dataset.reveal),answer=document.querySelector('#class-answer-'+i);answer.hidden=!answer.hidden;b.setAttribute('aria-expanded',String(!answer.hidden));b.textContent=answer.hidden?'정답·해설 열기':'정답·해설 접기';document.querySelector(`[data-class-option="${i}-${quiz[i].answer}"]`).classList.toggle('correct',!answer.hidden);return;}if(b.dataset.step!=null){const i=Number(b.dataset.step);if(mode==='teacher'||i<=state.furthest){if(steps[state.index].id==='compare'&&i!==state.index){cell1=cell2=true;position='off';}state.index=i;exploded=false;save();render();}return;}
 if(b.dataset.reading){magazine(b.dataset.reading);return;}
 if(b.dataset.practice){state.practice=b.dataset.practice;save();render();return;}
 if(b.dataset.observation){if(hotStop)return;const t=observations.find(t=>t.id===b.dataset.observation);compareMode=t.mode;cell1=!t.remove;cell2=true;document.querySelectorAll('[data-compare]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.compare===compareMode)));reading();refreshGate();return;}
 if(b.dataset.predict){state.prediction=b.dataset.predict;save();document.querySelectorAll('[data-predict]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelector('#prediction-feedback').textContent='예상을 남겼어요. 다음 화면에서 비교해 봐요.';refreshGate();guide?.praise();return;}
 if(b.dataset.compare){if(hotStop)return;compareMode=b.dataset.compare;cell1=cell2=true;document.querySelectorAll('[data-compare]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-cell]').forEach(x=>{x.checked=true;x.disabled=x.dataset.cell==='2'&&compareMode==='one';});reading();refreshGate();return;}
 if(b.dataset.position){position=b.dataset.position;tested.add(position);state.tested=[...tested];save();document.querySelectorAll('[data-position]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));reading();document.querySelector('#test-feedback').textContent=`${tested.size}/3 위치를 비교했어요.`;if(tested.size===3)mark('screen');else refreshGate();return;}
 if(b.dataset.quiz!=null){const i=Number(b.dataset.quiz),q=quiz[i],val=document.querySelector(`input[name=q${i}]:checked`),why=document.querySelector('#why-'+i);if(!val){why.textContent='먼저 답을 골라 주세요.';return;}state.answers[i]=Number(val.value);state.tries[i]=(state.tries[i]||0)+1;if(state.answers[i]===q.answer){state.checked[i]=true;why.textContent='○ '+q.why;guide?.praise();}else{state.checked[i]=false;why.textContent=state.tries[i]>1?'× '+q.why+' 연결을 다시 생각해 골라 보세요.':'× '+quizHints[i];}save();refreshGate();return;}
 switch(b.dataset.action){case'workbook':workbook();break;case'magazine':magazine();break;case'home':home();break;case'steps':{const rail=document.querySelector('#lesson-steps');rail.hidden=!rail.hidden;b.setAttribute('aria-expanded',String(!rail.hidden));break;}case'notes':notesOn=!notesOn;document.querySelector('#teacher-notes').hidden=!notesOn;b.setAttribute('aria-expanded',String(notesOn));break;case'demo':exploded=false;document.querySelector('[data-action=explode]').setAttribute('aria-pressed','false');document.querySelector('[data-action=explode]').textContent='분해해서 보기';rig?.set({id:steps[state.index].id,position,cell1,cell2,highlight,demo:true});break;case'previous':move(-1);break;case'next':move(1);break;case'confirm':if(mode!=='teacher'&&b.dataset.kind==='real'&&state.checks.length!==3){safetyReturn=state.index;state.practice='real';state.index=1;render();break;}mark(b.dataset.kind);{const el=document.querySelector('#confirm-feedback');if(el)el.textContent=b.dataset.kind==='real'?'실물 조립으로 기록했어요.':'화면 연습으로 기록했어요.';}break;case'observe':{const key=observationKey(compareMode,cell1,cell2);const feedback=document.querySelector('#observe-feedback');if(!key){feedback.textContent='전지 한 개를 남겨 비교해 주세요. 아래 관찰 목록에서 연결을 고를 수 있어요.';break;}observed.add(key);state.observations=[...observed];save();feedback.textContent=observations.find(t=>t.id===key).label+' 관찰을 남겼어요.';if(observations.every(t=>observed.has(t.id)))mark('screen');else refreshGate();break;}case'explode':exploded=!exploded;b.setAttribute('aria-pressed',String(exploded));b.textContent=exploded?'조립 모습 보기':'분해해서 보기';updateRig();break;case'highlight':highlight=!highlight;b.setAttribute('aria-pressed',String(highlight));updateRig();break;case'resetview':updateRig();break;case'help':help();break;case'mic':mic();break;case'selfcheck':reportCheck();break;case'print':print();break;case'download':{const blob=new Blob([JSON.stringify({book:'팝콘 실험실 파브르 9호',unit:'전류',...state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='나의-전류-실험-기록.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}case'model-exit':await document.exitFullscreen();break;case'fullscreen':case'model-fullscreen':{const target=b.dataset.action==='model-fullscreen'?document.querySelector('.viewport'):document.documentElement;try{if(document.fullscreenElement===target)await document.exitFullscreen();else{if(document.fullscreenElement)await document.exitFullscreen();await target.requestFullscreen();}window.dispatchEvent(new Event('resize'));}catch{const note=document.querySelector('#nav-state');if(note)note.textContent='이 브라우저에서는 전체 화면을 지원하지 않아요.';}break;}}
});
app.addEventListener('change',e=>{const t=e.target;if(t.dataset.comparisonBrightness){const id=t.dataset.comparisonBrightness;state.comparisonNotes[id]={...state.comparisonNotes[id],brightness:t.value};save();t.closest('.notebook-fields').querySelector('.note-save').textContent='내가 고른 관찰을 저장했어요.';}if(t.dataset.safe!=null){state[practice()==='real'?'checks':'screenChecks']=[...document.querySelectorAll('[data-safe]:checked')].map(x=>Number(x.dataset.safe));if(safetyChecks().length===3)mark('ready');save();refreshGate();}if(t.dataset.cell){if(t.dataset.cell==='1')cell1=t.checked;else cell2=t.checked;reading();refreshGate();}if(t.id==='record-kind'){if(mode!=='teacher'&&t.value==='real'&&state.checks.length!==3){safetyReturn=state.index;state.practice='real';state.index=1;render();return;}selectRecordSource(state,t.value);save();document.querySelectorAll("[data-record]").forEach(input=>{input.value=state.records[input.dataset.record]||"";});document.querySelector("#record-feedback").textContent=state.recordKind==="real"?"실물에서 직접 본 결과를 적어요. 화면 기록은 따로 보관했어요.":"화면에서 적은 관찰 기록을 불러왔어요.";refreshGate();}if(t.dataset.record){state.records[t.dataset.record]=t.value;state.recordSets[state.recordKind]={...state.records};save();refreshGate();}if(t.id==='reviewed'){state.done.report=t.checked&&!!state.report.trim();save();refreshGate();}if(t.name?.startsWith('q')){const i=Number(t.name.slice(1));state.answers[i]=Number(t.value);state.checked[i]=false;document.querySelector('#why-'+i).textContent='';save();refreshGate();}});
app.addEventListener('input',e=>{const t=e.target;if(t.dataset.comparisonReason){const id=t.dataset.comparisonReason;state.comparisonNotes[id]={...state.comparisonNotes[id],reason:t.value};save();t.closest('.notebook-fields').querySelector('.note-save').textContent='내 관찰 메모를 저장했어요.';}if(noteKeys.includes(t.dataset.workbookNote)){state.workbookNotes[t.dataset.workbookNote]=t.value;save();t.closest('.notebook-fields').querySelector('.note-save').textContent='내 생각을 저장했어요.';}if(e.target.id==='draft'){state.report=e.target.value;state.done.report=false;document.querySelector('#reviewed').checked=false;save();refreshGate();}});
window.addEventListener('hashchange',()=>{if(location.hash==='#home')home();});window.addEventListener('pagehide',cleanup);document.addEventListener('fullscreenchange',()=>{const view=document.fullscreenElement;if(view?.classList.contains('viewport')){const host=document.querySelector('#guide');if(host){guideAnchor=document.createComment('guide dock');host.before(guideAnchor);view.append(host);}}else if(guideAnchor?.parentNode){const host=document.querySelector('#guide');if(host)guideAnchor.before(host);guideAnchor.remove();guideAnchor=null;}window.dispatchEvent(new Event('resize'));document.querySelector('#model')?.dispatchEvent(new Event('stage:moved'));});
document.addEventListener('keydown',e=>{if(mode==='home'||e.defaultPrevented||e.altKey||e.ctrlKey||e.metaKey||document.querySelector('.popover-backdrop,dialog[open]')||e.target.closest?.('input,textarea,select,button,canvas,a'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();move(1);}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();move(-1);}else if(e.key.toLowerCase()==='f')document.querySelector('[data-action=fullscreen]')?.click();else if(mode==='teacher'&&e.key.toLowerCase()==='n')document.querySelector('[data-action=notes]')?.click();});
home();
