import { levels, SOLIDS } from "../../games/net-observatory/levels.js?v=net-2";
import { text } from "../../games/net-observatory/i18n.js?v=net-2";

const $=(selector)=>document.querySelector(selector),t=(key,vars={})=>text("ko",key,vars);let offset=0;
const select=$("#levelSelect"),toggle=$("#answerToggle"),grid=$("#problemGrid");
levels.forEach((level)=>{const option=document.createElement("option");option.value=level.id;option.textContent=`${level.id}. ${t(level.titleKey)} · ${t(level.bandKey)}`;select.append(option);});

function netSvg(cells,faces=[]){const cols=Math.max(...cells.map(([x])=>x))+1,rows=Math.max(...cells.map(([,y])=>y))+1,faceMap=new Map(faces.map((face)=>[face.cell.join(","),face])),canvas=180,size=28,offsetX=(canvas-cols*size)/2,offsetY=(canvas-rows*size)/2;return `<svg class="net-svg" viewBox="0 0 ${canvas} ${canvas}" aria-hidden="true">${cells.map(([x,y])=>{const face=faceMap.get(`${x},${y}`),arrow=face?.arrow?{up:"↑",right:"→",down:"↓",left:"←"}[face.arrow]:"",left=offsetX+x*size,top=offsetY+y*size;return `<g><rect x="${left}" y="${top}" width="${size}" height="${size}" fill="${face?.color||"#efd08d"}"/><text x="${left+size/2}" y="${top+(arrow?13:18)}">${face?.label||""}</text>${arrow?`<text class="arrow" x="${left+size/2}" y="${top+25}">${arrow}</text>`:""}</g>`;}).join("")}</svg>`;}
function cubeView(view){const arrow=(side)=>view[`${side}Arrow`]?`<i>${{up:"↑",right:"→",down:"↓",left:"←"}[view[`${side}Arrow`]]}</i>`:"";return `<span class="cube-view"><span class="cube-face top"><b>${view.top}</b>${arrow("top")}</span><span class="cube-face front"><b>${view.front}</b>${arrow("front")}</span><span class="cube-face right"><b>${view.right}</b>${arrow("right")}</span></span>`;}
function solidSvg(solid){const shapes={tetra:[[100,12,25,135,175,135],[100,12,100,106,25,135],[100,12,175,135,100,106]],cube:[[42,50,100,18,158,50,100,82],[42,50,100,82,100,145,42,112],[100,82,158,50,158,112,100,145]],octa:[[100,8,24,78,100,75],[100,8,176,78,100,75],[24,78,100,75,100,150],[176,78,100,75,100,150]],dodeca:[[100,10,158,42,144,105,100,145,56,105,42,42],[42,42,100,72,56,105],[158,42,100,72,144,105]],icosa:[[100,6,26,54,66,76],[100,6,66,76,100,67],[100,6,100,67,134,76],[100,6,134,76,174,54],[26,54,66,76,36,136],[66,76,100,67,100,152],[134,76,100,67,100,152],[174,54,134,76,164,136]]};return `<svg class="solid-svg" viewBox="0 0 200 160" aria-hidden="true">${(shapes[solid.id]||[]).map((points,index)=>`<polygon class="facet f${index%4}" points="${points.join(" ")}"/>`).join("")}</svg>`;}
function answerIndex(problem){if(problem.interaction==="choose-net"||problem.interaction==="fold-view"||problem.interaction==="symbol-view")return problem.choices.findIndex((choice)=>choice.id===problem.answer);if(problem.interaction==="dice-pair")return problem.answer;if(problem.interaction==="dice-opposite"||problem.interaction==="solid-adjacent")return problem.choices.indexOf(problem.answer);return problem.choices.findIndex((choice)=>choice.id===problem.answer);}
function prompt(problem){const vars=problem.interaction==="dice-opposite"?{face:problem.face}:problem.solid?{solid:t(problem.solid.nameKey)}:{};return t(problem.promptKey,vars);}
function choiceMarkup(problem,choice,index,show){const correct=show&&index===answerIndex(problem),mark=correct?" correct":"";if(problem.interaction==="choose-net")return `<div class="choice net-choice${mark}"><em>${index+1}</em>${netSvg(choice.cells)}</div>`;if(problem.interaction==="fold-view"||problem.interaction==="symbol-view")return `<div class="choice view-choice${mark}"><em>${index+1}</em>${cubeView(choice)}</div>`;if(problem.interaction==="dice-pair")return `<div class="choice number-choice${mark}"><em>${index+1}</em><strong>${choice[0]} ↔ ${choice[1]}</strong></div>`;if(problem.interaction==="dice-opposite"||problem.interaction==="solid-adjacent")return `<div class="choice number-choice${mark}"><em>${index+1}</em><strong>${choice}</strong></div>`;return `<div class="choice word-choice${mark}"><em>${index+1}</em><strong>${t(choice.nameKey)}</strong></div>`;}
function answerText(problem){const index=answerIndex(problem);if(problem.interaction==="fold-view"||problem.interaction==="symbol-view"){const view=problem.choices[index];return `정답 ${index+1}번 · 위 ${view.top}, 앞 ${view.front}, 오른쪽 ${view.right}`;}if(problem.interaction==="dice-opposite")return `정답 ${problem.answer} · 마주 보는 두 면의 합은 7` ;if(problem.interaction==="dice-pair"){const pair=problem.choices[index];return `정답 ${index+1}번 · ${pair[0]}과 ${pair[1]}`;}if(problem.interaction==="solid-adjacent")return `정답 ${problem.answer}개 · 한 면의 변 수와 같아요.`;if(problem.interaction==="solid-identify")return `정답 ${index+1}번 · ${t(problem.solid.nameKey)}`;return `정답 ${index+1}번 · 여섯 면이 겹치지 않고 접혀요.`;}
function problemVisual(problem,show){if(problem.interaction==="choose-net")return `<div class="choice-grid net-options">${problem.choices.map((choice,index)=>choiceMarkup(problem,choice,index,show)).join("")}</div>`;if(problem.interaction==="fold-view"||problem.interaction==="symbol-view")return `<div class="source-net">${netSvg(problem.cells,problem.faces)}</div><div class="choice-grid view-options">${problem.choices.map((choice,index)=>choiceMarkup(problem,choice,index,show)).join("")}</div>`;if(problem.interaction.startsWith("dice")){const face=problem.interaction==="dice-opposite"?problem.face:"?";return `<div class="simple-stage"><span class="die">${face}</span><div class="choice-grid simple-options">${problem.choices.map((choice,index)=>choiceMarkup(problem,choice,index,show)).join("")}</div></div>`;}return `<div class="simple-stage solid-stage">${solidSvg(problem.solid)}<small>${problem.solid.faces}개의 ${t(problem.solid.faceShape)} 면</small><div class="choice-grid simple-options">${problem.choices.map((choice,index)=>choiceMarkup(problem,choice,index,show)).join("")}</div></div>`;}
function problemsPerPage(level){return [1,2,4].includes(level.id)?3:4;}
function render(){const level=levels[Number(select.value||1)-1],show=toggle.checked,count=problemsPerPage(level),problems=Array.from({length:count},(_,index)=>level.problems[(offset+index)%level.problems.length]);grid.dataset.large=String(count===3);$("#sheetTitle").textContent=t(level.titleKey);$("#sheetDescription").textContent=t(level.subtitleKey);grid.replaceChildren();problems.forEach((problem,index)=>{const article=document.createElement("article");article.className=`problem interaction-${problem.interaction}`;article.innerHTML=`<header><b>${index+1}</b><span>${prompt(problem)}</span></header><div class="visual">${problemVisual(problem,show)}</div><div class="answer-line">${show?answerText(problem):"답: ____________________"}</div>`;grid.append(article);});}
select.addEventListener("change",()=>{offset=0;render();});toggle.addEventListener("change",render);$("#refreshButton").addEventListener("click",()=>{const level=levels[Number(select.value||1)-1];offset=(offset+problemsPerPage(level))%10;render();});$("#printButton").addEventListener("click",()=>print());render();
