(function(root){
 'use strict';
 const $=id=>document.getElementById(id),catalog=root.HFTypeAccessCatalog,rows=catalog.list().sort((a,b)=>a.id-b.id);
 let students=[],selected=null,original=new Set(),desired=new Set(),busy=false,epoch=0,listener=false,expiryTimer=null;
 function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
 function clearPrivate(){epoch++;students=[];selected=null;original.clear();desired.clear();$('student').replaceChildren(new Option('학생 선택',''));$('student').disabled=true;$('permissions').hidden=true;$('bank-options').replaceChildren();$('student-name').textContent='';$('current-mode').textContent='';$('mode-impact').textContent='';$('selection-count').textContent='';$('individual-mode').checked=false;$('save').disabled=true;if(expiryTimer)clearTimeout(expiryTimer);status('로그인 상태가 바뀌었습니다. 학생 목록을 다시 확인해 주세요.');}
 async function invoke(name,body){
  if(root.GFieldHFSupabase?.enabled()!==true)throw Error('서버 연결 설정을 확인해 주세요.');
  const requestEpoch=epoch,client=await root.GFieldHFSupabase.ready();if(!client)throw Error('서버 연결을 확인해 주세요.');
  if(!listener&&client.auth?.onAuthStateChange){listener=true;client.auth.onAuthStateChange(event=>{if(['SIGNED_OUT','SIGNED_IN','USER_UPDATED','TOKEN_REFRESHED'].includes(event))clearPrivate();});}
  if(client.auth?.getSession){const result=await client.auth.getSession(),expires=result.data?.session?.expires_at;if(Number.isFinite(expires)){if(expires*1000<=Date.now()){clearPrivate();throw Error('로그인이 만료되었습니다.');}if(expiryTimer)clearTimeout(expiryTimer);expiryTimer=setTimeout(clearPrivate,expires*1000-Date.now());}}
  const {data,error}=await client.functions.invoke(name,{body});if(requestEpoch!==epoch)throw Error('로그인 상태가 변경되어 이전 응답을 표시하지 않습니다.');if(error||data?.error)throw Error(data?.error||'관리자 로그인과 서버 연결을 확인해 주세요.');return data;
 }
 function changes(){return [...rows.map(r=>r.key),catalog.modeKey].filter(k=>original.has(k)!==desired.has(k)).map(key=>({key,enabled:desired.has(key)}));}
 function sync(){const count=changes().length,n=rows.filter(r=>desired.has(r.key)).length,mode=desired.has(catalog.modeKey);$('change-count').textContent=count?`${count}개 항목 변경`:'변경 없음';$('selection-count').textContent=`전체 54유형 중 ${n}유형 선택`;$('save').disabled=busy||!selected||count===0;$('individual-mode').checked=mode;$('individual-mode').disabled=busy||selected?.status!=='active';$('mode-impact').textContent=mode?`저장 후 개별 승인 적용 · ${n}유형${n===0?' · 이용 가능한 문제은행 유형 없음':''}`:'저장 후 기존 상품 승인 유지 · 유형 선택만으로 전환되지 않음';}
 function render(){const search=$('type-search').value.trim(),bank=$('bank-options');bank.replaceChildren();const matches=rows.filter(r=>!search||r.label.includes(search)||String(r.id)===search);for(const row of matches){const label=document.createElement('label');label.className='permission-item';const input=document.createElement('input');input.type='checkbox';input.dataset.key=row.key;input.checked=desired.has(row.key);input.disabled=busy||selected?.status!=='active';input.addEventListener('change',()=>{input.checked?desired.add(row.key):desired.delete(row.key);sync();});const span=document.createElement('span');span.textContent=String(row.id).padStart(2,'0')+' · '+row.label;label.append(input,span);bank.append(label);}if(!matches.length)bank.textContent='조건에 맞는 유형이 없습니다.';sync();}
 function select(){selected=students.find(s=>s.id===$('student').value)||null;$('permissions').hidden=!selected;if(!selected){original.clear();desired.clear();$('student-name').textContent='';$('bank-options').replaceChildren();return;}original=new Set((selected.permissions||[]).filter(k=>catalog.has(k)));desired=new Set(original);$('student-name').textContent=selected.name+' 학생';$('current-mode').textContent=original.has(catalog.modeKey)?'현재: 개별 승인 방식':'현재: 기존 상품 승인 방식';render();status(selected.status==='active'?'변경할 유형과 승인 방식을 확인해 주세요.':'비활성 학생입니다. 기존 학생 관리에서 상태를 확인해 주세요.',selected.status!=='active');}
 async function load(){if(busy)return;clearPrivate();busy=true;$('reload').disabled=true;status('기존 학생 목록을 확인하고 있습니다.');try{const data=await invoke('admin-students',{action:'list'});if(!Array.isArray(data.students))throw Error('학생 목록 응답을 확인할 수 없습니다.');students=data.students;students.forEach(s=>$('student').append(new Option(s.name+(s.status==='active'?'':' · 비활성'),s.id)));$('student').disabled=false;status('학생을 선택해 주세요.');}catch(e){clearPrivate();status(e.message,true);}finally{busy=false;$('reload').disabled=false;}}
 async function save(){if(busy||!selected)return;const edits=changes(),target=selected,requestEpoch=epoch;if(!edits.length)return;busy=true;render();$('student').disabled=true;$('reload').disabled=true;let done=0;try{for(const edit of edits){const data=await invoke('hyperfocus-type-access',{action:'set',studentId:target.id,permissionKey:edit.key,enabled:edit.enabled});if(data?.ok!==true||data.studentId!==target.id||data.permissionKey!==edit.key||data.enabled!==edit.enabled)throw Error('저장 결과를 확인할 수 없습니다.');edit.enabled?original.add(edit.key):original.delete(edit.key);done++;}status(`${done}개 승인 항목을 저장했습니다.`);}catch(e){status(`${done}개 저장되었습니다. 저장되지 않은 변경은 남아 있습니다. ${e.message}`,true);}finally{busy=false;$('reload').disabled=false;if(requestEpoch===epoch&&selected===target){target.permissions=[...new Set([...(target.permissions||[]).filter(k=>!catalog.has(k)),...original])];$('current-mode').textContent=original.has(catalog.modeKey)?'현재: 개별 승인 방식':'현재: 기존 상품 승인 방식';$('student').disabled=false;render();}}}
 $('reload').addEventListener('click',load);$('student').addEventListener('change',select);$('save').addEventListener('click',save);$('type-search').addEventListener('input',render);$('individual-mode').addEventListener('change',()=>{$('individual-mode').checked?desired.add(catalog.modeKey):desired.delete(catalog.modeKey);sync();});
 // Mode is saved last, after explicitly changed type keys. No automatic grants or mode conversion.
})(window);
