import { levels, directionBits } from "../../games/path-walk/levels.js?v=path-walk-1";
const $=selector=>document.querySelector(selector);let offset=0;const select=$("#levelSelect"),toggle=$("#answerToggle"),grid=$("#problemGrid");
levels.forEach(level=>{const option=document.createElement("option");option.value=level.id;option.textContent=`${level.id}. ${level.title.ko} · ${level.difficulty}`;select.append(option);});
function tileSvg(mask){const ends=[];if(mask&directionBits.N)ends.push([50,0]);if(mask&directionBits.E)ends.push([100,50]);if(mask&directionBits.S)ends.push([50,100]);if(mask&directionBits.W)ends.push([0,50]);const path=ends.map(([x,y])=>`M50 50 L${x} ${y}`).join(" ");return `<svg viewBox="0 0 100 100"><path class="road-shadow" d="${path}"></path><path class="road-line" d="${path}"></path><circle class="road-center" cx="50" cy="50" r="9"></circle></svg>`;}
function endpointHtml(problem,index){return problem.endpoints.filter(endpoint=>endpoint.index===index).map(endpoint=>`<span class="endpoint ${endpoint.kind} endpoint-${endpoint.dir}">${endpoint.kind==="start"?"S":"★"}</span>`).join("");}
function tileBoard(problem,answer){const masks=answer?problem.solved:problem.initial;return `<div class="problem-board" style="--cols:${problem.cols};--rows:${problem.rows}">${masks.map((mask,index)=>`<div class="tile${mask?"":" empty"}">${problem.interaction==="hidden-tile"&&index===problem.hiddenIndex&&!answer?'<span class="hidden">?</span>':mask?tileSvg(mask):""}${endpointHtml(problem,index)}</div>`).join("")}</div>${problem.interaction==="hidden-tile"&&!answer?`<div class="choice-row">${problem.choices.map(mask=>`<div class="choice">${tileSvg(mask)}</div>`).join("")}</div>`:""}`;}
function gridBoard(problem,answer){const blocked=new Set(problem.blocked),path=new Set(answer?problem.answerPath:[]);return `<div class="problem-board" style="--cols:${problem.cols};--rows:${problem.rows}">${Array.from({length:problem.rows*problem.cols},(_,index)=>`<div class="grid-cell${blocked.has(index)?" blocked":""}${path.has(index)?" path":""}${index===problem.start?" start":""}${index===problem.goal?" goal":""}"></div>`).join("")}</div>`;}
function render(){const level=levels[Number(select.value||1)-1],show=toggle.checked,problems=Array.from({length:6},(_,index)=>level.problems[(offset+index)%level.problems.length]);$("#sheetTitle").textContent=level.title.ko;$("#sheetDescription").textContent=level.description.ko;grid.replaceChildren();problems.forEach((problem,index)=>{const article=document.createElement("article");article.className="problem";const prompt=problem.interaction==="draw-shortest"?`가장 가까운 길을 그리세요.${show?` 정답: ${problem.shortest}칸`:""}`:problem.interaction==="hidden-tile"?"물음표에 들어갈 타일을 고르세요.":"빛나는 타일을 돌려 길을 완성하세요.";article.innerHTML=`<header><b>${index+1}</b><span>${prompt}</span></header>${problem.interaction==="draw-shortest"?gridBoard(problem,show):tileBoard(problem,show)}<div class="answer-line">${show&&problem.interaction!=="draw-shortest"?"정답 모양":""}</div>`;grid.append(article);});}
select.addEventListener("change",()=>{offset=0;render();});toggle.addEventListener("change",render);$("#refreshButton").addEventListener("click",()=>{offset=(offset+6)%10;render();});$("#printButton").addEventListener("click",()=>print());render();
