import { levels, directionBits, rotateMask, validateNetwork } from "./levels.js?v=path-walk-2";
import { readGameProgress, saveGameProgress } from "../../shared/profile-storage.js";

const $ = (selector) => document.querySelector(selector);
const params = new URLSearchParams(location.search);
const saved = readGameProgress("pathWalk");
const storedLanguage = localStorage.getItem("gfield-language") || "ko";
const lang = ["ko", "zh", "ja", "en"].includes(storedLanguage) ? storedLanguage : "ko";
const requestedLevel = Math.max(1, Math.min(5, Number(params.get("level")) || Number(saved.level) || 1));
const SESSION_SIZE = 5;
const recentKey = "gfield-path-walk-recent";
const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)");

const copy = {
  ko:{levels:"레벨",hint:"힌트",retry:"다시",worksheet:"학습지",next:"다음 문제",promptTile:"빛나는 길 타일을 눌러 출발점과 목적지를 이어 보세요.",promptBranch:"갈림길을 돌려 두 목적지에 모두 닿게 해 보세요.",promptShortest:"출발 칸부터 이웃한 칸을 차례로 눌러 가장 가까운 길을 그리세요.",promptHidden:"앞뒤 길을 보고 물음표 자리에 들어갈 타일을 고르세요.",guideTile:"타일을 누르면 오른쪽으로 90도 돌아가요.",guideShortest:"지나간 칸은 다시 밟을 수 없어요. 바로 전 칸을 누르면 한 칸 되돌아가요.",guideHidden:"길이 들어오는 변과 나가는 변을 함께 살펴보세요.",guideTitle:"길을 살펴봐요",turns:"돌린 횟수",moves:"지나간 칸",goal:"목표",oneGoal:"1곳",twoGoals:"2곳",shortestGoal:"{n}칸",boardTag:"길 타일",gridTag:"격자 산책",boardTitle:"끊기지 않게 연결해요",shortestTitle:"가장 가까운 길을 찾아요",hiddenTitle:"숨은 타일을 찾아요",waiting:"연결 전",connected:"길 완성",correct:"길이 모두 이어졌어요!",wrongHidden:"이 방향이면 길이 중간에 끊겨요.",notShortest:"목적지에는 도착했지만 가장 가까운 길은 {n}칸이에요.",blocked:"막힌 칸은 지나갈 수 없어요.",revisit:"이미 지나간 칸은 다시 밟을 수 없어요.",adjacent:"지금 있는 칸과 맞닿은 칸을 눌러 보세요.",levelComplete:"레벨 {n} 완료!",complete:"길의 방향을 끝까지 정확하게 이어 냈어요.",nextLevel:"다음 레벨",practice:"같은 레벨 더 풀기",world:"도형월드",chooseLevel:"레벨 선택",start:"S",target:"★"},
  en:{levels:"Levels",hint:"Hint",retry:"Restart",worksheet:"Worksheet",next:"Next",promptTile:"Tap the glowing tiles to connect start and goal.",promptBranch:"Turn branch tiles so the path reaches both goals.",promptShortest:"Tap adjacent cells from the start to draw a shortest route.",promptHidden:"Use the neighboring roads to choose the hidden tile.",guideTile:"Each tap turns a tile 90 degrees clockwise.",guideShortest:"Do not revisit cells. Tap the previous cell to step back.",guideHidden:"Check where the route enters and leaves the hidden cell.",guideTitle:"Read the route",turns:"Turns",moves:"Cells walked",goal:"Goal",oneGoal:"1 place",twoGoals:"2 places",shortestGoal:"{n} cells",boardTag:"ROAD TILES",gridTag:"GRID WALK",boardTitle:"Connect every road",shortestTitle:"Find a shortest route",hiddenTitle:"Find the hidden tile",waiting:"Not connected",connected:"Connected",correct:"Every road is connected!",wrongHidden:"That direction breaks the route.",notShortest:"You arrived, but a shortest route uses {n} cells.",blocked:"You cannot cross a blocked cell.",revisit:"You cannot visit the same cell twice.",adjacent:"Choose a cell next to your current cell.",levelComplete:"Level {n} complete!",complete:"You followed every route direction accurately.",nextLevel:"Next level",practice:"Practice again",world:"Geometry World",chooseLevel:"Choose a level",start:"S",target:"★"},
  zh:{levels:"关卡",hint:"提示",retry:"重来",worksheet:"练习纸",next:"下一题",promptTile:"点击发光的道路拼片，连接起点和终点。",promptBranch:"旋转岔路，让道路到达两个终点。",promptShortest:"从起点依次点击相邻格，画出最短路线。",promptHidden:"根据相邻道路选择隐藏拼片。",guideTile:"每次点击会顺时针旋转90度。",guideShortest:"不能重复格子，点击前一个格子可后退。",guideHidden:"同时观察道路进入和离开的方向。",guideTitle:"观察道路",turns:"旋转次数",moves:"经过格子",goal:"目标",oneGoal:"1处",twoGoals:"2处",shortestGoal:"{n}格",boardTag:"道路拼片",gridTag:"方格散步",boardTitle:"让道路不断开",shortestTitle:"寻找最短路线",hiddenTitle:"寻找隐藏拼片",waiting:"尚未连接",connected:"完成",correct:"道路全部连通！",wrongHidden:"这个方向会让道路断开。",notShortest:"到达了，但最短路线是{n}格。",blocked:"不能经过障碍格。",revisit:"不能重复经过同一格。",adjacent:"请选择当前格旁边的格子。",levelComplete:"第{n}关完成！",complete:"你准确连接了所有道路。",nextLevel:"下一关",practice:"再练一次",world:"几何世界",chooseLevel:"选择关卡",start:"起",target:"★"},
  ja:{levels:"レベル",hint:"ヒント",retry:"やり直す",worksheet:"プリント",next:"次の問題",promptTile:"光るタイルを押してスタートとゴールをつなぎましょう。",promptBranch:"分かれ道を回して二つのゴールへつなぎましょう。",promptShortest:"スタートから隣のマスを押して最短の道を描きましょう。",promptHidden:"前後の道から隠れたタイルを選びましょう。",guideTile:"押すたびに右へ90度回ります。",guideShortest:"同じマスは通れません。一つ前を押すと戻れます。",guideHidden:"道が入る辺と出る辺を一緒に見ましょう。",guideTitle:"道を見よう",turns:"回した回数",moves:"通ったマス",goal:"ゴール",oneGoal:"1か所",twoGoals:"2か所",shortestGoal:"{n}マス",boardTag:"道タイル",gridTag:"マスの散歩",boardTitle:"切れないようにつなごう",shortestTitle:"いちばん近い道",hiddenTitle:"隠れたタイル",waiting:"まだ",connected:"完成",correct:"道が全部つながりました！",wrongHidden:"この向きでは道が切れます。",notShortest:"着きましたが、最短は{n}マスです。",blocked:"ふさがったマスは通れません。",revisit:"同じマスは二度通れません。",adjacent:"今いるマスの隣を押しましょう。",levelComplete:"レベル{n}クリア！",complete:"道の向きを正しくつなげました。",nextLevel:"次のレベル",practice:"もう一度",world:"図形ワールド",chooseLevel:"レベルを選ぶ",start:"S",target:"★"}
};
const t = (key, vars = {}) => Object.entries(vars).reduce((value, [name, replacement]) => value.replaceAll(`{${name}}`, replacement), copy[lang]?.[key] || copy.ko[key] || key);

const supportCopy = {
  ko:{tile:"{row}행 {col}열 길 타일, 길 방향 {dirs}. 누르면 오른쪽으로 회전",locked:"{row}행 {col}열 고정 길 타일, 길 방향 {dirs}",choice:"보기 {n}, 길 방향 {dirs}",cell:"{row}행 {col}열",blockedCell:"{row}행 {col}열, 막힌 칸",hintTile:"빛나는 타일의 방향부터 살펴보세요.",hintTurn:"그 타일을 오른쪽으로 한 번 돌렸어요.",hintNeighbor:"지금 칸과 맞닿은 칸들을 먼저 살펴보세요.",hintExact:"초록 테두리 칸이 가장 가까운 길의 다음 칸이에요.",hintEliminate:"길이 끊기는 보기 하나를 지웠어요.",hintChoice:"초록 테두리 보기의 들어오는 길과 나가는 길을 비교해 보세요."},
  en:{tile:"Row {row}, column {col}, route tile facing {dirs}. Press to turn right",locked:"Row {row}, column {col}, fixed route tile facing {dirs}",choice:"Choice {n}, route facing {dirs}",cell:"Row {row}, column {col}",blockedCell:"Row {row}, column {col}, blocked",hintTile:"Start by checking the glowing tile.",hintTurn:"That tile turned one step to the right.",hintNeighbor:"First check the cells beside your current cell.",hintExact:"The green-outlined cell is the next step on a shortest route.",hintEliminate:"One choice that breaks the route was removed.",hintChoice:"Compare where the green-outlined route enters and leaves."},
  zh:{tile:"第{row}行第{col}列道路拼片，方向{dirs}。按下向右旋转",locked:"第{row}行第{col}列固定道路拼片，方向{dirs}",choice:"选项{n}，道路方向{dirs}",cell:"第{row}行第{col}列",blockedCell:"第{row}行第{col}列，障碍格",hintTile:"先观察发光拼片的方向。",hintTurn:"这块拼片向右旋转了一次。",hintNeighbor:"先观察当前位置旁边的格子。",hintExact:"绿色边框是最短路线的下一格。",hintEliminate:"已排除一个会让道路断开的选项。",hintChoice:"比较绿色边框选项的入口和出口。"},
  ja:{tile:"{row}行{col}列の道タイル、方向は{dirs}。押すと右へ回転",locked:"{row}行{col}列の固定タイル、方向は{dirs}",choice:"選択肢{n}、道の方向は{dirs}",cell:"{row}行{col}列",blockedCell:"{row}行{col}列、通れないマス",hintTile:"光るタイルの向きを見てみましょう。",hintTurn:"そのタイルを右へ一回回しました。",hintNeighbor:"今いるマスの隣を先に見ましょう。",hintExact:"緑の枠が最短の次のマスです。",hintEliminate:"道が切れる選択肢を一つ消しました。",hintChoice:"緑の枠の道の入口と出口を比べましょう。"}
};
const directionNames = {
  ko:{N:"위",E:"오른쪽",S:"아래",W:"왼쪽"}, en:{N:"up",E:"right",S:"down",W:"left"},
  zh:{N:"上",E:"右",S:"下",W:"左"}, ja:{N:"上",E:"右",S:"下",W:"左"}
};
const support = (key, vars = {}) => Object.entries(vars).reduce((value,[name,replacement])=>value.replaceAll(`{${name}}`,replacement),supportCopy[lang]?.[key]||supportCopy.ko[key]||key);
const maskLabel = (mask) => Object.entries(directionBits).filter(([,bit])=>mask&bit).map(([dir])=>directionNames[lang]?.[dir]||directionNames.ko[dir]).join(", ");

function shuffle(items) { const result=[...items]; for(let i=result.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];} return result; }
function makeSession(levelIndex) { let recent={}; try{recent=JSON.parse(localStorage.getItem(recentKey)||"{}");}catch{recent={};} const excluded=new Set(recent[levelIndex+1]||[]); const ordered=[...levels[levelIndex].problems].sort((a,b)=>a.reasoningSteps-b.reasoningSteps||a.id.localeCompare(b.id)); let pool=ordered.filter((problem)=>!excluded.has(problem.id)); if(pool.length<SESSION_SIZE)pool=shuffle(ordered); const session=pool.slice(0,SESSION_SIZE); recent[levelIndex+1]=session.map((problem)=>problem.id); localStorage.setItem(recentKey,JSON.stringify(recent)); return session; }

const state={level:requestedLevel-1,index:0,queue:makeSession(requestedLevel-1),masks:[],path:[],turns:0,solved:false,busy:false,hintCell:null,hintCells:[],hintStep:0,hintChoice:null,eliminatedChoices:[],autoNextTimer:null,audio:localStorage.getItem("gfield-audio-muted")!=="true"};
const ui={levelLabel:$("#levelLabel"),problemLabel:$("#problemLabel"),difficulty:$("#difficultyLabel"),title:$("#missionTitle"),prompt:$("#prompt"),guideTitle:$("#guideTitle"),guideText:$("#guideText"),turnsTitle:$("#turnsTitle"),turnCount:$("#turnCount"),goalTitle:$("#goalTitle"),goalCount:$("#goalCount"),boardTag:$("#boardTag"),boardTitle:$("#boardTitle"),status:$("#routeStatus"),board:$("#gameBoard"),choices:$("#choiceTray"),hint:$("#hintButton"),retry:$("#retryButton"),next:$("#nextButton"),sound:$("#soundButton"),levels:$("#levelButton"),levelDialog:$("#levelDialog"),levelList:$("#levelList"),closeLevels:$("#closeLevels"),complete:$("#completeDialog"),completeTitle:$("#completeTitle"),completeText:$("#completeText"),nextLevel:$("#nextLevelButton"),practice:$("#practiceButton"),success:$("#success"),toast:$("#toast")};
const problem=()=>state.queue[state.index];
const currentLevel=()=>levels[state.level];

function tileSvg(mask) {
  const ends=[];
  if(mask&directionBits.N)ends.push([50,0]); if(mask&directionBits.E)ends.push([100,50]); if(mask&directionBits.S)ends.push([50,100]); if(mask&directionBits.W)ends.push([0,50]);
  const path=ends.map(([x,y])=>`M50 50 L${x} ${y}`).join(" ");
  return `<svg viewBox="0 0 100 100" aria-hidden="true"><path class="road-groove" d="${path}"></path><path class="road-shadow" d="${path}"></path><path class="road-line" d="${path}"></path><path class="road-highlight" d="${path}"></path><circle class="road-center-shadow" cx="50" cy="50" r="13"></circle><circle class="road-center" cx="50" cy="50" r="10"></circle><circle class="road-center-highlight" cx="47" cy="47" r="4"></circle></svg>`;
}

function endpointHtml(problemData,index){return problemData.endpoints.filter((endpoint)=>endpoint.index===index).map((endpoint)=>`<span class="endpoint ${endpoint.kind} endpoint-${endpoint.dir}">${endpoint.kind==="start"?t("start"):t("target")}</span>`).join("");}

function renderTileBoard(focusIndex = null) {
  const p=problem(); ui.board.replaceChildren(); ui.board.style.setProperty("--cols",p.cols); ui.board.style.setProperty("--rows",p.rows);
  const editable=new Set(p.editable);
  state.masks.forEach((mask,index)=>{
    const cell=document.createElement("button"); cell.type="button";
    cell.dataset.index=String(index);
    const row=Math.floor(index/p.cols)+1,col=index%p.cols+1;
    if(p.interaction==="hidden-tile"&&index===p.hiddenIndex){cell.className="route-cell locked hidden-cell";cell.disabled=true;cell.setAttribute("aria-label",support("cell",{row,col}));cell.innerHTML=`<span class="hidden-mark">?</span>${endpointHtml(p,index)}`;}
    else if(!mask){cell.className="route-cell empty";cell.disabled=true;}
    else{cell.className=`route-cell ${editable.has(index)?"editable":"locked"}${state.hintCell===index?" hint":""}`;cell.disabled=!editable.has(index)||state.solved;cell.setAttribute("aria-label",support(editable.has(index)?"tile":"locked",{row,col,dirs:maskLabel(mask)}));cell.innerHTML=`${tileSvg(mask)}${endpointHtml(p,index)}`;if(editable.has(index))cell.addEventListener("click",()=>rotateTile(index));}
    ui.board.append(cell);
  });
  if(p.interaction==="hidden-tile")renderChoices(); else{ui.choices.hidden=true;ui.choices.replaceChildren();}
  if(focusIndex!==null)ui.board.querySelector(`[data-index="${focusIndex}"]`)?.focus({preventScroll:true});
}

function renderChoices(){const p=problem();ui.choices.hidden=false;ui.choices.replaceChildren();p.choices.forEach((mask,index)=>{const button=document.createElement("button");button.type="button";button.className=`tile-choice${state.eliminatedChoices.includes(index)?" eliminated":""}${state.hintChoice===index?" hinted":""}`;button.setAttribute("aria-label",support("choice",{n:index+1,dirs:maskLabel(mask)}));button.disabled=state.eliminatedChoices.includes(index)||state.solved;button.innerHTML=tileSvg(mask);button.addEventListener("click",()=>chooseHidden(index,button));ui.choices.append(button);});}

function renderGridBoard(focusIndex = null){const p=problem(),blocked=new Set(p.blocked),walked=new Set(state.path);ui.board.replaceChildren();ui.board.style.setProperty("--cols",p.cols);ui.board.style.setProperty("--rows",p.rows);for(let index=0;index<p.rows*p.cols;index+=1){const row=Math.floor(index/p.cols)+1,col=index%p.cols+1;const cell=document.createElement("button");cell.type="button";cell.dataset.index=String(index);cell.className=`grid-cell${blocked.has(index)?" blocked":""}${walked.has(index)?" walked":""}${index===p.start?" start":""}${index===p.goal?" goal":""}${state.hintCells.includes(index)?" hint":""}`;cell.setAttribute("aria-label",support(blocked.has(index)?"blockedCell":"cell",{row,col}));cell.disabled=blocked.has(index)||state.solved;cell.addEventListener("click",()=>walkTo(index));ui.board.append(cell);}ui.choices.hidden=true;if(focusIndex!==null)ui.board.querySelector(`[data-index="${focusIndex}"]`)?.focus({preventScroll:true});}

function render(reset=true){clearTimeout(state.autoNextTimer);const p=problem(),level=currentLevel();if(reset){state.masks=[...(p.initial||[])];state.path=p.interaction==="draw-shortest"?[p.start]:[];state.turns=0;state.solved=false;state.busy=false;state.hintCell=null;state.hintCells=[];state.hintStep=0;state.hintChoice=null;state.eliminatedChoices=[];}document.documentElement.lang=lang;ui.levelLabel.textContent=`LEVEL ${level.id}`;ui.problemLabel.textContent=`${state.index+1} / ${SESSION_SIZE}`;ui.difficulty.textContent=level.difficulty;ui.title.textContent=level.title[lang]||level.title.ko;ui.prompt.textContent=p.interaction==="draw-shortest"?t("promptShortest"):p.interaction==="hidden-tile"?t("promptHidden"):level.id===3?t("promptBranch"):t("promptTile");ui.guideTitle.textContent=t("guideTitle");ui.guideText.textContent=p.interaction==="draw-shortest"?t("guideShortest"):p.interaction==="hidden-tile"?t("guideHidden"):t("guideTile");ui.turnsTitle.textContent=p.interaction==="draw-shortest"?t("moves"):t("turns");ui.goalTitle.textContent=t("goal");ui.goalCount.textContent=p.interaction==="draw-shortest"?t("shortestGoal",{n:Math.max(0,p.shortest-1)}):level.id===3?t("twoGoals"):t("oneGoal");ui.boardTag.textContent=p.interaction==="draw-shortest"?t("gridTag"):t("boardTag");ui.boardTitle.textContent=p.interaction==="draw-shortest"?t("shortestTitle"):p.interaction==="hidden-tile"?t("hiddenTitle"):t("boardTitle");ui.status.textContent=t("waiting");ui.status.classList.remove("connected");ui.next.hidden=true;if(p.interaction==="draw-shortest")renderGridBoard();else renderTileBoard();updateCount();saveGameProgress("pathWalk",{level:state.level+1,problemIndex:state.index,queue:state.queue.map((item)=>item.id)});}

function updateCount(){const p=problem();const atGoal=p.interaction==="draw-shortest"&&state.path.at(-1)===p.goal;ui.turnCount.textContent=p.interaction==="draw-shortest"?Math.max(0,state.path.length-1-(atGoal?1:0)):state.turns;}
function rotateTile(index){if(state.solved||state.busy)return;state.masks[index]=rotateMask(state.masks[index]);state.turns+=1;state.hintCell=null;state.hintStep=0;renderTileBoard(index);updateCount();if(validateNetwork(problem(),state.masks))solve();}
function chooseHidden(index,button){if(state.solved||state.busy)return;const p=problem(),candidate=[...state.masks];candidate[p.hiddenIndex]=p.choices[index];if(validateNetwork(p,candidate)){state.masks=candidate;renderTileBoard();solve();return;}button.classList.add("wrong");tone("wrong");showToast(t("wrongHidden"));setTimeout(()=>button.classList.remove("wrong"),500);}
function walkTo(index){if(state.solved)return;const p=problem(),last=state.path.at(-1),previous=state.path.at(-2);if(index===previous){state.path.pop();state.hintCells=[];state.hintStep=0;renderGridBoard(state.path.at(-1));updateCount();return;}if(p.blocked.includes(index)){showToast(t("blocked"));return;}if(state.path.includes(index)){showToast(t("revisit"));return;}const row=Math.floor(index/p.cols),col=index%p.cols,lastRow=Math.floor(last/p.cols),lastCol=last%p.cols;if(Math.abs(row-lastRow)+Math.abs(col-lastCol)!==1){showToast(t("adjacent"));return;}state.path.push(index);state.hintCells=[];state.hintStep=0;renderGridBoard(index);updateCount();if(index===p.goal){if(state.path.length-1===p.shortest)solve();else showToast(t("notShortest",{n:Math.max(0,p.shortest-1)}));}}

function solve(){state.solved=true;ui.status.textContent=t("connected");ui.status.classList.add("connected");ui.next.hidden=false;ui.board.querySelectorAll("button").forEach((button)=>button.disabled=true);ui.choices.querySelectorAll("button").forEach((button)=>button.disabled=true);showToast(t("correct"));celebrate();saveGameProgress("pathWalk",{level:state.level+1,problemIndex:state.index,queue:state.queue.map((item)=>item.id),completedProblem:problem().id});scheduleAutoAdvance();}

function availableNeighbors(p,current){const row=Math.floor(current/p.cols),col=current%p.cols;return [[row-1,col],[row,col+1],[row+1,col],[row,col-1]].filter(([r,c])=>r>=0&&r<p.rows&&c>=0&&c<p.cols).map(([r,c])=>r*p.cols+c).filter((cell)=>!p.blocked.includes(cell)&&!state.path.includes(cell));}
function distanceToGoal(p,start,unavailable){const distance=new Map([[start,0]]),queue=[start];while(queue.length){const current=queue.shift();if(current===p.goal)return distance.get(current);const row=Math.floor(current/p.cols),col=current%p.cols;for(const [r,c] of [[row-1,col],[row,col+1],[row+1,col],[row,col-1]]){if(r<0||r>=p.rows||c<0||c>=p.cols)continue;const cell=r*p.cols+c;if(p.blocked.includes(cell)||unavailable.has(cell)||distance.has(cell))continue;distance.set(cell,distance.get(current)+1);queue.push(cell);}}return Infinity;}
function shortestNextCells(p){const current=state.path.at(-1),used=new Set(state.path.slice(0,-1)),stepsUsed=state.path.length-1;return availableNeighbors(p,current).filter((cell)=>stepsUsed+1+distanceToGoal(p,cell,used)===p.shortest);}
function hint(){const p=problem();if(state.solved)return;if(p.interaction==="draw-shortest"){if(state.hintStep===0){state.hintCells=availableNeighbors(p,state.path.at(-1));state.hintStep=1;showToast(support("hintNeighbor"));}else{state.hintCells=shortestNextCells(p);if(!state.hintCells.length){state.path=[p.start];state.hintCells=shortestNextCells(p);}state.hintStep=0;showToast(support("hintExact"));}renderGridBoard();updateCount();return;}if(p.interaction==="hidden-tile"){if(!state.eliminatedChoices.length){const wrong=p.choices.findIndex((_,index)=>index!==p.answer);state.eliminatedChoices=[wrong];showToast(support("hintEliminate"));}else{state.hintChoice=p.answer;showToast(support("hintChoice"));}renderChoices();return;}const index=p.editable.find((cellIndex)=>state.masks[cellIndex]!==p.solved[cellIndex]);if(index===undefined)return;if(state.hintCell!==index){state.hintCell=index;state.hintStep=1;renderTileBoard();showToast(support("hintTile"));return;}state.masks[index]=rotateMask(state.masks[index]);state.turns+=1;state.hintCell=null;state.hintStep=0;renderTileBoard();updateCount();showToast(support("hintTurn"));if(validateNetwork(p,state.masks))solve();}

function tone(kind){if(!state.audio)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;const context=new AudioContext();const notes=kind==="success"?[523,659,784]:kind==="wrong"?[180,145]:[440,554];notes.forEach((frequency,index)=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,context.currentTime+index*.08);gain.gain.exponentialRampToValueAtTime(.1,context.currentTime+index*.08+.015);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+index*.08+.18);oscillator.connect(gain).connect(context.destination);oscillator.start(context.currentTime+index*.08);oscillator.stop(context.currentTime+index*.08+.2);});setTimeout(()=>context.close(),650);}
function celebrate(){const words=["GOOD JOB!","GREAT JOB!","SUCCESS!"];ui.success.querySelector("strong").textContent=words[Math.floor(Math.random()*words.length)];ui.success.classList.remove("show");void ui.success.offsetWidth;ui.success.classList.add("show");clearTimeout(celebrate.timer);celebrate.timer=setTimeout(()=>ui.success.classList.remove("show"),reducedMotion.matches?220:1250);tone("success");}
function showToast(message){ui.toast.textContent=message;ui.toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>ui.toast.classList.remove("show"),2200);}
function scheduleAutoAdvance(){clearTimeout(state.autoNextTimer);state.autoNextTimer=setTimeout(nextProblem,reducedMotion.matches?140:1150);}
function nextProblem(){clearTimeout(state.autoNextTimer);if(!state.solved)return;if(state.index<SESSION_SIZE-1){state.index+=1;render();return;}ui.completeTitle.textContent=t("levelComplete",{n:state.level+1});ui.completeText.textContent=t("complete");ui.nextLevel.textContent=t("nextLevel");ui.nextLevel.hidden=state.level===levels.length-1;ui.practice.textContent=t("practice");ui.complete.querySelector("a").textContent=t("world");ui.complete.hidden=false;requestAnimationFrame(()=>ui.practice.focus());}
function startLevel(index){state.level=index;state.index=0;state.queue=makeSession(index);ui.levelDialog.hidden=true;ui.complete.hidden=true;render();renderLevelDialog();}
function renderLevelDialog(){ui.levelList.replaceChildren();levels.forEach((level,index)=>{const button=document.createElement("button");button.type="button";button.className="level-card";button.setAttribute("aria-current",index===state.level?"true":"false");button.innerHTML=`<span>${level.id}</span><strong>${level.title[lang]||level.title.ko}</strong><small>${level.description[lang]||level.description.ko}</small>`;button.addEventListener("click",()=>startLevel(index));ui.levelList.append(button);});}

ui.hint.addEventListener("click",hint);ui.retry.addEventListener("click",()=>render());ui.next.addEventListener("click",nextProblem);ui.levels.addEventListener("click",()=>{ui.levelDialog.hidden=false;requestAnimationFrame(()=>ui.levelList.querySelector("[aria-current='true']")?.focus());});ui.closeLevels.addEventListener("click",()=>{ui.levelDialog.hidden=true;ui.levels.focus();});ui.nextLevel.addEventListener("click",()=>startLevel(Math.min(levels.length-1,state.level+1)));ui.practice.addEventListener("click",()=>startLevel(state.level));ui.sound.addEventListener("click",()=>{state.audio=!state.audio;localStorage.setItem("gfield-audio-muted",String(!state.audio));ui.sound.innerHTML=state.audio?"&#9835;":"&#9834;&#824;";});document.addEventListener("keydown",(event)=>{if(event.key!=="Escape")return;if(!ui.levelDialog.hidden){ui.levelDialog.hidden=true;ui.levels.focus();}else if(!ui.complete.hidden){ui.complete.hidden=true;ui.levels.focus();}});
renderLevelDialog();render();
