import { levels, validateLevels } from "./levels.js?v=paper-fold-1";
import { readGameProgress, saveGameProgress } from "../../shared/profile-storage.js";

validateLevels();
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const params = new URLSearchParams(location.search);
const saved = readGameProgress("paperFold");
const queryLevel = Number(params.get("level"));
const requestedLevel = Math.max(1, Math.min(5, queryLevel || Number(saved.level) || 1));
const resumeProblem = queryLevel ? 0 : Math.max(0, Math.min(4, Number(saved.problemIndex) || 0));
const state = { lang: localStorage.getItem("gfield-language") || "ko", level: requestedLevel - 1, problem: resumeProblem, fold: 0, solved: false, hints: 0, wrong: 0, audio: localStorage.getItem("gfield-audio-muted") !== "true", tutorial: -1 };

const ui = { paper:$("#paper"), crease:$("#crease"), arrow:$("#foldArrow"), numbers:$("#numberGrid"), marks:$("#marks"), stack:$("#stackView"), status:$("#foldStatus"), prompt:$("#prompt"), answerPrompt:$("#answerPrompt"), choices:$("#choices"), next:$("#nextButton"), guide:$("#foldyGuide"), bubble:$("#guideBubble"), accessory:$("#foldyAccessory"), success:$("#success"), toast:$("#toast"), levelDialog:$("#levelDialog"), levelList:$("#levelList"), tutorial:$("#tutorial"), tutorialText:$("#tutorialText"), tutorialDots:$("#tutorialDots"), tutorialNext:$("#tutorialNext"), complete:$("#completeDialog") };

const I18N = {
  ko:{levels:"레벨",hint:"힌트",retry:"다시",worksheet:"학습지",next:"다음 문제",chooseLevel:"레벨 선택",foldFirst:"반짝이는 선을 눌러 종이를 접어 보세요.",answer:"정답을 골라 보세요.",correct:"정확해! 접힌 자리를 잘 찾았어.",wrong:"접힌 방향을 다시 천천히 살펴보자.",hintFold:"접은 순서를 거꾸로 한 단계씩 펼쳐 봐.",tap:"{dir} 방향으로 접기",done:"접기 완료",hole:"펼쳤을 때 구멍은 모두 몇 개일까요?",punch:"펼쳤을 때 생기는 모양의 수는 몇 개일까요?",top:"가장 위에 놓이는 수는 무엇일까요?",numberRemain:"남아 있는 수의 합은 얼마일까요?",numberCut:"잘려나간 수의 합은 얼마일까요?",cut:"펼쳤을 때 종이는 몇 조각일까요?",shape:"펼친 모양으로 알맞은 것을 고르세요.",stackBottom:"가장 아래에 있는 색종이는 무엇일까요?",stackOrder:"위에서부터 차례로 고르세요.",complete:"레벨 {n} 완료!",completeText:"새로운 접기 기술을 익혔어!",nextLevel:"다음 레벨",practice:"한 번 더",tutorial:["안녕! 나는 색종이 공방 친구 폴디야.","처음에는 반짝이는 접는 선만 보면 돼. 종이를 한 번 눌러 보자.","접기가 끝나면 답을 골라. 틀려도 접힌 방향을 다시 보면 돼!"],start:"시작하기",continue:"다음"},
  zh:{levels:"等级",hint:"提示",retry:"重来",worksheet:"练习纸",next:"下一题",chooseLevel:"选择等级",foldFirst:"点击发光的折线来折纸。",answer:"请选择答案。",correct:"正确！你找到了折叠位置。",wrong:"再慢慢看看折叠方向。",hintFold:"按相反顺序一步一步展开。",tap:"向{dir}折",done:"折叠完成",hole:"展开后共有几个孔？",punch:"展开后共有几个图形？",top:"最上面的数字是什么？",numberRemain:"剩下数字的和是多少？",numberCut:"剪掉数字的和是多少？",cut:"展开后共有几块？",shape:"选择正确的展开图。",stackBottom:"哪张纸在最下面？",stackOrder:"从上到下选择顺序。",complete:"第 {n} 级完成！",completeText:"学会了新的折纸技巧！",nextLevel:"下一级",practice:"再练一次",tutorial:["你好！我是折纸工坊的 Foldy。","先看发光的折线，点击纸张把它折起来。","折完后选择答案。答错也可以再看方向！"],start:"开始",continue:"下一步"},
  ja:{levels:"レベル",hint:"ヒント",retry:"もう一度",worksheet:"プリント",next:"次の問題",chooseLevel:"レベルを選ぶ",foldFirst:"光る折り線をタップして折りましょう。",answer:"答えを選びましょう。",correct:"正解！折った場所がわかったね。",wrong:"折る向きをゆっくり見直そう。",hintFold:"折った順番と反対に一つずつ開こう。",tap:"{dir}へ折る",done:"折り終わり",hole:"開くと穴はいくつ？",punch:"開くと形はいくつ？",top:"一番上の数は？",numberRemain:"残った数の合計は？",numberCut:"切り取った数の合計は？",cut:"開くと何枚になる？",shape:"正しい開いた形を選ぼう。",stackBottom:"一番下の紙は？",stackOrder:"上から順番に選ぼう。",complete:"レベル {n} クリア！",completeText:"新しい折り方を覚えたよ！",nextLevel:"次のレベル",practice:"もう一度",tutorial:["こんにちは！折り紙工房のフォルディだよ。","最初は光る折り線だけ見て、紙をタップしよう。","折り終わったら答えを選ぼう。まちがえても大丈夫！"],start:"スタート",continue:"次へ"},
  en:{levels:"Levels",hint:"Hint",retry:"Again",worksheet:"Worksheet",next:"Next",chooseLevel:"Choose a Level",foldFirst:"Tap the glowing crease to fold the paper.",answer:"Choose your answer.",correct:"Correct! You tracked the fold.",wrong:"Look at the folding direction again.",hintFold:"Unfold one step at a time in reverse order.",tap:"Fold {dir}",done:"Fold complete",hole:"How many holes after unfolding?",punch:"How many shapes after unfolding?",top:"Which number is on top?",numberRemain:"What is the sum of the remaining numbers?",numberCut:"What is the sum of the cut numbers?",cut:"How many pieces after unfolding?",shape:"Choose the correct unfolded shape.",stackBottom:"Which paper is at the bottom?",stackOrder:"Choose the order from top to bottom.",complete:"Level {n} Complete!",completeText:"You learned a new folding skill!",nextLevel:"Next Level",practice:"Practice Again",tutorial:["Hi! I am Foldy from Origami Studio.","Start with the glowing crease. Tap the paper once to fold it.","When folding is done, choose an answer. You can always look again!"],start:"Start",continue:"Next"}
};
const t=(key,vars={})=>Object.entries(vars).reduce((v,[k,x])=>v.replaceAll(`{${k}}`,String(x)),I18N[state.lang]?.[key]??I18N.ko[key]??key);
const problem=()=>levels[state.level].problems[state.problem];
const dirName=(dir)=>({ko:{left:"왼쪽",right:"오른쪽",up:"위",down:"아래","diag-main":"대각선","diag-anti":"반대 대각선"},zh:{left:"左",right:"右",up:"上",down:"下","diag-main":"对角线","diag-anti":"另一条对角线"},ja:{left:"左",right:"右",up:"上",down:"下","diag-main":"ななめ","diag-anti":"反対のななめ"},en:{left:"left",right:"right",up:"up",down:"down","diag-main":"diagonally","diag-anti":"the other diagonal"}}[state.lang]||{})[dir]||dir;

function applyLanguage(){document.documentElement.lang=state.lang;$$('[data-i18n]').forEach(n=>n.textContent=t(n.dataset.i18n));renderLevelList();updateScreen()}
function promptKey(type){return ({hole:"hole",punch:"punch",top:"top","number-remain":"numberRemain","number-cut":"numberCut",cut:"cut",shape:"shape","stack-bottom":"stackBottom","stack-order":"stackOrder"})[type]||"answer"}
function setGuide(message,speakIt=false){ui.bubble.textContent=message;ui.guide.classList.add("show");clearTimeout(setGuide.timer);setGuide.timer=setTimeout(()=>ui.guide.classList.remove("show"),2200);if(speakIt)speak(message)}
function speak(message){if(!state.audio||!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(message);u.lang={ko:"ko-KR",zh:"zh-CN",ja:"ja-JP",en:"en-US"}[state.lang];u.rate=.94;u.pitch=1.18;speechSynthesis.speak(u)}
let audioContext;
function playEffect(kind){
  if(!state.audio)return;
  const AudioContextClass=window.AudioContext||window.webkitAudioContext;
  if(!AudioContextClass)return;
  audioContext ||= new AudioContextClass();
  const notes=kind==="success"?[523,659,784]:kind==="wrong"?[196,165]:[440,554];
  notes.forEach((frequency,index)=>{
    const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();
    oscillator.type=kind==="success"?"triangle":"sine";
    oscillator.frequency.value=frequency;
    gain.gain.setValueAtTime(.0001,audioContext.currentTime+index*.07);
    gain.gain.exponentialRampToValueAtTime(kind==="wrong"?.025:.045,audioContext.currentTime+index*.07+.015);
    gain.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+index*.07+.15);
    oscillator.connect(gain).connect(audioContext.destination);
    oscillator.start(audioContext.currentTime+index*.07);
    oscillator.stop(audioContext.currentTime+index*.07+.17);
  });
}
function updateSound(){$("#soundButton").textContent=state.audio?"♪":"∕";$("#soundButton").setAttribute("aria-pressed",String(state.audio))}
function foldScale(folds){let x=1,y=1,rot=0;folds.forEach(d=>{if(d==="left"||d==="right")x*=.58;else if(d==="up"||d==="down")y*=.58;else{rot+=d==="diag-main"?45:-45;x*=.74;y*=.74}});return{x,y,rot}}
function renderNumbers(p){ui.numbers.replaceChildren();if(!p.numbers)return;p.numbers.forEach((value,index)=>{const b=document.createElement("b");b.textContent=value;b.classList.toggle("removed",p.removed?.includes(index));ui.numbers.append(b)})}
function renderMarks(p){ui.marks.replaceChildren();if(state.fold<p.folds.length)return;const count=p.punches||0;for(let i=0;i<count;i++){const m=document.createElement("i");m.className="hole-mark";ui.marks.append(m)}for(let i=0;i<(p.cuts||0);i++){const m=document.createElement("i");m.className=`cut-mark${i?" second":""}`;ui.marks.append(m)}}
function renderStack(p){ui.stack.replaceChildren();(p.layers||[]).forEach((letter,index,array)=>{const s=document.createElement("span");s.className="stack-sheet";s.textContent=letter;s.style.zIndex=String(array.length-index);s.style.setProperty("--r",`${[-8,7,-2][index]}deg`);s.style.setProperty("--x",`${index*5}px`);s.style.setProperty("--y",`${index*3}px`);ui.stack.append(s)})}
function renderChoices(){const p=problem();ui.choices.replaceChildren();p.choices.forEach(value=>{const b=document.createElement("button");b.type="button";b.className=`choice${p.type==="shape"?` shape-choice shape-${String(value).toLowerCase()}`:""}`;b.textContent=value.replaceAll("-"," → ");b.disabled=state.fold<p.folds.length||state.solved;b.addEventListener("click",()=>checkAnswer(value,b));ui.choices.append(b)})}
function updateScreen(){const p=problem(),level=levels[state.level],isStack=p.type.startsWith("stack");$("#levelLabel").textContent=`LEVEL ${level.id}`;$("#problemLabel").textContent=`${state.problem+1} / ${level.problems.length}`;$("#missionTitle").textContent=level.title[state.lang]||level.title.ko;$("#stars").textContent=`${"★".repeat(level.id)}${"☆".repeat(5-level.id)}`;ui.guide.dataset.level=String(level.id);ui.accessory.textContent=["","●","123","✂","★"][state.level];ui.stack.hidden=!isStack;ui.paper.hidden=isStack;ui.paper.className="paper";const scale=foldScale(p.folds.slice(0,state.fold));ui.paper.style.setProperty("--fold-x",scale.x);ui.paper.style.setProperty("--fold-y",scale.y);ui.paper.style.setProperty("--paper-rot",`${scale.rot}deg`);renderNumbers(p);renderStack(p);const waiting=state.fold<p.folds.length;if(waiting){const dir=p.folds[state.fold];ui.crease.className=`crease ${dir.startsWith("diag")?dir:dir==="left"||dir==="right"?"vertical":"horizontal"}`;ui.arrow.className=`fold-arrow ${dir}`;ui.paper.classList.add("ready");ui.status.textContent=t("tap",{dir:dirName(dir)});ui.prompt.textContent=t("foldFirst");ui.answerPrompt.textContent=t("foldFirst")}else{ui.crease.className="crease done";ui.arrow.className="fold-arrow";ui.status.textContent=t("done");ui.prompt.textContent=t(promptKey(p.type));ui.answerPrompt.textContent=t(promptKey(p.type))}renderMarks(p);renderChoices();ui.next.hidden=!state.solved;updateSound()}
function foldPaper(){const p=problem();if(state.solved||state.fold>=p.folds.length)return;state.fold+=1;playEffect("fold");const scale=foldScale(p.folds.slice(0,state.fold));ui.paper.style.setProperty("--fold-x",scale.x);ui.paper.style.setProperty("--fold-y",scale.y);ui.paper.style.setProperty("--paper-rot",`${scale.rot}deg`);setTimeout(updateScreen,430)}
function checkAnswer(value,button){if(state.solved)return;if(String(value)===problem().answer){state.solved=true;button.classList.add("correct");rewardProblem();playEffect("success");showSuccess();setGuide(t("correct"),false);setTimeout(updateScreen,250)}else{state.wrong+=1;playEffect("wrong");button.classList.add("wrong");setGuide(t("wrong"),false);setTimeout(()=>button.classList.remove("wrong"),500)}}
function rewardProblem(){const id=`paper-fold:${problem().id}`;let rewards=[];try{rewards=JSON.parse(localStorage.getItem("gfield-rewarded-games")||"[]")}catch{}if(!rewards.includes(id)){rewards.push(id);localStorage.setItem("gfield-rewarded-games",JSON.stringify(rewards));if(!state.hints&&state.wrong===0){const pts=Number(localStorage.getItem("gfield-points")||120)+10;localStorage.setItem("gfield-points",String(pts))}}saveGameProgress("paperFold",{level:state.level+1,problemIndex:state.problem,completedProblem:problem().id})}
function showSuccess(){ui.success.querySelector("strong").textContent=["GOOD JOB!","GREAT JOB!","SUCCESS!"][Math.floor(Math.random()*3)];ui.success.classList.remove("show");void ui.success.offsetWidth;ui.success.classList.add("show")}
function resetProblem(){state.fold=0;state.solved=false;state.hints=0;state.wrong=0;updateScreen()}
function nextProblem(){if(!state.solved)return;if(state.problem<levels[state.level].problems.length-1){state.problem+=1;resetProblem()}else showComplete()}
function showComplete(){const n=state.level+1;$("#completeTitle").textContent=t("complete",{n});$("#completeText").textContent=t("completeText");$("#nextLevelButton").textContent=t("nextLevel");$("#practiceButton").textContent=t("practice");ui.complete.hidden=false}
function selectLevel(index){state.level=Math.max(0,Math.min(levels.length-1,index));state.problem=0;ui.levelDialog.hidden=true;ui.complete.hidden=true;resetProblem();saveGameProgress("paperFold",{level:state.level+1,problemIndex:0})}
function renderLevelList(){ui.levelList.replaceChildren();levels.forEach((level,index)=>{const b=document.createElement("button");b.type="button";b.className="level-card";b.style.setProperty("--a",["#8ad5be","#78bde7","#ad94dc","#f29a86","#f3cb58"][index]);b.innerHTML=`<span class="level-art">${["□","○","123","✂","▱"][index]}</span><span class="level-copy"><strong>LEVEL ${level.id} · ${level.title[state.lang]||level.title.ko}</strong><small>${level.description[state.lang]||level.description.ko}</small></span>`;b.addEventListener("click",()=>selectLevel(index));ui.levelList.append(b)})}
function showToast(message){ui.toast.textContent=message;ui.toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>ui.toast.classList.remove("show"),1800)}
function openTutorial(){const key="gfield-paper-fold-tutorial-v1";if(state.level!==0||state.problem!==0||localStorage.getItem(key)==="done")return;state.tutorial=0;renderTutorial();ui.tutorial.hidden=false}
function renderTutorial(){const list=I18N[state.lang]?.tutorial||I18N.ko.tutorial;ui.tutorialText.textContent=list[state.tutorial];ui.tutorialNext.textContent=state.tutorial===list.length-1?t("start"):t("continue");ui.tutorialDots.innerHTML=list.map((_,i)=>`<i class="${i===state.tutorial?"active":""}"></i>`).join("");speak(list[state.tutorial])}
function advanceTutorial(){const list=I18N[state.lang]?.tutorial||I18N.ko.tutorial;if(state.tutorial<list.length-1){state.tutorial+=1;renderTutorial()}else{localStorage.setItem("gfield-paper-fold-tutorial-v1","done");ui.tutorial.hidden=true;state.tutorial=-1;setGuide(t("foldFirst"),true)}}

ui.paper.addEventListener("click",foldPaper);$("#retryButton").addEventListener("click",resetProblem);$("#hintButton").addEventListener("click",()=>{state.hints+=1;showToast(t("hintFold"));setGuide(t("hintFold"),false)});ui.next.addEventListener("click",nextProblem);$("#soundButton").addEventListener("click",()=>{state.audio=!state.audio;localStorage.setItem("gfield-audio-muted",String(!state.audio));updateSound()});$("#levelButton").addEventListener("click",()=>ui.levelDialog.hidden=false);$("#closeLevels").addEventListener("click",()=>ui.levelDialog.hidden=true);ui.levelDialog.addEventListener("click",e=>{if(e.target===ui.levelDialog)ui.levelDialog.hidden=true});ui.tutorialNext.addEventListener("click",advanceTutorial);$("#nextLevelButton").addEventListener("click",()=>state.level<4?selectLevel(state.level+1):location.assign("../../origami-studio/"));$("#practiceButton").addEventListener("click",()=>selectLevel(state.level));
document.documentElement.lang=state.lang;applyLanguage();renderLevelList();resetProblem();setTimeout(openTutorial,250);
