const copy = {
  ko: {
    title: "둘레 탐구", worksheet: "학습지", language: "언어", area: "학습 영역", back: "도형 정원", progress: "진행", answer: "둘레", compare: "A와 B의 둘레", less: "A의 둘레가 더 짧아요", equal: "둘레가 같아요", greater: "A의 둘레가 더 길어요", check: "확인", next: "다음 문제", done: "마치기", undo: "되돌리기", retry: "다시 풀기", hint: "생각의 실마리", review: "확인해 보기", complete: "둘레 탐구를 마쳤어요", completeText: "바깥 경계를 따라 길이를 비교했어요.", practice: "새 문제", correct: "조건에 맞아요.", retryAnswer: "바깥 경계를 빠짐없이 한 번씩 살펴보세요.", invalid: "답을 입력하거나 도형을 만들어 보세요.", disconnected: "색칠한 칸이 변끼리 한 덩어리로 이어져야 해요.", hole: "안쪽에 구멍이 없는 도형을 만들어 보세요.", "same-shape": "위치나 방향만 바꾼 모양이에요. 다른 모양을 만들어 보세요.", shared: "맞닿은 안쪽 변은 바깥 둘레에 넣지 않아요.", storage: "이번 진행을 이 기기에 저장하지 못했어요.", align: "경계 길이 나란히 보기", marked: n => `표시한 단위 선분 ${n}개`, built: n => `만든 도형의 둘레: ${n}`, unit: "한 칸의 변 길이", reference: "기준 A", drawing: "내 도형 B", segment: n => `선분 ${n}`, cell: (x,y) => `${y+1}행 ${x+1}열`, rules: { boundary: "둘레는 도형의 바깥 경계를 한 바퀴 돈 길이예요.", joined: "두 도형이 맞닿은 변은 합친 도형의 바깥 경계가 아니에요.", compare: "모양이나 칸 수가 달라도 둘레가 같을 수 있어요.", build: "돌리거나 뒤집어 겹치는 도형은 같은 모양으로 보아요." }
  },
  en: {
    title: "Perimeter Studio", worksheet: "Worksheet", language: "Language", area: "Activities", back: "Shape Garden", progress: "Progress", answer: "Perimeter", compare: "Perimeters of A and B", less: "A has a shorter perimeter", equal: "The perimeters are equal", greater: "A has a longer perimeter", check: "Check", next: "Next", done: "Finish", undo: "Undo", retry: "Start over", hint: "A clue", review: "Look again", complete: "Perimeter activity complete", completeText: "You compared lengths around the outside edges.", practice: "New problems", correct: "That meets the conditions.", retryAnswer: "Count every outside edge once, without skipping any.", invalid: "Enter an answer or make a shape.", disconnected: "The shaded squares must form one side-connected shape.", hole: "Make a shape with no holes inside.", "same-shape": "Moving or turning the same shape does not make a different shape.", shared: "An inside edge where the shapes meet is not part of the outside perimeter.", storage: "Your progress could not be saved on this device.", align: "Line up boundary lengths", marked: n => `${n} unit segments marked`, built: n => `Your shape's perimeter: ${n}`, unit: "One grid side", reference: "Reference A", drawing: "Your shape B", segment: n => `Segment ${n}`, cell: (x,y) => `Row ${y+1}, column ${x+1}`, rules: { boundary: "Perimeter is the length of one complete trip around a shape's outside boundary.", joined: "Edges where the two shapes meet are not on the combined shape's outside boundary.", compare: "Different shapes can have the same perimeter, even with different numbers of squares.", build: "Shapes that match after turning or flipping count as the same shape." }
  },
  zh: {
    title: "周长探究", worksheet: "练习纸", language: "语言", area: "学习领域", back: "图形花园", progress: "进度", answer: "周长", compare: "A与B的周长", less: "A的周长更短", equal: "周长相等", greater: "A的周长更长", check: "确认", next: "下一题", done: "完成", undo: "撤销", retry: "重新作答", hint: "思考提示", review: "再看一看", complete: "完成周长探究", completeText: "你沿着外边界比较了长度。", practice: "新题目", correct: "符合条件。", retryAnswer: "沿外边界数一圈，每条边只数一次。", invalid: "请输入答案或画出图形。", disconnected: "涂色方格必须通过边连成一个整体。", hole: "请画一个内部没有孔洞的图形。", "same-shape": "只改变位置或方向不算新的形状，请画出不同的形状。", shared: "两个图形接触的内部边不计入外周长。", storage: "无法在此设备保存进度。", align: "对齐边界长度", marked: n => `已标记${n}条单位线段`, built: n => `所画图形的周长：${n}`, unit: "一格的边长", reference: "图形A", drawing: "我的图形B", segment: n => `线段${n}`, cell: (x,y) => `第${y+1}行第${x+1}列`, rules: { boundary: "周长是沿图形外边界走一圈的长度。", joined: "两个图形接触的边不是合并后图形的外边界。", compare: "形状和格数不同，周长也可能相等。", build: "旋转或翻转后能完全重合的图形视为同一形状。" }
  },
  ja: {
    title: "周りの長さの探究", worksheet: "プリント", language: "言語", area: "学習分野", back: "図形の庭", progress: "進み具合", answer: "周りの長さ", compare: "AとBの周りの長さ", less: "Aのほうが短い", equal: "同じ長さ", greater: "Aのほうが長い", check: "確かめる", next: "次の問題", done: "終わる", undo: "元に戻す", retry: "やり直す", hint: "考える手がかり", review: "確かめよう", complete: "探究が終わりました", completeText: "外側のふちに沿って長さを比べました。", practice: "新しい問題", correct: "条件に合っています。", retryAnswer: "外側の辺を一つずつ、もれなく数えましょう。", invalid: "答えを入れるか、図形を作りましょう。", disconnected: "色をつけたますは辺で一つにつなげましょう。", hole: "中に穴のない図形を作りましょう。", "same-shape": "位置や向きを変えただけでは同じ形です。違う形を作りましょう。", shared: "二つの図形が接する内側の辺は、周りの長さに入れません。", storage: "この機器に進み具合を保存できませんでした。", align: "ふちの長さを並べる", marked: n => `印をつけた単位線分 ${n}本`, built: n => `作った図形の周りの長さ：${n}`, unit: "ひとますの辺の長さ", reference: "見本A", drawing: "自分の図形B", segment: n => `線分${n}`, cell: (x,y) => `${y+1}行${x+1}列`, rules: { boundary: "周りの長さは、図形の外側のふちを一周する長さです。", joined: "二つの図形が接する辺は、合わせた図形の外側にはありません。", compare: "形やますの数が違っても、周りの長さが同じことがあります。", build: "回したり裏返したりして重なる図形は、同じ形と考えます。" }
  }
};
export const translation = lang => copy[lang] || copy.ko;
