import {curriculumDetail,observationScreen,adviceMarkup,planAdviceMarkup} from './review-ui.mjs';
import {TRACKS,ELEMENTARY_BOOKS,TYPE_HELP,TYPE_NAMES,trackCourses,scopeLabel,personalityGroup,scorePersonality,positionRows,bookRecommendation,curriculumFor} from './flow.mjs';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={unknown:'미입력·확인 필요',not_started:'아직 시작하지 않음',learning:'공부한 경험 있음',paused:'쉬는 중',done:'마무리한 교재 있음',in_progress:'진행 중',reported_done:'완료했다고 보고',reviewed_done:'범위 확인 완료',elementary:'초등 범위',middle:'중등 범위',high:'고등 범위',other:'그 외',active:'계속하기',reduced:'줄여서 진행',ended:'종료'};
const label=v=>labels[v]||v;
function select(text,name,value,items){return `<label class="field"><span>${text}</span><select name="${name}">${items.map(x=>{const [v,t]=Array.isArray(x)?x:[x,label(x)];return `<option value="${esc(v)}" ${String(value??'')===String(v)?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;}
function input(text,name,value='',type='text',extra=''){return `<label class="field"><span>${text}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function choices(name,current,items,{multi=false}={}){return `<fieldset class="choices"><legend class="sr-only">선택해 주세요</legend>${items.map(([v,t])=>`<label class="option"><input name="${name}" type="${multi?'checkbox':'radio'}" value="${esc(v)}" ${(multi?(current||[]).includes(v):current===v)?'checked':''}><span>${esc(t)}</span></label>`).join('')}</fieldset>`;}
function savedBooks(s,key){return trackCourses(s,key).map(c=>`<div class="book-row"><div><strong>${esc(c.course)}</strong><span>${esc(scopeLabel(c))} · ${label(c.completion)}</span></div><button type="button" data-edit-book="${esc(c.id)}">수정</button></div>`).join('');}
function bookCard(s,key){const t=TRACKS[key];return {title:`${t.label}는 어떤 교재로 공부했나요?`,say:key==='application'?'최근 공부한 교재만 알려 주셔도 좋아요. 기본·응용과 심화는 따로 볼게요.':key==='depth'?'응용보다 이전 범위의 심화를 공부해도 괜찮아요. 실제 교재를 알려 주세요.':`최근 교재 하나 또는 공부한 교재들을 기록해 주세요.`,html:`${savedBooks(s,key)}${input('교재 이름','bookName',s.wizard.bookDrafts?.[key]||'','text',key==='application'?'list="book-options" autocomplete="off"':'autocomplete="off"')}<datalist id="book-options">${ELEMENTARY_BOOKS.map(x=>`<option value="${esc(x)}"></option>`).join('')}</datalist>${key==='application'?'<p class="note">초등 기본·응용 표준은 디딤돌 기본+응용이에요. 실제 공부한 교재를 입력해 주세요.</p>':''}<button type="button" class="secondary" data-add-book="${key}">이 교재 입력하기</button><details><summary>미시작·모름을 기록하려면</summary>${select('현재 상태','axisStatus',s.wizard.axisStatus[key]||'unknown',['unknown','learning','not_started','paused','done'])}</details>`};}
export function positionMarkup(s){return `<div class="position-board" aria-label="각 학습 축의 입력 위치"><span class="watermark" aria-hidden="true">GFIELD</span>${positionRows(s).map(r=>`<section class="position-row"><h3>${r.label}</h3><div>${r.courses.length?r.courses.map(c=>`<div class="position-entry"><span class="scope-tag">${label(c.level)}</span><strong>${esc(c.scope)}</strong><small>${esc(c.name)} · ${label(c.completion)}</small></div>`).join(''):`<p class="muted">${label(r.status)}</p>`}</div></section>`).join('')}</div><p class="note">입력한 학습 이력의 위치예요. 혼자 해결하는 정도와 실제 이해는 따로 확인해요.</p>`;}
export function screen(s,catalog,personality,books={books:[]}){const w=s.wizard,step=w.step;if(step==='course-review')return observationScreen(s);
 if(step.startsWith('books:'))return bookCard(s,step.split(':')[1]);
 if(step.startsWith('detail:')){const c=s.courses.find(x=>x.id===w.pendingCourseId);return {title:`${c?.course||'이 교재'}는 어디까지 공부했나요?`,say:'권·범위와 진행 상태를 아는 만큼 알려 주세요. 높은 과정도 입력할 수 있어요.',html:c?`${input('권·학기','volume',c.volume,'text','placeholder="예: 2-1, 1권, 중등 1-1"')}${input('마지막 단원·진행량','range',c.range,'text','placeholder="예: 3단원까지, 48쪽, 절반"')}${select('진행·완료 상태','completion',c.completion,['unknown','not_started','in_progress','reported_done','reviewed_done'])}<div data-curriculum-detail>${curriculumDetail(c,books)}</div><details><summary>단원·판본·혼자 푸는 정도도 입력하기</summary>${input('단원 이름','unit',c.unit)}${select('실제 학습 범위','level',c.level,['unknown','elementary','middle','high','other'])}${input('판본·발행 연도','edition',c.edition)}${select('계획할 교육과정','curriculumTarget',c.curriculumTarget,[['','확인 필요'],['2022','2022 개정'],['2015','2015 개정'],['other','그 외']])}${select('학습한 범위','coverageIntent',c.coverageIntent,['unknown',['whole','전체'],['selected_ranges','선택한 일부 범위']])}${input('혼자 해결하는 정도·도움','independence',c.independence,'text','placeholder="예: 읽기 도움, 힌트 후 시도, 혼자 설명"')}${select('현재 과정 상태','status',c.status,['active','reduced','paused','ended'])}${input('기준 계획에 담고 싶은 다음 범위','plannedRange',c.plannedRange)}${c.axis==='other'?input('과목·영역','subject',c.subject):''}</details>`:'<p>연결할 교재를 다시 선택해 주세요.</p>'};}
 switch(step){
 case 'intro':return {title:'우리 아이의 공부, 어디서부터 이어갈까요?',say:'안녕하세요, DOCSSAM입니다. 이 가이드는 우리 아이의 학습을 고민하는 학부모님을 위해 만들었습니다.',html:'<p class="intro-copy">많은 학생이 진행한 표준 커리큘럼과 비교하며 우리 아이의 현재 위치와 목표를 살펴볼 수 있어요.</p><p>정확한 개인별 진단에 앞서, 우리 아이의 기준 로드맵을 함께 정해 볼게요.</p>',next:'시작하기'};
 case 'age':return {title:'우리 아이는 몇 살인가요?',say:'우선 나이부터 알려 주세요.',html:select('아이의 나이','reportedAge',s.profile.reportedAge,[['','모름·나중에 입력'],...Array.from({length:15},(_,i)=>[i+4,`${i+4}세`])])};
 case 'birth':return {title:'몇 월에 태어났나요?',say:'같은 나이에서도 태어난 달을 함께 기록해 둘게요.',html:select('생월','reportedBirthMonth',s.profile.reportedBirthMonth,[['','모름·나중에 입력'],...Array.from({length:12},(_,i)=>[i+1,`${i+1}월`])])};
 case 'grade':return {title:'지금 실제 학년은 어떻게 되나요?',say:'학년과 공부한 진도는 따로 볼게요.',html:select('현재 학년','grade',s.profile.grade,[['','모름·나중에 입력'],['미취학','미취학'],...Array.from({length:6},(_,i)=>[`초${i+1}`,`초등 ${i+1}학년`]),...Array.from({length:3},(_,i)=>[`중${i+1}`,`중등 ${i+1}학년`]),...Array.from({length:3},(_,i)=>[`고${i+1}`,`고등 ${i+1}학년`])])};
 case 'thinking':return {title:'사고력 수학은 어떻게 경험했나요?',say:s.profile.grade==='미취학'?'유아 때 공부한 교재나 사고력 학원 경험부터 볼게요.':'교재나 학원 경험 중 아는 내용을 알려 주세요.',html:choices('thinkingExperience',w.thinkingExperience,[['books','사고력 교재로 공부했어요'],['academy','사고력 학원에 다녔어요'],['both','교재와 학원 경험이 모두 있어요'],['not_started','아직 시작하지 않았어요'],['unknown','지금은 잘 모르겠어요']])};
 case 'academy':return {title:'어느 사고력 학원에 다녔나요?',say:'소마·필즈·CMS와 그 외 학원의 경험을 각각 남길 수 있어요.',html:w.academies.map(a=>`<div class="book-row"><strong>${esc(a.institution)} · ${esc(a.level||'레벨 미입력')}</strong><button type="button" data-edit-academy="${esc(a.id)}">수정</button></div>`).join('')+select('학원','institution',w.academyDraft?.institution||'',[['','선택해 주세요'],'소마','필즈','CMS',['other','그 외']])+input('반·레벨 (알고 있다면)','academyLevel',w.academyDraft?.academyLevel||'')+`<details><summary>그 외 학원·현재/과거 이력</summary>${input('그 외 학원 이름','institutionOther',w.academyDraft?.institutionOther||'')}${select('다녔던 시점','academyStatus',w.academyDraft?.academyStatus||'unknown',[['unknown','시점 모름'],['current','지금 다니고 있어요'],['past','전에 다녔어요']])}</details><button type="button" data-add-academy>이 경험 입력하기</button>`};
 case 'depth-status':return {title:'심화 교재도 공부했나요?',say:'심화는 기본·응용과 다른 범위여도 괜찮아요. 아직 시작하지 않아도 그대로 남길게요.',html:choices('depthStatus',w.axisStatus.depth||'unknown',[['learning','지금 심화를 공부하고 있어요'],['done','마무리한 심화 교재가 있어요'],['paused','심화를 하다가 쉬고 있어요'],['not_started','아직 시작하지 않았어요'],['unknown','모름·나중에 입력']])};
 case 'position':return {title:'지금 공부한 위치를 먼저 볼게요.',say:'기본·응용과 심화, 사고력과 연산은 이렇게 따로 기록돼 있어요.',html:positionMarkup(s)};
 case 'personality':return {title:'우리 아이의 성향도 함께 살펴볼까요?',say:'기존 성향검사를 하면 공부를 이어가는 방법을 더 자세히 비교할 수 있어요.',html:personalityGroup(s.profile.reportedAge)?'<p>선택 검사예요. 하지 않아도 기준 로드맵을 볼 수 있습니다.</p><button type="button" class="primary" data-personality-start>성격검사 하기</button><button type="button" data-personality-skip>건너뛰고 계속하기</button>':'<p>현재 확인된 검사는 7~15세용이에요. 우리 아이의 학습 기록으로 로드맵을 이어갈게요.</p>',hideNext:!!personalityGroup(s.profile.reportedAge)};
 case 'personality-test':{const p=s.personality,q=personality.questions[p.group]?.[p.cursor];return {title:q?.question||'검사 문항을 확인해 주세요.',say:`기존 성향검사 ${p.cursor+1} / 10`,html:q?choices('personalityAnswer',p.answers[p.cursor]===undefined?'':String(p.answers[p.cursor]),q.options.map((o,i)=>[String(i),o.text]))+'<button type="button" class="quiet" data-personality-skip>검사는 여기서 그만하고 계속하기</button>':'',next:p.cursor===9?'성향 결과 보기':'다음',personality:true};}
 case 'personality-result':{const r=scorePersonality(s.personality,personality);return {title:r?`이번 답변에서는 ${r.label}의 성향이 보여요.`:'성향 결과를 아직 정하지 않았어요.',say:r?r.help:'검사 없이도 학습 기록으로 이어갈 수 있어요.',html:'<p>성향은 공부를 도와주는 방법의 참고예요. 진도·심화 진입과 학원 선택은 실제 학습 상태와 함께 살펴봐요.</p>'};}
 case 'goals':return {title:'지금은 어떤 방향을 원하시나요?',say:'학원 목표 없이도 현재 공부에서 이어가는 길을 볼 수 있어요.',html:choices('progression',w.progression,[['continue','기본·응용을 차근차근 이어가기'],['later','응용을 진행하고 이전 범위 심화는 나중에 더하기'],['parallel','응용과 이전 범위 심화를 함께 하기'],['remediation','필요한 범위를 보완한 뒤 다시 합류하기'],['undecided','아직 정하지 않고 비교하기']])+`<details><summary>초등 교재를 고를 때 고려할 점</summary>${select('가족이 바라는 방향·보고한 상황','bookNeed',w.bookNeed,[['standard','기본·응용 표준'],['progress_late','선행이 늦다고 생각해요'],['reading','지문 이해를 더 살펴보고 싶어요'],['fast','빠른 선행을 원해요'],['consolidation','다지기를 원해요']])}</details>`};
 case 'time':return {title:'집에서 함께 관리할 시간은 어느 정도인가요?',say:'아이의 공부 시간과 부모님이 함께할 시간은 따로 볼게요.',html:`${input('평일 하루 관리 가능 시간 (분)','weekdayMinutes',s.support.weekdayMinutes??'','number','min="0" max="1440"')}${input('주말 하루 관리 가능 시간 (분)','weekendMinutes',s.support.weekendMinutes??'','number','min="0" max="1440"')}<p class="note">아직 정하지 않았다면 비워 두셔도 좋아요.</p>`};
 case 'academy-time':return {title:'수학 학원은 주 몇 회, 몇 시간을 생각하시나요?',say:'희망하는 일정이에요. 현재 다니는 일정과 자동으로 합치지 않을게요.',html:input('희망하는 주당 횟수','desiredFrequency',s.academy.desiredFrequency??'','number','min="0" max="14" step="0.5"')+input('한 번에 공부할 시간 (분)','desiredSessionMinutes',s.academy.desiredSessionMinutes??'','number','min="0" max="1440"')};
 case 'interests':return {title:'함께 살펴볼 목표나 과목이 있나요?',say:'관심 있는 것만 골라 주세요. 선택하지 않아도 수학 로드맵은 이어져요.',html:choices('interests',w.interests,[['premier','프리미어·필즈 선발'],['hwangso','황소 초등 선발'],['science','과학'],['gifted','영재원·영재학급'],['competition','경시'],['highSchool','고등학교·진로'],['other','타 과목']],{multi:true})};
 case 'premier':return {title:'프리미어·필즈는 어떤 방향으로 생각하시나요?',say:'희망과 실제 선발·등록은 따로 기록해요.',html:select('현재 의사','premier',s.goals.premier,[['undecided','미정'],['consider','선발을 고려해요'],['current','현재 다니고 있어요'],['later','나중에 고려해요'],['none','선택하지 않아요']])};
 case 'hwangso':return {title:'황소 초등은 언제 고려하고 있나요?',say:'초2·초3·나중·미선택을 같은 선택으로 볼게요.',html:choices('hwangso',s.goals.hwangso,[['grade2','초2에 고려'],['grade3','초3에 고려'],['later','나중에 고려'],['none','선택하지 않음'],['undecided','아직 미정']])};
 case 'hwangso-reason':return {title:'이 방향을 생각하는 이유가 있나요?',say:'진도가 충분해도 천천히 심화를 배울 수 있어요. 우리 가족의 이유를 남길게요.',html:choices('hwangsoReasons',s.goals.hwangsoReasons,[['progress_pending','진도를 더 확인하거나 보완하려고요'],['young_depth','진도와 별개로 아직 어려 심화를 배우려 해요'],['thorough_alternative','황소 없이 꼼꼼히 공부하려고요'],['time_fit','시간 여건 때문이에요'],['child_preference','아이의 의견을 반영했어요'],['unsure','아직 이유를 정하지 않았어요']],{multi:true})};
 case 'science-detail':return {title:'과학은 어떤 공부를 하고 있나요?',say:'수학 진도와 독립적으로, 실제 과학 학습과 목표를 남겨요.',html:input('공부하는 교재·실험·탐구 (알고 있다면)','scienceCourse',w.scienceCourse||'')+input('현재 범위·단원','scienceRange',w.scienceRange||'')+input('과학에서 바라는 목표','sciencePurpose',s.goals.sciencePurpose||'')};
 case 'gifted':return {title:'어느 분야의 영재원을 생각하시나요?',say:'해당 기관과 지원 학년도의 공식 조건은 별도로 확인해요.',html:input('관심 기관·지역','giftedInstitution',s.goals.giftedInstitution||'')+input('분야 (수학·과학 등)','giftedField',s.goals.giftedField||'')};
 case 'competition':return {title:'경시는 자료 학습인가요, 응시 목표인가요?',say:'자료로 공부하는 것과 실제 대회에 참가하는 것은 따로 볼게요.',html:select('경시 방향','competitionIntent',s.goals.competitionIntent,[['undecided','미정'],['enter','대회 응시를 고려해요'],['do_not_enter','자료를 공부하고 응시는 선택하지 않아요']])+input('관심 대회·학습 자료','competitionName',w.competitionName||'')};
 case 'school':return {title:'관심 있는 진학 방향이 있나요?',say:'희망하는 방향을 남기고, 현재 학습 상태와 학교별 공식 조건은 구분할게요.',html:choices('schoolTypes',s.goals.schoolTypes,[['gifted_school','영재고'],['science_school','과학고'],['autonomous','자사고'],['general','일반고'],['undecided','미정']],{multi:true})+choices('medical',s.goals.medical?'yes':'no',[['no','진로는 아직 열어둘게요'],['yes','의학계열도 희망해요']])+input('검토할 학교·지원 학년도','institution',s.goals.institution||'')};
 case 'routes':{const rec=bookRecommendation(s,catalog),rows=positionRows(s);return {title:'우리 아이의 기준 경로를 골라 볼까요?',say:'기록한 현재 위치와 가족의 바람을 나누어 비교해 볼게요.',html:`<h2>기록한 현재 학습</h2>${rows.map(r=>`<p><strong>${r.label}</strong> · ${r.courses.length?r.courses.map(c=>esc(c.scope)).join(' / '):label(r.status)}</p>`).join('')}${curriculumFor(s.profile.grade,Number(s.profile.academicYear)||2026)?`<p class="note">학교 학년 기준 · ${esc(s.profile.academicYear||2026)}년 ${esc(curriculumFor(s.profile.grade,Number(s.profile.academicYear)||2026).name)}. 교재 판본과 단원 대응은 별도로 확인해요.</p>`:''}${adviceMarkup(s,books,personality)}<h2>가족이 바라는 진행 방식</h2>${choices('progression',w.progression,[['continue','기본·응용 계속'],['later','응용 먼저, 이전 범위 심화 나중 합류'],['parallel','서로 다른 범위 응용·심화 병행'],['same_scope','같은 범위 응용 뒤 심화 이어가기'],['remediation','필요한 범위 보완 후 합류'],['undecided','판단 보류·다시 확인']])}<h2>기준으로 이어갈 현재 과정</h2>${choices('selectedCourseIds',w.selectedCourseIds??s.courses.filter(c=>c.status!=='ended').map(c=>c.id),s.courses.map(c=>[c.id,`${c.course} · ${scopeLabel(c)}`]),{multi:true})}<p class="note">현재 학습은 부모님이 보고한 기록이에요. 입력하지 않은 심화나 약점을 추정하지 않아요.</p>${s.courses.some(c=>c.level==='elementary')||/^초/.test(s.profile.grade)?`<div class="recommendation"><strong>초등 교재 비교 제안 · ${esc(rec.book)}</strong><p>${esc(rec.reason)}에 대한 사용자 지정 교재 기준입니다. 실제 학습 기록과 별도예요.</p></div>`:''}${input('기준 계획 이름','planTitle',w.planTitle||'우리 아이 기준 로드맵')}${input('이 경로를 선택한 이유','planReason',w.planReason||'')}${input('심화 추가·합류를 다시 확인할 조건','reviewCondition',w.reviewCondition||'')}<details><summary>전체 갈림길과 근거를 직접 비교하기</summary><a href="workspace.html?tab=routes" data-workspace>전체 ${catalog.branches.length}개 갈림길 보기</a></details>`,next:'이 경로를 기준으로 저장'};}
 case 'plan':{const p=s.plans.find(x=>x.id===s.activePlanId),r=scorePersonality(s.personality,personality);return {title:p?.title||'아직 기준 경로를 선택하지 않았어요.',say:'현재 학습과 나중에 정한 기준은 따로 남겼어요. 목표가 바뀌면 다시 비교할 수 있어요.',html:p?`<p class="folio">${p.version}번째 기준 · ${esc(p.acceptedAt.slice(0,10))}</p><p><strong>가족이 선택한 진행 방향</strong> · ${esc(({continue:"기본·응용 계속",later:"응용 먼저, 이전 범위 심화 나중 합류",parallel:"서로 다른 범위 응용·심화 병행",same_scope:"같은 범위 시차 학습",remediation:"보완 후 합류",undecided:"판단 보류"})[p.progression?.kind]||"세부 경로 별도 선택")}</p>${p.goalsSnapshot.hwangso?`<p>황소 희망 · ${esc(({grade2:"초2 고려",grade3:"초3 고려",later:"나중에 고려",none:"선택하지 않음",undecided:"미정",unknown:"미입력"})[p.goalsSnapshot.hwangso]||p.goalsSnapshot.hwangso)}</p>`:""}<p class="note">현재 과정과 나중에 바라는 진행 방향을 함께 표시했어요. 합류·중단은 실제 학습을 확인한 뒤 다시 선택합니다.</p><div class="roadmap-line">${p.courseSnapshots.map(c=>`<section><h3>${TRACKS[trackOfSafe(c)]?.label||c.axis}</h3><strong>${esc(c.course)}</strong><p>${esc(scopeLabel(c))}</p><span>${label(p.trackStatuses[c.id])}</span></section>`).join('')}</div>${planAdviceMarkup(p)}<h2>다음 갈림길</h2>${p.reviewPoints.map(x=>`<p>${esc(x.condition)} → ${esc(x.nextAction)}</p>`).join('')}${r?`<p>성향 참고 · ${esc(r.label)}<br>${esc(r.help)}</p>`:''}<p class="note">진단 문항·채점이 연결되면 실제 이해도도 함께 확인해요. 지금은 학습 기록과 확인할 조건을 보존합니다.</p><div class="actions"><button type="button" data-change-route>목표·경로 다시 비교</button><a class="button" href="workspace.html?tab=plan" data-workspace>학습·진단·휴식 기록</a><button type="button" data-export>사본 보관</button></div>`:'<button type="button" data-change-route>경로 비교하기</button>',hideNext:true};}
 default:return {title:'기록한 내용으로 이어갈게요.',say:'필요한 정보만 하나씩 볼게요.',html:''};
 }
}
function trackOfSafe(c){return c.intakeTrack||(c.axis==='curriculum'?/심화/.test(c.depth||'')?'depth':'application':c.axis);}
