import {screen as previousScreen,esc,positionMarkup} from './intake.mjs';
import {TRACKS,trackCourses,scopeLabel,positionRows,personalityGroup,bookRecommendation,trackOf,scorePersonality} from './flow.mjs';
import {observationScreen,adviceMarkup,planAdviceMarkup,curriculumDetail} from './review-ui.mjs';
import {RELATIONS,INTENTS,TRIGGERS,defaultKind,relationCandidates,relationReview,relatedBranches,selectedIds,courseIntent} from './paths-v10.mjs';
import {getAnswer} from './engine.mjs';
import {courseScope} from './advisor.mjs';
const sel=(text,name,value,items)=>`<label class="field"><span>${esc(text)}</span><select name="${esc(name)}">${items.map(([v,t])=>`<option value="${esc(v)}" ${String(value??'')===String(v)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const input=(text,name,value='',type='text',extra='')=>`<label class="field"><span>${esc(text)}</span><input name="${esc(name)}" value="${esc(value)}" type="${type}" ${extra}></label>`;
const choose=(name,current,items,multi=false)=>`<fieldset class="choices"><legend class="sr-only">${esc(name==='direction'?'진행 방식':'선택 항목')}</legend>${items.map(([v,t])=>`<label class="option"><input name="${esc(name)}" value="${esc(v)}" type="${multi?'checkbox':'radio'}" ${(multi?current?.includes(v):current===v)?'checked':''}><span>${esc(t)}</span></label>`).join('')}</fieldset>`;
const completions=[['unknown','진행 상태 모름'],['not_started','아직 시작하지 않음'],['in_progress','진행 중'],['reported_done','완료했다고 보고'],['reviewed_done','범위 확인 완료']];
function courseFields(c,books){return `${input('권·학년학기 또는 마지막 범위','volume',c.volume||'','text','placeholder="예: 2-1, 중등 1-1, 3권"')}${sel('진행 상태','completion',c.completion||'unknown',completions)}<details><summary>진행량·도움·단원을 더 남기기</summary>${input('마지막 단원·진행량','range',c.range||'','text','placeholder="예: 48쪽, 절반, 마지막 범위 모름"')}${input('단원 이름','unit',c.unit||'')}${input('혼자 해결하는 정도·도움','independence',c.independence||'')}${sel('실제 과정 범위','level',c.level||'unknown',[['unknown','확인 필요'],['elementary','초등'],['middle','중등'],['high','고등'],['other','기타']])}${sel('실제 과정 상태','status',c.status||'active',[['active','현재 진행'],['reduced','줄여서 진행'],['paused','쉬는 중'],['ended','종료']])}</details><details><summary>판본·교육과정·목차 (선택)</summary>${input('판본·발행 연도','edition',c.edition||'')}<div data-curriculum-detail>${curriculumDetail(c,books)}</div>${sel('계획할 교육과정','curriculumTarget',c.curriculumTarget||'',[['','확인 필요'],['2022','2022 개정'],['2015','2015 개정'],['other','그 외']])}</details>`;}
function booksCard(s,key,books){
 const w=s.wizard,d=w.v10.bookDrafts?.[key]||{},existing=trackCourses(s,key);
 return {title:`${TRACKS[key].label}는 어떤 교재로 공부했나요?`,say:key==='depth'?'응용보다 이전 범위의 심화도 따로 기록할 수 있어요.':'마지막 교재 하나만 알려 주셔도 좋아요. 여러 교재도 추가할 수 있어요.',html:existing.map(c=>`<div class="book-row"><div><strong>${esc(c.course)}</strong><span>${esc(scopeLabel(c))} · ${esc(Object.fromEntries(completions)[c.completion])}</span></div><button type="button" data-edit-book="${esc(c.id)}">수정</button></div>`).join('')+`${input('교재·과정 이름','bookName',d.bookName||'','text','list="book-options" autocomplete="off"')}<datalist id="book-options">${(key==='application'?['디딤돌 기본+응용','최상위 S 수학','최상위 수학','쎈수학']:key==='thinking'&&s.profile.grade==='미취학'?['킨더팩토','키즈팩토','초등팩토','PRE1031','필즈 베이직']:[]).map(x=>`<option value="${esc(x)}"></option>`).join('')}</datalist>${courseFields({...d,course:d.bookName||''},books)}<button type="button" data-add-book="${esc(key)}">교재 추가</button><details><summary>교재가 없거나 지금은 모를 때</summary>${sel('이 축의 상태','axisStatus',w.axisStatus[key]||'unknown',[['unknown','잘 모르겠음'],['not_started','아직 시작하지 않음'],['learning','공부한 경험 있음'],['paused','쉬는 중'],['done','마무리한 교재 있음']])}</details>`,next:'이 기록으로 다음'};
}
export function screenV10(s,catalog,personality,books,design,contract){
 const w=s.wizard,v=w.v10,step=w.step;
 if(step==='intro')return {title:'우리 아이의 공부, 어디서부터 이어갈까요?',say:'안녕하세요. DOCSSAM입니다. 이 가이드는 우리 아이들의 학습을 고민하는 학부모님들을 위해 제작되었습니다.',html:'<p>정확한 개인별 로드맵은 아니지만 많은 학생들이 진행한 표준 커리큘럼과 비교하여 우리 아이들의 목표를 설정할 수 있습니다.</p><details><summary>이전에 보관한 입력을 가져오려면</summary><label class="field"><span>이전 입력 사본 (JSON)</span><input type="file" data-import-state accept="application/json,.json"></label><p class="note">선택한 사본으로 이어가며, 현재 저장 기록은 변경 이력에 보존합니다.</p></details>',next:'시작하기'};
 if(step.startsWith('books:'))return booksCard(s,step.split(':')[1],books);
 if(step.startsWith('detail:')){const c=s.courses.find(x=>x.id===w.pendingCourseId);return {title:'교재 기록을 수정할까요?',say:'아는 범위만 남겨 주세요. 상세 입력은 선택이에요.',html:c?input('교재 이름','editBookName',c.course)+courseFields(c,books):'<p>교재를 다시 선택해 주세요.</p>',next:'기록 수정 완료'};}
 if(step==='age')return {title:'우선 우리 아이의 나이가 몇 살일까요?',say:'나이와 공부한 진도는 따로 기록할게요.',html:sel('나이','reportedAge',s.profile.reportedAge,[['','모름·나중에 입력'],...Array.from({length:15},(_,i)=>[i+4,`${i+4}세`])])+([4,5,6].includes(s.profile.reportedAge)?sel('몇 월 생인가요?','reportedBirthMonth',s.profile.reportedBirthMonth,[['','모름·나중에 입력'],...Array.from({length:12},(_,i)=>[i+1,`${i+1}월`])]):'')};
 if(step==='interests')return {title:'함께 볼 목표나 과목이 있나요?',say:'목표를 고르지 않아도 지금 공부에서 이어가는 길을 볼 수 있어요.',html:'<p>지금 수학 흐름부터 보려면 그대로 다음으로 가세요.</p>'+[['선발·학원',[['premier','프리미어·필즈'],['hwangso','황소 초등']]],['과학·영재원·경시',[['science','과학'],['gifted','영재원·영재학급'],['competition','경시']]],['진학·타 과목',[['highSchool','고교·진로'],['other','타 과목']]]].map(([title,options])=>`<details ${options.some(([id])=>w.interests.includes(id))?'open':''}><summary>${title}${options.some(([id])=>w.interests.includes(id))?' · 선택됨':''}</summary>${choose('interests',w.interests,options,true)}</details>`).join('')};
 if(step==='time')return {title:'함께 관리할 시간은 어느 정도인가요?',say:'가정에서 관리할 시간과 수학 학원 희망 일정을 따로 남길게요.',html:input('평일 부모 관리 가능 시간 (분/일)','weekdayMinutes',s.support.weekdayMinutes??'','number','min="0" max="1440"')+input('주말 부모 관리 가능 시간 (분/일)','weekendMinutes',s.support.weekendMinutes??'','number','min="0" max="1440"')+`<details><summary>수학 학원 희망 일정</summary>${input('희망 주당 횟수','desiredFrequency',s.academy.desiredFrequency??'','number','min="0" max="14" step="0.5"')}${input('희망 회당 시간 (분)','desiredSessionMinutes',s.academy.desiredSessionMinutes??'','number','min="0" max="1440"')}</details><p class="note">아직 정하지 않았다면 비워 두셔도 좋아요.</p>`};
 if(step==='goals')return {title:'어떤 흐름을 먼저 비교해 볼까요?',say:'여러 과정은 서로 다른 방식으로 이어갈 수 있어요.',html:choose('direction',v.direction,[['continue','지금 흐름 이어가기'],['add_depth','심화도 더해 보기'],['depth_focus','심화를 중심으로 살펴보기'],['undecided','아직 모르겠어요']])+`<details><summary>초등 교재를 고를 때 고려할 점</summary>${sel('가족의 희망·보고한 상황','bookNeed',w.bookNeed||'standard',[['standard','기본·응용 표준'],['progress_late','선행이 늦다고 생각해요'],['reading','지문 이해를 더 살펴봐요'],['fast','빠른 선행을 원해요'],['consolidation','다지기를 원해요']])}</details>`};
 if(step==='hwangso-reason'){const old=previousScreen(s,catalog,personality,books);return {...old,html:old.html+`<details><summary>선택한 시점·설명도 함께 수정하기</summary>${sel('황소 희망 시점','hwangso',s.goals.hwangso,[['grade2','초2에 고려'],['grade3','초3에 고려'],['later','더 늦게 고려'],['none','선택하지 않음'],['undecided','미정']])}${input('가족이 생각한 이유','hwangsoReasonNote',s.goals.hwangsoReasonNote||'')}</details>`};}
 if(step==='gifted'){const old=previousScreen(s,catalog,personality,books);return {...old,html:old.html+input('지원 학년도 (알고 있다면)','admissionYear',s.goals.admissionYear||'')+input('지역','region',s.profile.region||'')+(/과학/.test(s.goals.giftedField||'')?`<details><summary>과학 학습도 남기기 (선택)</summary>${input('과학 교재·실험·탐구','scienceCourse',w.scienceCourse||'')}${input('현재 과학 범위','scienceRange',w.scienceRange||'')}${input('과학에서 바라는 목표','sciencePurpose',s.goals.sciencePurpose||'')}</details>`:'')};}
 if(step==='course-review'){const view=observationScreen(s);return {...view,say:v.pendingAcceptance?'선택한 경로에 필요한 이 범위만 살펴볼게요. 모르면 그대로 남겨도 좋아요.':view.say,next:v.pendingAcceptance?'이 관찰로 계속':'경로 비교로 돌아가기'};}
 if(step==='routes'){
  const ids=selectedIds(s),rec=bookRecommendation(s,catalog);
  return {title:'과정별로 어떻게 이어갈까요?',say:'지금 공부한 기록과 나중에 더할 과정을 나누어 비교해 볼게요.',html:(v.direction==='add_depth'?choose('variant',v.variant,[['parallel','지금 서로 다른 범위로 병행'],['later','응용을 이어가고 심화는 나중 추가'],['same_scope','같은 범위 응용 뒤 심화']]):`<p><strong>${esc(RELATIONS[defaultKind(s)])}</strong></p>`)+s.courses.map(c=>`<section class="intent-row"><label class="option"><input type="checkbox" name="selectedCourseIds" value="${esc(c.id)}" ${ids.includes(c.id)?'checked':''}><span>${esc(TRACKS[trackOf(c)]?.label||c.axis)} · ${esc(c.course)} · ${esc(scopeLabel(c))}</span></label>${sel('이 과정의 계획',`intent:${c.id}`,courseIntent(s,c),Object.entries(INTENTS))}</section>`).join('')+`<p class="note">계획에서 빼거나 쉬어도 실제 학습 기록은 남아 있어요.</p><details><summary>나중 추가할 교재·과정</summary>${v.plannedCourses.map(p=>`<div class="book-row"><span>${esc(TRACKS[p.track].label)} · ${esc(p.name)} · ${esc(p.scope||'범위 미정')} (예정)</span><button type="button" data-edit-planned="${esc(p.id)}">수정</button></div>`).join('')}${sel('예정 과정','plannedTrack',v.plannedDraft?.track|| (v.direction==='depth_focus'?'application':'depth'),Object.entries(TRACKS).map(([k,x])=>[k,x.label]))}${input('추가할 교재·과정 이름','plannedName',v.plannedDraft?.name||'')}${input('범위 (모르면 비워 두세요)','plannedScope',v.plannedDraft?.scope||'')}<button type="button" data-add-planned>예정 과정 추가</button></details><details><summary>보완·합류·휴식 관계를 더 연결하기</summary>${v.relations.map(r=>`<div class="book-row"><span>${esc(RELATIONS[r.kind])}</span><button type="button" data-edit-relation="${esc(r.id)}">수정</button></div>`).join('')}<button type="button" data-add-relation>관계 추가</button></details>${adviceMarkup(s,books,personality)}<details><summary>이번 경로의 다음 갈림길</summary>${relationCandidates(s).map(r=>`<p>${esc(RELATIONS[r.kind])} → ${esc(r.condition||'최근 수행·부담·시간과 가족의 의사를 다시 살펴보기')}</p>`).join('')}${sel('더 자세히 볼 갈림길','branchId',v.branchId||'',[['','선택해 주세요'],...relatedBranches(s,catalog,contract).map(b=>[b.id,b.title])])}<button type="button" data-branch-review>이 갈림길의 질문 보기</button></details>${/^초/.test(s.profile.grade)||s.courses.some(c=>c.level==='elementary')?`<details><summary>교재 비교 제안</summary><p>${esc(rec.book)} · ${esc(rec.reason)}</p></details>`:''}<details><summary>기준 이름·선택 이유·다음 확인 조건</summary>${input('기준 이름','planTitle',w.planTitle||'우리 아이 기준 로드맵')}${input('선택 이유','planReason',w.planReason||'')}${input('다시 살펴볼 조건','reviewCondition',v.reviewCondition||'')}</details>`,next:'이 경로를 기준으로 저장'};
 }
 if(step==='relation-editor'){
  const d=v.relationDraft||{};return {title:'어떤 과정이 어떻게 이어지나요?',say:'합류는 범위를 다시 살펴본 뒤 선택해요.',html:sel('관계','relationKind',d.kind||'R06',Object.entries(RELATIONS))+`<h2>기준이 되는 실제 과정</h2>${choose('relationSources',d.sourceCourseIds||[],s.courses.map(c=>[c.id,`${c.course} · ${scopeLabel(c)}`]),true)}<h2>나중 추가할 예정 과정</h2>${v.plannedCourses.length?choose('relationTargets',d.targetPlannedCourseIds||[],v.plannedCourses.map(p=>[p.id,`${p.name} · ${p.scope||'범위 미정'}`]),true):'<p>예정 과정이 아직 없어요. 대상은 미정으로 보관할 수 있어요.</p>'}${sel('다시 살펴볼 계기','relationTrigger',d.reviewTrigger||'family_review',Object.entries(TRIGGERS))}${input('확인할 범위·조건','relationCondition',d.condition||'')}`,next:'이 관계 보관'};
 }
 if(step==='branch-review'){
  const session=v.branchSession,b=catalog.branches.find(b=>b.id===session?.branchId),qid=session?.qids[session.cursor],q=catalog.questions.find(q=>q.id===qid);
  if(!b||!q)return {title:'갈림길의 기록을 확인했어요.',say:'필요할 때 다음 조건을 다시 살펴볼 수 있어요.',html:b?`<p>${esc(b.explanation)}</p><p>${esc(b.entry_and_remediation)}</p><p>다음: ${esc(b.next_branch_ids.map(id=>catalog.branches.find(x=>x.id===id)?.title||id).join(' / '))}</p>`:'',next:'경로 비교로 돌아가기'};
  const raw=getAnswer(s,qid,session.courseId||''),course=s.courses.find(c=>c.id===session.courseId);const ans=raw?.scopeSnapshot&&course&&JSON.stringify(raw.scopeSnapshot)!==JSON.stringify(courseScope(course))?null:raw;const opts=[...new Set([...q.answer_options,'모름·확인 필요'])];
  return {title:q.prompt,say:`${b.title}에서 확인할 내용이에요.`,html:sel('이 답변의 대상','branchCourseId',session.courseId||'',[['','가족·기관 공통 답변'],...s.courses.map(c=>[c.id,`${c.course} · ${scopeLabel(c)}`])])+choose('branchAnswers',ans?.values||[],opts.map(x=>[x,x]),true)+input('설명·출처 또는 최근 관찰','branchNote',ans?.note||'')+`<details><summary>이 질문의 근거·조건</summary><p>${esc(b.entry_and_remediation)}</p><p>${esc(q.followup)}</p><p>근거: ${esc(q.source_ids.join(', '))}</p></details>`,next:'이 답변으로 계속'};
 }
 if(step==='plan'){
  const p=s.plans.find(x=>x.id===s.activePlanId);if(!p?.courseRelations)return previousScreen(s,catalog,personality,books);
  const personalityResult=scorePersonality(p.personalitySnapshot||s.personality,personality);return {title:p.title,say:'실제 기록과 우리 가족이 선택한 기준을 따로 남겼어요.',html:`<p class="folio">${p.version}번째 기준 · ${esc(p.acceptedAt.slice(0,10))}</p><h2>지금 학습과 선택한 진행</h2><div class="roadmap-line">${p.courseSnapshots.map(c=>`<section><h3>${esc(TRACKS[trackOf(c)]?.label||c.axis)}</h3><strong>${esc(c.course)} · ${esc(scopeLabel(c))}</strong><p>가족이 선택한 진행 · ${esc(INTENTS[p.trackStatuses[c.id]==='paused'?'pause':p.trackStatuses[c.id]==='reduced'?'reduce':p.courseIntents[c.id]]||'판단 보류')}</p><small>실제 기록 · ${esc(Object.fromEntries(completions)[c.completion])}</small></section>`).join('')}</div>${p.plannedCourseSnapshots.length?`<h2>나중 추가할 과정 · 희망</h2>${p.plannedCourseSnapshots.map(c=>`<p>${esc(TRACKS[c.track].label)} · ${esc(c.name)} · ${esc(c.scope||'범위 미정')}</p>`).join('')}`:' '}<h2>병행·합류·휴식 관계</h2>${p.courseRelations.map(r=>{const review=relationReview(s,r);return `<article class="relation-summary"><h3>${esc(RELATIONS[r.kind])}</h3><p>${esc(r.condition||'최근 수행·도움·부담·시간과 가족의 의사를 다시 확인')}</p>${review.needsReview?'<p class="review-notice">기록·여건이 달라져 다시 살펴볼 관계예요.</p>':''}<details><summary>확인할 조건·연결 과정</summary><p>${esc(r.sourceCourseIds.map(id=>p.courseSnapshots.find(c=>c.id===id)?.course||s.courses.find(c=>c.id===id)?.course||'과정 확인').join(' / ')||'기준 과정 미정')}</p><p>${esc(r.unresolved.join(' / ')||'관찰 근거와 가족 선택을 다시 확인하며 진행')}</p></details></article>`;}).join('')}<p>황소 · ${esc(p.hwangsoInquiry==='not_asked'?'이번에는 별도 목표를 묻지 않음':({grade2:'초2 고려',grade3:'초3 고려',later:'더 늦게 고려',none:'선택하지 않음',undecided:'미정'})[p.goalsSnapshot.hwangso]||'확인 필요')}</p>${personalityResult?`<p>성향 참고 · ${esc(personalityResult.label)}<br>${esc(personalityResult.help)}</p>`:""}${planAdviceMarkup(p)}<p class="note">예정 과정은 실제로 시작한 기록과 구분돼요. 진단과 기관 조건은 필요한 단계에서 따로 확인합니다.</p><div class="actions"><button type="button" data-change-route>목표·경로 다시 비교</button><a class="button" href="workspace.html?tab=plan" data-workspace>학습·진단·휴식 기록</a><button type="button" data-export>사본 보관</button></div>`,hideNext:true};
 }
 return previousScreen(s,catalog,personality,books);
}
