import {bookFamily,resolveBook} from './curriculum.mjs';
import {HELP_OPTIONS,DEPTH_OPTIONS,courseScope,observationFor,routeAdvice} from './advisor.mjs';
import {esc} from './intake.mjs';
const sel=(label,name,value,items)=>`<label class="field"><span>${label}</span><select name="${name}">${items.map(([v,t])=>`<option value="${esc(v)}" ${String(value??'')===String(v)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const input=(label,name,value='',type='text',extra='')=>`<label class="field"><span>${label}</span><input name="${name}" value="${esc(value??'')}" type="${type}" ${extra}></label>`;
export function curriculumDetail(c,data){
 if(!bookFamily(c.course))return '';
 const r=resolveBook(c,data);
 const stateText={not_identified:'권·학기를 입력하면 확인된 목차를 찾아볼 수 있어요.',old_edition:'구판 이력은 그대로 남겨요. 현행판 단원을 구판 완료로 환산하지 않아요.',edition_unknown:'어느 개정판인지 알면 실제 목차를 연결할 수 있어요.',isbn_not_found:'입력한 ISBN은 확인된 자료에서 찾지 못했어요. 실제 교재의 ISBN을 다시 확인하거나 단원을 직접 적어 주세요.',edition_choice:'같은 권의 ISBN이 다른 판본이 있어요. 실제 교재의 ISBN을 확인해 주세요.',publisher_pending:'이 교재의 판본별 목차는 아직 확인 중이에요. 단원 이름을 직접 적어 주세요.',identity_conflict:'ISBN과 입력한 교재·권·판본이 달라요. 입력 내용을 확인해 주세요.',source_issue:'출판사 목차에 번호 중복이 있어 단원 자동 연결을 보류했어요. 실제 교재의 단원 이름을 적어 주세요.'};
 return `${sel('실제로 공부한 교재의 개정판','sourceCurriculum',c.sourceCurriculum||'',[['','모름·나중에 확인'],['2022','2022 개정판'],['2015','2015 개정판'],['other','그 외']])}${r.status==='edition_choice'?`${sel('실제 교재의 ISBN으로 판본 선택 (선택)','isbnChoice',c.isbn||'',[['','모름·직접 입력'],...r.candidates.map(b=>[b.isbn,`${b.title} · ISBN ${b.isbn}`])])}`:''}${['publisher_toc','retailer_toc'].includes(r.status)?`${sel('확인된 목차에서 단원 선택 (선택)','unitChoice',c.unit||'',[['','직접 입력·나중에 확인'],...r.selectableUnits.map(u=>[u.title,`${u.order}. ${u.title}`])])}<p class="note"><a href="${esc(r.book.sourceUrl)}" target="_blank" rel="noreferrer">${r.status==='retailer_toc'?'서점 목차 참고':'출판사 목차'}</a> · 2022 개정판 · ${r.book.checkedOn} 확인. 공부한 깊이와 완료는 별도로 기록해요.${r.status==='retailer_toc'?' 출판사 판본 대조는 확인 중이에요.':''}${r.book.units.some(u=>u.issues?.length)?' 원문 표기가 미확인인 단원은 선택 목록에서 보류했어요. 실제 단원 이름은 직접 적을 수 있어요.':''}</p>`:`<p class="note">${stateText[r.status]}</p>`}<details><summary>ISBN으로 판본 확인하기</summary>${input('실제로 공부한 교재 ISBN','isbn',c.isbn)}</details>`;
}
export function observationScreen(s){
 const w=s.wizard,c=s.courses.find(c=>c.id===w.reviewCourseId)||s.courses[0];
 if(!c)return {title:'먼저 학습한 교재를 알려 주세요.',say:'학습 상태는 실제 과정에 연결해 기록할게요.',html:'<p>현재 입력한 교재가 없어요. 교재를 입력한 뒤 다시 살펴볼 수 있어요.</p>',next:'경로 비교로 돌아가기'};
 const draft=w.observationDrafts?.[c.id];const same=draft&&JSON.stringify(draft.scope)===JSON.stringify(courseScope(c));const o=same?draft:observationFor(s,c);
 return {title:'이 범위는 어떻게 공부하고 있나요?',say:'최근 관찰한 모습만 알려 주세요. 모르면 비워 두셔도 좋아요.',html:`${sel('살펴볼 과정','reviewCourseId',c.id,s.courses.map(c=>[c.id,`${c.course} · ${[c.volume,c.unit,c.range].filter(Boolean).join(' · ')||'범위 미입력'}`]))}${sel('최근 문제를 혼자 해결하는 정도','help',o.help||'unknown',HELP_OPTIONS)}${sel('이 과정의 부담','burden',o.burden||'unknown',[['unknown','아직 확인하지 않았어요'],['manageable','지금은 감당할 만해요'],['high','부담이 큰 편이에요'],['varies','날마다 달라요']])}<details><summary>실제 학습 깊이·설명·시간도 함께 남기기</summary>${sel('이번 범위에서 실제로 공부한 깊이','depth',o.depth||'unknown',DEPTH_OPTIONS.map(v=>[v,v==='unknown'?'아직 확인하지 않았어요':v]))}${sel('풀이 설명을 살펴봤나요?','explanation',o.explanation||'unknown',[['unknown','확인하지 않았어요'],['example','설명한 예를 남길게요'],['needs_help','설명에 도움이 필요했어요'],['answer_only','답만 확인했어요']])}${input('최근 관찰한 예·날짜','example',o.example||'')}${input('아이의 이 과정 실제 학습 시간 (주당 분)','weeklyMinutes',o.weeklyMinutes,'number','min="0" max="10080"')}${input('부모님의 이 과정 관리 시간 (주당 분)','adultMinutes',o.adultMinutes,'number','min="0" max="10080"')}</details><p class="note">관찰은 선택한 권·단원·진행 범위에 연결돼요. 시험 결과와는 별도 기록입니다.</p>`,next:'이 관찰로 경로 비교하기'};
}
export function adviceMarkup(s,books,personality){
 const a=routeAdvice(s,books,personality);const observed=a.items.filter(i=>i.evidence!=='unknown');
 return `<section class="conditional-advice"><h2>학습 상태를 반영한 비교</h2>${observed.length?observed.map(i=>`<article><h3>${esc(i.title)} · ${esc(i.scope)}</h3><p><strong>${esc(i.direction)}</strong></p><p>${esc(i.reason)}</p></article>`).join(''):'<p>현재 범위와 희망하는 방향을 비교하고 있어요. 도움이 필요한 정도와 부담을 알려주시면 더 자세히 살펴볼 수 있어요.</p>'}${s.courses.length?'<button type="button" data-course-review>도움·부담을 함께 살펴보기</button>':''}<details><summary>선택한 과정의 시간 확인</summary><p>입력한 아이 학습 시간: 주 ${a.time.reportedChildMinutes}분${a.time.childUnknownCourseIds.length?` + 시간 미입력 ${a.time.childUnknownCourseIds.length}과정`:''}</p><p>입력한 부모 관리 시간: 주 ${a.time.reportedAdultMinutes}분${a.time.adultUnknownCourseIds.length?` + 시간 미입력 ${a.time.adultUnknownCourseIds.length}과정`:''}</p><p>${a.time.availableAdultMinutes===null?'가정의 전체 관리 가능 시간은 아직 미입력입니다.':`가정에서 관리 가능한 시간: 주 ${a.time.availableAdultMinutes}분`}</p><p>${a.time.adultFit==='reported_over'?'보고한 관리 시간이 가족의 가능 시간을 넘어요. 과정별 분량·병행을 다시 비교해 보세요.':a.time.adultFit==='within_reported'?'입력된 관리 시간은 가능 시간 안에 있어요. 아이의 실제 부담과 미등록 다른 일정도 함께 살펴봐요.':'시간이 비어 있는 부분이 있어 병행 여유를 확정하지 않아요.'}</p></details></section>`;
}

export function planAdviceMarkup(p){
 const a=p?.adviceSnapshot;if(!a)return '';
 return `<details class="conditional-advice"><summary>이 기준을 선택할 때 살펴본 학습 상태</summary>${a.items.map(i=>`<article><h3>${esc(i.title)} · ${esc(i.scope)}</h3><p>${esc(i.direction)}</p><p>${esc(i.reason)}</p></article>`).join('')}<p class="note">당시 가족이 보고한 관찰을 남긴 기록이에요. 이후 새 범위의 관찰이나 실제 진단은 따로 확인해요.</p></details>`;
}
