// ── 보캡 테스트 단어 데이터 ─────────────────────────────────────────────
// 새로운 날 추가하는 법: 사진을 Claude에게 올리면 이 배열 맨 앞에
// { id, date, label, words } 한 덩어리를 추가한다. id는 'd' + YYYYMMDD.
// def는 교재 문구를 그대로 베끼지 않고 같은 뜻의 쉬운 영어로 다시 쓴 것.
// ko는 인정할 답 여러 개(음성 인식이 어느 하나라도 포함하면 정답).
window.VOCAB_DAYS = [
  {
    id: 'd20260816',
    date: '2026-08-16',
    label: 'Week 1 · Unit 1 · Reading 1',
    words: [
      { en: 'have something in common', pos: 'idm',
        kw: ['share', 'same', 'common'], kwNeed: 1,
        def: 'to share the same interest or feature with someone',
        ko: ['공통점이 있다', '공통점'], koShow: '공통점이 있다',
        enAlt: ['in common', 'something in common'] },
      { en: 'left-handed', pos: 'adj',
        kw: ['left', 'hand'], kwNeed: 2,
        def: 'doing things mainly with the left hand',
        ko: ['왼손잡이'], koShow: '왼손잡이의',
        enAlt: ['left handed'] },
      { en: 'right-handed', pos: 'adj',
        kw: ['right', 'hand'], kwNeed: 2,
        def: 'doing things mainly with the right hand',
        ko: ['오른손잡이'], koShow: '오른손잡이의',
        enAlt: ['right handed'] },
      { en: 'population', pos: 'n',
        kw: ['people', 'number', 'live', 'many', 'place', 'area'], kwNeed: 2,
        def: 'how many people live in a certain place',
        ko: ['인구'], koShow: '인구' },
      { en: 'message', pos: 'n',
        kw: ['information', 'send', 'sent', 'words', 'someone', 'note'], kwNeed: 2,
        def: 'words or information you send to another person',
        ko: ['메시지', '메세지', '전갈', '전하는 말'], koShow: '메시지, 전하는 말' },
      { en: 'intelligent', pos: 'adj',
        kw: ['smart', 'clever', 'learn', 'understand'], kwNeed: 1,
        def: 'smart, and able to learn and understand things well',
        ko: ['똑똑한', '똑똑하다', '지능이 높은', '지능이 높다', '영리한', '영리하다'],
        koShow: '지능이 높은, 똑똑한' },
      { en: 'quality', pos: 'n',
        kw: ['good', 'excellent', 'standard', 'level'], kwNeed: 1,
        def: 'how good or excellent something is',
        ko: ['품질', '질 '], koShow: '품질, (좋은) 질' },
      { en: 'punctual', pos: 'adj',
        kw: ['on time', 'never late', 'not late', 'always time'], kwNeed: 1,
        def: 'always on time, and never late',
        ko: ['시간을 지키는', '시간을 잘 지키는', '시간을 지키다', '시간 엄수'],
        koShow: '시간을 잘 지키는' },
      { en: 'logic', pos: 'n',
        kw: ['thinking', 'reason', 'reasonable', 'clear'], kwNeed: 1,
        def: 'clear and reasonable thinking',
        ko: ['논리'], koShow: '논리' },
      { en: 'in order', pos: 'phr',
        kw: ['sequence', 'arranged', 'arrange', 'correct order', 'neat'], kwNeed: 1,
        def: 'arranged one after another in the right way',
        ko: ['순서대로', '정돈된', '차례대로'], koShow: '순서대로, 정돈된',
        enAlt: [] },
      { en: 'recognize', pos: 'v',
        kw: ['know', 'remember', 'seen before', 'saw before', 'saw it before'], kwNeed: 1,
        def: 'to know who or what something is, because you saw it before',
        ko: ['알아보다', '알아본다', '인식하다', '알아차리다'], koShow: '알아보다, 인식하다' },
      { en: 'movement', pos: 'n',
        kw: ['moving', 'move', 'position', 'location', 'changing'], kwNeed: 1,
        def: 'the act of moving or changing position',
        ko: ['움직임'], koShow: '움직임' },
      { en: 'accountant', pos: 'n',
        kw: ['money', 'financial', 'records', 'accounts'], kwNeed: 1,
        def: 'a person whose job is taking care of money records',
        ko: ['회계사'], koShow: '회계사' },
      { en: 'exception', pos: 'n',
        kw: ['rule', 'not follow', 'different', 'follow the rule'], kwNeed: 1,
        def: 'something that does not follow the usual rule',
        ko: ['예외'], koShow: '예외' },
      { en: 'practical', pos: 'adj',
        kw: ['useful', 'real', 'effective', 'helpful'], kwNeed: 1,
        def: 'useful and helpful in real life',
        ko: ['실용적인', '실용적이다', '실용적'], koShow: '실용적인' },
    ],
  },
];
