import { levels, resultFor } from "../../games/hidden-shape/levels.js?v=hidden-shape-3";
import { shapeSvg } from "../../games/hidden-shape/art.js?v=hidden-shape-3";

const $=(selector)=>document.querySelector(selector);let offset=0;const select=$("#levelSelect"),toggle=$("#answerToggle"),grid=$("#problemGrid");
levels.forEach((level)=>{const option=document.createElement("option");option.value=level.id;option.textContent=`${level.id}. ${level.title.ko} · ${level.difficulty}`;select.append(option);});
function promptFor(problem){if(problem.kind==="square-grid")return "정사각형 모눈에서 찾을 수 있는 크고 작은 정사각형은 모두 몇 개인가요?";if(problem.kind==="irregular-grid")return "그림에서 찾을 수 있는 크고 작은 사각형은 모두 몇 개입니까?";if(problem.kind==="triangle-grid")return "정삼각형 모눈에서 찾을 수 있는 크고 작은 삼각형은 모두 몇 개인가요?";return "다음 도형에서 찾을 수 있는 크고 작은 삼각형은 모두 몇 개인가요?";}
function breakdownFor(problem){const result=resultFor(problem);if(problem.kind==="fan"){const groups=problem.horizontalCount?[`가로선 ${result.bases}줄`]:[];groups.push(...result.byWidth.map((item)=>`밑변 ${item.size}칸: ${item.count}개`),`${result.byWidth.map((item)=>item.count).join("+")}=${result.total}`);return groups.join(" · ");}if(problem.kind==="square-grid")return result.bySize.map((item)=>`${item.size}칸: ${item.count}개`).join(" · ");if(problem.kind==="irregular-grid")return result.byArea.map((item)=>`넓이 ${item.area}: ${item.count}개`).join(" · ");return `위 방향 ${result.upward}개 · 아래 방향 ${result.downward}개`;}
function render(){const level=levels[Number(select.value||1)-1],show=toggle.checked,problems=Array.from({length:6},(_,index)=>level.problems[(offset+index)%level.problems.length]);$("#sheetTitle").textContent=level.title.ko;$("#sheetDescription").textContent=level.description.ko;grid.replaceChildren();problems.forEach((problem,index)=>{const article=document.createElement("article");article.className="problem";article.innerHTML=`<header><b>${index+1}</b><span>${promptFor(problem)}</span></header><div class="problem-art">${shapeSvg(problem,{label:promptFor(problem)})}</div><div class="answer-line">${show?`<strong>정답 ${problem.answer}개</strong><small>${breakdownFor(problem)}</small>`:"<span>답: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;개</span>"}</div>`;grid.append(article);});}
select.addEventListener("change",()=>{offset=0;render();});toggle.addEventListener("change",render);$("#refreshButton").addEventListener("click",()=>{offset=(offset+6)%10;render();});$("#printButton").addEventListener("click",()=>print());render();
