import { levels as polyLevels } from "../games/polyomino/levels.js?v=polyomino-2";
import { levels as equalLevels } from "../games/equal-partition/levels.js?v=equal-1";
import { levels as hiddenLevels } from "../games/hidden-shape/levels.js?v=hidden-shape-3";
import { readProfile } from "../shared/profile-storage.js";

const $=(selector)=>document.querySelector(selector),lang=localStorage.getItem("gfield-language")||"ko",profile=readProfile();
const copy={
  ko:{title:"도형 조각 정원",subtitle:"조각을 돌리고, 나누고, 그림 속 도형을 빠짐없이 찾아요.",polyTitle:"폴리오미노 퍼즐",polyDesc:"같은 조각 찾기에서 여러 조각으로 판 채우기까지",equalTitle:"똑같이 나누기",equalDesc:"같은 넓이에서 합동인 여러 조각 나누기까지",hiddenTitle:"숨은 도형 탐정",hiddenDesc:"삼각형과 사각형을 크기·방향·넓이별로 빠짐없이 세기",session:"레벨마다 10문제 · 한 번에 5문제",start:"시작하기"},
  en:{title:"Shape Garden",subtitle:"Turn pieces, partition boards, and find every hidden shape.",polyTitle:"Polyomino Puzzle",polyDesc:"Match pieces and cover boards exactly",equalTitle:"Equal Partition",equalDesc:"Progress from equal area to congruent regions",hiddenTitle:"Shape Detective",hiddenDesc:"Count triangles and rectangles by size, direction, and area",session:"10 per level · 5 each session",start:"Start"},
  zh:{title:"图形拼片花园",subtitle:"旋转拼片、等分图形，找出所有隐藏图形。",polyTitle:"多格骨牌拼图",polyDesc:"从寻找相同拼片到完整覆盖图板",equalTitle:"等分图形",equalDesc:"从相同面积逐步学习全等分割",hiddenTitle:"隐藏图形侦探",hiddenDesc:"按大小、方向和面积数三角形与四边形",session:"每级10题 · 每次5题",start:"开始"},
  ja:{title:"図形ピースの庭",subtitle:"ピースを回して分け、隠れた図形を全部見つけます。",polyTitle:"ポリオミノパズル",polyDesc:"同じピース探しから正確な敷きつめまで",equalTitle:"同じように分ける",equalDesc:"同じ広さから合同な分割まで",hiddenTitle:"かくれた図形探偵",hiddenDesc:"大きさ・向き・面積ごとに三角形と四角形を数える",session:"各レベル10問 · 1回5問",start:"スタート"}
};
const t=(key)=>copy[lang]?.[key]||copy.ko[key];
[["title","title"],["subtitle","subtitle"],["polyTitle","polyTitle"],["polyDesc","polyDesc"],["equalTitle","equalTitle"],["equalDesc","equalDesc"],["hiddenTitle","hiddenTitle"],["hiddenDesc","hiddenDesc"]].forEach(([id,key])=>{$(`#${id}`).textContent=t(key);});
[$("#sessionLabel"),$("#sessionLabel2"),$("#sessionLabel3")].forEach((element)=>{element.textContent=t("session");});
$("#playerName").textContent=profile.name||"GFIELD";$("#playerPoints").textContent=`${Number(localStorage.getItem("gfield-points")||120)} P`;

const polyNames={ko:[["같은 조각 찾기","돌리면 같은 조각"],["뒤집기 구별","돌리기와 뒤집기 비교"],["같은 조각 2~4개","기초 판 채우기"],["펜토미노 2개","복잡한 조각 맞추기"],["여러 조각 함께","서로 다른 조각으로 완성"]],en:[["Match Pieces","Find a rotated match"],["Turn or Flip","Tell reflection apart"],["Basic Cover","Cover with matching pieces"],["Pentomino Pair","Fit complex pieces"],["Mixed Cover","Complete with different pieces"]],zh:[["寻找相同拼片","找出旋转后相同的拼片"],["旋转或翻转","区分旋转与镜像"],["基础覆盖","用相同拼片填满图板"],["两个五格骨牌","拼合复杂拼片"],["混合覆盖","用不同拼片完成图板"]],ja:[["同じピース探し","回すと同じになるピース"],["回す・裏返す","回転と鏡映を見分ける"],["基本の敷きつめ","同じピースで盤を埋める"],["ペントミノ2個","複雑なピースを合わせる"],["ミックス敷きつめ","違うピースで完成する"]]};
const equalNames={ko:[["둘로 똑같이","같은 넓이 두 조각"],["여러 조각으로","세 조각과 네 조각"],["조건까지 맞게","표시와 수의 합"],["합동인 두 조각","돌리거나 뒤집어 포개기"],["합동 분할 도전","복잡한 판을 여러 조각으로"]],en:[["Split in Two","Two equal areas"],["More Regions","Three or four areas"],["Meet Conditions","Markers and number sums"],["Two Congruent Parts","Overlap after a turn or flip"],["Partition Challenge","Complex congruent regions"]],zh:[["分成两块","面积相同的两块"],["分成多块","三块或四块"],["满足条件","标记与数字和"],["两个全等图形","旋转或翻转后重合"],["全等分割挑战","复杂图板的多块分割"]],ja:[["二つに分ける","同じ広さの二つ"],["いくつかに分ける","三つ・四つに分ける"],["条件も合わせる","印と数の合計"],["合同な二つ","回す・裏返すと重なる"],["合同分割チャレンジ","複雑な盤を複数に分ける"]]};
const hiddenNames={ko:[["부채꼴 삼각형","크고 작은 삼각형 세기"],["겹친 삼각형","가로선마다 생기는 크고 작은 삼각형"],["정사각형 모눈","한 칸부터 큰 정사각형까지"],["붙인 사각형","완성된 사각형을 넓이별로"],["정삼각형 모눈","위·아래 방향을 함께 세기"]],en:[["Triangle Fan","Count large and small triangles"],["Layered Triangles","Count large and small triangles on every base"],["Square Grid","Count squares of every size"],["Joined Rectangles","Group complete quadrilaterals by area"],["Triangle Grid","Count upward and downward shapes"]],zh:[["扇形三角形","数大大小小的三角形"],["重叠三角形","数每条底边上的大小三角形"],["正方形方格","数出各种大小的正方形"],["拼接四边形","按面积数完整四边形"],["正三角形网格","数向上和向下的三角形"]],ja:[["扇形の三角形","大小の三角形を数える"],["重なった三角形","各底辺の大小の三角形を数える"],["正方形の方眼","全ての大きさを数える"],["つないだ四角形","面積別に四角形を数える"],["正三角形の格子","上向きと下向きを数える"]]};

function render(levels,selector,game,names){const grid=$(selector),list=names[lang]||names.en;levels.forEach((level,index)=>{const anchor=document.createElement("a");anchor.className="level-card";anchor.href=`../games/${game}/?level=${level.id}`;anchor.innerHTML=`<div class="preview preview-${index+1}" aria-hidden="true"><span>${level.id}</span><div class="mini-grid">${Array.from({length:12},(_,number)=>`<i style="--n:${number}"></i>`).join("")}</div></div><div><strong>${list[index][0]}</strong><p>${list[index][1]}</p><b>${t("start")} ›</b></div>`;grid.append(anchor);});}
render(polyLevels,"#polyLevels","polyomino",polyNames);render(equalLevels,"#equalLevels","equal-partition",equalNames);render(hiddenLevels,"#hiddenLevels","hidden-shape",hiddenNames);
