import { levels as polyLevels } from "../games/polyomino/levels.js?v=polyomino-2";
import { levels as equalLevels } from "../games/equal-partition/levels.js?v=equal-1";
import { readProfile } from "../shared/profile-storage.js";
const $=s=>document.querySelector(s),lang=localStorage.getItem("gfield-language")||"ko",profile=readProfile();
const copy={ko:{title:"도형 조각 정원",subtitle:"조각을 돌리고, 빈틈없이 채우고, 조건에 맞게 나누어요.",polyTitle:"폴리오미노 퍼즐",polyDesc:"같은 조각 찾기에서 여러 조각으로 판 채우기까지",equalTitle:"똑같이 나누기",equalDesc:"같은 넓이에서 합동인 여러 조각 나누기까지",session:"레벨마다 10문제 · 한 번에 5문제",start:"시작하기"},en:{title:"Shape Garden",subtitle:"Turn pieces, cover boards, and partition shapes by rules.",polyTitle:"Polyomino Puzzle",polyDesc:"Match pieces and cover boards exactly",equalTitle:"Equal Partition",equalDesc:"Progress from equal area to congruent regions",session:"10 per level · 5 each session",start:"Start"},zh:{title:"图形拼片花园",subtitle:"旋转拼片、填满图板，再按条件等分图形。",polyTitle:"多格骨牌拼图",polyDesc:"从寻找相同拼片到完整覆盖图板",equalTitle:"等分图形",equalDesc:"从相同面积逐步学习全等分割",session:"每级10题 · 每次5题",start:"开始"},ja:{title:"図形ピースの庭",subtitle:"ピースを回して敷きつめ、条件にそって形を分けます。",polyTitle:"ポリオミノパズル",polyDesc:"同じピース探しから正確な敷きつめまで",equalTitle:"同じように分ける",equalDesc:"同じ広さから合同な分割まで",session:"各レベル10問 · 1回5問",start:"スタート"}};const t=k=>copy[lang]?.[k]||copy.ko[k];
$("#title").textContent=t("title");$("#subtitle").textContent=t("subtitle");$("#polyTitle").textContent=t("polyTitle");$("#polyDesc").textContent=t("polyDesc");$("#equalTitle").textContent=t("equalTitle");$("#equalDesc").textContent=t("equalDesc");$("#sessionLabel").textContent=$("#sessionLabel2").textContent=t("session");$("#playerName").textContent=profile.name||"GFIELD";$("#playerPoints").textContent=`${Number(localStorage.getItem("gfield-points")||120)} P`;
const polyNames={ko:[["같은 조각 찾기","돌리면 같은 조각"],["뒤집기 구별","돌리기와 뒤집기 비교"],["같은 조각 2~4개","기초 판 채우기"],["펜토미노 2개","복잡한 조각 맞추기"],["여러 조각 함께","서로 다른 조각으로 완성"]],en:[["Match Pieces","Find a rotated match"],["Turn or Flip","Tell reflection apart"],["Basic Cover","Cover with matching pieces"],["Pentomino Pair","Fit complex pieces"],["Mixed Cover","Complete with different pieces"]],zh:[["寻找相同拼片","找出旋转后相同的拼片"],["旋转或翻转","区分旋转与镜像"],["基础覆盖","用相同拼片填满图板"],["两个五格骨牌","拼合复杂拼片"],["混合覆盖","用不同拼片完成图板"]],ja:[["同じピース探し","回すと同じになるピース"],["回す・裏返す","回転と鏡映を見分ける"],["基本の敷きつめ","同じピースで盤を埋める"],["ペントミノ2個","複雑なピースを合わせる"],["ミックス敷きつめ","違うピースで完成する"]]};
const equalNames={ko:[["둘로 똑같이","같은 넓이 두 조각"],["여러 조각으로","세 조각과 네 조각"],["조건까지 맞게","표시와 수의 합"],["합동인 두 조각","돌리거나 뒤집어 포개기"],["합동 분할 도전","복잡한 판을 여러 조각으로"]],en:[["Split in Two","Two equal areas"],["More Regions","Three or four areas"],["Meet Conditions","Markers and number sums"],["Two Congruent Parts","Overlap after a turn or flip"],["Partition Challenge","Complex congruent regions"]],zh:[["分成两块","面积相同的两块"],["分成多块","三块或四块"],["满足条件","标记与数字和"],["两个全等图形","旋转或翻转后重合"],["全等分割挑战","复杂图板的多块分割"]],ja:[["二つに分ける","同じ広さの二つ"],["いくつかに分ける","三つ・四つに分ける"],["条件も合わせる","印と数の合計"],["合同な二つ","回す・裏返すと重なる"],["合同分割チャレンジ","複雑な盤を複数に分ける"]]};
function render(levels,selector,game,names){const grid=$(selector),list=names[lang]||names.en;levels.forEach((level,i)=>{const a=document.createElement("a");a.className="level-card";a.href=`../games/${game}/?level=${level.id}`;a.innerHTML=`<div class="preview preview-${i+1}" aria-hidden="true"><span>${level.id}</span><div class="mini-grid">${Array.from({length:12},(_,n)=>`<i style="--n:${n}"></i>`).join("")}</div></div><div><strong>${list[i][0]}</strong><p>${list[i][1]}</p><b>${t("start")} ›</b></div>`;grid.append(a);});}
render(polyLevels,"#polyLevels","polyomino",polyNames);render(equalLevels,"#equalLevels","equal-partition",equalNames);
