'use strict';
// Operator-only, local preparation. Import and --self-test never create credentials.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const ROOT=path.resolve(__dirname,'../output/private-challenge'),MAX_BYTES=6*1024*1024,MAX_LEASE=3*60*60*1000,HEX=/^[a-f0-9]{64}$/;
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
function fail(code){throw Error(code);}
function validPath(value){return typeof value==='string'&&value.length<=300&&/^[A-Za-z0-9_./-]+\.json$/.test(value)&&value.split('/').every(part=>part&&part!=='.'&&part!=='..');}
function below(root,file){const rel=path.relative(root,file);return !!rel&&!rel.startsWith('..'+path.sep)&&rel!=='..'&&!path.isAbsolute(rel);}
function checkedFile(root,relative){if(!validPath(relative))fail('invalid_relative_path');const file=path.resolve(root,relative);if(!below(root,file))fail('path_escape');let cursor=root;for(const part of relative.split('/')){cursor=path.join(cursor,part);if(fs.lstatSync(cursor).isSymbolicLink())fail('symlink_disallowed');}if(!below(fs.realpathSync(root),fs.realpathSync(file)))fail('real_path_escape');const stat=fs.statSync(file);if(!stat.isFile()||stat.size<1||stat.size>MAX_BYTES)fail('invalid_file_size');return file;}
function readJsonBytes(root,relative){const file=checkedFile(root,relative),bytes=fs.readFileSync(file);if(bytes.length<1||bytes.length>MAX_BYTES)fail('invalid_file_size');try{JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}catch{fail('invalid_json');}return bytes;}
function validateManifest(manifest,load){
 if(!manifest||manifest.schemaVersion!==1||!/^challenge-[0-9]{17}$/.test(manifest.contentVersion)||!manifest.documents||!manifest.bank||!manifest.sources)fail('invalid_manifest');
 const refs=new Map();function walk(value){if(!value||typeof value!=='object')return;if(Object.hasOwn(value,'path')){if(!validPath(value.path)||!HEX.test(value.sha256)||value.path==='manifest.json')fail('invalid_manifest_reference');if(refs.has(value.path))fail('duplicate_manifest_reference');refs.set(value.path,value);}for(const v of Object.values(value))walk(v);}walk(manifest);if(!refs.size||refs.size>10000)fail('invalid_reference_count');
 const files={};for(const [relative,ref]of [...refs].sort(([a],[b])=>a.localeCompare(b))){const bytes=load(relative);if(!Buffer.isBuffer(bytes)||!bytes.length||bytes.length>MAX_BYTES)fail('invalid_file_size');if(sha(bytes)!==ref.sha256)fail('file_hash_mismatch');if(ref.bytes!==undefined&&ref.bytes!==bytes.length)fail('file_size_mismatch');try{JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}catch{fail('invalid_json');}files[relative]={sha256:ref.sha256,bytes:bytes.length};}return files;
}
function verifyPackage(out){
 const root=fs.realpathSync(ROOT),packageDir=path.resolve(out);if(path.dirname(packageDir)!==ROOT||!/^challenge-[0-9]{17}$/.test(path.basename(packageDir)))fail('package_out_of_scope');if(fs.lstatSync(packageDir).isSymbolicLink()||!below(root,fs.realpathSync(packageDir)))fail('package_symlink');const privateDir=path.join(packageDir,'private');if(fs.lstatSync(privateDir).isSymbolicLink())fail('private_symlink');const manifestBytes=readJsonBytes(privateDir,'manifest.json'),manifest=JSON.parse(manifestBytes.toString('utf8'));if(manifest.contentVersion!==path.basename(packageDir))fail('version_mismatch');const files=validateManifest(manifest,relative=>readJsonBytes(privateDir,relative));
 function scan(dir,prefix=''){const result=[];for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(entry.isSymbolicLink())fail('symlink_disallowed');const relative=prefix+entry.name;if(entry.isDirectory())result.push(...scan(path.join(dir,entry.name),relative+'/'));else if(entry.isFile())result.push(relative);else fail('unexpected_file_kind');}return result;}const actual=scan(privateDir).sort(),expected=[...Object.keys(files),'manifest.json'].sort();if(JSON.stringify(actual)!==JSON.stringify(expected))fail('unreferenced_private_file');files['manifest.json']={sha256:sha(manifestBytes),bytes:manifestBytes.length};return {out:packageDir,privateDir,contentVersion:manifest.contentVersion,files};
}
 function verifyLatest(){const latest=JSON.parse(fs.readFileSync(path.join(ROOT,'latest.json'),'utf8'));const verified=verifyPackage(latest.out);if(latest.contentVersion!==verified.contentVersion)fail('latest_version_mismatch');return verified;}
 function verifyNamed(version){if(typeof version!=='string'||!/^challenge-[0-9]{17}$/.test(version))fail('invalid_package_version');return verifyPackage(path.join(ROOT,version));}
function settingsText(release){return '// Temporary operator deployment input. Never commit or publish.\nexport const RELEASE = '+JSON.stringify(release,null,2)+';\n';}
function makeRelease(files,token,now){if(!/^[a-f0-9]{64}$/.test(token)||!Number.isSafeInteger(now))fail('invalid_lease_input');return {issuedAt:now,expiresAt:now+MAX_LEASE,tokenSha256:sha(token),files};}
function validateRelease(release,now=Date.now()){if(!release||!Number.isSafeInteger(release.issuedAt)||!Number.isSafeInteger(release.expiresAt)||release.issuedAt>now||release.expiresAt<=now||release.expiresAt-release.issuedAt>MAX_LEASE||release.expiresAt<=release.issuedAt||!HEX.test(release.tokenSha256)||!release.files||!Object.keys(release.files).length)fail('invalid_or_expired_release');for(const [relative,pin]of Object.entries(release.files))if(!validPath(relative)||!pin||!HEX.test(pin.sha256)||!Number.isSafeInteger(pin.bytes)||pin.bytes<1||pin.bytes>MAX_BYTES)fail('invalid_release_pin');}
function ensureIgnored(target){const repo=path.resolve(__dirname,'../..'),result=cp.spawnSync('git',['-c',`safe.directory=${repo.replaceAll('\\','/')}`,'check-ignore','--quiet','--',path.relative(repo,target)],{cwd:repo,stdio:'pipe'});if(result.status!==0)fail('operator_directory_not_gitignored');}
function prepare(verified){
 const parent=path.join(verified.out,'operator-release');ensureIgnored(path.join(parent,'probe','token.txt'));if(fs.existsSync(parent)&&fs.lstatSync(parent).isSymbolicLink())fail('operator_symlink');fs.mkdirSync(parent,{recursive:true,mode:0o700});const now=Date.now(),run=path.join(parent,new Date(now).toISOString().replace(/[^0-9]/g,'')+'-'+process.pid);fs.mkdirSync(run,{mode:0o700}); // Exclusive: EEXIST aborts; no token is overwritten.
 const token=crypto.randomBytes(32).toString('hex'),release=makeRelease(verified.files,token,now),plan={schemaVersion:1,contentVersion:verified.contentVersion,packageDir:verified.out,release};
 for(const[name,content]of[['token.txt',token],['release-settings.ts',settingsText(release)],['release-plan.json',JSON.stringify(plan,null,2)]])fs.writeFileSync(path.join(run,name),content,{flag:'wx',mode:0o600});return path.join(run,'release-settings.ts');
}
function selfTest(){const assert=require('node:assert/strict'),bytes=Buffer.from('{"sample":1}'),relative='v1/example.json',manifest={schemaVersion:1,contentVersion:'challenge-20260909000000000',documents:{sample:{path:relative,sha256:sha(bytes)}},bank:{},sources:{}};assert.equal(validateManifest(manifest,()=>bytes)[relative].bytes,bytes.length);for(const bad of ['../x.json','/x.json','v1/../x.json','v1\\x.json','https://x.json','v1/%2e.json','v1//x.json'])assert(!validPath(bad));assert.throws(()=>validateManifest(manifest,()=>Buffer.from('{}')));assert.throws(()=>validateManifest(manifest,()=>Buffer.alloc(MAX_BYTES+1)));const lease=makeRelease({[relative]:{sha256:sha(bytes),bytes:bytes.length}},'a'.repeat(64),1000);validateRelease(lease,1001);assert.throws(()=>validateRelease(lease,lease.expiresAt));assert.throws(()=>validateRelease({...lease,expiresAt:lease.expiresAt+1},1001));assert(!settingsText(lease).includes('a'.repeat(64)));return {checks:14,remoteRequests:0,credentialFilesCreated:0};}
 if(require.main===module){try{const args=process.argv.slice(2),named=args.indexOf('--package');const version=named===-1?null:args[named+1],rest=named===-1?args:args.filter((_,index)=>index!==named&&index!==named+1),verified=version?verifyNamed(version):verifyLatest();if(args.length===1&&args[0]==='--self-test')console.log(JSON.stringify(selfTest()));else if(rest.length===1&&rest[0]==='--execute')console.log(prepare(verified));else if(rest.length===0)console.log(JSON.stringify({status:'verified_dry_run',contentVersion:verified.contentVersion,files:Object.keys(verified.files).length,credentialFilesCreated:0}));else fail('usage_prepare_requires_execute_or_self_test');}catch{console.error('Release preparation failed; no credential is printed. Check the local package and protected output directory.');process.exitCode=1;}}
 module.exports={ROOT,MAX_BYTES,MAX_LEASE,sha,validPath,below,readJsonBytes,verifyPackage,verifyLatest,verifyNamed,validateManifest,validateRelease,settingsText,makeRelease,ensureIgnored,selfTest};
