'use strict';
// Explicit operator transport only. No service key, Auth, DB, or deployment calls.
const fs=require('node:fs'),path=require('node:path'),P=require('./prepare_challenge_release_ingest.cjs');
const ENDPOINT='https://uqtkxhchtbcizzteuvsq.supabase.co/functions/v1/hf-release-ingest';
function error(code){throw Error(code);}
function loadRun(run){
 const absolute=path.resolve(run),relative=path.relative(P.ROOT,absolute);if(!/^challenge-[0-9]{17}[\\/]operator-release[\\/][0-9]{17}-[0-9]+$/.test(relative))error('run_out_of_scope');let current=P.ROOT;for(const part of relative.split(path.sep)){current=path.join(current,part);if(fs.lstatSync(current).isSymbolicLink())error('run_symlink');}if(!P.below(fs.realpathSync(P.ROOT),fs.realpathSync(absolute)))error('run_real_path_escape');P.ensureIgnored(path.join(absolute,'token.txt'));
 const read=(name,limit)=>{const file=path.join(absolute,name),stat=fs.lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size<1||stat.size>limit)error('invalid_operator_file');return fs.readFileSync(file,'utf8');};const plan=JSON.parse(read('release-plan.json',P.MAX_BYTES));if(plan.schemaVersion!==1)error('invalid_plan');const packageDir=path.dirname(path.dirname(absolute));if(plan.packageDir!==packageDir||plan.contentVersion!==path.basename(packageDir))error('plan_package_mismatch');P.validateRelease(plan.release);if(read('release-settings.ts',P.MAX_BYTES)!==P.settingsText(plan.release))error('settings_plan_mismatch');const verified=P.verifyPackage(packageDir);if(JSON.stringify(verified.files)!==JSON.stringify(plan.release.files))error('package_pin_mismatch');return {run:absolute,plan,verified,readToken:()=>read('token.txt',64)};
}
async function readResponse(response){const reader=response.body?.getReader();if(!reader)error('missing_response');let size=0,chunks=[];try{for(;;){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>8192){await reader.cancel();error('oversize_response');}chunks.push(Buffer.from(value));}}finally{reader.releaseLock();}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{error('invalid_response');}}
async function uploadFiles({execute,release,token,readFile,fetchImpl=globalThis.fetch,now=Date.now,sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms)),progress=()=>{}}){
 if(execute!==true)error('execute_required');P.validateRelease(release,now());if(!/^[a-f0-9]{64}$/.test(token)||P.sha(token)!==release.tokenSha256)error('token_mismatch');const entries=Object.entries(release.files);if(!entries.some(([relative])=>relative==='manifest.json'))error('manifest_pin_required');
 // Validate every byte before the first request, then validate each body again immediately before sending it.
 const read=relative=>{const body=readFile(relative),pin=release.files[relative];if(!Buffer.isBuffer(body)||body.length!==pin.bytes||body.length>P.MAX_BYTES||P.sha(body)!==pin.sha256)error('local_file_mismatch');return body;};for(const[relative]of entries)read(relative);
 const results=[];let completed=0,failed=false,cursor=0;const queue=entries.filter(([relative])=>relative!=='manifest.json');
 async function one(relative,pin){let attempts=0;for(;;){P.validateRelease(release,now());const body=read(relative);attempts++;let response;try{response=await fetchImpl(ENDPOINT,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json','x-release-path':relative,Authorization:`Bearer ${token}`},body,signal:AbortSignal.timeout(30000)});}catch{error('transport_failure');}
   if(response.status!==200){const retry=response.status===429||response.status>=500&&response.status<=599;await response.body?.cancel();if(retry&&attempts<3){await sleep(Math.min(5000,1000*attempts));continue;}results.push({path:relative,sha256:pin.sha256,bytes:pin.bytes,status:'http_failure',httpStatus:response.status,attempts});return false;}
   const data=await readResponse(response);if(data.path!==relative||data.sha256!==pin.sha256||data.bytes!==pin.bytes||!['uploaded','already_present'].includes(data.status))error('response_pin_mismatch');results.push({path:relative,sha256:pin.sha256,bytes:pin.bytes,status:data.status,attempts});completed++;if(completed%50===0)progress(completed);return true;}}
 async function worker(){while(!failed&&cursor<queue.length){const[relative,pin]=queue[cursor++];try{if(!await one(relative,pin))failed=true;}catch{failed=true;results.push({path:relative,sha256:pin.sha256,bytes:pin.bytes,status:'verification_or_transport_failure'});}}}
 await Promise.all(Array.from({length:4},worker));
 if(!failed){const pin=release.files['manifest.json'];try{if(!await one('manifest.json',pin))failed=true;}catch{failed=true;results.push({path:'manifest.json',sha256:pin.sha256,bytes:pin.bytes,status:'verification_or_transport_failure'});}}
 for(const[relative,pin]of entries)if(!results.some(result=>result.path===relative))results.push({path:relative,sha256:pin.sha256,bytes:pin.bytes,status:'not_attempted',attempts:0});
 return {status:failed?'failed':'uploaded_readback_verified',expectedFiles:entries.length,verifiedFiles:completed,files:results,sealed:false,requiresOperatorSeal:true};
}
async function main(args){
 if(args.length===1&&args[0]==='--self-test'){console.log(JSON.stringify(await selfTest()));return;}
 if(![2,3].includes(args.length)||args[0]!=='--run'||args.length===3&&args[2]!=='--execute')error('usage_upload_run_execute');const loaded=loadRun(args[1]);if(args.length===2){console.log(JSON.stringify({status:'verified_dry_run',files:Object.keys(loaded.plan.release.files).length,remoteRequests:0}));return;}
 let report;try{report=await uploadFiles({execute:true,release:loaded.plan.release,token:loaded.readToken(),readFile:relative=>P.readJsonBytes(loaded.verified.privateDir,relative),progress:n=>console.log(`${n} files verified`)});}catch{report={status:'failed_before_transport_completion',files:[],sealed:false,requiresOperatorSeal:true};}
 const reportPath=path.join(loaded.run,'upload-report-'+new Date().toISOString().replace(/[^0-9]/g,'')+'-'+process.pid+'.json');fs.writeFileSync(reportPath,JSON.stringify(report,null,2),{flag:'wx',mode:0o600});console.log(JSON.stringify({status:report.status,verifiedFiles:report.verifiedFiles||0,report:reportPath,sealed:false,requiresOperatorSeal:true}));if(report.status!=='uploaded_readback_verified')process.exitCode=1;
}
async function selfTest(){
 const assert=require('node:assert/strict'),body=Buffer.from('{}'),paths=['v1/a.json','v1/b.json','manifest.json'],pins=Object.fromEntries(paths.map(p=>[p,{sha256:P.sha(body),bytes:body.length}])),token='b'.repeat(64),release=P.makeRelease(pins,token,1000);let calls=[];
 const good=async(url,options)=>{assert.equal(url,ENDPOINT);assert.equal(options.redirect,'error');assert(!Object.hasOwn(options.headers,'Origin'));calls.push(options.headers['x-release-path']);const relative=options.headers['x-release-path'];return new Response(JSON.stringify({path:relative,...pins[relative],status:'uploaded'}),{status:200});};const base={execute:true,release,token,readFile:()=>body,fetchImpl:good,now:()=>1001,sleep:async()=>{}};
 const report=await uploadFiles(base);assert.equal(report.status,'uploaded_readback_verified');assert.equal(calls.at(-1),'manifest.json');assert.equal(report.sealed,false);assert(!JSON.stringify(report).includes(token));
 await assert.rejects(()=>uploadFiles({...base,execute:false}));await assert.rejects(()=>uploadFiles({...base,token:'c'.repeat(64)}));await assert.rejects(()=>uploadFiles({...base,now:()=>release.expiresAt}));await assert.rejects(()=>uploadFiles({...base,readFile:()=>Buffer.from('{"bad":1}')}));
 for(const status of [401,409,429,503]){let count=0;const r=await uploadFiles({...base,release:{...release,files:{'manifest.json':pins['manifest.json']}},fetchImpl:async()=>{count++;return new Response('{}',{status});}});assert.equal(count,[429,503].includes(status)?3:1);assert.equal(r.status,'failed');}
 const mismatch=await uploadFiles({...base,fetchImpl:async()=>new Response(JSON.stringify({path:'v1/a.json',sha256:'0'.repeat(64),bytes:2,status:'uploaded'}))});assert.equal(mismatch.status,'failed');assert.equal(mismatch.files.find(f=>f.path==='manifest.json').status,'not_attempted');assert.equal(mismatch.files.length,paths.length);
 let n=0;const retry=await uploadFiles({...base,release:{...release,files:{'manifest.json':pins['manifest.json']}},fetchImpl:async(...args)=>++n===1?new Response('{}',{status:429}):good(...args)});assert.equal(retry.status,'uploaded_readback_verified');assert.equal(n,2);
 const manyPins=Object.fromEntries([...Array.from({length:12},(_,i)=>`v1/${i}.json`),'manifest.json'].map(p=>[p,pins['manifest.json']]));let active=0,maximum=0,finished=0;const parallel=await uploadFiles({...base,release:{...release,files:manyPins},fetchImpl:async(url,options)=>{active++;maximum=Math.max(maximum,active);const relative=options.headers['x-release-path'];if(relative==='manifest.json')assert.equal(finished,12);await new Promise(resolve=>setImmediate(resolve));active--;finished++;return new Response(JSON.stringify({path:relative,...manyPins[relative],status:'already_present'}));}});assert.equal(maximum,4);assert.equal(parallel.verifiedFiles,13);return {checks:29,remoteRequests:0,credentialFilesCreated:0};
}
if(require.main===module)main(process.argv.slice(2)).catch(()=>{console.error('Release upload failed. No credential or response body is printed. The operator must separately seal the endpoint.');process.exitCode=1;});
module.exports={ENDPOINT,loadRun,uploadFiles,selfTest};
