/* Public introduction QA. No remote writes, real questions, student data, or external CTA navigation. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const base=path.resolve(__dirname,'..'),out=path.join(base,'output/qa/challenge-intro');
let checks=0;const results=[];function check(label,ok){assert.ok(ok,label);checks++;results.push(label);}
(async()=>{fs.mkdirSync(out,{recursive:true});const server=http.createServer((req,res)=>{let name=decodeURIComponent(new URL(req.url,'http://local').pathname);if(name.endsWith('/'))name+='index.html';const file=path.resolve(base,'.'+name);if(!file.startsWith(base+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,bytes)=>{if(err){res.writeHead(404).end();return;}res.setHeader('content-type',({'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(bytes);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch();try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),requests=[],errors=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',async route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());
 await page.goto(origin+'/challenge/intro.html');await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));
 check('exact title',(await page.title()).includes('2026년 9월 챌린지 대비'));check('one h1',await page.locator('h1').count()===1);check('Korean language',await page.locator('html').getAttribute('lang')==='ko');check('no scripts or student auth lookup',await page.locator('script').count()===0);
 check('no private material requests',requests.every(url=>!/(?:\.js(?:\?|$)|private|question|answer|exam\.html|concepts\.html)/i.test(url)));
 const text=await page.locator('body').innerText(),compact=text.replace(/\s+/gu,' ');check('removed 6-year-old wording',!compact.includes('6세 학습'));for(const t of ['개념 교재','2권','예측 모의고사','4회','유사문제은행','문제 미리보기','로그인하고 문제은행 열기','별도 승인','60점은 본 프로그램의 학습 점검 기준','대영역·소영역·유형별','쉽게·같게·어렵게','승인된 학생의 이름'])check('verified content: '+t,compact.includes(t));
 check('no unsupported promises',!/(합격 보장|합격률|상위 \d|\d+%|원\/월|월 \d|경쟁학원)/.test(text));
 const consultation=fs.readFileSync(path.join(base,'portal-data.js'),'utf8').match(/consultationUrl:\s*"([^"]+)"/)[1],application='https://naver.me/xJcfYI9J';const ctas=await page.locator('a[href^="https:"]').evaluateAll(a=>a.map(x=>({href:x.href,target:x.target,rel:x.rel})));check('two Naver and two Kakao application links',ctas.length===4&&ctas.filter(x=>x.href===application).length===2&&ctas.filter(x=>x.href===consultation).length===2&&ctas.every(x=>x.target==='_blank'&&x.rel.includes('noopener')&&x.rel.includes('noreferrer')));
 check('source-confirmed two-fold paper preview',await page.locator('.fold-paper-figure').count()===3&&await page.locator('.fold-punch').count()===2&&compact.includes('오른쪽을 왼쪽으로')&&compact.includes('아래를 위로')&&compact.includes('구멍 2개'));
 check('library exists',fs.existsSync(path.join(base,'challenge/index.html')));check('existing library links',await page.locator('a[href="./index.html"]').count()===2);check('exact challenge login links',await page.locator('a[href="../?login=1&next=challenge"]').count()===2);check('exact bank login link',await page.locator('a[href="../?login=1&next=challenge-bank"]').count()===1);check('actual logo only',await page.locator('img').evaluateAll(a=>a.every(x=>x.getAttribute('src')==='assets/gfield-logo.png'&&x.complete&&x.naturalWidth>0)));
 for(const width of [1440,1000,768,390,320]){await page.setViewportSize({width,height:1000});check('no horizontal overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('visible links minimum touch height '+width,await page.locator('a').evaluateAll(a=>a.filter(x=>x.getBoundingClientRect().width>0&&!x.classList.contains('skip-link')).every(x=>x.getBoundingClientRect().height>=43.5)));if([1440,390].includes(width)){await page.screenshot({path:path.join(out,`full-${width}.png`),fullPage:true});await page.locator('.hero').screenshot({path:path.join(out,`hero-${width}.png`)});await page.locator('#review').screenshot({path:path.join(out,`review-${width}.png`)});}}
 await page.setViewportSize({width:1440,height:1000});await page.goto(origin+'/challenge/intro.html');await page.keyboard.press('Tab');check('first focus is skip link',await page.evaluate(()=>document.activeElement.classList.contains('skip-link')));check('visible keyboard outline',await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle!=='none'));await page.keyboard.press('Enter');check('skip link reaches main',new URL(page.url()).hash==='#main');
 await page.goto(origin+'/challenge/intro.html');const keyboardTargets=[];for(let i=0;i<11;i++){await page.keyboard.press('Tab');keyboardTargets.push(await page.evaluate(()=>document.activeElement.getAttribute('href')));}check('keyboard reaches consultation',keyboardTargets.includes(consultation));check('keyboard reaches library',keyboardTargets.includes('./index.html'));check('keyboard reaches section links',keyboardTargets.includes('#curriculum')&&keyboardTargets.includes('#bank'));
 await page.emulateMedia({reducedMotion:'reduce'});check('reduced motion removes transitions',await page.locator('.button').first().evaluate(x=>getComputedStyle(x).transitionDuration==='0s'));check('no console errors',errors.length===0);check('requests stay local',requests.every(u=>u.startsWith(origin)));
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,results,errors,consultation,publicPageOnly:true,remoteWrites:0,screenshots:['full-1440.png','hero-1440.png','review-1440.png','full-390.png','hero-390.png','review-390.png']},null,2));console.log(JSON.stringify({status:'passed',checks,errors,output:out}));
 }finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
