'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'hyper-focus/output/qa/challenge-fold-stack-studio');
const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const target=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!target.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(target,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',mime[path.extname(target)]||'application/octet-stream');res.end(data);});});
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:1000}});let checks=0,report=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto('http://127.0.0.1:'+server.address().port+'/hyper-focus/challenge/studio.html?teacherPreview=1&tab=bank');await page.waitForFunction(()=>!!window.HFChallengeStudio);
for(const difficulty of ['easy','same','hard']){
 await page.emulateMedia({media:'screen'});await page.setViewportSize({width:1280,height:1000});if(await page.locator('#clearSelection').isEnabled())await page.locator('#clearSelection').click();await page.locator('[name=difficulty][value='+difficulty+']').check();
  await page.locator('#bankRoundFilter').selectOption('all');for(const id of ['challenge-r1-extra-03','challenge-r4-main-12'])await page.locator('[data-select="'+id+'"]').check();
  await page.locator('#variantCount').fill('1');await page.locator('#buildPractice').click();await page.waitForFunction(d=>HFChallengeStudio.getSnapshot()?.difficulty===d&&HFChallengeStudio.getSnapshot()?.entries.length===2,difficulty);await page.locator('#printMode').selectOption('answers');await page.waitForFunction(()=>document.body.dataset.printReady==='true'&&document.body.dataset.watermarkReady==='true');
 const snapshot=await page.evaluate(()=>HFChallengeStudio.getSnapshot());assert(snapshot.entries.every(e=>e.question.solutionDiagram));checks++;
 const fold=snapshot.entries.find(e=>e.question.payload.kind==='geo-fold').question.payload,stack=snapshot.entries.find(e=>e.question.payload.kind==='geo-stack').question.payload;
 for(const width of [1280,390]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>document.activeElement?.blur());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');checks++;const diagrams=page.locator('#worksheetPages .solution-step-panels');assert.equal(await diagrams.count(),2);checks++;
 assert.deepEqual(await page.locator('#worksheetPages [data-fold-remaining]').evaluateAll(nodes=>nodes.map(n=>+n.dataset.foldRemaining)),Array.from({length:fold.folds.length+1},(_,i)=>fold.folds.length-i),'unfolding order preserved');checks++;
 assert.deepEqual(await page.locator('#worksheetPages [data-solution-layer]').evaluateAll(nodes=>nodes.map(n=>+n.dataset.solutionLayer)),Array.from({length:Math.max(...stack.heights.flat())},(_,i)=>i+1),'bottom-to-top layer order preserved');checks++;
 const labelSizes=await page.locator('#worksheetPages .solution-step-panels svg text').evaluateAll(nodes=>nodes.map(n=>{const m=n.getScreenCTM();return parseFloat(getComputedStyle(n).fontSize)*Math.hypot(m.c,m.d);}));assert(labelSizes.length>0&&Math.min(...labelSizes)>=12,'actual label size below 12px: '+Math.min(...labelSizes));checks++;
 for(let i=0;i<2;i++){await diagrams.nth(i).screenshot({path:path.join(out,difficulty+'-'+i+'-'+width+'-diagram.png')});}
 await page.locator('#worksheetPages').screenshot({path:path.join(out,difficulty+'-'+width+'-answers.png'),style:'.skip-link{visibility:hidden!important}'});
 }
 await page.emulateMedia({media:'print'});await page.setViewportSize({width:1280,height:1200});await page.waitForTimeout(100);const expected=await page.locator('.studio-page').count();assert(await page.locator('.studio-page').evaluateAll(nodes=>nodes.every(n=>n.scrollHeight<=n.clientHeight+2&&n.scrollWidth<=n.clientWidth+2)),'A4 content overflow');checks++;
 const bounds=await page.locator('.studio-page').evaluateAll(pages=>pages.flatMap(p=>{const b=p.getBoundingClientRect();const w=document.createTreeWalker(p,NodeFilter.SHOW_TEXT);const bad=[];while(w.nextNode()){if(!w.currentNode.textContent.trim())continue;const range=document.createRange();range.selectNodeContents(w.currentNode);for(const r of range.getClientRects())if(r.width&&(r.left<b.left-1||r.right>b.right+1||r.bottom>b.bottom+1))bad.push(w.currentNode.textContent);}return bad;}));assert.deepEqual(bounds,[],'text outside actual printpage');checks++;
  assert.equal(await page.locator('#worksheetPages .solution-step-panels').count(),2,'all answer groups still present in print');assert(await page.locator('.studio-page:not(.blank)').evaluateAll(nodes=>nodes.length>0&&nodes.every(node=>{const lines=[...node.querySelectorAll(':scope>.page-watermark>span')];return lines.length===3&&lines.every(line=>line.querySelector('.watermark-name')?.textContent==='교사용 검토'&&line.querySelector('.watermark-brand')?.textContent.includes('GFIELD · LETE-ON'));})),'three approved watermark lines required on every nonblank page');assert.equal(await page.locator('.studio-page.blank>.page-watermark').count(),0,'blank page must not be watermarked');checks+=3;
 const pdf=path.join(out,difficulty+'-answers.pdf');await page.pdf({path:pdf,preferCSSPageSize:true,printBackground:true});const actual=+execFileSync('pdfinfo',[pdf],{encoding:'utf8'}).match(/^Pages:\s+(\d+)/m)[1];assert.equal(actual,expected);checks++;
 for(let p=1;p<=actual;p++)execFileSync('pdftoppm',['-f',String(p),'-l',String(p),'-scale-to','1400','-png','-singlefile',pdf,path.join(out,difficulty+'-a4-'+p)]);report.push({difficulty,pages:actual,entries:snapshot.entries.map(e=>({typeId:e.question.typeId,seed:e.question.seed}))});
}
assert.deepEqual(errors,[]);checks++;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({status:'PASS',checks,cases:report,questionCodeChanges:0,remoteWrites:0},null,2));console.log(JSON.stringify({status:'PASS',checks,cases:report}));
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
