'use strict';
// Actual server/client/UI code; all Auth, entitlements, Storage and network responses are synthetic.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module');
const base=path.resolve(__dirname,'..'),TYPE='replace-count-constraints',MOCK='challenge-mock-1',BANK='challenge-bank-'+TYPE;
let checks=0;function ok(value,label){assert(value,label);checks++;}
function serverFactory(){const file=path.join(__dirname,'validate_challenge_private_content.cjs'),source=fs.readFileSync(file,'utf8'),end=source.indexOf('\n(async()=>{');assert(end>0);const context={require:createRequire(file),__dirname,console,Request,Response,TextDecoder,Uint8Array,ArrayBuffer,Blob,atob,Buffer,Date,Set,JSON,process:{argv:[]}};vm.createContext(context);vm.runInContext(source.slice(0,end),context);return vm.runInContext('edge',context);}
async function serverAudit(){
 const edge=serverFactory(),doc=part=>({action:'document',productKey:MOCK,part}),bank=part=>({action:'bank',typeId:TYPE,difficulty:'same',seed:0,part}),source=part=>({action:'source',round:1,section:'main',number:1,part});
 for(const[grants,allowed]of [[[MOCK],['document','source']],[[BANK],['bank','source']],[[],[]],[['challenge-concept-1'],[]],[['challenge-bank-*'],[]]])for(const target of [doc,bank,source])for(const part of ['questions','answers']){const body=target(part),f=edge({grants}),response=await f.request(body);ok(response.status===(allowed.includes(body.action)?200:403),`${grants.join(',')} → ${body.action}/${part}`);if(response.status===403)ok(f.storageReads.length===0,'Unauthorized purchase reads no Storage');}
 for(const grants of [[MOCK],[BANK]]){const f=edge({grants}),response=await f.request({action:'bank',typeId:'split-merge-chain',difficulty:'same',seed:0,part:'answers'});ok(response.status===403,'A different type requires a separate purchase');ok(f.storageReads.length===0,'No cross-type answer read');}
 const revoked=edge({grants:[BANK],revoked:true});ok((await revoked.request(bank('questions'))).status===403,'Revoked similar-study purchase denied');ok(revoked.storageReads.length===0,'Revoked bank causes no Storage read');
}
async function uiAudit(){
 const {chromium}=require('playwright'),browser=await chromium.launch();let mockInvokes=0;const pageErrors=[];
 async function pageFor(grants){const page=await browser.newPage();page.on('pageerror',e=>pageErrors.push(e.message));await page.addInitScript(keys=>{window.__grants=keys;window.__calls=[];},grants);await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin!=='https://purchase-boundary.test')return route.abort();const file=path.resolve(base,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(base+path.sep))return route.abort();if(url.pathname==='/supabase-config.js')return route.fulfill({contentType:'text/javascript',body:'window.GFIELD_HF_SUPABASE_CONFIG={enabled:true};'});if(url.pathname==='/supabase-client.js')return route.fulfill({contentType:'text/javascript',body:`window.GFieldHFSupabase={enabled:()=>true,ready:async()=>({auth:{onAuthStateChange:fn=>window.__authChange=fn,getSession:async()=>({data:{session:{expires_at:Date.now()/1000+3600}}})},functions:{invoke:async(name,{body})=>{window.__calls.push({name,body});if(name==='admin-students')return{data:{students:[{id:'11111111-1111-4111-8111-111111111111',name:'모의 검수 학생',status:'active',permissions:window.__grants}]}};if(name==='challenge-access'&&body.action==='set')return{data:{ok:true}};if(name==='challenge-access')return{data:{verified:true,studentId:'purchase-test',approvedStudentName:'모의 검수 학생',accountStatus:'active',permissionKeys:window.__grants,catalogVersion:window.HFChallengeAccessCatalog.version,verifiedAt:Date.now(),validUntil:Date.now()+60000,deliveryReady:true}};if(name!=='challenge-content')throw Error('Unexpected API');const shared={verified:true,studentId:'purchase-test',approvedStudentName:'모의 검수 학생',validUntil:Date.now()+60000,contentVersion:window.HFChallengePublicCatalog?.contentVersion||'mock'};const id=body.action==='bank'?'mock-variant-'+body.seed:'mock-source-'+body.round+'-'+body.section+'-'+body.number;return{data:{...shared,...(body.action==='document'?{document:{title:'검수용 시험지',styles:['exam.css'],html:'<section class="exam-page">검수용 시험지</section>'}}:body.part==='answers'?{answer:{id,answer:3,answerHtml:'3',solution:'1+2=3입니다.'}}:{question:{id,prompt:'검수용 문제입니다.',problemHtml:'<p>빈칸에 수를 쓰세요.</p>'}})}};}}})};`});try{const data=fs.readFileSync(file),type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'}[path.extname(file)]||'application/octet-stream';return route.fulfill({contentType:type,body:data});}catch{return route.fulfill({status:404,body:''});}});return page;}
 const contentCalls=page=>page.evaluate(()=>window.__calls.filter(c=>c.name==='challenge-content'));
 try{
  const mock=await pageFor([MOCK]);await mock.goto('https://purchase-boundary.test/challenge/studio.html?teacherPreview=1');await mock.waitForFunction(()=>window.HFChallengeStudio);ok(!await mock.evaluate(()=>HFChallengeStudio.isLocalPreview),'A forged teacher-preview query on a remote host is not privileged');ok(await mock.locator('#gradeRows .grade-row').count()===20,'Mock-only purchase opens its 20-question diagnosis');
  await mock.locator('#gradeRows [data-preview]').first().click();await mock.waitForFunction(()=>document.getElementById('questionPreview').open);await mock.click('#revealPreview');await mock.waitForFunction(()=>!document.getElementById('previewAnswer').hidden);ok((await contentCalls(mock)).every(c=>c.body.action==='source'),'Mock-only can review purchased original and original answer, not a variant');await mock.click('#closePreview');
  await mock.locator('#gradeRows input[value=wrong]').first().check();await mock.click('#tab-wrong');ok(await mock.locator('#bankRows input:enabled').count()===0,'Wrong-answer list does not grant similar study');await mock.click('#tab-bank');ok(await mock.locator('#bankRows input:enabled').count()===0,'Mock-only bank selections are locked');ok(await mock.locator('#buildPractice').isDisabled(),'Mock-only cannot build similar worksheet');
  await mock.evaluate(()=>{const input=document.querySelector('#bankRows input');input.disabled=false;input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}));});ok(await mock.evaluate(()=>HFChallengeStudio.getSelection().length)===0,'Forged enabled checkbox does not grant a bank selection');
  const denied=await mock.evaluate(async()=>HFChallengeVariants.generate({round:1,section:'main',number:1,difficulty:'same',seed:0}));ok(denied.status==='held','Direct generation entry point denies mock-only');ok(!(await contentCalls(mock)).some(c=>c.body.action==='bank'),'Denied generation invokes no content API');
  const bank=await pageFor([BANK]);await bank.goto('https://purchase-boundary.test/challenge/studio.html?tab=bank');await bank.waitForFunction(()=>window.HFChallengeStudio);ok(await bank.locator('#gradeRows .grade-row').count()===0&&await bank.locator('#makeDiagnosis').isDisabled(),'Bank-only does not grant mock diagnosis');ok(await bank.locator('#bankRows input:enabled').count()===1,'Exactly one purchased bank type is selectable');await bank.locator('#bankRows input:enabled').check();await bank.fill('#variantCount','1');await bank.click('#buildPractice');await bank.waitForFunction(()=>window.HFChallengeStudio.getSnapshot());ok((await contentCalls(bank)).some(c=>c.body.action==='bank'),'Purchased similar type can generate');
  const docDenied=await bank.evaluate(async()=>{try{await HFChallengeContent.request({action:'document',productKey:'challenge-mock-1',part:'answers'});return false;}catch{return true;}});ok(docDenied,'Bank-only direct mock answer request rejected');ok(!(await contentCalls(bank)).some(c=>c.body.action==='document'),'Bank-only sends no mock document API request');
  await bank.evaluate(()=>window.__grants=[]);await bank.click('#refreshAccess');ok(await bank.locator('#worksheetPanel').isHidden(),'Revocation hides built similar worksheet');await bank.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));ok(await bank.locator('#worksheetPages').innerHTML()==='','Revocation clears printable bank content');
  const exam=await pageFor([BANK]);await exam.goto('https://purchase-boundary.test/challenge/exam.html?round=1&teacherPreview=1');await exam.waitForFunction(()=>window.HFChallengeAccess?.status().verified);ok(await exam.locator('main').isHidden(),'Forged exam URL remains hidden with bank-only purchase');ok((await contentCalls(exam)).length===0,'Forbidden mock URL retrieves no protected content');
  const admin=await pageFor([]);await admin.goto('https://purchase-boundary.test/challenge/admin.html');ok(await admin.evaluate(()=>__calls.length)===0,'Approval page performs no automatic grants or reads');await admin.click('#reload');await admin.selectOption('#student','11111111-1111-4111-8111-111111111111');ok(await admin.locator('input[type=checkbox]:checked').count()===0,'A student with no purchases has no default checks');ok(await admin.locator('#bank-options input').count()===104,'Similar study is 104 separate checkboxes');await admin.locator(`input[data-key="${MOCK}"]`).check();ok(await admin.locator('#bank-options input:checked').count()===0,'Checking mock purchase checks no similar types');await admin.click('#save');await admin.waitForFunction(()=>document.getElementById('status').textContent.includes('저장했습니다'));let writes=await admin.evaluate(()=>__calls.filter(c=>c.name==='challenge-access'));ok(writes.length===1&&writes[0].body.permissionKey===MOCK,'Mock-only save sends exactly the one selected mock grant');await admin.locator(`input[data-key="${BANK}"]`).check();await admin.click('#save');await admin.waitForFunction(()=>__calls.filter(c=>c.name==='challenge-access').length===2);writes=await admin.evaluate(()=>__calls.filter(c=>c.name==='challenge-access'));ok(writes.length===2&&writes[1].body.permissionKey===BANK,'Adding similar study sends only its explicitly selected type');ok(writes.every(c=>!c.body.permissionKey.includes('*')),'No wildcard or bundle approval payload');
  for(const page of [mock,bank,exam,admin])mockInvokes+=await page.evaluate(()=>__calls.length);ok(pageErrors.length===0,'No browser script failures');
 }finally{await browser.close();}
 return mockInvokes;
}
async function run(){await serverAudit();const mockedApiCalls=await uiAudit();return {status:'passed',checks,mockedApiCalls,remoteRequests:0,realStudentWrites:0,scope:'Separate mock/concept/type purchases, original preview exception, no automatic bundle grants'};}
if(require.main===module)run().then(result=>console.log(JSON.stringify(result,null,2))).catch(error=>{console.error(error);process.exitCode=1;});
module.exports={run};
