/* Teacher-only local UI QA. No real student records or remote writes. */
const path=require('path'),fs=require('fs'),http=require('http'),assert=require('assert/strict');
const {execFileSync}=require('child_process');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'hyper-focus/output/qa/challenge-studio');
const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const target=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!target.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(target,(error,data)=>{if(error){res.writeHead(404).end();return;}res.setHeader('Content-Type',mime[path.extname(target)]||'application/octet-stream');res.end(data);});});
const checks=[];function check(name,condition){assert.ok(condition,name);checks.push(name);}
function pdfPages(name){return Number(execFileSync('pdfinfo',[path.join(out,name)],{encoding:'utf8'}).match(/^Pages:\s+(\d+)/m)?.[1]);}
(async()=>{
 fs.mkdirSync(out,{recursive:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',request=>{if(!new URL(request.url()).hostname.match(/^(127\.0\.0\.1|localhost)$/))external.push(request.url());});
 try{
 const url=`http://127.0.0.1:${server.address().port}/hyper-focus/challenge/studio.html?teacherPreview=1`;
 await page.goto(url,{waitUntil:'networkidle'});await page.waitForFunction(()=>!!window.HFChallengeStudio,{}, {timeout:5000}).catch(async error=>{throw new Error(`${error.message} / ${await page.locator('#studioMessage').innerText()} / ${errors.join(';')}`);});
 check('20 pending, not false zero',await page.locator('.grade-row').count()===20 && (await page.locator('#scoreSummary').innerText()).includes('미입력'));
 check('explicit empty count',await page.locator('#variantCount').inputValue()==='');
 await page.screenshot({path:path.join(out,'desktop-grading.png'),fullPage:false});
 const inputs=page.locator('[data-grade]');for(let i=0;i<20;i++)await inputs.nth(i*3+(i<11?1:2)).check();
 check('55 points below60', (await page.locator('#scoreSummary').innerText()).includes('55'));
 await page.locator('#makeDiagnosis').click();check('diagnosis has hierarchy',await page.locator('.diagnosis-table').count()===3);
 check('one more question to60',(await page.locator('#diagnosisPanel').innerText()).includes('1문항'));
 await page.locator('#diagnosisPanel').screenshot({path:path.join(out,'diagnosis.png')});
 await page.locator('#practiceWrong').click();check('wrong-only nine rows',await page.locator('.bank-row').count()===9);
 const wrongIds=await page.locator('[data-select]').evaluateAll(nodes=>nodes.map(n=>n.dataset.select));check('wrong-only source ids',wrongIds.every(id=>Number(id.split('-').at(-1))>11));
 await page.locator('#tab-bank').click();check('fullbank 26 rows',await page.locator('.bank-row').count()===26);
 const eligible=page.locator('[data-select]:not(:disabled)').first();const selectedId=await eligible.getAttribute('data-select');await eligible.check();
 await page.locator('#studioSearch').fill('존재하지않는검색어');check('filter zero while selection preserved',(await page.locator('#resultCount').innerText()).startsWith('0') && (await page.locator('#selectionCount').innerText()).includes('현재 결과 밖 1'));
 await page.locator('#studioSearch').fill('');await page.locator('#studioSearch').evaluate(input=>{input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));input.value='화살표';input.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));});
 check('composition keeps input focus value',await page.locator('#studioSearch').inputValue()==='화살표');
 await page.locator('#studioSearch').evaluate(input=>input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));check('IME committed search',await page.locator('[data-select="challenge-r1-main-13"]').count()===1);await page.locator('#studioSearch').fill('');
 await page.locator(`[data-preview="${selectedId}"]`).last().click();check('no answers in preview DOM',await page.locator('#previewAnswer').innerHTML()==='');check('real prompt preview',(await page.locator('#previewQuestion .studio-prompt').innerText()).length>10);
 await page.locator('#questionPreview').screenshot({path:path.join(out,'question-preview.png')});await page.locator('#revealPreview').click();check('answer only on explicit reveal',await page.locator('#previewAnswer').isVisible());await page.keyboard.press('Escape');check('escape closes preview',!await page.locator('#questionPreview').isVisible());
 await page.locator('#variantCount').fill('3');await page.locator('#buildPractice').click();await page.waitForFunction(()=>!!window.HFChallengeStudio.getSnapshot());const snapshot=await page.evaluate(()=>window.HFChallengeStudio.getSnapshot());check('3 unique snapshot questions',snapshot.entries.length===3 && new Set(snapshot.entries.map(e=>JSON.stringify(e.question.payload))).size===3);
 await page.locator('#printMode').selectOption('both');await page.waitForFunction(()=>document.body.dataset.printReady==='true');check('mode does not regenerate',JSON.stringify(snapshot)===JSON.stringify(await page.evaluate(()=>window.HFChallengeStudio.getSnapshot())));
 const pages=await page.locator('.studio-page').count(),answerIndex=await page.locator('.studio-page').evaluateAll(nodes=>nodes.findIndex(n=>n.classList.contains('answer-front'))+1);check('answercover starts odd physical page',answerIndex%2===1);
 await page.emulateMedia({media:'print'});await page.pdf({path:path.join(out,'worksheet-qa.pdf'),preferCSSPageSize:true,printBackground:true});check('actual PDF page count equals layout',pdfPages('worksheet-qa.pdf')===pages);check('all printpages watermarked except spacer',await page.locator('.studio-page:not(.blank):not([data-watermark])').count()===0);
 const clipped=await page.locator('.studio-page').evaluateAll(nodes=>nodes.flatMap((n,i)=>n.scrollHeight>n.clientHeight+2?[i+1]:[]));check('print no page overflow',clipped.length===0);await page.emulateMedia({media:'screen'});
 await page.locator('#printMode').selectOption('questions');check('questions have no answer content',await page.locator('.studio-answer,.answer-front').count()===0);
 await page.locator('#printMode').selectOption('quick');check('quick answers match snapshot',await page.locator('.quick-answer-list p').count()===3);
 await page.locator('#printMode').selectOption('answers');check('answers only',await page.locator('.studio-problem').count()===0 && await page.locator('.studio-answer').count()===3);
 for(const mode of ['questions','answers','quick']){await page.locator('#printMode').selectOption(mode);await page.waitForFunction(()=>document.body.dataset.printReady==='true');const expected=await page.locator('.studio-page').count();await page.emulateMedia({media:'print'});await page.pdf({path:path.join(out,`${mode}-only-qa.pdf`),preferCSSPageSize:true,printBackground:true});check(`${mode} actual PDF count`,pdfPages(`${mode}-only-qa.pdf`)===expected);await page.emulateMedia({media:'screen'});}
 await page.locator('#closeWorksheet').click();await page.locator('#tab-bank').click();await page.locator('#studioRound').selectOption('4');check('round change retains selection',(await page.locator('#selectionCount').innerText()).includes('현재 결과 밖 1'));
 const examHref=await page.locator('#studioExamLink').getAttribute('href');check('local exam link preserves round and preview',examHref.includes('round=4')&&examHref.includes('teacherPreview=1'));
 await page.screenshot({path:path.join(out,'desktop-bank.png'),fullPage:false});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'mobile-bank.png'),fullPage:true});check('390px no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#tab-grade').click();await page.screenshot({path:path.join(out,'mobile-grade.png'),fullPage:false});check('mobile grade no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#tab-grade').focus();await page.keyboard.press('ArrowRight');check('keyboard tabs',await page.locator('#tab-wrong').getAttribute('aria-selected')==='true');
 await page.locator('#tab-bank').click();await page.locator('#clearSelection').click();await page.setViewportSize({width:1440,height:1100});
 for(const [round,number] of [[1,7],[1,20],[2,18],[3,4]]){await page.locator('#studioRound').selectOption(String(round));await page.locator(`[data-select="challenge-r${round}-main-${String(number).padStart(2,'0')}"]`).check();}
 await page.locator('#variantCount').fill('1');const previousTime=await page.evaluate(()=>window.HFChallengeStudio.getSnapshot().createdAt);await page.locator('#buildPractice').click();await page.waitForFunction(previous=>window.HFChallengeStudio.getSnapshot()?.createdAt!==previous,previousTime);await page.waitForFunction(()=>document.body.dataset.printReady==='true');
 check('dense sources all preserved',await page.evaluate(()=>window.HFChallengeStudio.getSnapshot().entries.length===4));
 await page.locator('#printMode').selectOption('both');await page.waitForFunction(()=>document.body.dataset.printReady==='true');await page.emulateMedia({media:'print'});
 const denseOverflow=await page.locator('.studio-page').evaluateAll(nodes=>nodes.flatMap((n,i)=>{const bounds=n.getBoundingClientRect(),bad=[...n.querySelectorAll('.studio-problem,.studio-answer')].some(child=>child.getBoundingClientRect().bottom>bounds.bottom-25);return n.scrollHeight>n.clientHeight+2||bad?[i+1]:[];}));check('dense A4 content fits',denseOverflow.length===0);
 await page.locator('.studio-page').nth(1).screenshot({path:path.join(out,'dense-dom-second.png')});fs.writeFileSync(path.join(out,'dense-dom.json'),JSON.stringify(await page.locator('.studio-page').evaluateAll(nodes=>nodes.map(node=>({page:node.getBoundingClientRect().toJSON(),head:node.querySelector('.page-brand')?.getBoundingClientRect().toJSON(),questions:[...node.querySelectorAll('.studio-problem')].map(n=>n.getBoundingClientRect().toJSON())}))),null,2));await page.pdf({path:path.join(out,'dense-worksheet-qa.pdf'),preferCSSPageSize:true,printBackground:true});check('dense actual PDF count',pdfPages('dense-worksheet-qa.pdf')===await page.locator('.studio-page').count());await page.emulateMedia({media:'screen'});
 await page.locator('#printMode').selectOption('questions');await page.waitForFunction(()=>document.body.dataset.printReady==='true');await page.setViewportSize({width:390,height:844});await page.locator('#printMode').focus();await page.locator('#worksheetPages .studio-page').first().screenshot({path:path.join(out,'mobile-dense-page.png')});check('dense mobile no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const generatedPrompt=await page.evaluate(()=>window.HFChallengeStudio.getSnapshot().entries[0].question.prompt);await page.locator('[data-enlarge="0"]').click();check('enlarge shows generated question not source',(await page.locator('#previewQuestion .studio-prompt').innerText())===generatedPrompt);check('enlarged art stays legible',await page.locator('#previewQuestion .studio-art').evaluate(node=>node.getBoundingClientRect().width>=660));check('zoom does not overflow whole mobile page',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('preview watermark retained',await page.locator('#previewQuestion').getAttribute('data-watermark')!==null);check('no answer in enlarged preview',await page.locator('#previewAnswer').innerHTML()==='');await page.locator('#questionPreview').screenshot({path:path.join(out,'mobile-zoom.png')});await page.keyboard.press('Escape');
 await page.locator('#printMode').selectOption('answers');await page.waitForFunction(()=>document.body.dataset.printReady==='true');await page.locator('#printMode').selectOption('questions');await page.waitForFunction(()=>document.body.dataset.printReady==='true');check('rapid view changes never regenerate',await page.evaluate(()=>window.HFChallengeStudio.getSnapshot().entries.length===4));
 await page.setViewportSize({width:1440,height:1100});await page.locator('#clearSelection').click();await page.locator('[name="difficulty"][value="hard"]').check();for(const [round,number] of [[1,17],[4,19]]){await page.locator('#studioRound').selectOption(String(round));await page.locator(`[data-select="challenge-r${round}-main-${number}"]`).check();}await page.locator('#variantCount').fill('1');await page.locator('#buildPractice').click();await page.waitForFunction(()=>window.HFChallengeStudio.getSnapshot()?.entries.length===2&&window.HFChallengeStudio.getSnapshot()?.difficulty==='hard');await page.locator('#printMode').selectOption('both');await page.waitForFunction(()=>document.body.dataset.printReady==='true');await page.emulateMedia({media:'print'});check('hard dense conditions fit A4',await page.locator('.studio-page').evaluateAll(nodes=>nodes.every(n=>n.scrollHeight<=n.clientHeight+2)));await page.pdf({path:path.join(out,'hard-dense-qa.pdf'),preferCSSPageSize:true,printBackground:true});check('hard dense actual PDF count',pdfPages('hard-dense-qa.pdf')===await page.locator('.studio-page').count());await page.emulateMedia({media:'screen'});await page.setViewportSize({width:390,height:844});
 await page.locator('#closeWorksheet').click();await page.locator('#jumpAssembly').click();check('mobile assembly jump keyboard focus',await page.locator('#assemblyPanel').evaluate(node=>node===document.activeElement));
 await page.setViewportSize({width:1440,height:1100});await page.locator('#tab-grade').click();await page.locator('#studioRound').selectOption('1');await page.locator('#makeDiagnosis').click();await page.locator('#printDiagnosis').click();await page.waitForFunction(()=>document.body.dataset.printReady==='true');await page.emulateMedia({media:'print'});check('diagnosis print fits',await page.locator('.studio-page').evaluateAll(nodes=>nodes.every(n=>n.scrollHeight<=n.clientHeight+2)));await page.pdf({path:path.join(out,'diagnosis-qa.pdf'),preferCSSPageSize:true,printBackground:true});check('diagnosis actual PDF count',pdfPages('diagnosis-qa.pdf')===await page.locator('.studio-page').count());await page.emulateMedia({media:'screen'});
 await page.locator('#closeWorksheet').click();await page.evaluate(()=>{window.__qaIdentity={studentId:'qa-student-a',name:'검수용 학생 가'};window.HFChallengeAccess={allow:()=>true,watermarkIdentity:()=>window.__qaIdentity};window.dispatchEvent(new CustomEvent('hfchallengeaccesschange',{detail:{reason:'verified'}}));});
 await page.locator('#tab-bank').click();await page.locator('#studioStudent').fill('임의 입력 이름');await page.locator('#buildPractice').click();await page.waitForFunction(()=>window.HFChallengeStudio.getSnapshot()?.approvedIdentity?.studentId==='qa-student-a');await page.waitForFunction(()=>document.body.dataset.printReady==='true');
 check('server approved identity watermark only',await page.locator('.studio-page:not(.blank)').evaluateAll(nodes=>nodes.every(n=>n.dataset.watermark.includes('검수용 학생 가')&&!n.dataset.watermark.includes('임의 입력'))));check('snapshot bound approved student',await page.evaluate(()=>window.HFChallengeStudio.getSnapshot().student.name==='검수용 학생 가'));
 await page.locator('#clearSelection').click();await page.locator('#studioRound').selectOption('1');await page.locator('[data-select="challenge-r1-main-07"]').check();await page.locator('#variantCount').fill('1');await page.locator('#buildPractice').click();await page.waitForFunction(()=>window.HFChallengeStudio.getSnapshot()?.entries.length===1);await page.locator('#printMode').selectOption('both');await page.waitForFunction(()=>document.body.dataset.printReady==='true');check('odd problem page adds duplex spacer',await page.locator('.studio-page.blank').count()===1);check('spacer alone has no watermark',await page.locator('.studio-page.blank[data-watermark]').count()===0);await page.emulateMedia({media:'print'});await page.pdf({path:path.join(out,'approved-identity-duplex-qa.pdf'),preferCSSPageSize:true,printBackground:true});await page.emulateMedia({media:'screen'});
 await page.evaluate(()=>{window.__qaIdentity={studentId:'qa-student-b',name:'검수용 학생 나'};window.dispatchEvent(new CustomEvent('hfchallengeaccesschange',{detail:{reason:'verified'}}));});check('identity change removes old learner output',await page.locator('#worksheetPages').innerHTML()==='' && await page.locator('#worksheetPanel').isHidden());await page.locator('#printMode').evaluate(select=>select.dispatchEvent(new Event('change')));check('old identity snapshot cannot print',await page.evaluate(()=>document.body.dataset.printReady!=='true'));
 await page.evaluate(()=>{window.HFChallengeAccess={allow:()=>false};window.dispatchEvent(new Event('hfchallengeaccesschange'));});await page.locator('#tab-bank').click();check('revoked access blocks preview',await page.locator('[data-preview]:not(:disabled)').count()===0);check('revoked access blocks generation',await page.locator('#buildPractice').isDisabled());
 check('local teacher mode no external requests',external.length===0);
 const linked=await browser.newPage();await linked.goto(url+'&tab=bank&round=2');await linked.waitForFunction(()=>!!window.HFChallengeStudio);check('bank round deep link',await linked.locator('#tab-bank').getAttribute('aria-selected')==='true'&&await linked.locator('#studioRound').inputValue()==='2');await linked.close();
 const locked=await browser.newPage();await locked.route('**/*',route=>{const pathname=new URL(route.request().url()).pathname;if(pathname.endsWith('supabase-config.js'))return route.fulfill({contentType:'text/javascript',body:'window.GFIELD_HF_SUPABASE_CONFIG={enabled:false};'});const target=path.resolve(root,'.'+pathname);if(!target.startsWith(root+path.sep)||!fs.existsSync(target))return route.fulfill({status:404,body:''});return route.fulfill({contentType:mime[path.extname(target)]||'application/octet-stream',body:fs.readFileSync(target)});});await locked.goto('http://studio.invalid/hyper-focus/challenge/studio.html?teacherPreview=1');await locked.waitForFunction(()=>!!window.HFChallengeStudio);check('remote preview parameter fails closed',await locked.locator('.grade-row').count()===0 && await locked.locator('#makeDiagnosis').isDisabled());check('remote exam link never adds teacher preview',!(await locked.locator('#studioExamLink').getAttribute('href')).includes('teacherPreview'));await locked.close();
 check('browser errors none',errors.length===0);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks:checks.length,passed:checks,pages,answerIndex,errors,external},null,2));console.log(JSON.stringify({passed:checks.length,pages,answerIndex,out}));
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;server.close();});
