'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const provider=require('../challenge/variant-provider.js'),extension=require('../challenge/variant-geometry-extension.js');
const more=require('./challenge-more-solvers.cjs'),geometry=require('./supplement-geometry.cjs');
const allPartitions=geometry.partitions(4),canonical=a=>JSON.stringify(a),sum=a=>a.reduce((s,v)=>s+v,0),clone=a=>JSON.parse(JSON.stringify(a));
const normalizeParts=a=>a.map(p=>p.slice().sort((a,b)=>a-b)).sort((a,b)=>a[0]-b[0]);
const lineKey=p=>p.slice(1).map((b,i)=>[p[i].join(),b.join()].sort().join(':')).sort().join('|');
const rotate=p=>p.map(([x,y])=>[2-y,x]);
const markName={circle:'파란 동그라미',triangle:'초록 세모',square:'빨간 네모',star:'노란 별','purple-circle':'보라 동그라미','orange-square':'주황 네모'};
function oppositeAnswer(p){const symbols=[...new Set(p.views.flat())];while(symbols.length<6)symbols.push('unseen'+symbols.length);const [front,top,right]=p.views[0],rest=symbols.filter(v=>![front,top,right].includes(v)),perms=a=>a.length?a.flatMap((x,i)=>perms(a.filter((_,j)=>j!==i)).map(a=>[x,...a])):[[]],faces=['T','B','F','K','R','L'],opposite={T:'B',B:'T',F:'K',K:'F',R:'L',L:'R'};function orientations(s){const seen=new Set,out=[],queue=[s];while(queue.length){const a=queue.shift(),k=faces.map(f=>a[f]).join('|');if(seen.has(k))continue;seen.add(k);out.push(a);queue.push({...a,T:a.F,K:a.T,B:a.K,F:a.B},{...a,T:a.L,R:a.T,B:a.R,L:a.B});}return out;}const answers=new Set;for(const a of perms(rest)){const s={T:top,F:front,R:right,B:a[0],K:a[1],L:a[2]},rotations=orientations(s);if(p.views.every(([f,t,r])=>rotations.some(a=>a.F===f&&a.T===t&&a.R===r)))answers.add(s[opposite[faces.find(f=>s[f]===p.query)]]);}assert.equal(answers.size,1);const symbol=[...answers][0];assert(markName[symbol],'answer marker not observed');return markName[symbol];}
function multiLinks(p){const results=[],adj=Array.from({length:p.w*p.h},(_,n)=>Array.from({length:p.w*p.h},(_,v)=>v).filter(v=>Math.abs(n%p.w-v%p.w)+Math.abs(Math.floor(n/p.w)-Math.floor(v/p.w))===1));function start(i,used,paths){if(i===p.pairs.length){results.push(paths);return;}const[a,b]=p.pairs[i],reserved=p.pairs.flatMap((x,j)=>j===i?[]:x).reduce((mask,n)=>mask|1<<n,used);function extend(n,mask,path){if(n===b){start(i+1,used|mask,[...paths,path]);return;}for(const v of adj[n])if(!(mask&(1<<v))&&!(reserved&(1<<v)))extend(v,mask|1<<v,[...path,v]);}extend(a,1<<a,[a]);}start(0,0,[]);return results;}
function solve(q){const p=q.payload;switch(p.kind){
 case 'geo-cycle':{const n=Array.from({length:p.sequence.length-1},(_,i)=>i+1).find(n=>p.sequence.every((a,i)=>canonical(a)===canonical(p.sequence[i%n])));assert(n);return Array.from({length:p.missingCount},(_,i)=>p.sequence[(p.sequence.length+i)%n]);}
 case 'geo-analogy':assert(p.examples.every(a=>new Set(a).size===a.length));return p.options.findIndex(a=>canonical(a)===canonical(p.query.slice().reverse()))+1;
 case 'geo-matrix':{let x,y;p.matrix.forEach((a,j)=>a.forEach((v,i)=>{if(v===null){x=i;y=j;}}));if(p.query)[y,x]=p.query;const results=new Set,m=clone(p.matrix),n=m.length;function complete(){let empty;for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(m[r][c]===null)empty=[r,c];if(!empty){results.add(m[y][x]);return;}const[r,c]=empty;for(let v=0;v<n;v++)if(!m[r].includes(v)&&!m.some(a=>a[c]===v)){m[r][c]=v;complete();m[r][c]=null;}}complete();assert.equal(results.size,1);return p.options.findIndex(a=>canonical(a)===canonical(p.pairs[[...results][0]]))+1;}
 case 'geo-stars':{const missing=[];for(let mask=0;mask<2**p.slots;mask++){const a=Array.from({length:p.slots},(_,i)=>i).filter(i=>mask&(1<<i)),valid=Array.isArray(p.rules)?p.rules.every(rule=>a.filter(index=>rule.indices.includes(index)).length===rule.choose):a.length===p.choose;if(valid&&!p.shown.some(v=>canonical(a)===canonical(v)))missing.push(a);}assert.equal(missing.length,1);return missing[0];}
 case 'geo-digital':{const answers=p.equations.map(eq=>{const a=[];for(let n=0;n<101;n++){const e=eq.map(t=>t==='blank'?n:t);if((e[1]==='+'?e[0]+e[2]:e[0]-e[2])===e[4])a.push(n);}assert.equal(a.length,1);return a[0];});return sum(answers);}
 case 'geo-rotation':{const possible=[];for(let step=0;step<4;step++){let a=p.examples[0],valid=true;for(const actual of p.examples){if(lineKey(a)!==lineKey(actual))valid=false;for(let t=0;t<step;t++)a=rotate(a);}if(valid)possible.push(step);}assert.equal(possible.length,1);let target=p.examples[0];for(let i=0;i<(p.targetPosition-1)*possible[0];i++)target=rotate(target);const options=p.options.flatMap((a,i)=>lineKey(a)===lineKey(target)?[i+1]:[]);assert.equal(options.length,1);return options[0];}
 case 'geo-fold':{const reflect=([x,y],f)=>f.startsWith('diag-main-')?[y,x]:f.startsWith('diag-anti-')?[p.size-1-y,p.size-1-x]:f==='right-to-left'||f==='left-to-right'?[p.size-1-x,y]:[x,p.size-1-y];let holes=p.holes.map(a=>a.slice());for(let i=p.folds.length-1;i>=0;i--){holes=[...holes,...holes.map(h=>reflect(h,p.folds[i]))];holes=[...new Map(holes.map(h=>[canonical(h),h])).values()];}const answer=holes.sort((a,b)=>a[1]-b[1]||a[0]-b[0]).map(([x,y])=>y*p.size+x);assert.equal(answer.length,p.holes.length*2**p.folds.length);return answer;}
 case 'geo-cubes':return p.heights.flat().reduce((total,height)=>total+height,0);
 case 'geo-route-count':return require('./challenge-priority-solvers.cjs').solve({...p,typeId:'priority-route-count',start:[0,0],end:[p.columns,p.rows]});
 case 'geo-top':{const occupied=p.heights.flatMap((a,y)=>a.flatMap((h,x)=>h?[y*3+x]:[]));const valid=p.options.flatMap((a,i)=>canonical(a)===canonical(occupied)?[i+1]:[]);assert.equal(valid.length,1);return valid[0];}
 case 'geo-stack':return more.solve({...p,kind:'bricks-stack'});
 case 'geo-bricks':return more.solve({...p,kind:'bricks'});
 case 'geo-links':case 'geo-walk':{const solutions=p.kind==='geo-links'?multiLinks(p):more.pathsFor({...p,kind:'walk'});assert.equal(solutions.length,1);return solutions[0];}
 case 'geo-tiles':{const solutions=more.tileSolutions(p.target),mapping=p.options.map(a=>more.tileBases.findIndex(b=>geometry.shapeKey(a)===geometry.shapeKey(b))+1),answers=[...new Map(solutions.map(s=>{const a=s.pair.map(id=>mapping.indexOf(id)+1).sort((a,b)=>a-b);return[canonical(a),a];})).values()].filter(a=>a.every(n=>n>0));assert.equal(answers.length,1);return answers[0];}
 case 'geo-partition':{const choices=allPartitions.filter(t=>t.parts.every(a=>p.apples.filter(i=>a.includes(i)).length===1&&p.berries.filter(i=>a.includes(i)).length===1));assert.equal(choices.length,1);return normalizeParts(choices[0].parts);}
 case 'geo-opposite':return oppositeAnswer(p);
 case 'geo-symbol-roll':{const value=more.roll({top:1,front:2,right:3,moves:p.moves});assert.equal(value,1);return markName[p.mark];}
 case 'geo-quadrilaterals':return geometry.quadrilaterals(p.points,p.segments).length;
 case 'geo-pattern':{const area=t=>Math.abs(t.reduce((s,p,i)=>s+p[0]*t[(i+1)%3][1]-p[1]*t[(i+1)%3][0],0))/2;const big=sum(p.target.map(area)),red=sum(p.redPiece.map(area)),green=sum(p.greenPiece.map(area));assert(p.target.every(t=>area(t)===green));assert.equal(new Set(p.target.map(t=>t.map(String).sort().join('|'))).size,p.target.length);assert(p.redPiece.every(t=>p.target.some(a=>canonical(a)===canonical(t))));return(big-red)/green;}
 default:throw Error('Missing independent geometry solver '+p.kind);
}}
function verifyFoldGeometry(q){
 const p=q.payload,rule=fold=>{
  if(fold==='right-to-left')return point=>.5-point.x;
  if(fold==='left-to-right')return point=>point.x-.5;
  if(fold==='bottom-to-top')return point=>.5-point.y;
  if(fold==='top-to-bottom')return point=>point.y-.5;
  if(fold==='diag-main-lower-to-upper')return point=>point.x-point.y;
  if(fold==='diag-main-upper-to-lower')return point=>point.y-point.x;
  if(fold==='diag-anti-upper-left-to-lower-right')return point=>point.x+point.y-1;
  if(fold==='diag-anti-lower-right-to-upper-left')return point=>1-point.x-point.y;
  throw Error('unknown fold '+fold);
 },clip=(polygon,keep)=>{const out=[];for(let i=0;i<polygon.length;i++){const a=polygon[i],b=polygon[(i+1)%polygon.length],da=keep(a),db=keep(b);if(da>=-1e-9)out.push(a);if((da>1e-9&&db< -1e-9)||(da< -1e-9&&db>1e-9)){const t=da/(da-db);out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});}}return out;},area=polygon=>Math.abs(polygon.reduce((total,a,index)=>{const b=polygon[(index+1)%polygon.length];return total+a.x*b.y-b.x*a.y;},0))/2;
 let polygon=[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}],expected=[];for(const fold of p.folds){expected.push(polygon.map(point=>[point.x,point.y]));polygon=clip(polygon,rule(fold));}expected.push(polygon.map(point=>[point.x,point.y]));
 assert.deepEqual(p.stagePolygons,expected,'fold stages must be the exact retained half-plane polygons');
 assert.deepEqual(p.stagePolygons.map(stage=>area(stage.map(([x,y])=>({x,y})))),Array.from({length:p.folds.length+1},(_,index)=>1/2**index),'each real fold must halve the retained paper polygon');
 for(const [x,y] of p.holes){const point={x:(x+.5)/p.size,y:(y+.5)/p.size};assert(p.folds.every(fold=>rule(fold)(point)>1e-6),'hole must lie inside the final folded paper and off every crease');}
 assert(q.problemHtml.includes('data-fold-engine="half-plane-mirror"'),'Fields half-plane folding engine marker missing');
 assert.equal((q.problemHtml.match(/data-fold-stage=/g)||[]).length,p.folds.length+1,'every real fold stage must be visible');
 assert.equal((q.problemHtml.match(/data-fold-arrow=/g)||[]).length,p.folds.length,'every fold needs a curved direction arrow');
 assert.equal((q.problemHtml.match(/data-fold-hole=/g)||[]).length,p.holes.length,'only the holes on the final folded paper should be shown');
 for(const fold of p.folds)assert(q.problemHtml.includes(`data-fold-direction="${fold}"`),'missing visible fold direction '+fold);
}
function topVisible(p){const bricks=p.heights.flatMap((a,y)=>a.flatMap((h,x)=>Array.from({length:h},(_,z)=>[x,y,z])));for(let y=0;y<3;y++)for(let x=0;x<3;x++){const h=p.heights[y][x];if(!h)continue;const origin=[x+.5,y+.5,h];for(const b of bricks){const enter=Math.max(...b.map((v,i)=>v-origin[i])),leave=Math.min(...b.map((v,i)=>v+1-origin[i]));assert(!(leave>Math.max(enter,1e-8)),'answer-bearing top face is occluded');}}}
function visibleBrickOwners(bricks){const visible=[];for(let owner=0;owner<bricks.length;owner++){const b=bricks[owner];let found=false;for(let axis=0;axis<3&&!found;axis++){const other=[0,1,2].filter(k=>k!==axis);for(let a=0;a<b[other[0]+3]*3&&!found;a++)for(let c=0;c<b[other[1]+3]*3&&!found;c++){const point=b.slice(0,3);point[axis]+=b[axis+3];point[other[0]]+=(a+.5)/3;point[other[1]]+=(c+.5)/3;const blocked=bricks.some((v,i)=>i!==owner&&Math.min(...v.slice(0,3).map((x,k)=>x+v[k+3]-point[k]))>Math.max(1e-7,...v.slice(0,3).map((x,k)=>x-point[k])));if(!blocked)found=true;}}if(found)visible.push(owner);}return visible;}
async function run(){let checks=0,negativeChecks=0;const rows=provider.list().filter(row=>extension.supports(provider.getSource(row))),evidence=[];assert.equal(rows.length,25);for(const row of rows){const source=provider.getSource(row),before=canonical(source),forms=new Set;for(const difficulty of ['easy','same','hard']){if(!extension.levels(source)[difficulty]){assert.throws(()=>extension.generate(source,difficulty,0));continue;}for(let seed=0;seed<30;seed++){const q=extension.generate(source,difficulty,seed);assert.deepEqual(q.answer,solve(q),row.key+' '+difficulty+' '+seed);assert.deepEqual(q,extension.generate(source,difficulty,seed));assert.equal(q.typeId,source.typeId);assert(!/undefined|NaN/.test(q.problemHtml));assert.equal(q.evidence.release,'locked','implementer cannot approve');assert.equal(q.learnerFit.learner_stage,'6세 유치원');for(const k of ['language','representations','prerequisites','reasoning-load','response-mode'])assert(q.learnerFit[k]&&q.evidence.criteria.includes(k));if(q.payload.kind==='geo-top')topVisible(q.payload);if(q.payload.kind==='geo-fold')verifyFoldGeometry(q);if(q.payload.kind==='geo-bricks')assert.equal(visibleBrickOwners(q.payload.bricks).length,q.payload.bricks.length,'visible-only brick type contains a hidden block');if(q.payload.kind==='geo-tiles'&&q.payload.requiresBothTransforms){const fits=more.tileSolutions(q.payload.target),norm=a=>{const x=Math.min(...a.map(p=>p[0])),y=Math.min(...a.map(p=>p[1]));return a.map(([u,v])=>[u-x,v-y]).sort((a,b)=>a[1]-b[1]||a[0]-b[0]);};assert(fits.every(s=>s.parts.every((a,i)=>canonical(norm(a))!==canonical(norm(more.tileBases[s.pair[i]-1])))),'hard tile can be filled without transforming both pieces');}if(q.payload.kind==='geo-stack'){assert(q.payload.bricks.some(b=>b[5]===2),'standing bricks lost');assert(q.payload.bricks.some(b=>b[3]===2||b[4]===2),'lying bricks lost');const broken=clone(q.payload);broken.bricks.pop();assert.throws(()=>more.solve({...broken,kind:'bricks-stack'}));negativeChecks++;}const broken=clone(q);broken.answer='incorrect answer';assert.notDeepEqual(broken.answer,solve(broken));negativeChecks++;checks++;forms.add(canonical(q.payload));}}assert.equal(canonical(source),before);assert(forms.size>1,row.key+' has no variation');evidence.push({key:row.key,typeId:row.typeId,levels:extension.levels(source),distinctModels:forms.size,learner_stage:'6세 유치원',gate:'learner-fit',criteria:{language:'한국어 지시문·보기 번호를 사용하며 학년 용어 계산 없음',representations:extension.generate(source,'same',17).payload.kind,prerequisites:'세기·간단한 더하기와 빼기·눈과 손으로 모양 비교; 공식과 곱셈식 요구 없음','reasoning-load':extension.notes(source),'response-mode':'source prompt의 색칠·연결·분할·계수·번호 쓰기 유지'},release:'locked',independentReview:'parent pending'});}
 for(const seed of [-1,1.2,NaN,4294967296])assert.throws(()=>extension.generate(provider.getSource(rows[0]),'same',seed));assert.equal(extension.supports({typeId:'not-registered',payload:{}}),false);assert.throws(()=>extension.generate(provider.getSource(rows[0]),'unknown',1));
const out=path.resolve(__dirname,'../output/qa/challenge-geometry-extension');fs.mkdirSync(out,{recursive:true});const report={passed:true,occurrences:rows.length,checks,negativeChecks,learner_stage:'6세 유치원',release:'locked pending parent independent review',evidence};fs.writeFileSync(path.join(out,'math-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,evidence:undefined}));if(process.argv.includes('--render'))await render(rows,out);if(process.argv.includes('--symbol-render'))await render(rows.filter(row=>row.typeId==='r4-extra-6'),path.join(out,'symbol-final'),[0,41]);return report;}
async function render(rows,out,seeds=[41]){fs.mkdirSync(out,{recursive:true});const{chromium}=require('playwright'),http=require('node:http'),rootDir=path.resolve(__dirname,'../challenge');const server=http.createServer((req,res)=>{const file=path.resolve(rootDir,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(rootDir+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.png')?'image/png':file.endsWith('.css')?'text/css':'text/javascript');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`,browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1000,height:900},deviceScaleFactor:1});const samples=rows.flatMap(row=>{const source=provider.getSource(row);return ['easy','same','hard'].filter(d=>extension.levels(source)[d]).flatMap(d=>seeds.map(seed=>({row:{...row,key:row.key+'-'+d+(seeds.length>1?'-seed'+seed:'')},q:extension.generate(source,d,seed)})));}),errors=[],screens=[];page.on('pageerror',e=>errors.push(e.message));const css=`*{box-sizing:border-box}body{margin:0;background:#edf0f2;color:#243e50;font-family:'Malgun Gothic',sans-serif}article{position:relative;width:min(760px,100%);padding:28px;margin:20px auto;background:white;break-after:page}header{border-bottom:1px solid #78909e;display:flex;align-items:center;gap:24px;margin-bottom:22px}header img{width:105px}header small{display:block;letter-spacing:.2em}h2{font-size:18px}p{font-size:18px;line-height:1.7;white-space:pre-line}.challenge-visual{width:100%;height:auto;max-height:none}.wm{position:absolute;inset:48% 0 auto;text-align:center;transform:rotate(-23deg);opacity:.065;pointer-events:none;font-size:34px}footer{border-top:1px solid #b4c1c7;padding-top:10px;margin-top:20px;color:#687c89;font-size:12px}@media(max-width:450px){article{padding:16px;margin:0 auto 16px}p{font-size:16px}}@page{size:A4;margin:12mm}@media print{body{background:white}article{width:186mm;height:272mm;margin:0;padding:10mm 5mm}header{margin-bottom:7mm}p{font-size:14pt}.wm{opacity:.065}footer{position:absolute;bottom:8mm;left:5mm;right:5mm}}`;
 const article=({row,q},answer=false)=>`<article><div class="wm">GFIELD · LETE-ON</div><header><div><img src="${base}assets/gfield-logo.png"><small>LETE-ON</small></div><h2>2026년 9월 챌린지 대비<br>${row.round}회 ${row.section==='extra'?'추가 ':''}${row.number}번 · ${answer?'풀이':'유사문제 검수'}</h2></header><p>${q.prompt}</p>${answer?`<p>${q.answerHtml}</p>${q.solutionDiagram||''}<p>${q.solution}</p>`:q.problemHtml}<footer>교사용 검토 · GFIELD / LETE-ON</footer></article>`;
 try{for(const sample of samples){for(const width of [1000,390]){
  await page.setViewportSize({width,height:950});await page.setContent(`<base href="${base}"><style>${css}</style>${article(sample)}`,{waitUntil:'networkidle'});
  await page.locator('article').screenshot({path:path.join(out,`${sample.row.key}-${width}.png`)});
  const outside=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,svg:[...document.querySelectorAll('svg.geometry-extension')].flatMap(svg=>{
   const a=svg.getBoundingClientRect();return [...svg.children].filter(n=>n.getBBox).flatMap(n=>{
    let b=n.getBoundingClientRect();
    // Nested sprite SVG clips an oversized atlas; check its viewport, not the atlas bounding box.
    if(n.tagName.toLowerCase()==='svg'&&n.getAttribute('overflow')==='hidden'){
     const m=svg.getScreenCTM(),tl=new DOMPoint(n.x.baseVal.value,n.y.baseVal.value).matrixTransform(m),br=new DOMPoint(n.x.baseVal.value+n.width.baseVal.value,n.y.baseVal.value+n.height.baseVal.value).matrixTransform(m);
     b={left:tl.x,top:tl.y,right:br.x,bottom:br.y,width:br.x-tl.x,height:br.y-tl.y};
    }
    return b.width&&b.height&&(b.left<a.left-3||b.right>a.right+3||b.top<a.top-3||b.bottom>a.bottom+3)?[n.tagName+':'+n.textContent]:[];
   });
  })}));
  assert.equal(outside.overflow,false,sample.row.key+' mobile overflow');assert.deepEqual(outside.svg,[],sample.row.key+' clipped SVG at '+width);screens.push({key:sample.row.key,width,overflow:false});
 }}
 await page.setViewportSize({width:900,height:1200});await page.setContent(`<base href="${base}"><style>${css}</style>${samples.map(s=>article(s)).join('')}${samples.map(s=>article(s,true)).join('')}`,{waitUntil:'networkidle'});await page.emulateMedia({media:'print'});const clipped=await page.evaluate(()=>[...document.querySelectorAll('article')].flatMap((a,i)=>{const b=a.getBoundingClientRect(),f=a.querySelector('footer').getBoundingClientRect();return [...a.children].filter(n=>!n.matches('footer,.wm')).some(n=>n.getBoundingClientRect().bottom>f.top-5)?[i+1]:[];}));assert.deepEqual(clipped,[],'A4 content overlaps footer');await page.pdf({path:path.join(out,'geometry-questions-and-answers.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'render-report.json'),JSON.stringify({passed:true,screens,a4Pages:samples.length*2,clipped,errors,approvedStudentData:false},null,2));console.log(JSON.stringify({render:true,screens:screens.length,a4Pages:samples.length*2,clipped}));}finally{await browser.close();server.close();}}
if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1;});module.exports={solve,run,topVisible};
