'use strict';
// Layout fixtures select real generator results without editing source or real student data.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const V=require('../challenge/variant-provider.js'),root=path.resolve(__dirname,'../..'),out=path.join(root,'hyper-focus/output/qa/challenge-long-solutions-print');
const runtime='C:/Users/user/.cache/codex-runtimes/codex-primary-runtime',python=path.join(runtime,'dependencies/python/python.exe'),marker=path.join(runtime,'plugins/openai-primary-runtime/plugins/pdf/skills/pdf/container_tools/mark_artifact_operation_started.mjs');
const longest=types=>{let best=null;for(const ref of V.list().filter(x=>types.includes(x.typeId)))for(const difficulty of ['easy','same','hard'])for(let seed=0;seed<100;seed++){const q=V.generate({...ref,difficulty,seed}).question;if(!best||q.solution.length>best.length)best={ref,difficulty,seed,length:q.solution.length,q};}return best;};
const fixtures=[longest(['replace-magic-triangle']),longest(['r2-fruit-logic-table','r4-main-19'])],fixed=Object.fromEntries(fixtures.map(x=>[x.ref.key,{seed:x.seed,difficulty:x.difficulty}]));
const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const target=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!target.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(target,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',mime[path.extname(target)]||'application/octet-stream');res.end(data);});});
const normalize=s=>String(s).replace(/\s/g,'');
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let checks=0,marked=process.argv.includes('--artifact-marked');const report={status:'RUNNING',fixtures:fixtures.map(({ref,difficulty,seed,length})=>({typeId:ref.typeId,difficulty,seed,length})),cases:[],fixtureMethod:'Only generator difficulty/seed arguments are pinned; real generated content and actual Studio rendering are unchanged. Deliberately mixed difficulties stress pagination.',watermarkIdentity:'Explicit localhost teacher preview, not an authenticated student test',remoteWrites:0};
try{
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname!=='127.0.0.1')return route.abort();if(url.pathname.endsWith('/variant-provider.js')){const original=await route.fetch(),suffix=`;{const original=window.HFChallengeVariants,fixed=${JSON.stringify(fixed)};window.HFChallengeVariants=Object.freeze({...original,generate(args){const selected=fixed[[args.round,args.section,args.number].join('-')];return original.generate(selected?{...args,...selected}:args);}});}`;return route.fulfill({response:original,body:(await original.text())+suffix});}return route.continue();});
 await page.goto(`http://127.0.0.1:${server.address().port}/hyper-focus/challenge/studio.html?teacherPreview=1&tab=bank`);await page.waitForFunction(()=>!!window.HFChallengeStudio);assert(await page.evaluate(()=>HFChallengeStudio.isLocalPreview));checks++;
 await page.locator('[name=difficulty][value=hard]').check();for(const fixture of fixtures){await page.locator('#studioRound').selectOption(String(fixture.ref.round));const id=`challenge-r${fixture.ref.round}-${fixture.ref.section}-${String(fixture.ref.number).padStart(2,'0')}`;await page.locator(`[data-select="${id}"]`).check();}
 await page.locator('#variantCount').fill('1');await page.locator('#buildPractice').click();await page.waitForFunction(()=>HFChallengeStudio.getSnapshot()?.entries.length===2);const snapshot=await page.evaluate(()=>HFChallengeStudio.getSnapshot());assert.equal(snapshot.entries.length,2);
 for(let i=0;i<2;i++)assert.deepEqual(snapshot.entries[i].question,fixtures[i].q,'Fixture must be the actual source generator result');checks+=3;
 for(const mode of ['answers','questions']){
  await page.emulateMedia({media:'screen'});await page.setViewportSize({width:1280,height:1000});await page.locator('#printMode').selectOption(mode);
  await page.waitForFunction(()=>document.body.dataset.printReady==='true'||document.querySelector('#studioMessage').textContent.includes('인쇄 구성을 확인해야'));
  const ready=await page.evaluate(()=>document.body.dataset.printReady==='true');
  if(!ready){report.status='BLOCKED';report.blocker=await page.locator('#studioMessage').innerText();report.blockedMode=mode;for(const width of [1280,390]){await page.setViewportSize({width,height:1000});await page.screenshot({path:path.join(out,`blocked-${mode}-${width}.png`),fullPage:true});}break;}
  checks++;const selector=mode==='answers'?'.studio-answer':'.studio-problem';
  for(const width of [1280,390]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow '+width);checks++;
   const text=normalize(await page.locator('#worksheetPages').innerText());for(let i=0;i<fixtures.length;i++){if(mode==='answers'){const actual=await page.locator(`#worksheetPages [data-answer-entry="${i}"] [data-solution-text]`).evaluateAll(nodes=>nodes.map(n=>n.textContent).join(''));assert.equal(actual,fixtures[i].q.solution,'DOM must preserve every solution character '+width);}else assert(text.includes(normalize(fixtures[i].q.prompt)),'DOM missing full prompt '+width);}checks+=2;
   await page.locator('#worksheetPages').screenshot({path:path.join(out,`${mode}-${width}.png`),style:'.skip-link{visibility:hidden!important}'});
  }
  await page.emulateMedia({media:'print'});await page.setViewportSize({width:1280,height:1200});await page.evaluate(()=>document.fonts.ready);
  const pages=await page.locator('.studio-page').evaluateAll(nodes=>nodes.map(n=>({text:n.innerText,watermark:n.dataset.watermark,height:n.clientHeight,scroll:n.scrollHeight,width:n.clientWidth,scrollWidth:n.scrollWidth,fragments:[...n.querySelectorAll('[data-answer-entry]')].map(a=>({index:+a.dataset.answerEntry,title:a.querySelector('h3').textContent,continued:a.classList.contains('studio-answer-continuation'),text:a.querySelector('[data-solution-text]')?.textContent||'',fontSize:a.querySelector('[data-solution-text]')?parseFloat(getComputedStyle(a.querySelector('[data-solution-text]')).fontSize):null}))})));assert(pages.length);assert(pages.every(p=>p.scroll<=p.height+2&&p.scrollWidth<=p.width+2),'A4 element overflow');checks++;
  const outside=await page.locator('.studio-page').evaluateAll(nodes=>nodes.flatMap(p=>{const b=p.getBoundingClientRect(),walker=document.createTreeWalker(p,NodeFilter.SHOW_TEXT),bad=[];while(walker.nextNode()){if(!walker.currentNode.textContent.trim())continue;const range=document.createRange();range.selectNodeContents(walker.currentNode);for(const r of range.getClientRects())if(r.width&&(r.left<b.left-1||r.right>b.right+1||r.bottom>b.bottom-18))bad.push(walker.currentNode.textContent);}return bad;}));assert.deepEqual(outside,[],'Text outside print page or bottom margin');checks++;
  assert(pages.every(p=>p.watermark&&p.watermark.includes('LETE-ON')&&p.watermark.includes('교사용 검토')));checks++;
  if(!marked){execFileSync(process.execPath,[marker,'--operation-kind','create','--expected-output-count','2','--output-format','pdf']);marked=true;}
  const pdf=path.join(out,`${mode}.pdf`);await page.pdf({path:pdf,preferCSSPageSize:true,printBackground:true});
  const extracted=JSON.parse(execFileSync(python,['-c','import json,sys; from pypdf import PdfReader; d=PdfReader(sys.argv[1]); print(json.dumps([p.extract_text() or "" for p in d.pages],ensure_ascii=True))',pdf],{encoding:'utf8',maxBuffer:2e7}));assert.equal(extracted.length,pages.length,'Unexpected spill PDF page');checks++;
  for(let i=0;i<extracted.length;i++){const txt=normalize(extracted[i]);assert(txt.includes('LETE-ON')&&txt.includes('G.FIELD')&&txt.includes('교사용검토'),'PDF watermark text missing '+i);checks++;assert(txt.includes(String(i+1)),'Page folio missing');checks++;execFileSync('pdftoppm',['-f',String(i+1),'-l',String(i+1),'-scale-to','1600','-png','-singlefile',pdf,path.join(out,`${mode}-a4-${i+1}`)]);}
  if(mode==='answers'){
   for(let p=0;p<pages.length;p++)for(const fragment of pages[p].fragments){assert(normalize(extracted[p]).includes(normalize(fragment.text)),'PDF paragraph fragment missing');assert(fragment.fontSize===null||fragment.fontSize>=14,'Do not shrink solution font');assert(fragment.title.startsWith((fragment.index+1)+'번'),'Original answer number lost');if(fragment.continued)assert(fragment.title.includes('계속'),'Continuation must be labeled');checks+=4;}
   for(let i=0;i<fixtures.length;i++){const fragments=pages.flatMap(p=>p.fragments).filter(f=>f.index===i);assert.equal(fragments.map(f=>f.text).join(''),fixtures[i].q.solution,'Printed fragments do not reconstruct entire source');assert.equal(fragments.filter(f=>!f.continued).length,1);checks+=2;}
  }else{const combined=normalize(extracted.join(''));for(const fixture of fixtures){assert(combined.includes(normalize(fixture.q.prompt)),'Actual PDF is missing source prompt');checks++;}}
  report.cases.push({mode,pages:pages.length,articles:await page.locator(selector).count(),continuations:pages.flatMap(p=>p.fragments).filter(f=>f.continued).length,pdf,watermarkedPages:extracted.length});
 }
 assert.deepEqual(errors,[]);checks++;if(report.status==='RUNNING')report.status='PASS';report.checks=checks;
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
