/* Independent answer enumeration; no production solver or hidden answer is used as an oracle. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const provider=require('../challenge/variant-provider.js'),levels=require('../challenge/variant-core-levels.js');
let checks=0,generated=0;const specimens=[],coverage=[];
const eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;},ok=(v,label)=>{assert.ok(v,label);checks++;};
function permutations(a){if(!a.length)return [[]];const result=[];for(let i=0;i<a.length;i++)for(const tail of permutations(a.slice(0,i).concat(a.slice(i+1))))result.push([a[i],...tail]);return result;}
const sum=a=>a.reduce((a,b)=>a+b,0);
function solve(q){const p=q.payload;
 if(p.kind==='core-balance'){ok(q.prompt.includes(`배로 바꾸면 ${p.pearsPerApple+1}개`),'visible intermediate, not final answer');const valid=[];for(let apple=1;apple<=12;apple++)for(let pear=1;pear<=6;pear++)if(apple===p.pearsPerApple*pear&&pear===p.berriesPerPear)valid.push(apple+pear);eq(valid.length,1);return valid[0];}
 if(p.kind==='core-triangle'){if(q.difficulty==='hard'){ok(p.targets[0].left-p.targets[0].right!==p.targets[1].left-p.targets[1].right,'non-identical target transformation');ok(q.answer!==p.targets[0].center,'cannot copy target center');}const rules=[t=>t.top+t.left===t.center+t.right,t=>t.top+t.right===t.center+t.left,t=>t.top+t.center===t.left+t.right];eq(rules.filter(f=>p.examples.every(f)).length,1);const answers=new Set();for(let circle=0;circle<=30;circle++)for(let box=0;box<=30;box++){const good=p.targets.every(t=>{const get=k=>t[k]==='○'?circle:t[k]==='□'?box:t[k];return get('top')+get('left')===get('center')+get('right');});if(good)answers.add(box);}eq(answers.size,1);if(q.difficulty==='easy')ok(q.prompt.includes('합과 같습니다'));return [...answers][0];}
 if(p.kind==='core-rotation'){const key=a=>a.map(([y,x])=>y*3+x).sort((a,b)=>a-b).join(','),rot=a=>a.map(([y,x])=>[x,2-y]);const pairs=[];for(let a=0;a<4;a++)for(let b=a+1;b<4;b++){let cells=p.options[a];let same=false;for(let n=0;n<4;n++){same ||= key(cells)===key(p.options[b]);cells=rot(cells);}if(same)pairs.push([a+1,b+1]);}eq(pairs.length,1);eq(p.options.map(a=>a.length),[3,3,3,3]);return pairs[0];}
 if(p.kind==='core-mountain'){let n=0;for(let row=1;row<=p.figure;row++){const line=[];for(let v=1;v<=row;v++)line.push(v);for(let v=row-1;v;v--)line.push(v);n+=line.filter(v=>p.digits.includes(v)).length;}return n;}
 if(p.kind==='core-apartment'){const valid=permutations(p.people).filter(order=>p.clues.every(c=>{const a=order.indexOf(c.a)+1,b=order.indexOf(c.b)+1;switch(c.kind){case'at':return a===c.floor;case'notAt':return a!==c.floor;case'above':return a>b;case'adjacentAbove':return a-b===1;case'gap':return a-b===c.gap;default:throw Error(c.kind);}}));eq(valid.length,1);if(q.difficulty==='hard')ok(p.clues.every(c=>c.kind!=='at'));return valid[0];}
 if(p.kind==='core-pyramid'){const values=permutations(p.cards).filter(a=>!p.fixed||a[p.fixed.index]===p.fixed.value).map(a=>{while(a.length>1){const b=[];for(let i=0;i<a.length-1;i++)b.push(a[i]+a[i+1]);a=b;}return a[0];}),lo=Math.min(...values),hi=Math.max(...values);ok(hi<=100,'child-sized sums');ok(q.solution.includes(`${hi}${p.operation==='sum'?'+':'−'}${lo}=`));eq(p.cards.length,q.difficulty==='hard'?5:4);return p.operation==='sum'?hi+lo:hi-lo;}
 if(p.kind==='core-code'){ok(p.examples.every(e=>e.value!==p.encode),'encode cannot copy any example');ok(p.examples.every(e=>JSON.stringify(e.cells)!==JSON.stringify(p.shown)),'decode cannot copy any example');const a=p.examples.map(e=>[...e.cells.map(Number),e.value]);for(let i=0;i<4;i++){const j=a.findIndex((row,j)=>j>=i&&Math.abs(row[i])>1e-8);ok(j>=i,'visible matrix full rank');[a[i],a[j]]=[a[j],a[i]];const pivot=a[i][i];for(let c=i;c<5;c++)a[i][c]/=pivot;for(let row=0;row<4;row++)if(row!==i){const f=a[row][i];for(let c=i;c<5;c++)a[row][c]-=f*a[i][c];}}const weights=a.map(row=>row[4]),matches=[];for(let mask=0;mask<16;mask++){let value=0;const cells=[];for(let i=0;i<4;i++)if(mask&(1<<i)){value+=weights[i];cells.push(i+1);}if(value===p.encode)matches.push(cells);}eq(matches.length,1);return [matches[0],sum(weights.filter((_,i)=>p.shown[i]))];}
 if(p.kind==='core-group'){const sequence=[];let count=0,colorIndex=0;for(let i=0;i<p.position;i++){count+=p.step;sequence.push([p.colors[p.period[colorIndex]],count]);colorIndex++;if(colorIndex===p.period.length)colorIndex=0;}return sequence.at(-1);}
 if(p.kind==='roll'){
  const state={top:p.top,bottom:7-p.top,south:p.front,north:7-p.front,east:p.right,west:7-p.right},values=Object.values(state),opposite={R:'L',L:'R',U:'D',D:'U'},delta={R:[1,0],L:[-1,0],U:[0,-1],D:[0,1]};
  eq(new Set(values).size,6,'six distinct die faces');eq(state.top+state.bottom,7);eq(state.south+state.north,7);eq(state.east+state.west,7);ok(q.problemHtml.includes('<circle'),'visible dice pips');ok(q.prompt.includes('합이 7'),'opposite-face rule is visible');
  eq(p.moves.length,q.difficulty==='hard'?5:3,'reasoning evidence is move count');ok(p.moves.slice(1).every((move,i)=>opposite[move]!==p.moves[i]),'no immediate inverse cancellation');
  const turns=p.moves.slice(1).filter((move,i)=>move!==p.moves[i]).length;ok(turns>=(q.difficulty==='hard'?3:2),'enough direction changes');ok(new Set(p.moves).size>=(q.difficulty==='hard'?3:2),'enough distinct directions');
  let x=0,y=0;const visited=new Set(['0,0']);for(const move of p.moves){x+=delta[move][0];y+=delta[move][1];ok(!visited.has(`${x},${y}`),'path does not revisit an earlier square');visited.add(`${x},${y}`);}
  let current=state;for(const move of p.moves){const s=current;if(move==='R')current={top:s.west,bottom:s.east,south:s.south,north:s.north,east:s.top,west:s.bottom};else if(move==='L')current={top:s.east,bottom:s.west,south:s.south,north:s.north,east:s.bottom,west:s.top};else if(move==='U')current={top:s.south,bottom:s.north,south:s.bottom,north:s.top,east:s.east,west:s.west};else if(move==='D')current={top:s.north,bottom:s.south,south:s.top,north:s.bottom,east:s.east,west:s.west};else throw Error('Unknown roll '+move);}
  const answer=p.query==='bottom'?current.bottom:current.top;ok(answer!==(p.query==='bottom'?state.bottom:state.top),'destination face is not the visibly unchanged starting answer');return answer;
 }
 if(p.kind==='core-net'){// Independent 3D right-hand frames: columns are local horizontal, vertical, outward axes.
  const dot=(a,b)=>sum(a.map((v,i)=>v*b[i])),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
  const rotate=(v,axis,sign)=>cross(axis,v).map((n,i)=>(sign*n+axis[i]*dot(axis,v))||0);
  const frames=new Map([[0,[[1,0,0],[0,1,0],[0,0,1]]]]),queue=[0];while(queue.length){const i=queue.shift(),f=frames.get(i);for(let j=0;j<6;j++){const dx=p.cells[j][0]-p.cells[i][0],dy=p.cells[j][1]-p.cells[i][1];if(Math.abs(dx)+Math.abs(dy)!==1)continue;const axis=dx?f[1]:f[0],sign=dx?dx:-dy,next=f.map(v=>rotate(v,axis,sign));if(frames.has(j))eq(frames.get(j),next);else{frames.set(j,next);queue.push(j);}}}eq(frames.size,6);const normals=p.cells.map((_,i)=>frames.get(i)[2]);eq(new Set(normals.map(String)).size,6);const values=p.query.map(i=>{const opposite=normals.findIndex(n=>dot(normals[i],n)===-1);ok(opposite>=0&&p.shown[opposite]!==null);return p.rule==='seven'?7-p.shown[opposite]:p.shown[opposite];});if(p.rule==='seven')ok(q.problemHtml.includes('<circle'),'actual dice pips');return p.sum?sum(values):values.join(', ');
 }
 if(p.kind==='core-operators'){const symbols=[...new Set(permutations(['+','+','-','=']).map(a=>a.join('')))],matches=[];for(const ops of symbols){let l=0,r=0,sign=1,right=false;for(let i=0;i<p.numbers.length;i++){if(right)r+=sign*p.numbers[i];else l+=sign*p.numbers[i];if(ops[i]==='='){right=true;sign=1;}else sign=ops[i]==='-'?-1:1;}if(l===r)matches.push(p.numbers.map((n,i)=>n+(i<4?' '+ops[i]+' ':'')).join(''));}eq(matches.length,1);ok(q.prompt.includes('+ 두 개, − 한 개, = 한 개'));ok(q.prompt.includes('붙여 쓰지는 않습니다'));return matches[0];}
 throw Error('Unknown kind '+p.kind);
}
if(require.main===module){for(const row of provider.list()){const source=provider.getSource(row),before=JSON.stringify(source);for(const difficulty of ['easy','same','hard']){
 if(!levels.supports(source,difficulty))continue;if(difficulty==='same')eq(source.typeId,'r3-main-13','same-level override is limited to promoted dice type');const unique=new Set();for(let seed=0;seed<1000;seed++){const q=levels.generate(source,difficulty,seed);eq(q.answer,solve(q),`${source.typeId}/${difficulty}/${seed}`);eq(q,levels.generate(source,difficulty,seed),'deterministic');eq(JSON.stringify(source),before,'immutable source');ok(!/undefined|NaN|data-answer|answerHtml/.test(q.problemHtml));ok(q.solution.length>10);unique.add(JSON.stringify(q.payload));generated++;if(seed===23)specimens.push({id:source.typeId,difficulty,q});}coverage.push({typeId:source.typeId,difficulty,unique:unique.size});
}}
eq(coverage.length,17);eq(coverage.filter(x=>x.difficulty==='easy').length,6);eq(coverage.filter(x=>x.difficulty==='same').length,0);eq(coverage.filter(x=>x.difficulty==='hard').length,11);
for(const d of ['same','bad',null])eq(levels.supports({typeId:'triangle-number-rule'},d),false);
for(const seed of [-1,1.1,4294967296,NaN]){assert.throws(()=>levels.generate({typeId:'triangle-number-rule'},'easy',seed));checks++;}}
async function render(){const {chromium}=require('playwright'),base=path.resolve(__dirname,'..'),out=path.join(base,'output/qa/challenge-core-levels');fs.mkdirSync(out,{recursive:true});const server=http.createServer((req,res)=>{if(req.url==='/challenge/render'){res.setHeader('content-type','text/html');res.end('<!doctype html><meta charset="utf-8">');return;}const name=path.resolve(base,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!name.startsWith(base+path.sep)){res.writeHead(403).end();return;}fs.readFile(name,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('content-type',name.endsWith('.png')?'image/png':'application/octet-stream');res.end(data);});});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch();try{const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.address().port}/challenge/render`);const html=`<!doctype html><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#f0f3f5;font:16px/1.6 'Malgun Gothic',sans-serif;color:#233f55}main{max-width:1000px;margin:auto;padding:24px}article{background:white;padding:28px;margin:0 0 24px;border:1px solid #dbe2e7;break-inside:avoid}h2{font-size:18px}p{white-space:pre-line}svg{width:100%;height:auto}.solution{padding-top:18px;border-top:1px solid #ddd;color:#345e59}@media(max-width:600px){main{padding:10px}article{padding:16px}}</style><main>${specimens.map(({id,difficulty,q})=>`<article><h2>${id} · ${difficulty}</h2><p>${q.prompt}</p>${q.problemHtml}<p class="solution">${q.answerHtml}<br>${q.solution}</p></article>`).join('')}</main>`;await page.setContent(html,{waitUntil:'domcontentloaded'});await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))));for(const width of [1200,390]){await page.setViewportSize({width,height:900});await page.screenshot({path:path.join(out,`all-${width}.png`),fullPage:true});eq(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow');eq(await page.locator('article').count(),specimens.length);eq(await page.evaluate(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0)),true,'all raster assets loaded');}await page.setViewportSize({width:1200,height:900});for(const i of [0,2,5,8,12,16].filter(index=>index<specimens.length))await page.locator('article').nth(i).screenshot({path:path.join(out,`sample-${i}.png`)});await page.pdf({path:path.join(out,'samples.pdf'),format:'A4',printBackground:true});fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,generated,coverage},null,2));console.log(JSON.stringify({checks,generated,coverage,output:out}));}finally{await browser.close();await new Promise(r=>server.close(r));}}
module.exports={solve};
if(require.main===module){if(process.argv.includes('--render'))render().catch(e=>{console.error(e);process.exitCode=1;});else console.log(JSON.stringify({checks,generated,coverage}));}
