const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),{stripTypeScriptTypes}=require('node:module');
const base=path.resolve(__dirname,'..'),folder=path.join(base,'supabase/functions/hyperfocus-practice-content'),contract=fs.readFileSync(path.join(folder,'content-contract.ts'),'utf8'),source=fs.readFileSync(path.join(folder,'index.ts'),'utf8');
const executable=stripTypeScriptTypes(contract.replace(/^export /gm,'')+'\n'+source.replace(/^import .*\n/gm,'').replace(/^export /gm,''),{mode:'strip'});
const studentId='11111111-1111-4111-8111-111111111111',otherId='22222222-2222-4222-8222-222222222222',version='hf-qa-20260909',mode='hyperfocus-bank-individual-mode';let checks=0;
const ok=(v,label)=>{assert.ok(v,label);checks++;},hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function fixture(){const files={},manifest={schemaVersion:1,contentVersion:version,bank:{}};for(const typeId of [1,2,54]){const key='q'+String(typeId).padStart(2,'0');manifest.bank[key]={};for(const difficulty of ['easy','same','hard']){const tiers=manifest.bank[key][difficulty]={};for(const accessTier of ['free','paid']){const totalCount=accessTier==='free'?2:5,pool=tiers[accessTier]={releaseStatus:'verified',shards:[],totalCount};for(let index=0;index<Math.ceil(totalCount/2);index++){const count=Math.min(2,totalCount-index*2),shard={count};for(const part of ['questions','answers']){const p=`v1/bank/${key}/${difficulty}.${accessTier}.${part}.${index}.json`,items=Array.from({length:count},(_,i)=>{const id=`${key}-${difficulty}-${accessTier}-${index*2+i}`;return part==='questions'?{id,prompt:'빈칸에 수를 쓰세요.',problemHtml:'<svg viewBox="0 0 80 50"><rect x="10" y="10" width="20" height="20"/></svg>'}:{id,answerHtml:'<b>검수용 정답</b>',solution:'검수용 별도 풀이',solutionDiagram:'<svg></svg>'};});files[p]=JSON.stringify({schemaVersion:1,contentVersion:version,typeId,difficulty,accessTier,part,shardIndex:index,items});shard[part]={path:p,sha256:hash(files[p])};}pool.shards.push(shard);}}}}return {files,manifest};}
function edge(options={}){let now=Date.now();const claims={exp:Math.floor(now/1000)+3600,app_metadata:{hf_role:'student'},session_id:'live',...options.claims},token='x.'+Buffer.from(JSON.stringify(claims)).toString('base64url')+'.y',user={id:studentId,is_anonymous:false,app_metadata:{hf_role:'student'},...options.user};const bundle=fixture();options.mutate?.(bundle);const manifestText=JSON.stringify(bundle.manifest);bundle.files['manifest.json']=manifestText;
 const reads=[];let profiles=0,buckets=0;function createClient(url,key){const service=key==='secret';return {auth:{getUser:async()=>({data:{user:options.badToken?null:user},error:null})},from(table){let id;const q={select(){return q;},eq(k,v){id=v;return q;},maybeSingle:async()=>{assert.equal(table,'hf_students');assert.equal(service,false);assert.equal(id,studentId);profiles++;return {data:options.profileDenied||claims.session_id!=='live'||(options.sessionChanged&&profiles>1)?null:{id:options.wrongProfile?otherId:studentId,display_name:options.nameChanged&&profiles>1?'다른 이름':'검수용 서버 학생',account_status:options.inactive?'suspended':'active'},error:null};},then(resolve){assert.equal(table,'hf_entitlements');assert.equal(service,false);assert.equal(id,studentId);let grants=options.grants||['hyperfocus','hyperfocus-extra'];if(options.grantsAfter&&profiles>1)grants=options.grantsAfter;return Promise.resolve({data:grants.map(permission_key=>({permission_key,starts_at:new Date(now+(options.future?1000:-1000)).toISOString(),expires_at:options.expired?new Date(now-1).toISOString():null,revoked_at:options.revoked?'now':null})),error:options.dbError?Error('RLS'):null}).then(resolve);}};return q;},storage:{getBucket:async bucket=>{assert.equal(service,true);assert.equal(bucket,'hf-practice-private');buckets++;return {data:options.bucketMissing?null:{id:bucket,public:options.publicBucket===true},error:null};},from(bucket){assert.equal(service,true);assert.equal(bucket,'hf-practice-private');return {download:async p=>{reads.push(p);if(options.delay&&p!=='manifest.json')now+=61000;if(options.noFile||!bundle.files[p])return {data:null,error:Error('missing')};return {data:new Blob([options.corrupt&&p!=='manifest.json'?'broken':bundle.files[p]]),error:null};}};}}};}
 class Clock extends Date{static now(){return now;}}const env={SUPABASE_URL:'https://mock.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public',SUPABASE_SECRET_KEY:'secret',HF_PRACTICE_PRIVATE_DELIVERY_READY:options.ready===false?'false':'true',HF_PRACTICE_MANIFEST_SHA256:options.pin??hash(manifestText)};
 const context={Request,Response,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,Blob,atob,Date:Clock,Set,JSON,console,crypto:crypto.webcrypto,createClient,Deno:{env:{get:k=>env[k]},serve:fn=>context.handler=fn}};vm.createContext(context);vm.runInContext(executable,context);
 const request=(body,headers={},method='POST')=>context.handler(new Request('https://example/hyperfocus-practice-content',{method,headers:{authorization:'Bearer '+token,'content-type':'application/json',...headers},...(method==='OPTIONS'||method==='GET'?{}:{body:JSON.stringify(body)})}));return {context,request,reads,bundle,get profiles(){return profiles;},get buckets(){return buckets;}};
}
function updateFile(bundle,p,fn){const data=JSON.parse(bundle.files[p]);fn(data);bundle.files[p]=JSON.stringify(data);for(const levels of Object.values(bundle.manifest.bank))for(const tiers of Object.values(levels))for(const pool of Object.values(tiers))for(const shard of pool.shards)for(const part of ['questions','answers'])if(shard[part].path===p)shard[part].sha256=hash(bundle.files[p]);}
const request={action:'practice',types:[{typeId:1,difficulty:'same'}],countPerType:2,seed:3,accessTier:'paid',part:'questions'};
async function main(){
 for(const [label,options,body,headers,status]of [
 ['missing token',{},request,{authorization:''},401],['bad token',{badToken:true},request,{},401],['expired token',{claims:{exp:1}},request,{},401],['anonymous',{user:{is_anonymous:true}},request,{},401],['auth role',{user:{app_metadata:{hf_role:'admin'}}},request,{},403],['jwt role',{claims:{app_metadata:{hf_role:'admin'}}},request,{},403],['user metadata forged',{user:{app_metadata:{},user_metadata:{hf_role:'student'}}},request,{},403],
 ['profile denied',{profileDenied:true},request,{},403],['wrong student row',{wrongProfile:true},request,{},403],['inactive',{inactive:true},request,{},403],['dead session',{claims:{session_id:'dead'}},request,{},403],['DB denied',{dbError:true},request,{},403],['expired grants',{expired:true},request,{},403],['future grants',{future:true},request,{},403],['revoked grants',{revoked:true},request,{},403],
 ['base required',{grants:['hyperfocus-extra']},request,{},403],['paid required',{grants:['hyperfocus']},request,{},403],['exact individual required',{grants:['hyperfocus','problem-bank',mode,'hyperfocus-bank-q02']},request,{},403],['all selected required',{grants:['hyperfocus','problem-bank',mode,'hyperfocus-bank-q01']},{...request,types:[...request.types,{typeId:2,difficulty:'hard'}]},{},403],['challenge grant isolated',{grants:['challenge-bank-r3-main-1']},request,{},403],['wildcard',{grants:['*']},request,{},403],
 ['cross student parameter',{}, {...request,studentId:otherId},{},400],['path injection',{}, {...request,path:'../../private.json'},{},400],['invalid type',{}, {...request,types:[{typeId:55,difficulty:'same'}]},{},400],['string type',{}, {...request,types:[{typeId:'1',difficulty:'same'}]},{},400],['nested extra',{}, {...request,types:[{typeId:1,difficulty:'same',answer:true}]},{},400],['duplicate type',{}, {...request,types:[...request.types,...request.types]},{},400],['too many types',{}, {...request,types:Array.from({length:21},(_,i)=>({typeId:i+1,difficulty:'same'}))},{},400],['empty types',{}, {...request,types:[]},{},400],['bad difficulty',{}, {...request,types:[{typeId:1,difficulty:'advanced'}]},{},400],['negative seed',{}, {...request,seed:-1},{},400],['string seed',{}, {...request,seed:'3'},{},400],['large seed',{}, {...request,seed:4294967296},{},400],['fractional count',{}, {...request,countPerType:1.5},{},400],['zero count',{}, {...request,countPerType:0},{},400],['large paid count',{}, {...request,countPerType:21},{},400],['free escalation',{}, {...request,accessTier:'free',countPerType:3},{},400],['unknown tier',{}, {...request,accessTier:'admin'},{},400],['both parts',{}, {...request,part:'all'},{},400],['body limit',{}, {...request,extra:'x'.repeat(5000)},{},400],['bad content type',{},request,{'content-type':'text/plain'},400],['bad origin',{},request,{origin:'https://attacker.example'},403]
 ]){const e=edge(options),r=await e.request(body,headers);ok(r.status===status,label);ok(e.reads.length===0&&e.buckets===0,label+' denied before storage');}
 for(const options of [{ready:false},{bucketMissing:true},{publicBucket:true},{pin:''},{pin:'0'.repeat(64)},{noFile:true},{corrupt:true}])ok((await edge(options).request(request)).status===503,'delivery held/storage integrity');
 for(const grants of [['hyperfocus','hyperfocus-extra'],['hyperfocus','problem-bank'],['hyperfocus','problem-bank','hyperfocus-bank-q02'],['hyperfocus','problem-bank',mode,'hyperfocus-bank-q01']]){const e=edge({grants}),r=await e.request(request),data=await r.json();ok(r.status===200,'legacy or exact individual grant');ok(data.studentId===studentId&&data.approvedStudentName==='검수용 서버 학생','server identity');ok(data.questions.length===2&&!data.answers&&!JSON.stringify(data).includes('검수용 정답'),'question answer separation');ok(e.profiles===2,'fresh RLS after storage');ok(e.reads.every(p=>!p.includes('.answers.')),'questions never download answers');ok(r.headers.get('cache-control')==='no-store','no cache');}
 for(const grants of [['hyperfocus'],['hyperfocus',mode,'hyperfocus-bank-q01']]){let ids;for(const seed of [0,1,200,4294967295]){const e=edge({grants}),r=await e.request({...request,accessTier:'free',seed}),data=await r.json();ok(r.status===200,'free still base/individual checked');const nowIds=data.questions.map(q=>q.id);if(ids)ok(JSON.stringify(nowIds)===JSON.stringify(ids),'free seed cannot enumerate');ids=nowIds;ok(e.reads.filter(p=>p!=='manifest.json').every(p=>p.includes('.free.questions.')),'physically separate free pool');}}
 for(const seed of [0,1,4,5,4294967295]){const e=edge(),q=await (await e.request({...request,countPerType:5,seed})).json(),a=await (await e.request({...request,countPerType:5,seed,part:'answers'})).json();ok(q.questions.length===5&&new Set(q.questions.map(x=>x.id)).size===5,'unique bounded selection');ok(JSON.stringify(q.questions.map(x=>x.id))===JSON.stringify(a.answers.map(x=>x.id)),'same q/a identity and order');ok(!a.questions&&a.answers.every(x=>x.solution),'separate answer response');}
 for(const options of [{grantsAfter:['hyperfocus']},{grantsAfter:['hyperfocus','problem-bank',mode]},{sessionChanged:true},{nameChanged:true},{delay:true}]){const e=edge(options),r=await e.request(request);ok(r.status===403,'revoke/session/name/expiry while loading');ok(!(await r.text()).includes('검수용'),'failed response no question/name');}
 const p='v1/bank/q01/same.paid.questions.1.json';
 for(const [label,mutate]of [
 ['held pool',b=>b.manifest.bank.q01.same.paid.releaseStatus='held'],['unset pool status',b=>delete b.manifest.bank.q01.same.paid.releaseStatus],['unknown pool status',b=>b.manifest.bank.q01.same.paid.releaseStatus='ready'],['bad manifest path',b=>b.manifest.bank.q01.same.paid.shards[1].questions.path='../secret'],['wrong product manifest',b=>b.manifest.bank['challenge-mock-1']=b.manifest.bank.q01],['free larger than two',b=>b.manifest.bank.q01.same.free.totalCount=3],['wrong sum',b=>b.manifest.bank.q01.same.paid.totalCount=6],['zero shard',b=>b.manifest.bank.q01.same.paid.shards[1].count=0],
 ...[['root answer',f=>f.answer='LEAK'],['nested answer',f=>f.items[0].answer='LEAK'],['nested payload',f=>f.items[0].payload={answer:3}],['wrong type',f=>f.typeId=2],['wrong tier',f=>f.accessTier='free'],['wrong part',f=>f.part='answers'],['wrong version',f=>f.contentVersion='other'],['wrong index',f=>f.shardIndex=0],['wrong count',f=>f.items=[]],['duplicate id',f=>f.items[1].id=f.items[0].id],['script',f=>f.items[0].problemHtml='<script>bad()</script>'],['event',f=>f.items[0].problemHtml='<img onerror="bad()">'],['external image',f=>f.items[0].problemHtml='<image href="https://bad/x.png"/>'],['answer attribute',f=>f.items[0].problemHtml='<span data-answer="4"></span>']].map(([label,fn])=>[label,b=>updateFile(b,p,fn)])
 ])ok((await edge({mutate}).request(request)).status===503,label);
 const c=edge().context;for(let id=1;id<=54;id++){const t=c.requestTarget({...request,types:[{typeId:id,difficulty:'hard'}]});ok(t&&t.types[0].key==='q'+String(id).padStart(2,'0'),'exact 54 type identity');}ok(c.requestTarget({...request,types:[{typeId:0,difficulty:'same'}]})===null,'zero type denied');
 ok(!/\.rpc\(|\.upload\(|\.update\(|\.insert\(|createSignedUrl|challenge-content|hf-challenge-private/.test(source),'no writes and no Challenge content dependencies');
 if(process.argv.includes('--package'))packageAudit();console.log(JSON.stringify({status:'passed',checks,remoteWrites:0,server:'actual TypeScript with mocked Auth/RLS/Storage',release:'held until private package upload, pinned manifest, hosting deny verification and deployment'}));
}
function packageAudit(){const latestFile=process.env.HF_PRIVATE_PACKAGE_LATEST||path.join(base,'output/private-practice/latest.json'),latest=JSON.parse(fs.readFileSync(latestFile,'utf8')),privateRoot=path.join(path.resolve(latest.out),'private'),allowed=path.join(base,'output')+path.sep;ok(privateRoot.startsWith(allowed),'scoped package');const bytes=fs.readFileSync(path.join(privateRoot,'manifest.json')),manifest=JSON.parse(bytes),c=edge().context;c.validateManifest(manifest);ok(bytes.length<=524288,'manifest bytes');let files=0,variants=0,maxBytes=0,heldPools=0,verifiedPools=0;const failures=[];
 for(const [key,levels]of Object.entries(manifest.bank))for(const[difficulty,tiers]of Object.entries(levels))for(const[accessTier,pool]of Object.entries(tiers)){const ids=new Set();if(pool.releaseStatus==='verified')verifiedPools++;else heldPools++;let offset=0;for(const shard of pool.shards){const records={};for(const part of ['questions','answers'])try{const target=c.requestTarget({action:'practice',types:[{typeId:Number(key.slice(1)),difficulty}],countPerType:1,seed:offset,accessTier,part}),selection={...shard[part],typeId:Number(key.slice(1)),key,difficulty,accessTier,part,number:1,itemIndex:0,shardIndex:pool.shards.indexOf(shard),expectedCount:shard.count};if(pool.releaseStatus==='verified'){ok(c.selectReferences(manifest,target).length===1,'verified pool selectable');}else{assert.throws(()=>c.selectReferences(manifest,target));checks++;}const p=path.resolve(privateRoot,selection.path);ok(p.startsWith(privateRoot+path.sep),'fixed private scope');const data=fs.readFileSync(p);maxBytes=Math.max(maxBytes,data.length);ok(data.length<=8000000,'file byte limit');ok(hash(data)===selection.sha256,'file hash');records[part]=JSON.parse(data);if(part==='questions')ok(!/정답\s*[:：]|정답은|class\s*=\s*["'][^"']*(?:answer-page|answer-card|solution-panel|answer-section)/i.test(JSON.stringify(records[part])),'no answer markers in question shard');c.selectContent(records[part],manifest,selection);files++;}catch(e){failures.push({typeId:key,difficulty,accessTier,part,error:e.message});}if(records.questions&&records.answers){ok(records.questions.items.length===records.answers.items.length,'paired counts');for(let i=0;i<records.questions.items.length;i++){const q=records.questions.items[i],a=records.answers.items[i];ok(q.id===a.id,'paired identity');ok(!ids.has(q.id),'cross-shard unique IDs');ids.add(q.id);variants++;}}offset+=shard.count;}}
 console.log(JSON.stringify({realPackage:{contentVersion:manifest.contentVersion,types:Object.keys(manifest.bank).length,files,variants,heldPools,verifiedPools,maxBytes,manifestSHA256:hash(bytes),failures}}));ok(failures.length===0,'all package contract checks');}
if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1;});module.exports={edge};
