const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),latest=JSON.parse(fs.readFileSync(path.join(root,'output/private-challenge/latest.json'))),build=JSON.parse(fs.readFileSync(path.join(latest.out,'build-report.json'))),privateRoot=path.join(latest.out,'private'),manifest=JSON.parse(fs.readFileSync(path.join(privateRoot,'manifest.json'))),out=path.join(root,'output/qa/challenge-remote-ui');
const context=vm.createContext({});vm.runInContext(stripTypeScriptTypes(fs.readFileSync(path.join(root,'supabase/functions/challenge-content/content-contract.ts'),'utf8').replace(/^export /gm,''),{mode:'strip'})+';globalThis.contract={requestTarget,selectReference,selectContent,validateManifest};',context);context.contract.validateManifest(manifest);
const origin='http://private-challenge.test',results=[],publicFiles=new Set(build.publicFiles),protectedRequests=[];
function check(name,pass){results.push({name,pass:!!pass});if(!pass)throw Error(name);}
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch();
 async function open(file,keys){const page=await browser.newPage({viewport:{width:1200,height:900}}),calls=[],errors=[],state={keys,name:'검수용 승인학생',id:'11111111-1111-4111-8111-111111111111'};
  page.on('pageerror',e=>errors.push(e.message));await page.exposeFunction('qaInvoke',async(name,body)=>{calls.push({name,...body});if(name==='challenge-access')return {data:{verified:true,studentId:state.id,approvedStudentName:state.name,accountStatus:'active',permissionKeys:state.keys,verifiedAt:Date.now(),validUntil:Date.now()+60000,deliveryReady:true,catalogVersion:'challenge-access-v1'}};
   if(name!=='challenge-content')throw Error('Unexpected external function');if(state.contentGate)await state.contentGate;const target=context.contract.requestTarget(body);if(!target||!target.permissionKeys.some(k=>state.keys.includes(k)))return {error:{message:'denied'}};const ref=context.contract.selectReference(manifest,target),data=JSON.parse(fs.readFileSync(path.join(privateRoot,ref.path)));return {data:{verified:true,studentId:state.id,approvedStudentName:state.name,validUntil:Date.now()+60000,contentVersion:state.contentVersion||manifest.contentVersion,...context.contract.selectContent(data,manifest,target)}};});
  await page.addInitScript(()=>{window.__printCount=0;window.print=()=>window.__printCount++;});
  await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();if(u.pathname.endsWith('/supabase-config.js'))return route.fulfill({contentType:'text/javascript',body:'window.GFIELD_HF_SUPABASE_CONFIG={enabled:true};'});if(u.pathname.endsWith('/supabase-client.js'))return route.fulfill({contentType:'text/javascript',body:'window.GFieldHFSupabase={enabled:()=>true,ready:async()=>({auth:{onAuthStateChange:fn=>window.__qaAuth=fn},functions:{invoke:(name,{body})=>window.qaInvoke(name,body)}})};'});const name=u.pathname.replace(/^\/challenge\//,'');if(!publicFiles.has(name)){protectedRequests.push(name);return route.fulfill({status:404,body:''});}const target=path.join(latest.out,'public/hyper-focus/challenge',name);return route.fulfill({contentType:({'.js':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png'})[path.extname(target)]||'text/plain',body:fs.readFileSync(target)});});
  await page.goto(origin+'/challenge/'+file);return {page,calls,errors,state};
 }
 try{
  for(const kind of ['concept','mock']){const key=`challenge-${kind}-2`,f=await open((kind==='concept'?'concepts':'exam')+'.html?round=2',[key]),selector=kind==='concept'?'.concept-page':'.exam-page';await f.page.waitForSelector(selector,{state:'attached'});
   check(kind+' questions loaded without answers',f.calls.filter(c=>c.name==='challenge-content').every(c=>c.part==='questions'));
   check(kind+' no answer nodes initially',await f.page.locator('.answer-pages,.answer-page,.answer-cover-page').count()===0);
   check(kind+' approved watermark',await f.page.locator(selector).first().evaluate(el=>(el.textContent+' '+el.dataset.watermark).includes('검수용 승인학생')));
   if(kind==='concept')await f.page.locator('#answers').check();else await f.page.locator('#printAnswers').click();
   await f.page.waitForSelector(kind==='concept'?'.answer-pages':'.answer-page',{state:'attached'});check(kind+' answer fetch explicit',f.calls.some(c=>c.part==='answers'));
   await f.page.setViewportSize({width:390,height:844});check(kind+' mobile width',await f.page.evaluate(()=>document.documentElement.scrollWidth<=390));await f.page.screenshot({path:path.join(out,kind+'-mobile.png')});
   await f.page.evaluate(()=>window.HFChallengeAccess.clear());check(kind+' expiry removes document',await f.page.locator('main').innerHTML()==='');check(kind+' no JS errors',!f.errors.length);await f.page.close();
  }
  const f=await open('studio.html?tab=bank&round=1',['challenge-mock-1','challenge-bank-replace-count-constraints']);await f.page.waitForFunction(()=>!!window.HFChallengeStudio);
  check('catalog sends no source questions',f.calls.every(c=>c.name==='challenge-access'));
  await f.page.locator('#bankRows [data-preview="challenge-r1-main-01"]').click();await f.page.waitForFunction(()=>document.querySelector('#previewQuestion').textContent.length>5);
  check('source preview approved watermark',(await f.page.locator('#previewQuestion').getAttribute('data-watermark')).includes('검수용 승인학생'));check('source preview no answer request',f.calls.filter(c=>c.name==='challenge-content').every(c=>c.part==='questions'));
  await f.page.locator('#revealPreview').click();await f.page.waitForFunction(()=>!document.querySelector('#previewAnswer').hidden);check('source answer explicit',f.calls.some(c=>c.action==='source'&&c.part==='answers'));await f.page.locator('#closePreview').click();
  await f.page.locator('[data-select="challenge-r1-main-01"]').check();await f.page.locator('#variantCount').fill('2');await f.page.locator('#buildPractice').click();await f.page.waitForFunction(()=>document.body.dataset.printReady==='true');
  check('generated worksheet contains no answer in snapshot',await f.page.evaluate(()=>window.HFChallengeStudio.getSnapshot().entries.every(e=>!('answer' in e.question)&&!('answerHtml' in e.question)&&!('solution' in e.question)&&!('payload' in e.question))));
  check('bank question does not request answers',f.calls.filter(c=>c.action==='bank').every(c=>c.part==='questions'));
  await f.page.locator('#printMode').selectOption('both');await f.page.waitForFunction(()=>document.querySelectorAll('.studio-answer').length===2&&document.body.dataset.printReady==='true');check('bank answer explicit',f.calls.some(c=>c.action==='bank'&&c.part==='answers'));
  await f.page.screenshot({path:path.join(out,'studio-desktop.png'),fullPage:true});await f.page.setViewportSize({width:390,height:844});check('studio mobile width',await f.page.evaluate(()=>document.documentElement.scrollWidth<=390));
  const cleaned=await f.page.evaluate(()=>window.HFChallengeContent.safeHtml('<img src="https://bad.test/x" onerror="alert(1)"><script>bad()</script><svg><a href="javascript:alert(1)">x</a></svg>'));check('unsafe markup stripped',!/(onerror|script|https:|javascript:)/.test(cleaned));
  f.state.contentGate=new Promise(resolve=>f.state.releaseContent=resolve);const beforeCalls=f.calls.length;const delayed=f.page.evaluate(()=>window.HFChallengeContent.request({action:'bank',typeId:'replace-count-constraints',difficulty:'same',seed:22,part:'answers'}).then(()=>true,()=>false));while(f.calls.length===beforeCalls)await new Promise(r=>setTimeout(r,10));await f.page.evaluate(()=>window.HFChallengeAccess.clear());f.state.releaseContent();check('late answer rejected after access clear',await delayed===false);f.state.contentGate=null;check('late answer does not restore worksheet',await f.page.locator('#worksheetPages').innerHTML()==='');f.state.keys=[];await f.page.evaluate(()=>window.HFChallengeAccess.refresh());check('revoked removes worksheet',await f.page.locator('#worksheetPages').innerHTML()==='');check('studio JS errors none',!f.errors.length);await f.page.close();
  const fruit=await open('studio.html?tab=bank&round=2',['challenge-bank-replace-fruit-pair-cancel']);await fruit.page.waitForFunction(()=>!!window.HFChallengeStudio);await fruit.page.locator('#bankRows [data-preview="challenge-r2-main-11"]').click();await fruit.page.waitForSelector('#previewQuestion image',{state:'attached'});check('private raster embedded once',await fruit.page.locator('#previewQuestion image').count()===1&&await fruit.page.locator('#previewQuestion use').count()===19);await fruit.page.screenshot({path:path.join(out,'private-fruit-preview.png')});await fruit.page.close();
  const denied=await open('exam.html?round=1',[]);await denied.page.waitForTimeout(120);check('unapproved never requests content',denied.calls.every(c=>c.name==='challenge-access'));check('unapproved empty main',await denied.page.locator('main').innerHTML()==='');await denied.page.close();
  const changed=await open('concepts.html?round=1',['challenge-concept-1']);await changed.page.waitForSelector('.concept-page',{state:'attached'});changed.state.contentVersion='different-edition';await changed.page.locator('#answers').check();await changed.page.waitForFunction(()=>document.querySelector('main').innerHTML==='');check('document rejects answer from another edition',(await changed.page.locator('#documentAccessStatus').innerText()).includes('같은 버전'));await changed.page.close();
  const finite=Object.entries(build.poolCounts).find(([k,c])=>k.endsWith(':same')&&c>0&&c<20);check('finite pool fixture exists',!!finite);const type=finite[0].slice(0,-5),sourceId=Object.keys(manifest.sources).find(id=>manifest.sources[id].typeId===type),[r,section,number]=sourceId.split('-');const limited=await open(`studio.html?tab=bank&round=${r}`,['challenge-bank-'+type]);await limited.page.waitForFunction(()=>!!window.HFChallengeStudio);await limited.page.locator(`[data-select="challenge-r${r}-${section}-${number.padStart(2,'0')}"]`).check();await limited.page.locator('#variantCount').fill(String(finite[1]+1));check('finite pool limit blocks excess request',await limited.page.locator('#buildPractice').isDisabled());check('finite pool limit explains actual capacity',(await limited.page.locator('#assemblySummary').innerText()).includes(`1~${finite[1]}문항`));check('finite pool blocked before content call',limited.calls.every(c=>c.name==='challenge-access'));await limited.page.close();check('protected static request count zero',protectedRequests.length===0);
 }finally{await browser.close();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({results,protectedRequests,remoteWrites:0,scope:'Real client UI and actual private package; synthetic auth and function transport. Not live RLS.'},null,2));}
 console.log(JSON.stringify({passed:results.length,out}));
})().catch(e=>{console.error(e);process.exitCode=1;});
