const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),{stripTypeScriptTypes}=require('node:module');
const base=path.resolve(__dirname,'..'),folder=path.join(base,'supabase/functions/challenge-content');
const contract=fs.readFileSync(path.join(folder,'content-contract.ts'),'utf8'),source=fs.readFileSync(path.join(folder,'index.ts'),'utf8');
const executable=stripTypeScriptTypes(contract.replace(/^export /gm,'')+'\n'+source.replace(/^import .*\r?\n/gm,'').replace(/^export /gm,''),{mode:'strip'});
const studentId='11111111-1111-4111-8111-111111111111',otherId='22222222-2222-4222-8222-222222222222',typeId='replace-count-constraints',productKey='challenge-mock-1',version='qa-20260909';
let checks=0;function ok(value,label){assert.ok(value,label);checks++;}
function hash(s){return crypto.createHash('sha256').update(s).digest('hex');}
function fixture(){
 const files={},manifest={schemaVersion:1,contentVersion:version,documents:{},bank:{},sources:{}};
 const q=i=>({id:'variant-'+i,prompt:'그림을 보고 빈칸을 채우세요.',problemHtml:'<svg viewBox="0 0 100 50"><path d="M0 0 L10 10" /></svg>'});
 const a=i=>({id:'variant-'+i,answerHtml:'<b>검수용 답 '+i+'</b>',solution:'검수용 풀이',solutionDiagram:'<svg></svg>'});
 function add(p,v){files[p]=JSON.stringify(v);return {path:p,sha256:hash(files[p])};}
 const d={},b={},s={typeId};
 for(const part of ['questions','answers']){
  d[part]=add(`v1/documents/${productKey}.${part}.json`,{schemaVersion:1,contentVersion:version,productKey,part,document:{title:'검수용 문서',html:part==='questions'?'<section>질문과 답칸</section>':'<section>검수용 답안</section>',styles:['exam.css']}});
  b[part]=add(`v1/bank/${typeId}/same.${part}.json`,{schemaVersion:1,contentVersion:version,typeId,difficulty:'same',part,items:[0,1].map(part==='questions'?q:a)});
  s[part]=add(`v1/sources/1-main-1.${part}.json`,{schemaVersion:1,contentVersion:version,sourceId:'1-main-1',typeId,part,...(part==='questions'?{question:q(0)}:{answer:a(0)})});
 }
 manifest.documents[productKey]=d;manifest.bank[typeId]={same:b};manifest.sources['1-main-1']=s;
 return {files,manifest};
}
function edge(options={}){
 const now=Date.now(),claims={exp:Math.floor(now/1000)+3600,app_metadata:{hf_role:'student'},session_id:'live',...options.claims},token='x.'+Buffer.from(JSON.stringify(claims)).toString('base64url')+'.y';
 const user={id:studentId,is_anonymous:false,app_metadata:{hf_role:options.role||'student'},...options.user};
 const bundle=fixture();options.mutate?.(bundle);
 const manifestText=JSON.stringify(bundle.manifest),pin=options.pin??hash(manifestText);bundle.files['manifest.json']=manifestText;
 let storageReads=[],profileReads=0,authReads=0,bucketReads=0;
 function createClient(url,key){const service=key==='secret';return {
  auth:{getUser:async()=>{authReads++;return {data:{user:options.badToken?null:user},error:options.badToken?Error('bad'):null};}},
  from(table){let target;const query={select(){return query;},eq(k,v){target=v;return query;},maybeSingle:async()=>{assert.equal(service,false);assert.equal(table,'hf_students');assert.equal(target,studentId);profileReads++;return {data:options.profileDenied||claims.session_id!=='live'||(options.sessionRevokedDuring&&profileReads>1)?null:{id:options.wrongProfile?otherId:studentId,display_name:options.nameChangedDuring&&profileReads>1?'변경된 이름':'검수용 서버 이름',account_status:options.inactive?'suspended':'active'},error:null};},then(resolve){assert.equal(table,'hf_entitlements');assert.equal(service,false);assert.equal(target,studentId);const keys=options.grants||[productKey,'challenge-bank-'+typeId];let entries=keys.map(permission_key=>({permission_key,starts_at:new Date(now-1000).toISOString(),expires_at:options.expired?new Date(now-1).toISOString():null,revoked_at:options.revoked||(options.revokedDuring&&profileReads>1)?new Date(now).toISOString():null}));if(options.future)entries=entries.map(e=>({...e,starts_at:new Date(now+60000).toISOString()}));return Promise.resolve({data:entries,error:options.readError?Error('db'):null}).then(resolve);}};return query;},
  storage:{getBucket:async name=>{assert.equal(service,true);assert.equal(name,'hf-challenge-private');bucketReads++;return {data:options.bucketMissing?null:{id:name,public:options.publicBucket===true},error:null};},from(name){assert.equal(name,'hf-challenge-private');assert.equal(service,true);return {download:async p=>{storageReads.push(p);if(options.noFile||!(p in bundle.files))return {data:null,error:Error('not found')};const text=options.corrupt&&p!=='manifest.json'?'corrupt':bundle.files[p];return {data:new Blob([text],{type:'application/json'}),error:null};}};}}
 };}
 const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public',SUPABASE_SECRET_KEY:'secret',CHALLENGE_PRIVATE_DELIVERY_READY:options.ready===false?'false':'true',CHALLENGE_MANIFEST_SHA256:pin};
 if(options.noReadyEnvironment)delete env.CHALLENGE_PRIVATE_DELIVERY_READY;
 if(options.noPinEnvironment)delete env.CHALLENGE_MANIFEST_SHA256;
 const RELEASE_CONFIG={ready:options.buildReady===true,manifestSha256:options.buildPin===true?pin:''};
 const context={Request,Response,TextDecoder,Uint8Array,ArrayBuffer,Blob,atob,Date,Set,JSON,console,crypto:crypto.webcrypto,createClient,RELEASE_CONFIG,Deno:{env:{get:k=>env[k]},serve:fn=>context.handler=fn}};vm.createContext(context);vm.runInContext(executable,context);
 async function request(body,headers={},method='POST'){return context.handler(new Request('https://example/challenge-content',{method,headers:{authorization:'Bearer '+token,'content-type':'application/json',...headers},...(method==='GET'||method==='OPTIONS'?{}:{body:JSON.stringify(body)})}));}
 return {request,storageReads,get profileReads(){return profileReads;},get authReads(){return authReads;},get bucketReads(){return bucketReads;},context,bundle};
}
function updateFile(bundle,p,fn){const file=JSON.parse(bundle.files[p]);fn(file);bundle.files[p]=JSON.stringify(file);for(const group of [bundle.manifest.documents[productKey],bundle.manifest.bank[typeId].same,bundle.manifest.sources['1-main-1']])for(const part of ['questions','answers'])if(group[part].path===p)group[part].sha256=hash(bundle.files[p]);}
function shardFixture(bundle){const entry=bundle.manifest.bank[typeId].same;const shards=[{count:1},{count:1}];for(const part of ['questions','answers']){const full=JSON.parse(bundle.files[entry[part].path]);shards.forEach((shard,index)=>{const p=`v1/bank/${typeId}/same.${part}.${index}.json`,file={...full,items:[full.items[index]],shardIndex:index};bundle.files[p]=JSON.stringify(file);shard[part]={path:p,sha256:hash(bundle.files[p])};});}bundle.manifest.bank[typeId].same={shards,totalCount:2};}
function packageAudit(){
 const latest=JSON.parse(fs.readFileSync(path.join(base,'output/private-challenge/latest.json'),'utf8')),out=path.resolve(latest.out),root=path.resolve(base,'output/private-challenge');
 ok(out.startsWith(root+path.sep),'package stays in scoped output');
 const privateRoot=path.join(out,'private'),manifest=JSON.parse(fs.readFileSync(path.join(privateRoot,'manifest.json'),'utf8')),context=edge().context;
 context.validateManifest(manifest);ok(true,'real manifest contract');
 ok(fs.statSync(path.join(privateRoot,'manifest.json')).size<=524288,'real manifest within server byte limit');ok(manifest.contentVersion===latest.contentVersion,'latest version matches manifest');
 let files=0,questions=0,answers=0,variants=0,maxBytes=0;const failures=[],oversized=[];
 function check(target){
  let data;
  try{const ref=context.selectReference(manifest,target),filePath=path.resolve(privateRoot,ref.path);ok(filePath.startsWith(privateRoot+path.sep),'private asset scoped');const bytes=fs.readFileSync(filePath);maxBytes=Math.max(maxBytes,bytes.length);if(bytes.length>(target.kind==='document'?12000000:8000000))oversized.push({kind:target.kind,id:target.id,difficulty:target.difficulty||null,part:target.part,bytes:bytes.length});ok(hash(bytes)===ref.sha256,'real asset digest');data=JSON.parse(bytes);const result=context.selectContent(data,manifest,target);if(target.part==='questions')ok(!/정답\s*[:：]|정답은|class\s*=\s*["'][^"']*(?:answer-page|answer-card|solution-panel|answer-section)/i.test(JSON.stringify(data)),'question package no explicit answer or solution markers');files++;target.part==='questions'?questions++:answers++;return {data,result};}catch(e){const badFields=[];function scan(v,key=''){if(typeof v==='string'&&(/html$|diagram$/i.test(key))&&!context.html(v,target.part)){const uris=[...v.matchAll(/\b(?:href|src|xlink:href)\s*=\s*(["'])(.*?)\1/gi)].map(m=>m[2].startsWith('data:')?'embedded image':m[2].slice(0,60));badFields.push({field:key,uriKinds:[...new Set(uris)],comment:v.includes('<!--'),event:/\bon[a-z]+\s*=/i.test(v),urls:v.includes('url(')});}else if(v&&typeof v==='object')for(const[k,x]of Object.entries(v))scan(x,k);}scan(data);failures.push({kind:target.kind,id:target.id,part:target.part,difficulty:target.difficulty||null,error:e.message,badFields:badFields.slice(0,2)});return null;}
 }
 for(const id of Object.keys(manifest.documents))for(const part of ['questions','answers'])check(context.requestTarget({action:'document',productKey:id,part}));
 for(const id of Object.keys(manifest.sources)){const[r,section,n]=id.split('-'),q=check(context.requestTarget({action:'source',round:+r,section,number:+n,part:'questions'})),a=check(context.requestTarget({action:'source',round:+r,section,number:+n,part:'answers'}));if(q&&a)ok(q.result.question.id===a.result.answer.id,'source question and answer IDs match');}
 for(const [id,pools]of Object.entries(manifest.bank))for(const difficulty of Object.keys(pools)){
  const pool=pools[difficulty],seeds=[];if(pool.shards){let offset=0;for(const shard of pool.shards){seeds.push(offset);offset+=shard.count;}}else seeds.push(0);
  const uniqueIds=new Set();for(const seed of seeds){const q=check(context.requestTarget({action:'bank',typeId:id,difficulty,seed,part:'questions'})),a=check(context.requestTarget({action:'bank',typeId:id,difficulty,seed,part:'answers'}));
   if(q&&a){ok(q.data.items.length===a.data.items.length,'matching pool size');for(let i=0;i<q.data.items.length;i++){const question=q.data.items[i],answer=a.data.items[i];ok(question.id===answer.id,'matching deterministic question/answer ID');ok(!uniqueIds.has(question.id),'IDs unique across shards');uniqueIds.add(question.id);variants++;}}
  }
 }
 console.log(JSON.stringify({realPackage:{contentVersion:manifest.contentVersion,documents:Object.keys(manifest.documents).length,sources:Object.keys(manifest.sources).length,bankTypes:Object.keys(manifest.bank).length,difficultyPools:Object.values(manifest.bank).reduce((n,p)=>n+Object.keys(p).length,0),files,questions,answers,variants,maxBytes,oversized,failures}}));
 ok(failures.length===0,'all real package assets match server contract');
 ok(oversized.length===0,'all real package assets fit server byte limits');
}
(async()=>{
 const doc={action:'document',productKey,part:'questions'},bank={action:'bank',typeId,difficulty:'same',seed:7,part:'questions'},sourceRequest={action:'source',round:1,section:'main',number:1,part:'questions'};
 for(const [options,status] of [[{noReadyEnvironment:true,noPinEnvironment:true},503],[{noReadyEnvironment:true,noPinEnvironment:true,buildReady:true,buildPin:true},200],[{ready:false,noPinEnvironment:true,buildReady:true,buildPin:true},503]]){
  const f=edge(options);ok((await f.request(doc)).status===status,'reviewed build pin and environment stop override');
 }
 for(const [label,options,body,headers,status]of [
  ['missing token',{},doc,{authorization:''},401],['invalid token',{badToken:true},doc,{},401],['expired token',{claims:{exp:1}},doc,{},401],['anonymous',{user:{is_anonymous:true}},doc,{},401],
  ['admin is not student',{role:'admin'},doc,{},403],['claim mismatch',{claims:{app_metadata:{hf_role:'admin'}}},doc,{},403],['user metadata forged',{role:'visitor',user:{user_metadata:{hf_role:'student'}}},doc,{},403],
  ['inactive student',{inactive:true},doc,{},403],['profile RLS denied',{profileDenied:true},doc,{},403],['wrong profile',{wrongProfile:true},doc,{},403],['revoked session',{claims:{session_id:'dead'}},doc,{},403],['grant revoked',{revoked:true},doc,{},403],['grant expired',{expired:true},doc,{},403],['future grant',{future:true},doc,{},403],['DB read failure',{readError:true},doc,{},403],
  ['cross student parameter',{}, {...doc,studentId:otherId},{},400],['path injection',{}, {...doc,path:'../../answers.json'},{},400],['bank key cannot open mock',{grants:['challenge-bank-'+typeId]},doc,{},403],['mock grant cannot generate all bank',{grants:[productKey]},bank,{},403],['other mock',{grants:['challenge-mock-2']},sourceRequest,{},403],
  ['wildcard',{grants:['*']},doc,{},403],['legacy broad',{grants:['hyperfocus']},doc,{},403],['unknown document',{}, {...doc,productKey:'challenge-mock-5'},{},400],['unknown type',{}, {...bank,typeId:'../../secret'},{},400],['invalid difficulty',{}, {...bank,difficulty:'advanced'},{},400],['negative seed',{}, {...bank,seed:-1},{},400],['large seed',{}, {...bank,seed:4294967296},{},400],['string seed',{}, {...bank,seed:'7'},{},400],['invalid source',{}, {...sourceRequest,number:21},{},400],['fractional source',{}, {...sourceRequest,number:1.5},{},400],['invalid part',{}, {...doc,part:'all'},{},400],['large body',{}, {...doc,extra:'x'.repeat(5000)},{},400],['bad MIME',{},doc,{'content-type':'text/plain'},400],['cross origin',{},doc,{origin:'https://attacker.example'},403]
 ]){const f=edge(options),r=await f.request(body,headers);ok(r.status===status,label);ok(f.storageReads.length===0&&f.bucketReads===0,label+' before storage');}
 for(const [label,options]of [['held flag',{ready:false}],['missing bucket',{bucketMissing:true}],['public bucket',{publicBucket:true}],['missing manifest pin',{pin:''}],['bad manifest pin',{pin:'0'.repeat(64)}],['missing file',{noFile:true}],['corrupt asset',{corrupt:true}]]){const f=edge(options);ok((await f.request(doc)).status===503,label);}
 for(const req of [doc,bank,sourceRequest]){const f=edge(),r=await f.request(req),data=await r.json();ok(r.status===200,'authorized '+req.action);ok(data.verified===true&&data.studentId===studentId&&data.approvedStudentName==='검수용 서버 이름','server identity '+req.action);ok(data.contentVersion===version&&data.part==='questions','version '+req.action);ok(r.headers.get('cache-control')==='no-store','no cache '+req.action);ok(!JSON.stringify(data).includes('검수용 답')&&!('answer'in data)&&!('payload'in data),'questions no answer '+req.action);ok(f.storageReads.length===2&&!f.storageReads.some(p=>p.includes('.answers.')),'questions never fetch answers '+req.action);ok(f.profileReads===2,'recheck after download '+req.action);}
 for(const grants of [[productKey],['challenge-bank-'+typeId]])ok((await edge({grants}).request(sourceRequest)).status===200,'source either exact grant');
 for(const req of [doc,bank,sourceRequest]){const f=edge(),r=await f.request({...req,part:'answers'}),data=await r.json();ok(r.status===200,'explicit answers '+req.action);ok(!f.storageReads.some(p=>p.includes('.questions.')),'answers separate asset '+req.action);if(req.action!=='document')ok(data.answer.id==='variant-'+(req.action==='bank'?1:0)&&!data.question,'answer id '+req.action);}
 for(const option of ['revokedDuring','sessionRevokedDuring','nameChangedDuring']){const f=edge({[option]:true});const r=await f.request(doc);ok(r.status===403&&f.storageReads.length===2,option+' after storage blocked');ok(!(await r.text()).includes('검수용'),'blocked response no contents');}
 for(const seed of [0,1,2,7,4294967295])for(const part of ['questions','answers']){const f=edge({mutate:shardFixture}),r=await f.request({...bank,seed,part}),data=await r.json();ok(r.status===200,'shard delivery');ok((data.question||data.answer).id==='variant-'+seed%2,'shard deterministic ID');ok(f.storageReads[1]===`v1/bank/${typeId}/same.${part}.${seed%2}.json`,'only selected shard and part read');}
 for(const [label,mutate]of [['wrong total',b=>b.manifest.bank[typeId].same.totalCount=3],['zero count',b=>b.manifest.bank[typeId].same.shards[0].count=0],['shard path traversal',b=>b.manifest.bank[typeId].same.shards[0].questions.path='v1/other.json'],['wrong shard index',b=>{const ref=b.manifest.bank[typeId].same.shards[1].questions;const data=JSON.parse(b.files[ref.path]);data.shardIndex=0;b.files[ref.path]=JSON.stringify(data);ref.sha256=hash(b.files[ref.path]);}],['wrong shard item count',b=>{const ref=b.manifest.bank[typeId].same.shards[1].questions;const data=JSON.parse(b.files[ref.path]);data.items=[];b.files[ref.path]=JSON.stringify(data);ref.sha256=hash(b.files[ref.path]);}]])ok((await edge({mutate:b=>{shardFixture(b);mutate(b);}}).request(bank)).status===503,label);
 for(const [label,mutate]of [
  ['manifest traversal',b=>b.manifest.documents[productKey].questions.path='../private.json'],['manifest source mismatch',b=>b.manifest.sources['1-main-1'].typeId='other'],['manifest unknown key',b=>b.manifest.documents['challenge-mock-999']=b.manifest.documents[productKey]],
  ['question answer field',b=>updateFile(b,`v1/bank/${typeId}/same.questions.json`,f=>f.items[0].answer='LEAK')],['question payload',b=>updateFile(b,`v1/bank/${typeId}/same.questions.json`,f=>f.items[0].payload={answer:4})],['root answer field',b=>updateFile(b,`v1/documents/${productKey}.questions.json`,f=>f.answerHtml='LEAK')],
  ['bad styles',b=>updateFile(b,`v1/documents/${productKey}.questions.json`,f=>f.document.styles=['https://attacker.example/x.css'])],['script',b=>updateFile(b,`v1/documents/${productKey}.questions.json`,f=>f.document.html='<script>alert(1)</script>')],['event handler',b=>updateFile(b,`v1/documents/${productKey}.questions.json`,f=>f.document.html='<img onerror="alert(1)">')],['answer attribute',b=>updateFile(b,`v1/documents/${productKey}.questions.json`,f=>f.document.html='<span data-answer="4"></span>')],['external asset',b=>updateFile(b,`v1/documents/${productKey}.questions.json`,f=>f.document.html='<img src="https://attacker.example/a.png">')],
  ['wrong version',b=>updateFile(b,`v1/documents/${productKey}.questions.json`,f=>f.contentVersion='other')],['wrong product',b=>updateFile(b,`v1/documents/${productKey}.questions.json`,f=>f.productKey='challenge-mock-2')],['duplicate pool id',b=>updateFile(b,`v1/bank/${typeId}/same.questions.json`,f=>f.items[1].id=f.items[0].id)],['wrong part',b=>updateFile(b,`v1/bank/${typeId}/same.questions.json`,f=>f.part='answers')]
 ]){const f=edge({mutate}),req=label.includes('pool')||label==='question answer field'||label==='question payload'||label==='wrong part'?bank:doc;ok((await f.request(req)).status===503,label);}
 const lookup=edge().context;for(const [id,t]of Object.entries(vm.runInContext('SOURCE_TYPES',lookup))){const [round,section,number]=id.split('-'),target=lookup.requestTarget({action:'source',round:Number(round),section,number:Number(number),part:'questions'});ok(target.typeId===t&&target.permissionKeys.includes('challenge-bank-'+t),'fixed source occurrence '+id);}
 ok(!/\.rpc\(|\.upload\(|\.update\(|\.insert\(|createSignedUrl/.test(source),'server never mutates or returns storage URLs');
 if(process.argv.includes('--package'))packageAudit();
 console.log(JSON.stringify({status:'passed',checks,remoteWrites:0,liveQueries:'bucket metadata discovery only, not student data',server:'actual TS with mocked Auth/RLS/Storage',release:'held until bucket upload, pinned manifest, hosting deny verification and deployment'}));
})().catch(e=>{console.error(e);process.exitCode=1;});
