const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const base=path.resolve(__dirname,'..'),catalog=require('../challenge/access-catalog.js'),diagnosis=require('../challenge/diagnosis-core.js');
let checks=0;function ok(v,label){assert.ok(v,label);checks++;}
const keys=catalog.list().map(e=>e.key),key='challenge-concept-1',studentId='11111111-1111-4111-8111-111111111111',adminId='22222222-2222-4222-8222-222222222222';
const migration=fs.readFileSync(path.join(base,'supabase/migrations/20260908222618_challenge_permission_catalog.sql'),'utf8');
const edgeSource=fs.readFileSync(path.join(base,'supabase/functions/challenge-access/index.ts'),'utf8');
const edgeJs=stripTypeScriptTypes(edgeSource.replace(/^import .*\n/gm,''),{mode:'strip'}).replace('export async function handleRequest','async function handleRequest');
function edge(options={}){
 const now=Date.now(),claims={exp:Math.floor(now/1000)+3600,iat:Math.floor(now/1000),aal:'aal2',session_id:'live',app_metadata:{hf_role:options.role||'admin'},...options.claims};
 const token='x.'+Buffer.from(JSON.stringify(claims)).toString('base64url')+'.y';let mutationCalls=[],authCalls=0;
 const role=options.role||'admin';const user={id:role==='student'?studentId:adminId,is_anonymous:false,app_metadata:{hf_role:role},...options.user};
 function clientFactory(url,k){const service=k==='secret';return {auth:{getUser:async()=>{authCalls++;return {data:{user:options.authFailure?null:user},error:options.authFailure?new Error('invalid'):null};}},from(table){let eq={};const query={select(){return query;},eq(k,v){eq[k]=v;return query;},maybeSingle:async()=>{
  if(table==='hf_admin_accounts'){const valid=claims.aal==='aal2'&&claims.session_id==='live'&&options.staffVisible!==false;return {data:valid?{role:'admin',account_status:'active',authorization_changed_at:new Date(now-100000).toISOString(),...options.staff}:null,error:null};}
  if(table==='hf_students')return {data:options.studentMissing||(!service&&options.profileVisible===false)?null:{id:eq.id||studentId,display_name:'검수용 학생',account_status:options.studentStatus||'active'},error:null};
  if(table==='hf_permission_catalog')return {data:options.catalogMissing?null:{permission_key:eq.permission_key},error:null};
  throw Error(table);
 },then(resolve){if(table!=='hf_entitlements')throw Error(table);const entries=options.entries||[{permission_key:key,starts_at:new Date(now-1000).toISOString(),expires_at:null,revoked_at:null}];return Promise.resolve({data:entries,error:options.entitlementError?new Error('down'):null}).then(resolve);}};return query;},rpc:async(name,args)=>{mutationCalls.push({name,args});return {data:!options.rpcFailure,error:null};}};}
 const context={Request,Response,TextDecoder,Uint8Array,atob,Date,Set,JSON,console,createClient:clientFactory,RELEASE_CONFIG:{ready:options.buildReady===true},Deno:{env:{get:k=>k==='CHALLENGE_PRIVATE_DELIVERY_READY'&&options.noReadyEnvironment?undefined:({SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public',SUPABASE_SECRET_KEY:'secret',CHALLENGE_PRIVATE_DELIVERY_READY:options.ready?'true':'false'})[k]},serve:fn=>context.handler=fn}};
 vm.createContext(context);vm.runInContext(edgeJs,context);
 async function request(body,headers={}){return context.handler(new Request('https://example/challenge-access',{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json',...headers},body:JSON.stringify(body)}));}
 return {request,mutationCalls,get authCalls(){return authCalls;}};
}
function browser(options={}){
 let clock=Date.now(),onAuth=null,invokes=0,timers=[],events=[];
 const response=()=>({verified:true,studentId,approvedStudentName:'서버 승인 이름',accountStatus:'active',permissionKeys:[key],verifiedAt:clock,validUntil:clock+60000,deliveryReady:true,catalogVersion:catalog.version,...(typeof options.data==='function'?options.data(clock):options.data)});
 const mockClient={auth:{onAuthStateChange:fn=>{onAuth=fn;if(options.initialAuthEvent)fn('SIGNED_IN',{user:{id:studentId}});}},functions:{invoke:async()=>{invokes++;if(options.invoke)return options.invoke(invokes,response);return options.failure?{error:new Error('offline')}:{data:response()};}}};
 const context={module:{exports:{}},require:()=>catalog,location:{hostname:options.host??'example.com',search:options.search||''},URLSearchParams,Date:{now:()=>clock},setTimeout:(fn,delay=0)=>{timers.push({fn,due:clock+delay,cancelled:false});return timers.length;},clearTimeout:id=>{if(timers[id-1])timers[id-1].cancelled=true;},CustomEvent:class{constructor(type,init){this.type=type;this.detail=init.detail;}},dispatchEvent:e=>events.push(e),GFieldHFSupabase:{enabled:()=>options.enabled!==false,ready:async()=>mockClient}};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(base,'challenge/access-service.js'),'utf8'),context);
 const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
 async function elapse(ms){const end=clock+ms;let steps=0;while(true){const due=timers.filter(t=>!t.cancelled&&t.due<=end).sort((a,b)=>a.due-b.due)[0];if(!due)break;if(++steps>100)throw Error('timer hot loop');clock=Math.max(clock,due.due);due.cancelled=true;due.fn();await flush();}clock=end;await flush();}
 return {api:context.module.exports,context,events,timers,options,flush,elapse,get now(){return clock;},get invokes(){return invokes;},auth:event=>onAuth(event),advance:ms=>clock+=ms};
}
async function browserAudit(){
 const {chromium}=require('playwright'),http=require('node:http');
 const out=path.join(base,'output/qa/challenge-access');fs.mkdirSync(out,{recursive:true});
 const server=http.createServer((req,res)=>{const file=path.resolve(base,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!file.startsWith(base+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return;}const ext=path.extname(file);res.setHeader('content-type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[ext]||'application/octet-stream');res.end(data);});});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const b=await chromium.launch();
 try{
  const page=await b.newPage({viewport:{width:1200,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/supabase-config.js',route=>route.fulfill({contentType:'text/javascript',body:'window.GFIELD_HF_SUPABASE_CONFIG={enabled:true};'}));
  await page.route('**/supabase-client.js',route=>route.fulfill({contentType:'text/javascript',body:`window.__calls=[];window.__fail=false;window.GFieldHFSupabase={enabled:()=>true,ready:async()=>({auth:{onAuthStateChange:fn=>window.__authChange=fn,getSession:async()=>({data:{session:{expires_at:Date.now()/1000+3600}}})},functions:{invoke:async(name,{body})=>{window.__calls.push({name,body});if(window.__fail)return{error:{message:'offline'}};return name==='admin-students'?{data:{students:[{id:'${studentId}',name:'검수용 학생 가',status:'active',permissions:['hyperfocus','${key}']},{id:'${adminId}',name:'검수용 학생 나',status:'active',permissions:[]}]}}:{data:{ok:true}};}}})};`}));
  await page.goto(`http://127.0.0.1:${server.address().port}/challenge/admin.html`);
  ok(await page.locator('#permissions').isHidden(),'admin initially no student data');ok(await page.evaluate(()=>window.__calls.length)===0,'no automatic network or write');
  await page.click('#reload');await page.selectOption('#student',studentId);ok(await page.locator('#bank-options input').count()===104,'admin 104 type options');
  await page.screenshot({path:path.join(out,'admin-desktop.png')});
  await page.locator('input[data-key="challenge-mock-2"]').check();await page.selectOption('#round-filter','4');ok(await page.locator('#bank-options input').count()===26,'round filter');await page.fill('#type-search','주사위');ok(await page.locator('#bank-options input').count()===2,'type search');await page.fill('#type-search','');await page.selectOption('#round-filter','all');
  await page.click('#save');const writes=await page.evaluate(()=>window.__calls.filter(c=>c.name==='challenge-access'));ok(writes.length===1&&writes[0].body.permissionKey==='challenge-mock-2'&&writes[0].body.enabled===true,'admin only changed granular key saved');
  ok(!writes.some(c=>c.body.permissionKey==='hyperfocus'),'legacy grant untouched');
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'admin-mobile.png')});
  ok(await page.evaluate(()=>document.documentElement.scrollWidth<=390),'390px no horizontal overflow');await page.locator('#type-search').scrollIntoViewIfNeeded();await page.locator('#type-search').focus();await page.screenshot({path:path.join(out,'admin-mobile-types.png')});
  ok(await page.locator('#type-search').evaluate(e=>getComputedStyle(e).fontSize)==='16px','mobile input size');
  await page.evaluate(()=>window.__authChange('SIGNED_OUT'));ok(await page.locator('#permissions').isHidden()&&await page.locator('#student option').count()===1,'logout removes students and permissions');
  await page.evaluate(()=>window.__fail=true);await page.click('#reload');ok(await page.locator('#permissions').isHidden(),'failure no previous student');ok(errors.length===0,'admin JS errors zero');
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({viewport:[1200,390],horizontalOverflow:false,errors,server:'mocked; no real students or writes'},null,2));
 }finally{await b.close();await new Promise(resolve=>server.close(resolve));}
}
(async()=>{
 ok(keys.length===110&&new Set(keys).size===110,'exact additive 110 permission keys');
 for(let r=1;r<=4;r++)for(const q of [...diagnosis.describeRound(r).questions,...diagnosis.describeRound(r).extra])ok(catalog.has('challenge-bank-'+q.typeId),'all current source types permissioned');
 for(const permission of keys){ok(migration.includes("'"+permission+"'"),'SQL catalog parity');ok(edgeSource.includes('"'+permission+'"'),'server exact allowlist parity');}
 ok(!/insert into public\.hf_entitlements|delete from|drop |alter table|update public/i.test(migration),'migration no grants/revocations/schema broadening');
 const set={action:'set',studentId,permissionKey:key,enabled:true};
 for(const [label,opts,body,headers,status] of [
  ['missing bearer',{},set,{authorization:''},401],['invalid JWT',{authFailure:true},set,{},401],['anonymous',{user:{is_anonymous:true}},set,{},401],['expired JWT',{claims:{exp:1}},set,{},401],
  ['student cannot set',{role:'student'},set,{},403],['user metadata cannot elevate',{role:'student',user:{user_metadata:{hf_role:'admin'}}},set,{},403],['content editor cannot set',{role:'content_editor'},set,{},403],
  ['staff revoked',{staffVisible:false},set,{},403],['inactive staff',{staff:{account_status:'suspended'}},set,{},403],['old staff token',{claims:{iat:1}},set,{},403],['bad staff issue time',{claims:{iat:'invalid'}},set,{},403],
  ['RLS MFA required',{claims:{aal:'aal1'}},set,{},403],['revoked session RLS',{claims:{session_id:'revoked'}},set,{},403],['wildcard denied',{}, {...set,permissionKey:'challenge-bank-*'}, {},400],
  ['legacy permission denied',{}, {...set,permissionKey:'hyperfocus'}, {},400],['unknown catalog key denied',{}, {...set,permissionKey:'challenge-bank-invented'}, {},400],['extra fields denied',{}, {...set,role:'admin'}, {},400],
  ['string enabled denied',{}, {...set,enabled:'true'}, {},400],['invalid target ID',{}, {...set,studentId:'other'}, {},400],['cross origin denied',{},set,{origin:'https://attacker.example'},403],
  ['target missing',{studentMissing:true},set,{},404],['target suspended',{studentStatus:'suspended'},set,{},409],['migration absent',{catalogMissing:true},set,{},503],
  ['student profile RLS denied',{role:'student',profileVisible:false},{action:'self'},{},403],['self cannot select another',{role:'student'},{action:'self',studentId:adminId},{},403],['entitlement read failed',{role:'student',entitlementError:true},{action:'self'},{},503]
 ]){const f=edge(opts),r=await f.request(body,headers);ok(r.status===status,label);ok(f.mutationCalls.length===0,label+' no mutation');}
 const granted=edge();ok((await granted.request(set)).status===200,'valid admin grant');ok(granted.mutationCalls.length===1&&granted.mutationCalls[0].name==='hf_set_student_entitlement'&&granted.mutationCalls[0].args.p_granted_by===adminId,'existing RPC and caller identity');
 const revoked=edge({studentStatus:'suspended'});ok((await revoked.request({...set,enabled:false})).status===200,'inactive target may revoke');
 const student=edge({role:'student'}),reply=await(await student.request({action:'self'})).json();ok(reply.approvedStudentName==='검수용 학생'&&reply.deliveryReady===false,'server name + default release block');ok(student.mutationCalls.length===0,'student read no writes');
 const built=edge({role:'student',noReadyEnvironment:true,buildReady:true}),builtReply=await(await built.request({action:'self'})).json();ok(builtReply.deliveryReady===true,'reviewed build enables release when environment is absent');
 const stopped=edge({role:'student',ready:false,buildReady:true}),stoppedReply=await(await stopped.request({action:'self'})).json();ok(stoppedReply.deliveryReady===false,'environment false overrides reviewed build');
 const now=Date.now(),filtered=edge({role:'student',entries:[{permission_key:key,starts_at:new Date(now-1000).toISOString(),expires_at:new Date(now-1).toISOString()},{permission_key:'hyperfocus',starts_at:new Date(now-1000).toISOString()},{permission_key:'challenge-mock-1',starts_at:new Date(now-1000).toISOString(),revoked_at:new Date(now).toISOString()}]});ok((await(await filtered.request({action:'self'})).json()).permissionKeys.length===0,'expired revoked unrelated grants filtered');
 for(const options of [{},{enabled:false},{failure:true},{data:{verified:false}},{data:{deliveryReady:false}},{data:{accountStatus:'suspended'}},{data:{permissionKeys:['*']}},{data:{validUntil:1}},{host:'example.com',search:'?teacherPreview=1&name=위조',enabled:false}]){
  const f=browser(options);ok(!f.api.allow(key),'default deny');if(Object.keys(options).length)await f.api.refresh();ok(!f.api.allow(key),'invalid/blocked response denies');ok(!f.api.allow('hyperfocus'),'legacy no blanket grant');
 }
 const initialSignIn=browser({initialAuthEvent:true});await initialSignIn.api.refresh();ok(initialSignIn.api.allow(key),'initial SIGNED_IN callback does not cancel first verification');
 const valid=browser();await valid.api.refresh();ok(valid.api.allow(key),'verified exact key allows');ok(!valid.api.allow('challenge-concept-2'),'ungranted volume denied');ok(valid.api.approvedStudentName()==='서버 승인 이름','watermark server identity');const exposed=valid.api.watermarkIdentity();exposed.name='위조';ok(valid.api.approvedStudentName()==='서버 승인 이름','identity copy immutable');valid.auth('SIGNED_OUT');ok(!valid.api.allow(key)&&valid.api.watermarkIdentity()===null,'logout clears permissions and identity');ok(valid.events.some(e=>e.detail.reason==='session-changed'),'logout event');
 const expiry=browser();await expiry.api.refresh();expiry.advance(60001);ok(!expiry.api.allow(key)&&expiry.api.watermarkIdentity()===null,'expired immediate deny');await expiry.elapse(0);ok(expiry.events.some(e=>e.detail.reason==='expired'),'expiry event');
 const continuous=browser();await continuous.api.refresh();const originalUntil=continuous.api.status().validUntil,originalEvents=continuous.events.length,oldExpiry=continuous.timers[0].fn;
 ok(continuous.api.status().refreshAt===continuous.now+45000,'60s lease renews at 45s');await continuous.elapse(45000);ok(continuous.invokes===2&&continuous.api.allow(key),'background read renews while access stays allowed');ok(continuous.events.length===originalEvents,'same identity and grants have no clearing/redraw event');
 oldExpiry();ok(continuous.api.allow(key)&&continuous.events.length===originalEvents,'cancelled old expiry callback cannot clear renewed lease');
 await continuous.elapse(135001);ok(continuous.now>originalUntil&&continuous.api.allow(key)&&continuous.api.watermarkIdentity().studentId===studentId,'continuous learner remains authorized well beyond 60 seconds');ok(continuous.events.length===originalEvents,'successive renewals preserve diagnosis and worksheet consumers');ok(continuous.invokes===5,'one renewal per lease schedule, no request storm');
 continuous.api.clear();ok(continuous.timers.filter(t=>!t.cancelled).length===0&&continuous.api.status().refreshAt===null,'clear cancels renewal and expiry timers');const clearedCalls=continuous.invokes;await continuous.elapse(180000);ok(continuous.invokes===clearedCalls,'clear never restarts background requests');
 const renewalFailure=browser();await renewalFailure.api.refresh();renewalFailure.options.failure=true;await renewalFailure.elapse(45000);ok(!renewalFailure.api.allow(key)&&renewalFailure.api.watermarkIdentity()===null,'background error immediately revokes cached access before original expiry');ok(renewalFailure.events.at(-1).detail.reason==='verification-failed'&&renewalFailure.timers.every(t=>t.cancelled),'failure notifies consumers and cancels both timers');
 const withdrawal=browser({data:{permissionKeys:[key,'challenge-mock-1']}});await withdrawal.api.refresh();withdrawal.options.data={permissionKeys:['challenge-mock-1']};await withdrawal.elapse(45000);ok(!withdrawal.api.allow(key)&&withdrawal.api.allow('challenge-mock-1'),'individual revoked key denied while unrelated approved key remains');ok(withdrawal.events.at(-1).detail.reason==='permissions-changed','individual revocation triggers displayed-content cleanup');
 const changedStudent=browser();await changedStudent.api.refresh();changedStudent.options.data={studentId:adminId,approvedStudentName:'다른 검수 학생'};await changedStudent.elapse(45000);ok(changedStudent.api.watermarkIdentity().studentId===adminId&&changedStudent.events.at(-1).detail.reason==='identity-changed','new approved identity invalidates old learner displays');
 const reordered=browser({data:{permissionKeys:[key,'challenge-mock-1']}});await reordered.api.refresh();const beforeReorder=reordered.events.length;reordered.options.data={permissionKeys:['challenge-mock-1',key]};await reordered.elapse(45000);ok(reordered.events.length===beforeReorder,'same permission set in new order is silent');
 const deliveryRevoked=browser();await deliveryRevoked.api.refresh();deliveryRevoked.options.data={deliveryReady:false};await deliveryRevoked.elapse(45000);ok(!deliveryRevoked.api.allow(key)&&deliveryRevoked.events.at(-1).detail.reason==='permissions-changed','private delivery readiness withdrawal blocks immediately');
 let resolveSlow;const slow=browser({invoke:(n,response)=>n===1?{data:response()}:new Promise(resolve=>{resolveSlow=()=>resolve({data:response()});})});await slow.api.refresh();await slow.elapse(45000);ok(slow.api.allow(key),'fresh lease remains usable during slow renewal');await slow.elapse(15001);ok(!slow.api.allow(key)&&slow.events.at(-1).detail.reason==='expired','hung renewal never extends old expiry');resolveSlow();await slow.flush();ok(!slow.api.allow(key),'late response cannot resurrect expired lease');
 let resolveLogout;const loggingOut=browser({invoke:(n,response)=>n===1?{data:response()}:new Promise(resolve=>{resolveLogout=()=>resolve({data:response()});})});await loggingOut.api.refresh();await loggingOut.elapse(45000);loggingOut.auth('SIGNED_OUT');resolveLogout();await loggingOut.flush();ok(!loggingOut.api.allow(key)&&loggingOut.api.watermarkIdentity()===null,'late background response cannot restore logged-out learner');ok(loggingOut.timers.every(t=>t.cancelled),'logout cancels all lease timers');
 for(const event of ['SIGNED_IN','USER_UPDATED']){const changed=browser();await changed.api.refresh();changed.auth(event);ok(!changed.api.allow(key)&&changed.events.at(-1).detail.reason==='session-changed','authentication transition remains fail closed: '+event);}
 const tokenRenewed=browser();await tokenRenewed.api.refresh();const tokenEvents=tokenRenewed.events.length;tokenRenewed.auth('TOKEN_REFRESHED');ok(tokenRenewed.api.allow(key),'token renewal preserves existing valid lease while server rechecks');await tokenRenewed.flush();ok(tokenRenewed.invokes===2&&tokenRenewed.events.length===tokenEvents&&tokenRenewed.api.allow(key),'same verified token renewal is silent and retains learner work');
 tokenRenewed.options.failure=true;tokenRenewed.auth('TOKEN_REFRESHED');await tokenRenewed.flush();ok(!tokenRenewed.api.allow(key)&&tokenRenewed.events.at(-1).detail.reason==='verification-failed','failed token renewal server recheck clears access');
 const tokenChanged=browser();await tokenChanged.api.refresh();tokenChanged.options.data={studentId:adminId,approvedStudentName:'다른 검수 학생'};tokenChanged.auth('TOKEN_REFRESHED');await tokenChanged.flush();ok(tokenChanged.api.watermarkIdentity().studentId===adminId&&tokenChanged.events.at(-1).detail.reason==='identity-changed','token renewal changed server identity invalidates previous display');
 let resolveDedupe;const deduped=browser({invoke:(n,response)=>n===1?{data:response()}:new Promise(resolve=>{resolveDedupe=()=>resolve({data:response()});})});await deduped.api.refresh();const manualA=deduped.api.refresh(),manualB=deduped.api.refresh();await deduped.flush();ok(deduped.invokes===2,'concurrent checks share one in-flight request');resolveDedupe();await Promise.all([manualA,manualB]);ok(deduped.api.allow(key),'deduplicated response retains valid access');
 const local=browser({host:'localhost',search:'?teacherPreview=1&name=가짜'});await local.api.refresh();ok(local.api.allow(key)&&local.invokes===0,'explicit local preview no auth calls');ok(local.api.watermarkIdentity()===null,'local preview cannot claim approved student');
 const file=browser({host:'',search:'?teacherPreview=1'});ok(!file.api.isTeacherPreview(),'file protocol no bypass');
 if(process.argv.includes('--browser'))await browserAudit();
 console.log(JSON.stringify({status:'passed',checks,permissionKeys:keys.length,remoteWrites:0,authorizationTests:'mocked dependencies; live RLS and deployment not verified',release:'blocked pending private delivery'}));
})().catch(e=>{console.error(e);process.exitCode=1;});
