'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'hyper-focus/output/qa/challenge-answer-continuation'),mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');res.end(data);});});
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:1000}});let checks=0;
try{
 await page.route('**/variant-provider.js',r=>r.fulfill({contentType:'application/javascript',body:fs.readFileSync(path.join(root,'hyper-focus/challenge/variant-provider.js'),'utf8')+'\nconst originalVariants=HFChallengeVariants;window.HFChallengeVariants={...originalVariants,generate(args){const result=JSON.parse(JSON.stringify(originalVariants.generate(args)));if(result.question){result.question.solution=window.__longSolution;result.question.solutionDiagram=window.__testDiagram||"";}return result;}};'}));
 await page.route('**/supabase-client.js',r=>r.fulfill({contentType:'application/javascript',body:''}));
 const sentences=Array.from({length:85},(_,i)=>'제'+(i+1)+'단계에서는 빈칸의 수를 하나씩 확인합니다. 더한 결과와 남은 조건을 모두 다시 확인합니다. ').join('')+' 끝에 <img src=x onerror=alert(1)> 와 🧮가 있어도 글자로 보입니다.';
 const cases=[{name:'sentences',text:sentences,diagram:'<table><tr><td>풀이 표는 한 번만</td></tr></table>'},{name:'graphemes',text:'가나다🧮'.repeat(2400),diagram:''}];
 for(const test of cases){
 await page.goto('http://127.0.0.1:'+server.address().port+'/hyper-focus/challenge/studio.html?teacherPreview=1&tab=bank');await page.waitForFunction(()=>!!HFChallengeStudio);await page.evaluate(t=>{window.__longSolution=t.text;window.__testDiagram=t.diagram;},test);
 await page.locator('[data-select]:not(:disabled)').first().check();await page.locator('#variantCount').fill('1');await page.locator('#buildPractice').click();await page.waitForFunction(()=>HFChallengeStudio.getSnapshot()?.entries.length===1);const snapshot=await page.evaluate(()=>JSON.stringify(HFChallengeStudio.getSnapshot()));
 for(const width of [1280,390]){await page.setViewportSize({width,height:1000});await page.emulateMedia({media:'screen'});await page.locator('#printMode').selectOption('answers');await page.waitForFunction(()=>document.body.dataset.printReady==='true');
 assert.equal(await page.locator('.studio-answer').count(),1);assert(await page.locator('.studio-answer-continuation').count()>0);checks+=2;
 const text=await page.locator('#worksheetPages [data-solution-text]').evaluateAll(nodes=>nodes.map(n=>n.textContent).join(''));assert.equal(text,test.text,'every original character exactly once');checks++;
 assert(await page.locator('[data-answer-entry]').evaluateAll(nodes=>nodes.every(n=>n.dataset.answerEntry==='0')));assert(await page.locator('.studio-answer-continuation h3').evaluateAll(nodes=>nodes.every(n=>n.textContent==='1번 (계속)')));checks+=2;
 assert.equal(await page.locator('#worksheetPages img[onerror]').count(),0);assert.equal(await page.locator('#worksheetPages .studio-art').count(),test.diagram?1:0);checks+=2;
 await page.emulateMedia({media:'print'});assert(await page.locator('.studio-page').evaluateAll(nodes=>nodes.every(n=>n.scrollHeight<=n.clientHeight+2&&n.scrollWidth<=n.clientWidth+2)));assert.equal(await page.locator('.studio-page:not(.blank):not([data-watermark])').count(),0);checks+=2;
 assert(await page.locator('[data-solution-text]').evaluateAll(nodes=>nodes.every(n=>parseFloat(getComputedStyle(n).fontSize)===14)));checks++;
 await page.emulateMedia({media:'screen'});await page.locator('#worksheetPages').screenshot({path:path.join(out,test.name+'-'+width+'.png'),style:'.skip-link{visibility:hidden!important}'});if(width===390)await page.locator('.studio-answer-continuation').first().screenshot({path:path.join(out,test.name+'-continuation-390.png'),style:'.skip-link{visibility:hidden!important}'});assert.equal(await page.evaluate(()=>JSON.stringify(HFChallengeStudio.getSnapshot())),snapshot);checks++;
 }
 for(const mode of ['questions','quick','both']){await page.locator('#printMode').selectOption(mode);await page.waitForFunction(()=>document.body.dataset.printReady==='true');assert.equal(await page.evaluate(()=>JSON.stringify(HFChallengeStudio.getSnapshot())),snapshot);checks++;if(mode==='both'){assert.equal(await page.locator('.studio-page.blank').count(),1);assert.equal(await page.locator('.studio-answer').count(),1);checks+=2;}}
 }
 await page.reload();await page.waitForFunction(()=>!!HFChallengeStudio);await page.evaluate(()=>{window.__longSolution='짧은 풀이입니다.';window.__testDiagram='<div style="height:2000px">너무 큰 풀이 그림</div>';});await page.locator('[data-select]:not(:disabled)').first().check();await page.locator('#variantCount').fill('1');await page.locator('#buildPractice').click();await page.waitForFunction(()=>HFChallengeStudio.getSnapshot()?.entries.length===1);await page.locator('#printMode').selectOption('answers');await page.waitForFunction(()=>document.querySelector('#studioMessage').textContent.includes('풀이 그림이 한 페이지를 넘습니다'));assert.equal(await page.locator('#worksheetPages').innerHTML(),'');assert.equal(await page.evaluate(()=>document.body.dataset.printReady),'false');checks+=2;
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({status:'PASS',checks,cases:cases.map(c=>({name:c.name,length:c.text.length})),preservedSnapshot:true,remoteWrites:0},null,2));console.log(JSON.stringify({status:'PASS',checks}));
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
